### ISSUE TITLE
[Enhancement] transparency on windows / overlay for windows?

### ISSUE THREAD

**Issue by Unip0rn** [Airblader/i3#101]
Just thought about using a chat programm (in this case telegram) in a "overlay", so make it floating an transparent to a certain level. 
By doing so you have the advantage of doing this to any Window you want to use like that and e.g. could even place the documentation of an API over some piece of your IDE that only monitors something while coding.
Hope I made my point clear and understandable, thanks so far for the grat work :)

**Comment by Airblader** [comment]
Transparency is not a window management task, it's a compositing task. i3 is a non-compositing window manager, so to do this you need a separate compositor such as compton.

I use compton including transparency myself, so feel free to check out [my compton config](https://github.com/Airblader/dotfiles-manjaro/blob/master/.compton.conf), but beware that compositor configuration depends greatly on your machine. You might have to do some research to configure it properly (just trial&error it).

**Comment by Unip0rn** [comment]
Thanks for the help, my mistake :+1:
