### ISSUE TITLE
[Q] why fork

### ISSUE THREAD

**Issue by gozes** [Airblader/i3#104]
I being using i3 for a while and just learn about i3-gaps. I was wandering, why a fork?  why can't this work/patches can't go to upstream i3? If they where on upstream everyone could use them if they wanted to instead of having two competing versions of i3

**Comment by Airblader** [comment]
> why can't this work/patches can't go to upstream i3?

Because we don't want these features upstream.

> If they where on upstream everyone could use them

Everybody _can_ use them. Forks aren't a bad thing, in particular since I'm both the maintainer of i3-gaps and a maintainer for i3.
