### ISSUE TITLE
Error 1

### ISSUE THREAD

**Issue by huyducnguyen1198** [Airblader/i3#105]
i have installed the Dependencies, but when i run "make"
it turns out like this 
`[i3] Link i3
/usr/bin/ld: cannot find -lxcb-xrm
collect2: error: ld returned 1 exit status
src/i3.mk:75: recipe for target 'i3' failed
make: *** [i3] Error 1
`
plz help me

**Comment by Airblader** [comment]
You are lacking the xcb-util-xrm dependency. You need to install that first. Most distros have it packaged by now.
