### ISSUE TITLE
missing configure.{ac/in} in gaps branch

### ISSUE THREAD

**Issue by kaminek** [Airblader/i3#107]
when running `autoreconf --force --install` there is no configure file.

seen in **gaps** branch.

**Comment by kaminek** [comment]
seen also on `gaps-next` branch tag `4.12`

**Comment by Airblader** [comment]
That's because i3 only recently switched to autotools and it's in no release yet. Therefore it's not in 4.12 which is equal to the 4.12 tag or the gaps branch.

**Comment by kaminek** [comment]
according to you, which branch/tag should i build to get it work ?

**Comment by Airblader** [comment]
If you want to build using autotools, use `gaps-next@HEAD`.

**Comment by Airblader** [comment]
… and if you want to build 4.12, just build it with `make && sudo make install` (no autotools).

**Comment by kaminek** [comment]
thx man, great project btw
