### ISSUE TITLE
Gaps don't work in tabbed or stacked layout .

### ISSUE THREAD

**Issue by ghost** [Airblader/i3#108]
So the name says it all . 
How to reproduce : 
1.Switch to tabbed layout .
2.Split horizontaly/verticaly
3.Try to change gap size

OS : Manjaro
Version : i3 version 4.12 (2016-03-06, branch "4.12") © 2009 Michael Stapelberg and contributors

**Comment by Airblader** [comment]
Yes, this is intended. Decorations on such containers and gaps just don't go together in a meaningful way. Sorry.
