### ISSUE TITLE
Unable to Install i3-gaps

### ISSUE THREAD

**Issue by LimitSpectrum** [Airblader/i3#109]
Trying to install i3-gaps according to the given instructions. I've installed all listed dependencies and am getting the following output after running "make":

```
make  all-am
make[1]: Entering directory `/home/atreus/Downloads/i3-gaps/build'
  AR       libi3.a
  CC       src/i3-commands.o
../../i3-gaps/src/commands.c:17:38: fatal error: sanitizer/lsan_interface.h: No such file or directory
 #include <sanitizer/lsan_interface.h>
                                      ^
compilation terminated.
make[1]: *** [src/i3-commands.o] Error 1
make[1]: Leaving directory `/home/atreus/Downloads/i3-gaps/build'
make: *** [all] Error 2
```

I cannot proceed with the installation, what might correct this problem?

**Comment by Airblader** [comment]
You don't have the sanitizer's headers installed. Those should come with the compiler – both clang and gcc have it. What compiler (and version) do you use?

Also, can you please re-report this upstream at i3/i3? Thanks. Closing so we can track it there.
