### ISSUE TITLE
Resize containers per mouse in both x and y direction

### ISSUE THREAD

**Issue by nim-** [Airblader/i3#11]
I know this is probably pretty far fetched, but it's a pretty cool feature and the only thing I miss in i3 after using this fork.

In bspwm it's possible, when using $mod+ Right Click, to manipulate both the x axis and the y axis at once, whereas i3 only allows the manipulation of one axis.

Example:
http://youtu.be/U17CLayt_aA?t=14s (14 seconds in)

Would this be possible to implement?

**Comment by Airblader** [comment]
I don't know from the top of my head, but I'll take a look at it to see how complicated it would be. This sounds like something that could also make it into the official i3. Did you open a ticket for this there as well?

**Comment by nim-** [comment]
I havn't done that, no.

I know the author is very strict about what he wants to implement into his project, which of course is all fair and square as it is his baby. I opened a ticket there previously in regards to the possiblity of centering the titles of containers (as opposed to having them align to the left, which is what happens now), which he rejected, saying it would give the users too many options. So I figured your fork with its extra features would be a better place for the feature request.

But sure, I can do it if you want me to? :)

**Comment by Airblader** [comment]
Yes, Michael is very strict. But it seems like this might be a fair point, so it'd be great if you opened a ticket there as well.

Whenever possible, it's good if my changes are merged in i3 as well as it will make maintaining the fork easier. If it doesn't happen, oh well. Worth a try. :)

**Comment by nim-** [comment]
http://bugs.i3wm.org/query/ticket/1412

I submitted a ticket :) Let's wait and see

**Comment by Airblader** [comment]
Thanks!

**Comment by Airblader** [comment]
Michael over at i3 accepted the idea and will accept patches for it. Great!

**Comment by nim-** [comment]
That's indeed wonderful :)

**Comment by Airblader** [comment]
I've just started playing around with it. Quoting myself from bugs.i3wm:

This might actually not be that easy. It certainly isn't as easy as with floating windows (which might just be the reason it's different for them).
Consider a layout hsplit(term1, vsplit(term2, term3)).
First of all, you need to make sure whether resizing in both directions makes sense. Resizing the inner corners of term2 or term3 does, but resizing in both x/y direction for term1 never makes sense.
Also, when resizing the top left corner of term 3, you need to both update the relation between term2 and term 3 and the relation between term1 and the vsplit container. So you resize on multiple levels in the tree.
This might be tricky.

**Comment by nim-** [comment]
Would looking at the bspwm source code make any sense, perhaps? I'm unfortunately not a programmer (yet...), so I don't know much about it, but the source code is definitely available here on git.

**Comment by Airblader** [comment]
Probably not because my guess is that bspwm does things differently. Still, it can't hurt to look into it and I probably will do that.

However, either way, this isn't a trivial feature (IMHO). I'll be on vacation for a few weeks and I might or might not work on this then. But if I don't, I'll take anoter look once I'm back for sure.

**Comment by nim-** [comment]
Sounds very good.

Have a nice vacation!

**Comment by nim-** [comment]
Hi again and happy new year

I don't think the proposition in this post deserved its own issue, and whether you were already working on it in regards to this issue (how's it going by the way? Is it possible to implement?), but I think it would almost be essential if you could remove the "delay" there is when resizing tiling windows right now in i3. I mean, when I resize tiling windows with the mouse right now, a line appears on the screen which I drag, and only when I let go of the mouse the windows finally resize instead of resizing immediately as I drag the mouse. I hope I could explain it well enough. The feature of this issue post would probably be a little bit clunky without removing this limitation I think.

Obviously, I'm not a programmer and I don't know how much effort this would take to implement and if it is something you are willing to spend time on, but with or without the bspwm-like tiling window resize system this would be a very nice thing to have.

Thanks regardless, I really love this fork

**Comment by Airblader** [comment]
Hi,

I haven't worked on this again yet since I'm still in the US and instead of starting on this all over again I'll wait to be back home where I have what I already did for this. I'll be back in a week, though. :)

I understand what you mean by "delay". I'll have to look into it to see how much effort it would be. I'll let you know!

**Comment by jjn2009** [comment]
I really like this about bspwm as well. I look forward to trying out your implementation. As well as the delay thing.

**Comment by Airblader** [comment]
Just to not leave you guys hanging. Unfortunately, I'm just super busy at work right now and barely find time to really look into this. I will, of course, leave it open and if I find the time I'll try to work on this, but patches from others are also welcome. 

As of now, I just can't make promises about when in the near future I can work on this. A real life job has priority ;) 

(This doesn't affect maintaining this fork to stay up to date with i3, of course. This feature is just not trivial, but I'd definitely like it too)

**Comment by nim-** [comment]
That's of course completely understandable :) Good luck with work

I was just curious if you've found out more about how difficult this will be to implement. Do you think it's possible?

**Comment by Airblader** [comment]
Possible, yes, I would definitely assume so. My idea so far was that I only need to consider all directions in the drag event and do two resizes at the same time, plus some corner case handling.

What really confused me so far was that it looked like a lot of code was involved with the current handling and I'd expect it to be much less. I never got around to investigating it a lot. I've written a new resize handler as a first attempt, but it currently just crashes i3 when resizing anything (not surpringly, since I actually know very little C – believe it or not).

**Comment by jjn2009** [comment]
np thanks for the update.

**Comment by Airblader** [comment]
Closing now in favor of upstream https://github.com/i3/i3/issues/1122
