### ISSUE TITLE
Cairo / PKG_CONFIG_PATH errors on Debian 8.6

### ISSUE THREAD

**Issue by ryder-d** [Airblader/i3#113]
I'm in the process of installing i3-gaps on my Debian 8.6 system with i3 already installed. When I run:
`../configure --prefix=/usr --sysconfdir=/etc` the output ends with: 
```
configure: error: Package requirements (cairo >= 1.14.4 pangocairo) were not met:

Requested 'cairo >= 1.14.4' but version of cairo is 1.14.0

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables PANGOCAIRO_CFLAGS
and PANGOCAIRO_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.
```
I don't see a package when I use `apt-cache search pangocairo`

`echo $PKG_CONFIG_PATH` is empty as well

**Comment by Airblader** [comment]
> Requested 'cairo >= 1.14.4' but version of cairo is 1.14.0

So you don't have the correct dependencies. That's the issue. I'm fairly sure that 1.14.0 will also work, so you could modify the dependencies to only check for that.

Regarding other issues about the build system (like the messages you got there), please file it against upstream i3.
