### ISSUE TITLE
Gaps in tabbed containers broken

### ISSUE THREAD

**Issue by prutheus** [Airblader/i3#115]
Output of `i3 --moreversion 2>&- || i3 --version`:

Binary i3 version:  4.13-18-g251dd46 (2016-11-12, branch "gaps-next") © 2009 Michael Stapelberg and contributors
Running i3 version: 4.13-18-g251dd46 (2016-11-12, branch "gaps-next") (pid 504)
Loaded i3 config: /home/prutheus/.config/i3/config (Last modified: Thu 15 Dec 2016 10:21:27 PM CET, 925307 seconds ago)

The i3 binary you just called: /usr/bin/i3
The i3 binary you are running: i3

**What I did:**

I created a tabbed container in my workspace. Inside such a tab, i was creating more containers with the vertical and horizontal orientation mode.

**What I saw:**

The horizontal and vertical orientated containers inside this tab of the big tabbed container doesn't have a gap between themself. everywhere are gaps working, but not inside a tabbed container.

**What I expected instead:**
How to get gaps working there? Or is it intended to not have gaps there?

**Comment by Airblader** [comment]
As you suspected, it is intended to not have gaps there. Handling this with decoration – which are mandatory in this case – is just too difficult.
