### ISSUE TITLE
[Bug] Black Background Behind Titlebar

### ISSUE THREAD

**Issue by ooaj** [Airblader/i3#116]
Binary i3 version:  4.13-non-git © 2009 Michael Stapelberg and contributors
Running i3 version: 4.13-non-git (pid 1835)l-c to abort…)
Loaded i3 config: /home/ooa/.config/i3/config (Last modified: Wed 28 Dec 2016 07:45:55 PM +03, 916 seconds ago)

The i3 binary you just called: /usr/bin/i3
The i3 binary you are running: i3

I was using i3-gaps with titlebars removed with this for_window [class="^.*] border pixel 0, but it wasn't possible to resize windows with a mouse without a titlebar (which I really need for mpv and URxvt), so I manually added for_window for Firefox, Hexchat and Thunderbird, so I could use resize feature with other programs. However, the thing is, I'm getting a black box thingy behind my URxvt, or with any other application that has a titlebar (so, all but Firefox, Hexchat and Thunderbird). 

Here's what I mean:

https://i.imgur.com/q3g2ePX.png
https://i.imgur.com/7bcl8lN.png

config: https://p.teknik.io/rfrvw

**Comment by Airblader** [comment]
That's why you need to disable titlebars. »But I need them« doesn't magically make them work, sorry.

**Comment by AlxHnr** [comment]
Is there any reason why this can't be fixed? Tabbed windows have working title bars with no issues.

**Comment by Airblader** [comment]
It can be fixed, but (to my knowledge) only with great effort, and that would likely make it even worse to keep it up to date with upstream long-term. The solution is https://github.com/i3/i3/issues/3724, which has 400+ upvotes, but no one ever made a serious attempt at it, myself included.
