### ISSUE TITLE
Show empty workspaces

### ISSUE THREAD

**Issue by eoli3n** [Airblader/i3#117]
https://github.com/i3/i3/issues/2617

i3wm refuse this, i don't understand why a simple option cause problem.
Is there a way to add that feature to i3-gaps ?

I want it to let my polybar looks like that bspwm config
![alt text](http://i.imgur.com/A6spiZZ.png)

**Comment by Airblader** [comment]
>  i don't understand why a simple option cause problem.

The opposite of »it causes problems« isn't »it should be implemented«.

It is not a goal of i3 to be the most configurable window manager it could be. And one of the core concepts of i3's window management is to keep workspaces only as long as needed, discard them whenever possible and recreate them when necessary.

You seem to think that i3 »hides« workspaces from you, but that's just not the case. Once you switch away from an empty workspace, this workspace will actually be *closed* and doesn't exist anymore. And that is why you won't see it anymore – because it's not there.

> Is there a way to add that feature to i3-gaps ?

Why not just keep a window on all the workspaces you want to be open?

But the answer is no, I don't want to add this to i3-gaps, because there is no actual feature here. The only reason to keep workspaces open like that is to have a constant list of workspaces in a bar which really is a non-feature because it doesn't actually *add* anything to the system (other than complexity).

FYI: https://github.com/jaagr/polybar/issues/162

**Comment by Airblader** [comment]
Actually I think I'm not as decided as I thought I am. If somebody raises a PR that convinces me implementation-wise, I'll consider adding it.

**Comment by EgonSpengler** [comment]
It seems to me this would break (or appear to break) current workspace functionality. I use i3 in an almost exclusively multi-monitor setup, which creates a workspace on whichever monitor I used to access it. While this may seem intuitive with a single monitor, it doesn't seem a valid request in the general case, where workspaces aren't necessarily accessible from a monitor.

**Comment by Airblader** [comment]
I don't see the issue you're describing, but just to be perfectly clear: adding this involves a configuration switch. I'm not going to change behavior for all users.

**Comment by eoli3n** [comment]
I use multimonitor too. The feature idea is just to be able to lock some workspace, all if you want, by setting a var in conf file as 

```
workspace $tag locked
```

It should work as there is a window on the workspace, exept there isnt one

i use 
```
bindsym $mod+less move workspace to output right
bindsym $mod+Shift+less move workspace to output up
```
to move workspaces between monitors

and 
```
workspace $tag1 output DP-1-1
```
to autoopen a workspace on a specific monitor

The pull request might consider adding a color scheme for locked workspaces.
As i said, a lock workspace is a workspace with NO window but keeped opened anyway.

```
# class                 border  backgr. text    indicator child_border
client.focused          #FFFFFF #A4A4A4 #000000 #ffffff   #333333
client.focused_inactive #333333 #5f676a #ffffff #484e50   #000000
client.unfocused        #333333 #222222 #888888 #292d2e   #222222
client.urgent           #2f343a #900000 #ffffff #900000   #900000
client.placeholder      #000000 #0c0c0c #ffffff #000000   #0c0c0c
client.locked ... ... ... ... ...
```
 ?

**Comment by NickeZ** [comment]
I'm also in a multi-monitor setup, and it would be nice to always have 1,2,3 on first, 4,5,6 on second and 7,8,9 on last screen. Whenever a workspace is on the "wrong" screen I always hit the wrong key combination and/or look at the wrong screen.. =)

**Comment by eoli3n** [comment]
you can do that with 

```
workspace $tag1 output MONITOR1
workspace $tag2 output MONITOR1
workspace $tag3 output MONITOR1
workspace $tag4 output MONITOR2
workspace $tag5 output MONITOR2
workspace $tag6 output MONITOR2
workspace $tag7 output MONITOR3
workspace $tag8 output MONITOR3
workspace $tag9 output MONITOR3
```

see https://github.com/eoli3n/dotfiles/blob/master/.i3/config#L159

**Comment by NickeZ** [comment]
Sweet, thanks! What will happen if I unplug/plug the monitor? (cannot try it since I'm not at work atm)

**Comment by eoli3n** [comment]
workspaces are automatically moved to an active display

**Comment by alanpreed** [comment]
I like to have a graphical pager to display what is open on each workspace, such as the one provided by lxpanel.  The workspaces that this displays are not numbered, which makes using it with the non-persistent workspaces in i3 rather confusing.

For example: if you have applications on workspaces 2, 7 and 9, then three workspaces will be shown next to each other in the pager.  However, there is no indication as to which keys they are bound to.  Persistent workspaces would fix this, so I would really like this feature to be implemented!

**Comment by clawoflight** [comment]
I am very happy that they are not persistent, it's much cleaner.

If you want to know what's on each desktop, use them for specific tasks and give them icons as name :)

**Comment by alanpreed** [comment]
As the maintainer stated above:
> just to be perfectly clear: adding this involves a configuration switch. I'm not going to change behavior for all users.

I prefer the flexibility of the graphical pager, rather than tying workspaces to specific programs. To each their own, though.

**Comment by karambaq** [comment]
Any news?

**Comment by Airblader** [comment]
@karambaq See above:

> If somebody raises a PR that convinces me implementation-wise, I'll consider adding it.

**Comment by robclancy** [comment]
I'd like something like this but the workspace doesn't need to even exist. It just needs to know which screen to go to when created and have i3bar have the buttons for the workspace show even if it doesn't exist.

I'm assuming I can probably do this already by hacking i3bar? I'd like this because then I can also name my workspaces instead of just using numbers.

(this is the only issue I found that is open and even remotely considered to using, no idea what the difference is with this repository and i3/i3)

**Comment by Airblader** [comment]
i3status doesn't display workspace buttons, that's i3bar. The difference of this repo to vanilla i3 is described in detail in the README.

What you are describing is exactly what is being discussed here. In i3, an empty workspace that isn't active (meaning the workspace shown on some output) doesnt exist at all. Empty, active workspaces are shown in i3bar today already, so this is only about empty inactive workspaces which is equivalent to non-existing workspaces (but requires some definition of "which ones could exist")

**Comment by robclancy** [comment]
Yeah I already edited i3Status to i3Bar when I realized my mistake.

Basically what I would like is a button on i3Bar, the same workspace buttons (maybe they could be styled slightly different when the workspace doesn't exist) which will switch to that workspace (so create it) and put it on the correct screen at the same time (same screen the button is on). I'm assuming this is probably already possible with something like polybar which I have been meaning to try out.

**Comment by r1fl** [comment]
any updates?

**Comment by oblitum** [comment]
I don't see much use displaying empty workspaces either, but there's another issue, most bars when in i3 won't display even the inactive nonempty workspaces! I've only seen i3bar do that. I'd like an option on that at least. Anyone knows of a bar for i3 that supports displaying nonempty inactive workspaces besides i3bar?

**Comment by robclancy** [comment]
"I can't see the use so all the people who want it are wrong"

**Comment by oblitum** [comment]
@robclancy Did you make the last part up? Because I don't see it anywhere else.

**Comment by allumik** [comment]
I don't know if this is worth a new post or does it belong in this thread topic-wise, but i was searching for a solution to multi-monitor setup problem:

When connecting the output to several monitors, I set the i3bar output only to my primary (in my case laptop screen eDP1), but then i won't see the external monitor workplaces anymore. So it would be nice to have an option to see all opened workplaces on all the screens (for example "show_all_ws true" or "show_all_ws eDP1") or as more expanded option - sum output of several screens to specific screen (for example "bar { output DVI1 HDMI1 → eDP1 }").

This probably would be something OP could use as a hack: if you could assign workplaces on external monitors which are not there, then they are being forced to be opened with no apps inside - and still be visible on your main output's tray. Ofc if this is possible... just an idea.

**Comment by andersfylling** [comment]
I was looking for this feature as well. I simply want to show all 10 titles at the bottom left at any time. Even if that workspace has no windows.

It makes sense that a workspace should not exist when there is no content. But I'm only interested in keeping the menu size fixed, and as such, I need to a way to display the empty workspaces as well.

Apparently someone has a fork with this feature. I can't remember who. But I'm not sure why no PR has been opened from it :laughing:

**Comment by laureanray** [comment]
I this still being worked on?

**Comment by orestisfl** [comment]
My guess is no and given that i3-gaps will not accept any new features (and ideally will be merge to i3: https://github.com/i3/i3/issues/3724), I see this as something that should be discussed in the i3wm issue tracker.

When https://github.com/i3/i3/issues/3818 is implemented, this feature is also going to be covered.

For these reasons, I am closing this issue in favor of https://github.com/i3/i3/issues/3818.
