### ISSUE TITLE
Gap opacity

### ISSUE THREAD

**Issue by eoli3n** [Airblader/i3#119]
is there any way to set an opacity to the gap, not complete transparency ?

![alt text](http://ptpb.pw/VLSh.png)

**Comment by Airblader** [comment]
I don't understand the question. For there to be something partially opaque there has to be something providing that opaqueness. But a gap is.. A gap. There is virtually nothing in that area. What do you expect to provide any opaqueness?

**Comment by eoli3n** [comment]
simple question, thx for answer :)

**Comment by eoli3n** [comment]
another question ?
![alt text](https://camo.githubusercontent.com/7da062cb011d81a3551cd34ee2d33886ee6b2e06/687474703a2f2f692e696d6775722e636f6d2f7938735a45366f2e6a7067)

In your exemple screen, what's your term ? how do you display image inside ? terminology ?

**Comment by Airblader** [comment]
The emulator I use is Termite. I'm actually not sure how neofetch displays that image, never cared to investigate. But that's neofetch, so you can see how they're doing it in their source code.

**Comment by eoli3n** [comment]
huhu just found it in your package list before reading your comment, thx
