### ISSUE TITLE
Gap between containers double as big as between container and edge of screen/panel

### ISSUE THREAD

**Issue by nim-** [Airblader/i3#12]
I don't know if this is a bug or an intended feature, but it would be nice to be able to do something about it.

If I have, say, gap_size = 10, then the gap_size between container A and B will total 20, whereas the gap_size between a container and the edge of the screen will be 10. Would be nice to have consistency, so gap_size = 10 would be 10 everywhere.

Here's a crappy picture for reference:
http://imgur.com/XiHoLXH

Thanks

**Comment by Airblader** [comment]
It's neither a feature, nor a bug. I'd say it's a side-effect. Every container just insets its content with the gaps patch and so two adjacent containers will both use the same inset which appears to be double then.

There's different ways to approach this. But it really does bug me as well (because I want large gaps to the edge of the screen, but not between containers), so it's likely that I'll do something about it. In fact that's the reason why I opened #10 which would go a little further than this, but may be harder to deal with.

I'll have to think about a good way to deal with this. But just doing it the way you suggested might be a good first step to deal with this.

**Comment by Airblader** [comment]
I've found an easy way to do this (the way you suggested here, for now). :)
I'll have to clean it up and then commit it, but I'll wait a day or two before merging it so I can test it a little.

Of course, you're free to test that branch as well once I pushed it.

Edit: Actually, it's not quite correct yet. I'll figure it out, though.
Edit 2: Found the mistake. I'll clean it up, push it and let you know.

**Comment by Airblader** [comment]
I've pushed the branch `feature-equidistant-gaps` now. It'd be cool if you could test it and give me some feedback. 

I'd be especially interested in whether this works correctly with multiple monitors. For example, if your two screens are next to each other, is the correct gap size on the left edge of the right screen being used? I can't imagine it being wrong, but just want to be sure.

I'll also test this for a bit and then merge it back.

**Comment by nim-** [comment]
Hi

I get this error when trying to compile it:

make
[libi3] CC libi3/get_process_filename.c
In file included from libi3/get_process_filename.c:20:0:
include/libi3.h:21:25: fatal error: pango/pango.h: No such file or directory
 #include <pango/pango.h>
                         ^
compilation terminated.
libi3/libi3.mk:12: recipe for target 'libi3/get_process_filename.o' failed
make: **\* [libi3/get_process_filename.o] Error 1

**Comment by Airblader** [comment]
That's weird. Are you sure you compiled i3 before on that machine? It seems you are missing `libpango1.0-dev`. Can you check whether that package is installed?

If you get more errors like this after, make sure that (at least) all of these are installed:

```
libxcb1-dev libxcb-keysyms1-dev libpango1.0-dev libxcb-util0-dev libxcb-icccm4-dev libyajl-dev libstartup-notification0-dev libxcb-randr0-dev libev-dev libxcb-cursor-dev libxcb-xinerama0-dev
```

FYI, this is what it looks like for me now: http://i.imgur.com/kUmkrut.png

**Comment by nim-** [comment]
Yep, it's odd, I've compiled new versions of your fork several times on that machine.
I'll try checking again when I get home from work. Thanks!

Looks very good, by the way.

**Comment by Airblader** [comment]
Have you had a chance to try again yet? I've been using it all day and had no problems whatsoever, so I'll merge this into the main branch tomorrow.

**Comment by nim-** [comment]
Hi

I only just got home, but I've got no idea how to clone a single branch. Google gives me nothing. As soon as I figure it out I'll get back to you...

**Comment by Airblader** [comment]
You don't clone a branch. Once you cloned the repo, you just check it out (from inside the repositorie's directory):

```
git checkout feature-equidistant-gaps
```

**Comment by nim-** [comment]
Thank you.

It runs beatifully on my multimonitor setup. No issues at all.
I'll of course report back if anything happens.

**Comment by Airblader** [comment]
Awesome, thank you. I'll merge this back tomorrow then. You can just do `git checkout gaps` again then. Also, just in case, you can get the latest state of the repository by doing `git pull` and then just recompile. ;)

**Comment by nim-** [comment]
Ah, I see. Git is really nifty, I must say!!

**Comment by Joe-Dowd** [comment]
I've also tested it and it's working perfectly on multi-monitor and single monitor.

**Comment by Airblader** [comment]
Awesome; the more feedback, the better. Thank you!

**Comment by Airblader** [comment]
This is now merged into the main branches.

@nim- You can now do

```
git checkout gaps
git pull
make && sudo make install
```
