### ISSUE TITLE
libxcb-xrm0 is available in Ubuntu 16.10 and Debian "Stretch" 9

### ISSUE THREAD

**Issue by zeorin** [Airblader/i3#120]
`sudo apt install libxcb-xrm0` will install `xcb-util-xrm` on [Debian Stretch](https://packages.debian.org/source/stretch/xcb-util-xrm) and [Ubuntu 16.10](http://packages.ubuntu.com/yakkety/libxcb-xrm0). Perhaps update the wiki with this?

**Comment by Airblader** [comment]
Thanks for the info. The wiki already has libxcb-xrm-dev, which should also be fine, no?

**Comment by zeorin** [comment]
I'd imagine that just installing the headers will solve any compilation issues, but cause runtime issues without the actual library installed…

**Comment by Airblader** [comment]
I see. I'm not too familiar with Debian packages. :-) The wiki should be free to edit. Do you just wanna take care of it? Much appreciated!

**Comment by zeorin** [comment]
I've updated the wiki. For reference in Debian packaging, `*-dev` packages contain the headers (and `*-dbg` packages contain debugging symbols, there are usually *at least* 3 packages for every program, but may be more—Debian is fond of splitting things up into many libraries).

**Comment by Airblader** [comment]
Great, thank you!
