### ISSUE TITLE
Error on following instructions to install under NixOS

### ISSUE THREAD

**Issue by realcomplex** [Airblader/i3#122]
According to the wiki for this project, installing i3-gaps under NixOS is as easy as adding the following to `/etc/nixos/configuration.nix`:
```
services.xserver.windowManager = {
  i3 = {
    enable = true;
    package = pkgs.i3-gaps;
  };
  default = "i3";
};
```
However, on running `nixos-rebuild switch` with that configuration, I get an error:
```
error: The option `services.xserver.windowManager.i3.package' defined in `/etc/nixos/configuration.nix` does not exist.
```
What should I do instead?

Thanks in advance for the help!

**Comment by Airblader** [comment]
I'm not a nixOS guy, but my coworker @fmthoma can probably help.

**Comment by fmthoma** [comment]
If you're using NixOS 16.09, the correct configuration is
```
services.xserver.windowManager = {
  i3-gaps.enable = true;
  default = "i3-gaps";
};
```
It changed on NixOS master, and I updated the Wiki prematurely.

**Comment by realcomplex** [comment]
Oh okay, thanks for the help! Does that mean that I should use what the wiki here says in the future, as the nix repository gets updated?

**Comment by fmthoma** [comment]
> Does that mean that I should use what the wiki here says in the future, as the nix repository gets updated?

When you switch to NixOS unstable, or the next release, then yes. But I updated the Wiki so there should not be any confusion now.
