### ISSUE TITLE
i3-gaps 'breaking' with Google-Chrome-Stable -> Download -> Show in Folder

### ISSUE THREAD

**Issue by DaveTacker** [Airblader/i3#124]
Output of `i3 --moreversion 2>&- || i3 --version`:

Binary i3 version:  4.13-50-ga98717d (2017-01-03, branch "gaps-next") © 2009 Michael Stapelberg and contributors
Running i3 version: 4.13-50-ga98717d (2017-01-03, branch "gaps-next") (pid 4860)
Loaded i3 config: /home/dave/.i3/config (Last modified: Wed 25 Jan 2017 09:05:55 PM HST, 65059 seconds ago)

The i3 binary you just called: /usr/bin/i3
The i3 binary you are running: i3

URL to a logfile as per http://i3wm.org/docs/debugging.html:

http://logs.i3wm.org/logs/5708007778287616.bz2

**What I did:**

When using Google-Chrome-Stable Version 55.0.2883.87 (64-bit) after downloading a file and choosing 'Show in folder' the current workspace seems to freeze up. 

**What I saw:**

Clicking on any elements doesn't seem to make any difference. Here are some [screenshots](http://imgur.com/a/b0tTr).

**What I expected instead:**

That the workspace didn't freeze up. :)

**Comment by Airblader** [comment]
This is not related to i3-gaps features, so please report this upstream in i3.

**Comment by DaveTacker** [comment]
Will do, thanks!
