### ISSUE TITLE
window focus indicator

### ISSUE THREAD

**Issue by vKnmnn** [Airblader/i3#126]
@Airblader 

Hi, 
is there currently a feature to decrease a window's gaps when it gains focus?
I'd like to have an indicator on what window is active. this would also combine well with a keybind
 to toggle that gap a few times, so one can notice which window is currently in focus.

**Comment by Airblader** [comment]
There isn't and the feature in itself doesn't make sense with how gaps work. Gaps aren't window-specific.

**Comment by vKnmnn** [comment]
ok, then how do you know which window is curently focused ?
i'm asking from the workflow point of view

**Comment by Airblader** [comment]
i3 offers window borders where the focused window's borders can have a different color. For i3-gaps you only need to disable titlebars, not borders.

**Comment by vKnmnn** [comment]
i see. i'll try out what i can do, thanks

**Comment by Airblader** [comment]
All you need to do is

````
for_window [class="^.*"] border pixel 3
````

instead of `0`. The important part is that it says `pixel` instead of `normal`. 

You can also use things like shading in your compositor to highlight the focused window etc. But this lies outside the realm of i3.

**Comment by vKnmnn** [comment]
i tried accomplishing the dimming with compton for what it's worth. but it only darkens other windows when i have a floating one on top.
edit: after reenabling the borders, compton properly dims other windows.
also, i see now i could set the border's colors to transparent for focused windows, which would be - in a way - just what i had wanted

**Comment by alexshi0000** [comment]
Can you change the colour of the border to be transparent?
