### ISSUE TITLE
Workspace save not working as expected

### ISSUE THREAD

**Issue by arivarton** [Airblader/i3#127]
Output of `i3 --moreversion 2>&- || i3 --version`:
Binary i3 version:  4.13 (2016-11-08, branch "4.13") © 2009 Michael Stapelberg and contributors
Running i3 version: 4.13 (2016-11-08, branch "4.13") (pid 537)
Loaded i3 config: /home/vidr/.config/i3/config (Last modified: Thu 16 Feb 2017 17:29:29 GMT, 1946 seconds ago)

The i3 binary you just called: /usr/bin/i3
The i3 binary you are running: i3

**What I did:**

Trying to save a workspace like this:
http://imgur.com/a/2PQud

Here are the two config files it creates:
The one that doesn't work as expected: http://pastebin.com/MRWuKhsQ
This works as expected: http://pastebin.com/Eq8xxGzk

Also a sidenote: When splitting horizontally, the window should be split with the horizon. As it is in i3 it splits vertically. I think the creator of i3 didn't understand the meaning of horizontal and vertical. First thing I did with my config was to rotate the bindings for splitting windows.

(These issues might be more related to the upstream version of i3 but im trying here first)

**Comment by Airblader** [comment]
> Also a sidenote: When splitting horizontally, the window should be split with the horizon. As it is in i3 it splits vertically. I think the creator of i3 didn't understand the meaning of horizontal and vertical.

They very well did understand it, but "vertical split" refers to the direction in which the windows are placed, not the "split axis". We know that people have different understandings here, but both notions are totally fine.

> These issues might be more related to the upstream version of i3 but im trying here first

Yes, this is entirely upstream so let's please handle it there. But before you open an issue there, make sure to read [this Troubleshooting entry](http://i3wm.org/docs/layout-saving.html#_restoring_a_vertically_split_workspace). From what I can tell that's the issue you're having.

If it's not, please open an issue upstream – I'm closing this one here. If you only have additional comments or questions feel free to ask them here. Thanks!

**Comment by arivarton** [comment]
> They very well did understand it, but "vertical split" refers to the direction in which the windows are placed, not the "split axis". We know that people have different understandings here, but both notions are totally fine.

Ok, that atleast makes logical sense although im not used to it.

> Yes, this is entirely upstream so let's please handle it there. But before you open an issue there, make sure to read this Troubleshooting entry. From what I can tell that's the issue you're having.

That did the trick, should have done some RTFM.

Cheers!
