### ISSUE TITLE
Error in configure

### ISSUE THREAD

**Issue by Mofiqul** [Airblader/i3#129]
Hello I tried to install i3-gaps and I already installed all the dependencies bit it gives me the following error
 ```
./configure.ac --prefix=/usr --sysconfdir=/etc --disable-sanitizers
./configure.ac: line 4: syntax error near unexpected token `[2.69]'
./configure.ac: line 4: `AC_PREREQ([2.69])'
```

I am using Ubuntu 16.04LTS and I have i3 installed already.

**Comment by Airblader** [comment]
Putting the error into Google immediately yields https://github.com/vcftools/vcftools/issues/25.

**Comment by Mofiqul** [comment]
but if I ./configure it says No such file in the directory

**Comment by Airblader** [comment]
The instructions can be found [in the wiki](https://github.com/Airblader/i3/wiki/Compiling-&-Installing).

**Comment by Mofiqul** [comment]
[https://www.dropbox.com/s/2q11z9uglewi5nx/i3.png.jpg?dl=0]
screenshot

**Comment by Mofiqul** [comment]
```
autoreconf --force --install
configure.ac:121: installing './ar-lib'
configure.ac:60: installing './compile'
configure.ac:7: installing './config.guess'
configure.ac:7: installing './config.sub'
configure.ac:8: installing './install-sh'
configure.ac:8: installing './missing'
Makefile.am:208: warning: '%'-style pattern rules are a GNU make extension
Makefile.am: installing './depcomp'
parallel-tests: installing './test-driver'

```
is it done?
