### ISSUE TITLE
Updating cairo package on raspberry pi

### ISSUE THREAD

**Issue by rave1** [Airblader/i3#130]
After installing all necessary dependencies I still cannont finish the installation because the command:
"../configure --prefix=/usr --sysconfdir=/etc --disable-sanitizers"
Says that my cairo package is 1.14.0 and it needs at least 1.14.4, but when I try to update the package the output is that i have already the newest version.
Pls help

**Comment by Airblader** [comment]
Ask the maintainers of your distribution to update the cairo package. As of now you're not fulfilling the dependency i3 asks for. This is an issue of your distribution, not i3.
