### ISSUE TITLE
Enable transparency for placeholder windows

### ISSUE THREAD

**Issue by ghost** [Airblader/i3#132]
If I understand correctly, this could be controlled by client.placeholder or client.background?

**Comment by Airblader** [comment]
I somewhat assume that https://github.com/i3/i3/pull/2646 might have solved this already. Can you make sure to run a current development version of i3 and try if it really doesn't work?

**Comment by ghost** [comment]
```
 % i3 -v
i3 version 4.13-111-g7a9e51db (2017-02-24, branch "gaps-next") © 2009 Michael Stapelberg and contributors
```

I tried
```
set $none #00000000
client.placeholder      $none   $none   $none   $none
client.background       $none
```
but it didn't work.

**Comment by 8carlosf** [comment]
don't you need to do `set $none "#00000000"`? otherwise the last part will be read as a comment..

Edit: I really don't know if this is true, just putting it out there

**Comment by Luvideria** [comment]
> don't you need to do `set $none "#00000000"`? otherwise the last part will be read as a comment..
> 
> Edit: I really don't know if this is true, just putting it out there

No, in the i3 config file the line is commented if it **begins** by a '#'

**Comment by Airblader** [comment]
I'm closing this issue has i3-gaps is being migrated into i3. If this issue still applies, please reopen it in i3.
