### ISSUE TITLE
Compatible with 14.04.4?

### ISSUE THREAD

**Issue by chrisgreg** [Airblader/i3#134]
I have to run 14.04.4 as it's the latest version of Ubuntu that's compatible with my graphics card (7870XT). 

**What I did:**

../configure --prefix=/usr --sysconfdir=/etc --disable-sanitizers

**What I saw:**

checking for PANGOCAIRO... no configure: error: Package requirements (cairo >= 1.14.4 pangocairo) were not met:
Requested 'cairo >= 1.14.4' but version of cairo is 1.13.1
Consider adjusting the PKG_CONFIG_PATH environment variable if you installed software in a non-standard prefix.
Alternatively, you may set the environment variables PANGOCAIRO_CFLAGS and PANGOCAIRO_LIBS to avoid the need to call pkg-config. See the pkg-config man page for more details.

Possible to build on 14.04.4?

**Comment by fifdick** [comment]
had the same problem and solved it by installing cairo  1.14.4 from source:
https://www.cairographics.org/news/cairo-1.14.4/
