### ISSUE TITLE
Installation requires automake on Fedora 25

### ISSUE THREAD

**Issue by dbd** [Airblader/i3#136]
Output of `i3 --moreversion 2>&- || i3 --version`:
 Pre installation 
_REPLACE: i3 version output_
 N/A
URL to a logfile as per http://i3wm.org/docs/debugging.html:

Log : https://gist.github.com/dbd/ce6b658834ef8f34b388f5bbd5937614_

**What I did:**

autoreconf --force --install

**What I saw:**

Can't exec "aclocal": No such file or directory at /usr/share/autoconf/Autom4te/FileUtils.pm line 326.
autoreconf: failed to run aclocal: No such file or directory

**What I expected instead:**

configure.ac:121: installing './ar-lib'
configure.ac:60: installing './compile'
configure.ac:7: installing './config.guess'
configure.ac:7: installing './config.sub'
configure.ac:8: installing './install-sh'
configure.ac:8: installing './missing'
Makefile.am:208: warning: '%'-style pattern rules are a GNU make extension
Makefile.am: installing './depcomp'
parallel-tests: installing './test-driver'

Suggesting update to the wiki to include missing build requires

**Comment by Airblader** [comment]
The distros I know, like Arch, explicitly exclude core tools for compiling software from dependencies since it'd just be a dependency of basically everything. 

If Fedora has the convention to include these dependencies (please verify) feel free to update the wiki as necessary.
