### ISSUE TITLE
Strange behavior while resizing URxvt in floating mode

### ISSUE THREAD

**Issue by GRX78FL** [Airblader/i3#137]
Output of `i3 --moreversion 2>&- || i3 --version`:

`Binary i3 version:  4.13-111-g7a9e51db (2017-02-24, branch "gaps-next") © 2009 Michael Stapelberg and contributors
Running i3 version: 4.13-111-g7a9e51db (2017-02-24, branch "gaps-next") (pid 848)
Loaded i3 config: /home/$USER/.config/i3/config (Last modified: Mon 06 Mar 2017 12:29:44 AM EST, 69792 seconds ago)
The i3 binary you just called: /usr/bin/i3
The i3 binary you are running: i3`

**What I did:**

urxvt running tiled
$mod + shift + spcabar (float-tiled toggle, as default configs)
urxvt running in floting mode
$mod + r (resize, as default - arrows)
left arrow (shrink height ) > working
down arrow (grow width) > working
up arrow (shrink height) > working
right arrow (grow width) > not working

**What I saw:**

It grows just twice then i have to `ESC` the resize mode, reload i3 with `$mod + shift + r ` and enter the resize mode with the same outcome.

**What I expected instead:**
i expected it to grow as much as I want, lol.

**Comment by Airblader** [comment]
Please report this in i3 instead of i3-gaps and make sure to attach logs.

**Comment by GRX78FL** [comment]
Why to i3?
I'm having this issue only on i3-gaps.
it works just fine in i3.

**Comment by Airblader** [comment]
Is that still the case if you use the development version of i3 and not the version packaged in your distribution (i.e., compiling from source)? 

If so please provide your config and a minimal log file as described in the debugging docs.

**Comment by GRX78FL** [comment]
That's correct:
----
I'm always using the latest i3-gaps version.
Since I'm using Debian Stretch (9.0) there's no official package to install, therefore compiling from source is the only way.
My i3 config http://pastebin.com/BTMyJgbj
My partial i3 log http://pastebin.com/L4QLUccT
Thanks for the patience

**Comment by Airblader** [comment]
Why a partial i3 log file? It doesn't contain anything useful. Please provide a full log file as outlined in the debugging docs.

By the way, I can reproduce this issue with your setting of 5px / 5ppt. I think this is probably due to the resize increments urxvt specifies. Does resizing work if you use 10px / 10ppt instead?

**Comment by GRX78FL** [comment]
Back again.
----
Sorry for not being active in this period.
The problem doesn't persist with the default increase size of 10px / 10ppt.
So we could consider this a non problem; anyways - I'm still going to provide a full log in a few hours (maybe a day) so that it can be archived for future review.
Thanks and sorry again, you're doing a great job :)

**Comment by Airblader** [comment]
Thanks. There are no logs needed, this confirms that this is due to the resize increment hints that urxvt specifies. Everything is working as intended here – urxvt doesn't allow resizing by this little.
