### ISSUE TITLE
ghost image in gas area

### ISSUE THREAD

**Issue by heelsleeh** [Airblader/i3#139]
Output of `i3 --moreversion 2>&- || i3 --version`:
Binary i3 version:  4.13-111-g7a9e51d (2017-02-24, branch "gaps-next") © 2009 Michael Stapelberg and contributors
Running i3 version: 4.13-111-g7a9e51d (2017-02-24, branch "gaps-next") (pid 26496)
Loaded i3 config: /home/zosy/.config/i3/config (Last modified: Tue 21 Mar 2017 08:57:53 PM CST, 112 seconds ago)

The i3 binary you just called: /usr/bin/i3
The i3 binary you are running: i3

URL to a logfile as per http://i3wm.org/docs/debugging.html:

http://logs.i3wm.org/logs/5658044692168704.bz2

**What I did:**

open applications as usual

**What I saw:**
![heelsleeh-2017-03-21-20 20 21](https://cloud.githubusercontent.com/assets/24011272/24178904/f410a41e-0ee6-11e7-84bf-43f7ecc543ef.png)

**What I expected instead:**
_REPLACE: e.g. "Focus should be on the window to the left"_

**Comment by Airblader** [comment]
Habe you read the Readme?

**Comment by heelsleeh** [comment]
@Airblader i see now, thanks for the great work.
