### ISSUE TITLE
Missing file during make build/man/i3.xml

### ISSUE THREAD

**Issue by drgnomage** [Airblader/i3#140]
This error is happening with the AUR on both i3-gaps-git i3-gaps-next-git and compiling from the git on my freshly installed Arch Linux 64-bit on my desktop.

During the make command I am getting an error of:
$ make
make  all-am
make[1]: Entering directory '/home/josh/git/i3/build'
  CC       libi3/libi3_a-dpi.o
  CC       libi3/libi3_a-draw_util.o
  CC       libi3/libi3_a-fake_configure_notify.o
  CC       libi3/libi3_a-font.o
  CC       libi3/libi3_a-format_placeholders.o
  CC       libi3/libi3_a-get_colorpixel.o
  CC       libi3/libi3_a-get_config_path.o
  CC       libi3/libi3_a-get_exe_path.o
  CC       libi3/libi3_a-get_mod_mask.o
  CC       libi3/libi3_a-get_process_filename.o
  CC       libi3/libi3_a-get_visualtype.o
  CC       libi3/libi3_a-ipc_connect.o
  CC       libi3/libi3_a-ipc_recv_message.o
  CC       libi3/libi3_a-ipc_send_message.o
  CC       libi3/libi3_a-is_debug_build.o
  CC       libi3/libi3_a-mkdirp.o
  CC       libi3/libi3_a-resolve_tilde.o
  CC       libi3/libi3_a-root_atom_contents.o
  CC       libi3/libi3_a-safewrappers.o
  CC       libi3/libi3_a-string.o
  CC       libi3/libi3_a-strndup.o
  CC       libi3/libi3_a-ucs2_conversion.o
  AR       libi3.a
ar: `u' modifier ignored since `D' is the default (see `U')
  CC       src/i3-assignments.o
  CC       src/i3-bindings.o
  CC       src/i3-click.o
  CC       src/i3-commands.o
  GEN      i3-command-parser.stamp
  CC       src/i3-commands_parser.o
  CC       src/i3-con.o
  CC       src/i3-config.o
  CC       src/i3-config_directives.o
  GEN      i3-config-parser.stamp
  CC       src/i3-config_parser.o
  CC       src/i3-display_version.o
  CC       src/i3-ewmh.o
  CC       src/i3-fake_outputs.o
  CC       src/i3-floating.o
  CC       src/i3-handlers.o
  CC       src/i3-ipc.o
  CC       src/i3-key_press.o
  CC       src/i3-load_layout.o
  CC       src/i3-log.o
  CC       src/i3-main.o
  CC       src/i3-manage.o
  CC       src/i3-match.o
  CC       src/i3-move.o
  CC       src/i3-output.o
  CC       src/i3-randr.o
  CC       src/i3-regex.o
  CC       src/i3-render.o
  CC       src/i3-resize.o
  CC       src/i3-restore_layout.o
  CC       src/i3-scratchpad.o
  CC       src/i3-sd-daemon.o
  CC       src/i3-sighandler.o
  CC       src/i3-startup.o
  CC       src/i3-tree.o
  CC       src/i3-util.o
  CC       src/i3-version.o
  CC       src/i3-window.o
  CC       src/i3-workspace.o
  CC       src/i3-x.o
  CC       src/i3-xcb.o
  CC       src/i3-xcursor.o
  CC       src/i3-xinerama.o
  CCLD     i3
  CC       i3bar/src/i3bar_i3bar-child.o
  CC       i3bar/src/i3bar_i3bar-config.o
  CC       i3bar/src/i3bar_i3bar-ipc.o
  CC       i3bar/src/i3bar_i3bar-main.o
  CC       i3bar/src/i3bar_i3bar-mode.o
  CC       i3bar/src/i3bar_i3bar-outputs.o
  CC       i3bar/src/i3bar_i3bar-parse_json_header.o
  CC       i3bar/src/i3bar_i3bar-workspaces.o
  CC       i3bar/src/i3bar_i3bar-xcb.o
  CCLD     i3bar/i3bar
  CC       i3-config-wizard/i3_config_wizard_i3_config_wizard-main.o
  CCLD     i3-config-wizard/i3-config-wizard
  CC       i3-dump-log/i3_dump_log_i3_dump_log-main.o
  CCLD     i3-dump-log/i3-dump-log
  CC       i3-input/i3_input_i3_input-keysym2ucs.o
  CC       i3-input/i3_input_i3_input-main.o
  CCLD     i3-input/i3-input
  CC       i3-msg/i3_msg_i3_msg-main.o
  CCLD     i3-msg/i3-msg
  CC       i3-nagbar/i3_nagbar_i3_nagbar-main.o
  CCLD     i3-nagbar/i3-nagbar
  GEN      man/i3.xml
  GEN      man/i3.1
Input file /home/josh/git/i3/build/man/i3.xml not found
make[1]: *** [Makefile:3797: man/i3.1] Error 1
make[1]: Leaving directory '/home/josh/git/i3/build'
make: *** [Makefile:1242: all] Error 2

Everything is compiling fine on my laptop (Arch Linux 64-bit) however so I am guessing I don't have a required package installed?

Please let me know if I need to provide any more relevant information.

**Comment by kiddico** [comment]
It might have to do with not having [xmlto installed](https://www.archlinux.org/packages/?q=xmlto). I know fairly little about i3's build process, there's quite a bit that's done, but with i3.xml failing, and xmlto being the only dependency for arch related to xml it's probably a good start.
