### ISSUE TITLE
Workspaces display bug when reloading

### ISSUE THREAD

**Issue by tomleb** [Airblader/i3#143]
Output of `i3 --moreversion 2>&- || i3 --version`:

Binary i3 version:  4.13-127-g3bbc3c64 (2017-04-28, branch "gaps-next") © 2009 Michael Stapelberg and contributors
Running i3 version: 4.13-127-g3bbc3c64 (2017-04-28, branch "gaps-next") (pid 897)
Loaded i3 config: /home/tomleb/.config/i3/config (Last modified: Tue 02 May 2017 06:09:47 PM EDT, 69 seconds ago)

The i3 binary you just called: /usr/bin/i3
The i3 binary you are running: i3

URL to a logfile as per http://i3wm.org/docs/debugging.html:

http://logs.i3wm.org/logs/5719721496281088.bz2

**What I did:**

Reload i3 using either 'i3 reload' or Mod-shift-c.

**What I saw:**

The workspaces (left of the bar) disappears. Everything else is fine; i3bar displays information from i3blocks fine. The usual refresh is fine.

Switching workspaces fixes it, the workspaces appears as the should.

**What I expected instead:**

Workspaces should not disappear completely when reloading i3.

**Comment by Airblader** [comment]
See https://github.com/i3/i3/pull/2760. I just need to merge upstream to get the fix in. Will do ASAP.

**Comment by tomleb** [comment]
Perfect, also need to update it on the AUR once it is merged.
Thanks

**Comment by Airblader** [comment]
I've merged it now and pushed the AUR package. Let me know if the update doesn't fix it (but make sure to restart i3 beforehand, not just reload :-))
