### ISSUE TITLE
Custom colors for i3-nagbar

### ISSUE THREAD

**Issue by arcmags** [Airblader/i3#144]
I use a local patch to customize the colors of i3-nagbar.  Would there be any interest if I implemented the setting of these colors via the i3 config file?

**Comment by Airblader** [comment]
Configuring that in the config file makes no sense since i3-nagbar is a standalone tool. Either way, I don't think I'd want this. i3-nagbar is really not a tool I'd recommend anyone to use for anything beyond what i3 uses it for. There's much better suited tools out there.

**Comment by arcmags** [comment]
That's kind of what I figured.  Thanks for the quick reply.
