### ISSUE TITLE
Make failed due to missing bracket

### ISSUE THREAD

**Issue by manuraj17** [Airblader/i3#145]
Output of `i3 --moreversion 2>&- || i3 --version`:

```
Binary i3 version:  4.11 (2015-09-30, branch "4.11") © 2009 Michael Stapelberg and contributors
Running i3 version: 4.11 (2015-09-30, branch "4.11") (pid 25564)
Loaded i3 config: /home/manu/.config/i3/config (Last modified: Monday 22 May 2017 10:52:41 AM IST, 18996 seconds ago)

The i3 binary you just called: /usr/bin/i3
The i3 binary you are running: i3
```

URL to a logfile as per http://i3wm.org/docs/debugging.html:

_REPLACE: URL to logfile_

**What I did:**

Disclaimer: I am already running i3.

I was trying to compile i3-gaps using make and I ran into the following error. 

```
Makefile:2597: warning: ignoring old recipe for target 'testcases/test_inject_randr15-inject_randr1.5.o'
Makefile:4959: *** unterminated variable reference.  Stop.
```

**What I saw:**

Error message as above. 

**What I expected instead:**

Make to complete succesfully. 

I was able to fix this issue by editing the makefile and closing a bracket at line `4959`. 

Being new to the code base and my lack of experience in the languages uses I was not able to fully look into what the root cause of the issue was. In case required I am happy to make a pull request with the fix if I could get some guidance on the code.

**Comment by Airblader** [comment]
> I was able to fix this issue by editing the makefile and closing a bracket at line 4959.

There is no Makefile in the codebase anymore, only a Makefile.am. Please clarify what exactly you did. I'm fairly sure this is not a bug in the repository, though, but a local problem, since many people build this every day.

**Comment by manuraj17** [comment]
@Airblader I was trying to run make after cloning the repo and following the compile steps. I was running `make` after `../configure --prefix=/usr --sysconfdir=/etc --disable-sanitizers`. 
I ran into an error then as shown above and was able to solve it by closing a bracket. 
Please feel free to close this issue if you believe it is a local issue. I was not sure how to get into depth of it.

**Comment by Airblader** [comment]
The Makefile is generated and doesn't even have 4,000 lines on my system. Can you please show the context of that line?

**Comment by manuraj17** [comment]
This is from the Makefile generated in my system, am pasting the block that had the error. 
Pasting along with line number. 
```
4959 am--fnord am--fnord-all $(TEST_LOGS) $(TEST_LOGS:
4960   @ HOST="$(HOST)" \
4961   ; test ".$$HOST" = "." && HOST=` sh /home/manu/Manu/Applications/i3-gaps/config.guess ` \
4962   ; BUILD=` grep "^#### $$HOST " Makefile | sed -e 's/.*|//' ` \
4963   ; use=` basename "$@" -all `; n=` echo $$BUILD | wc -w ` \
4964   ; echo "MAKE $$HOST : $$n * $@"; if test "$$n" -eq "0" ; then : \
4965   ; BUILD=` grep "^####.*|" Makefile |tail -1| sed -e 's/.*|//' ` ; fi \
4966   ; test ".$$BUILD" = "." && BUILD="." \
4967   ; test "$$use" = "$@" && BUILD=` echo "$$BUILD" | tail -1 ` \
4968   ; for i in $$BUILD ; do test ".$$i" = "." && continue \
4969   ; (cd "$$i" && test ! -f configure && $(MAKE) $$use) || exit; done
```

At line number 4959, `$(TEST_LOGS` is missing a bracket. I just added that. so as to be like this below: 
```
4959 am--fnord am--fnord-all $(TEST_LOGS) $(TEST_LOGS):
4960   @ HOST="$(HOST)" \
4961   ; test ".$$HOST" = "." && HOST=` sh /home/manu/Manu/Applications/i3-gaps/config.guess ` \
4962   ; BUILD=` grep "^#### $$HOST " Makefile | sed -e 's/.*|//' ` \
4963   ; use=` basename "$@" -all `; n=` echo $$BUILD | wc -w ` \
4964   ; echo "MAKE $$HOST : $$n * $@"; if test "$$n" -eq "0" ; then : \
4965   ; BUILD=` grep "^####.*|" Makefile |tail -1| sed -e 's/.*|//' ` ; fi \
4966   ; test ".$$BUILD" = "." && BUILD="." \
4967   ; test "$$use" = "$@" && BUILD=` echo "$$BUILD" | tail -1 ` \
4968   ; for i in $$BUILD ; do test ".$$i" = "." && continue \
4969   ; (cd "$$i" && test ! -f configure && $(MAKE) $$use) || exit; done
```

Again, am not sure if this is specific to something in my system or not.

**Comment by Airblader** [comment]
This is entirely generated by automake and nowhere in the repository. Out of curiosity, can you reproduce this error if you run the process again in a new checkout? If so, can you reproduce it using upstream i3?

**Comment by manuraj17** [comment]
I will check on that get back to you with the results.

**Comment by Airblader** [comment]
Any news?

**Comment by manuraj17** [comment]
@Airblader Apologies, I have been travelling. Will probably try to update by weekend.

**Comment by manuraj17** [comment]
@Airblader Apologies for the delay. I had to be away with lot of personal stuff. I tried recreating the issue but was unable to. I guess it was something specific based on the context that I was in. Closing this issue now.
