### ISSUE TITLE
Unable to build

### ISSUE THREAD

**Issue by Ayuei** [Airblader/i3#148]
To preface, I am a noob and fairly new to linux, so if it's something obvious I apologize.

Output of `i3 --moreversion 2>&- || i3 --version`:
```
Binary i3 version:  4.13 (2016-11-08) © 2009 Michael Stapelberg and contributors
Running i3 version: 4.13 (2016-11-08) (pid 1551)o abort…)
Loaded i3 config: /home/vin/.config/i3/config (Last modified: Sat 03 Jun 2017 11:06:00 AEST, 213388 seconds ago)

The i3 binary you just called: /usr/bin/i3
The i3 binary you are running: i3 

```

**What I did:**

I wasn't unable to install polybar on my ubuntu 17.04 distribution and used the instructions found in here to install polybar which required the installation of xcb-randr 1.12. Gaps stopped working after successful installation of polybar.

[Link](https://github.com/jaagr/polybar/issues/463)

**Error output**
``` 
make  all-am
make[1]: Entering directory '/home/vin/Applications/i3-gaps-next/build'
  CCLD     i3
src/i3-randr.o: In function `randr_query_outputs_15':
/home/vin/Applications/i3-gaps-next/build/../../i3-gaps-next/src/randr.c:552: undefined reference to `xcb_randr_get_monitors'
/home/vin/Applications/i3-gaps-next/build/../../i3-gaps-next/src/randr.c:551: undefined reference to `xcb_randr_get_monitors_reply'
/home/vin/Applications/i3-gaps-next/build/../../i3-gaps-next/src/randr.c:570: undefined reference to `xcb_randr_get_monitors_monitors_length'
/home/vin/Applications/i3-gaps-next/build/../../i3-gaps-next/src/randr.c:575: undefined reference to `xcb_randr_get_monitors_monitors_iterator'
/home/vin/Applications/i3-gaps-next/build/../../i3-gaps-next/src/randr.c:577: undefined reference to `xcb_randr_monitor_info_next'
collect2: error: ld returned 1 exit status
Makefile:1493: recipe for target 'i3' failed
make[1]: *** [i3] Error 1
make[1]: Leaving directory '/home/vin/Applications/i3-gaps-next/build'
Makefile:1243: recipe for target 'all' failed
make: *** [all] Error 2
```

I tried removing all the installed packages to no avail and reinstalling them.
I also downgraded xcb-randr in the hopes of getting gaps to work again.
xcb-randr output.
```
pkg-config --print-provides xcb-randr
xcb-randr = 1.11.1
```

**Comment by Airblader** [comment]
I'm going to close because of the reasons mentioned in https://github.com/Airblader/i3/wiki/Compiling-&-Installing.

But to give you a suggestion, try cloning and building in a completely new checkout after the downgrade. xcb-randr 1.12 introduces support for RandR 1.5 which i3 implemented optionally, and it will not be compiled in based on a switch. I assume that your current build configuration tells us to compile it in but with 1.11.1 you no longer have it available, causing the build to fail.

**Comment by ENBYSS** [comment]
@Ayuei How did you downgrade xcb-randr? I cannot find a way to do so.

**EDIT:** Nevermind, I went into the libxcb-1.12 folder and ran `sudo make uninstall`.
