### ISSUE TITLE
keybind to hide indicator?

### ISSUE THREAD

**Issue by eNzyOfficial** [Airblader/i3#150]
Hey @Airblader,

Is there a way to hide the indicator? By default it doesn't show, then when you press mod+v, the indicator shows. Now if I create a new window, the indicator disappears back to the border colour, when I close that new window, the indicator comes back. Or if I press mod+v by accident or even change my mind about creating the new window I'm stuck with the indicator on that window.

It would be nice (unless it's already a thing and I'm completely overlooking it in the docs) to have the ability to set a keybind to hide the indicator if I no longer have any need to see it.

Much love yo! :+1:

**Comment by Airblader** [comment]
Just make the indicator the same color as the border. :-)
