### ISSUE TITLE
Smart gaps specific value?

### ISSUE THREAD

**Issue by TheBabu** [Airblader/i3#151]
This is more of a question than an issue, but is it possible to have when smart gaps is enabled, so that instead of having the outer border gap 0, but instead a specific outer gap value?

Thanks for any help!

**Comment by Airblader** [comment]
No, this isn't possible. 

Closing since it's just a question. Feel free to keep commenting with further questions.

**Comment by TheBabu** [comment]
Thank you for the speedy reply! I guess that answers my question! Thank you!
