### ISSUE TITLE
Quickly adding and removing borders is not very seamless

### ISSUE THREAD

**Issue by TheBabu** [Airblader/i3#152]
Here I am using i3 ipc python to make the border to appear and disappear when it if focused for 0.5 seconds.
I originally posted this question in the ipc python github (acrisci/i3ipc-python#62), but I also wanted to know if the i3 github can also answer my question...

![image](https://user-images.githubusercontent.com/24832107/27504385-74a08474-583d-11e7-8301-5ace83f6a0a4.png)

You can see in this gif that I have it so that when a window is focused a border comes up and then disappears after a couple of seconds. (You can see my code here: http://termbin.com/fsia)
The problem is that the window is sort of "resized", every time you add a border. I don't know if this is possible in i3, but is there a way so that when you add a border it doesn't "resize" the window?
(Using version 4.13)
Thanks for any help!

**Comment by TheBabu** [comment]
Another idea that I have is also having the border always there, but just have the color of the border change... But how would I do that?

**Comment by Airblader** [comment]
This isn't possible in i3-gaps either. I did look into this once, but it's somewhat of a nightmare configuration wise, so I'm not looking to implementing this in i3-gaps.
