### ISSUE TITLE
smart_borders doesn't work correctly

### ISSUE THREAD

**Issue by karambaq** [Airblader/i3#153]
Binary i3 version:  4.13-174-gc6338872 (2017-06-15, branch "gaps-next") © 2009 Michael Stapelberg and contributors
Running i3 version: 4.13-174-gc6338872 (2017-06-15, branch "gaps-next") (pid 6277)
Loaded i3 config: /home/maxq/.config/i3/config (Last modified: Ср 28 июн 2017 15:03:48, 793 seconds ago)

The i3 binary you just called: /usr/bin/i3
The i3 binary you are running: i3

I turn smart_borders on and when this is the only not floating window on the workspace it's fine, but when I open floating window I see borders here. Thanks.

![screenshot-2017-06-28_15 16 33](https://user-images.githubusercontent.com/14233969/27636667-3b19d65c-5c15-11e7-823c-0aabb561503e.png)
![screenshot-2017-06-28_15 16 36](https://user-images.githubusercontent.com/14233969/27636671-409f912a-5c15-11e7-8ae0-70f8a1c247f4.png)

**Comment by Airblader** [comment]
This is by design. Smart borders only affect tiling containers, not floating ones.

**Comment by karambaq** [comment]
No way to fix it?

**Comment by Airblader** [comment]
Can't fix what ain't broken.

You can write a script using the IPC to get the behavior you want.
