### ISSUE TITLE
Proper support of window titlebar

### ISSUE THREAD

**Issue by FichteFoll** [Airblader/i3#158]
It's mentioned in a couple places (including the readme) that window titles don't properly function with the way gaps are implemented in i3-gaps. This issue should serve as a dump to store and follow any infromation related to this problem, because I was unable to find a dedicated one.

Related: https://github.com/Airblader/i3/issues/42, https://github.com/Airblader/i3/issues/48

**Comment by Airblader** [comment]
I think this would be fixed with https://github.com/i3/i3/issues/1966, but we won't know until we have that. Unfortunately it is a severe and deep change in i3 and there are no immediate plans on my part to work on this in the forseeable future.
