### ISSUE TITLE
I3 error Shadow memory range interleaves with an existing memory mapping with kernel 4.13

### ISSUE THREAD

**Issue by CodeMonkey80s** [Airblader/i3#160]
[debug.txt](https://github.com/Airblader/i3/files/1218452/debug.txt)
Output of `i3 --moreversion 2>&- || i3 --version`:

Binary i3 version:  4.13-158-gf0e6dcbf (2017-05-23, branch "gaps-next") © 2009 Michael Stapelberg and contributors
Running i3 version: 4.13-158-gf0e6dcbf (2017-05-23, branch "gaps-next") (pid 1669)
Loaded i3 config: /home/mp/.config/i3/config (Last modified: Wed 09 Aug 2017 10:08:19 PM CEST, 158793 seconds ago)

The i3 binary you just called: /usr/bin/i3
The i3 binary you are running: x-window/i3

https://gist.github.com/xPrzybyLx/214cdf08600e5b9e3fa9750942c2e070

**What I did:**

Installed kernel 4.13.0-rc4 with Nvidia 384.59 binary drivers. Then tried to start i3 by issuing command
`startx` and `i3`.

I have the same issue with kernel 4.12.* but i3 is working fine on my current 4.11.10 + 384.59 nvidia drivers.

**What I saw:**

I3 did not start at all (attached ulr to debug log).

**What I expected instead:**

To run i3.

**Comment by Airblader** [comment]
Does this only happen with i3-gaps or also with the current HEAD of i3?

**Comment by CodeMonkey80s** [comment]
I have recompiled the `i3-gaps` again - but first made a `git pull` to get the latest code.

It seems that for now everything works fine with `kernel 4.12.8` - I haven't checked the `4.13.*` yet...

    mp@blackhole ~ $ which i3
    /usr/bin/i3
    mp@blackhole ~ $ i3 --version
    i3 version 4.13-264-geba03fb3 (2017-08-20, branch "gaps-next") © 2009 Michael Stapelberg and 
    contributors
    mp@blackhole ~ $ uname -a
    Linux blackhole 4.12.8-041208-generic #201708161815 SMP Wed Aug 16 22:17:30 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

**Comment by Airblader** [comment]
I'm going to close due to the combination of it working right now and my question having gone unanswered. If it happens again please answer it and open the issue upstream if it can be reproduced there as well.
