### ISSUE TITLE
Cant install i3-gaps

### ISSUE THREAD

**Issue by mgarbvs** [Airblader/i3#161]
I get this error when compiling.
warning: failed to load external entity "http://docbook.sourceforge.net/release/xsl/current/manpages/docbook.xsl"
compilation error: file /tmp/xmlto-xsl.eMmhOF line 4 element import
xsl:import : unable to load http://docbook.sourceforge.net/release/xsl/current/manpages/docbook.xsl
make[1]: *** [Makefile:3765: man/i3.1] Error 5

This is on a fresh install. Any ideas?

**Comment by Airblader** [comment]
I assume this is some kind of networking problem; the URL is reachable for me. For compiling issues please see https://github.com/Airblader/i3/wiki/Compiling-&-Installing and use channels such as reddit for questions.
