### ISSUE TITLE
Is there an option to modify the 'space' between workspace buttons?

### ISSUE THREAD

**Issue by SyrakuShaikh** [Airblader/i3#164]
version 4.14

After upgrading =i3gaps= from 4.13 to 4.14, I find that the space between workspace buttons (already set 'strip_workspace_numbers' to yes, so only buttons are left) become much larger.

So, is there an option or some methods that I can modify this 'space' between workspace buttons?

Thanks!

**Comment by Airblader** [comment]
Can you post a screen shot? There was no change in this area so this might be a bug.

**Comment by SyrakuShaikh** [comment]
![st-2017-09-06_08-56-46](https://user-images.githubusercontent.com/9691144/30089767-6404b55c-92e1-11e7-8522-9f456d5dc81e.png)
I don't have a screenshot of an old version of i3gaps. It seems to me the width which two workspace buttons occupy can contain three buttons in the old version.

**Comment by Airblader** [comment]
Can you do the following, please?

* First of all, check whether this happens with vanilla i3 4.14. If so, let's move the bug over there.
* Either way, check if a downgrade to 4.13 fixes it so that we can actually pinpoint it to a change of i3.
* Provide your config. :-)

**Comment by SyrakuShaikh** [comment]
- vanilla i3 4.14 & 4.13 don't solve this problem. Big space is still there.
- I have no idea how to downgrade an 'aur' package `i3-gaps-git` to 4.13, therefore cannot provide a screenshot which seems having-the-right-space to me.
- my config is based on yours with slight modifications 
https://gist.github.com/SyrakuShaikh/7e88a587e3411a890d6f4da02210ea85

**Comment by SyrakuShaikh** [comment]
change the config from `set $ws1 "1:  "` to `set $ws1 "1:"` makes it better.
Since this is not a big problem, just let it go.
Thanks. This issue can be closed now.

**Comment by Airblader** [comment]
Fair enough.
