### ISSUE TITLE
Tray cutting part of the output of the status command

### ISSUE THREAD

**Issue by guiniol** [Airblader/i3#166]
**Output of `i3 --moreversion 2>&- || i3 --version`:**

```
Binary i3 version:  4.14-non-git © 2009 Michael Stapelberg and contributors
Running i3 version: 4.14-non-git (pid 978)rl-c to abort…)
Loaded i3 config: /home/guiniol/.i3/config (Last modified: Fri 01 Sep 2017 12:19:01 PM CEST, 606961 seconds ago)

The i3 binary you just called: /usr/bin/i3
The i3 binary you are running: i3
```

**What I did:**

I started i3 with a `tray_output` and a `status_command` on the same screen (I use `py3status` as a status command).

**What I saw:**

The tray and the status command overlap slightly, cutting part of the status command output.
![screenshot from 2017-09-08 12-54-25](https://user-images.githubusercontent.com/3483433/30208806-61e3c802-9495-11e7-9366-116797b5c207.png)

**What I expected instead:**

The status command and the tray should not overlap. Reverting to version 4.13 (4.13-2, in the AUR on Archlinux) fixes this problem. The latest git HEAD has the same problem.

If there's anything else I can to help, just ask.

**Comment by Airblader** [comment]
Can you reproduce this with vanilla i3?

**Comment by guiniol** [comment]
I tried both 4.13 and 4.14 with vanilla i3 and they work properly.

**Comment by Airblader** [comment]
Thanks! This might be related to #164.

**Comment by guiniol** [comment]
Could be. It does feel as if the tray is taking more space than it should, but the status command doesn't know about it.

**Comment by Airblader** [comment]
Can you try applying this patch?

```
diff --git a/i3bar/src/xcb.c b/i3bar/src/xcb.c
index aed431ea..9ed3bb2b 100644
--- a/i3bar/src/xcb.c
+++ b/i3bar/src/xcb.c
@@ -317,7 +317,7 @@ void draw_statusline(i3_output *output, uint32_t clip_left, bool use_focus_color
         draw_util_text(text, &output->statusline_buffer, fg_color, colors.bar_bg,
                        x + render->x_offset + logical_px(block->border_left),
                        bar_height / 2 - font.height / 2,
-                       render->width - logical_px(block->border_left - block->border_right));
+                       render->width - logical_px(block->border_left + block->border_right));
         x += full_render_width;
 
         /* If this is not the last block, draw a separator. */
```

**Comment by guiniol** [comment]
I may have done something wrong, but this is what I end up with: 
![screenshot from 2017-09-08 14-03-13](https://user-images.githubusercontent.com/3483433/30210849-7a75bfde-949e-11e7-8efc-01e625c4e479.png)

Every block in the status bar is now truncated. This was applied to the `gaps-next` branch. The package was half the size of the original package, so this could be me. I'll check out to make sure I compiled it properly.

EDIT: the workspaces on the right are on another screen.

EDIT: same thing with the `gaps` branch

**Comment by Airblader** [comment]
OK, thinking about it some more, let's try this patch:

```
diff --git a/i3bar/src/xcb.c b/i3bar/src/xcb.c
index aed431ea..93575d90 100644
--- a/i3bar/src/xcb.c
+++ b/i3bar/src/xcb.c
@@ -286,6 +286,7 @@ void draw_statusline(i3_output *output, uint32_t clip_left, bool use_focus_color
         color_t bg_color = bar_color;
 
         int full_render_width = render->width + render->x_offset + render->x_append;
+        bool is_border = !!block->border;
         if (block->border || block->background || block->urgent) {
             /* Let's determine the colors first. */
             color_t border_color = bar_color;
@@ -306,7 +307,6 @@ void draw_statusline(i3_output *output, uint32_t clip_left, bool use_focus_color
                                 bar_height - logical_px(2));
 
             /* Draw the background. */
-            bool is_border = !!block->border;
             draw_util_rectangle(&output->statusline_buffer, bg_color,
                                 x + is_border * logical_px(block->border_left),
                                 logical_px(1) + is_border * logical_px(block->border_top),
@@ -315,9 +315,9 @@ void draw_statusline(i3_output *output, uint32_t clip_left, bool use_focus_color
         }
 
         draw_util_text(text, &output->statusline_buffer, fg_color, colors.bar_bg,
-                       x + render->x_offset + logical_px(block->border_left),
+                       x + render->x_offset + is_border * logical_px(block->border_left),
                        bar_height / 2 - font.height / 2,
-                       render->width - logical_px(block->border_left - block->border_right));
+                       render->width - is_border * logical_px(block->border_left + block->border_right));
         x += full_render_width;
 
         /* If this is not the last block, draw a separator. */
```

**Comment by guiniol** [comment]
That works. (or at least, I don't see anything wrong with it at the moment).

EDIT: also works on the 4.14 release (previous test was done on HEAD)

**Comment by Airblader** [comment]
Thanks. I've pushed the commit now. Not sure what system you're on, but I'll update the i3-gaps-next-git package in the Arch AUR as well.

**Comment by guiniol** [comment]
Thanks.
I'm on Arch, but I use the `i3-gaps` in the AUR. What's the difference between `i3-gaps-git` and `i3-gaps-next-git` ?

**Comment by Airblader** [comment]
The latter contains the development branch, the former the release branch. And i3-gaps is built from the release tarball.

**Comment by guiniol** [comment]
Ok. I patched my version of `i3-gaps` until the next release ^^

**Comment by guiniol** [comment]
Hello again.
This happens again with the new release (14.1), but as far as I can see, the patch wasn't included.
Was it expected ?

EDIT: forgot to add, but the patch you provided last time does work on this release too

**Comment by Airblader** [comment]
The fix has never been pushed to gaps (master equivalent), only to gaps-next (next equivalent), so maybe it was just that you had been running it locally, still? Anyway, I also pushed the fix to gaps now. The branching strategy in i3-gaps is a bit weird to manage right now… I'm thinking of simply keeping gaps and gaps-next equal.

**Comment by guiniol** [comment]
I had patched it myself, but I thought `gaps-next` pointed to what was going to be in the next release, hence my confusion ^^
So, `gaps-next` is a reimplementation of the gaps ? Should I be running it ?

**Comment by Airblader** [comment]
gaps is the equivalent of i3's master and gaps-next that of next. Not having merged this patch into gaps during the release was simply a mistake on my end. :-)

I'd typically recommend going with gaps-next and I personally run that one as well. There's a chance you'll catch a bug earlier than others, but you'll also get the fix and features quicker.

**Comment by guiniol** [comment]
Ok. Switched to gaps-next!
