### ISSUE TITLE
Rounded corners

### ISSUE THREAD

**Issue by ghost** [Airblader/i3#167]
Rounded corners are super sexy. There are patches for some floating wms (I know about Openbox, Fluxbox and FVWM). Is there any chance of implementing them in i3?

**Comment by Airblader** [comment]
I don't really see a point for that in a tiling WM, but tastes differ. However, I'm not looking to add something like that to i3-gaps, no. If you do write a patch for it feel free to show it here anyway though, if it turns out to be surprisingly easy to implement I might reconsider.

**Comment by weilbith** [comment]
It seems like a lot of people would like this: [reddit post](https://www.reddit.com/r/unixporn/comments/7h0rm0/what_would_you_want_in_a_wm/)

**Comment by mrjovanovic** [comment]
Would you perhaps consider it as an option for floating windows?

**Comment by Airblader** [comment]
AFAIK a mandatory prerequisite for this would be support of the Shape extension (correct me if I'm wrong). This has in theory been accepted upstream, so once someone landed that in i3 we could think about revisiting rounded corners. I'm definitely not willing to add Shape only in i3-gaps as that's likely a lot of maintenance overhead.

**Comment by vn-ki** [comment]
Any updates on this? This is something I'm really looking forward to.

**Comment by syslino** [comment]
I'd like this feature as well! would look great with the gaps extension on i3!

**Comment by emad-elsaid** [comment]
Hello there, I landed on this issue while looking for making windows corners rounded a little, After reading the thread I was thinking maybe adding the feature doesn't require a lot of expertise? so if someone can explain how this would be implemented I can experiment a little on my machine, maybe come up with an implementation that is sufficient for most people?

So @Airblader Is there an implementation in mind you think will fit the current code structure?

**Comment by Airblader** [comment]
As stated above, the first step IMHO is to support Shape in i3.

**Comment by emad-elsaid** [comment]
Just to make sure we're on the same page, you're referring to this 
https://www.x.org/releases/X11R7.7/doc/xextproto/shape.html

correct?

**Comment by Airblader** [comment]
Yes, that's the extension.

**Comment by baronleonardo** [comment]
any news about this feature ?

**Comment by Airblader** [comment]
Shape has landed in i3. Specifically regarding rounded corners there's no news.

**Comment by Demonstrandum** [comment]
Would be interesting to see, I think.

**Comment by Airblader** [comment]
Please don't comment unless there's information to add. Each comment sends an email to everyone watching this issue. If you just want to voice support, you can do with reaction emojis. Thanks!

**Comment by Trollwut** [comment]
There is a fork, where some user tried to implement rounded corners: https://github.com/resloved/i3

Reddit thread (with scrot) here: https://www.reddit.com/r/unixporn/comments/8i8ik6/i3gaps_hacky_i3_rounded_titlebar/

And here the changes on the fork: https://github.com/resloved/i3/commit/83a12f774f8fc177ac459f5abbcef4a347e7319c

Can someone confirm this might be the right approach? Unfortunatelly I'm not too fit in C, but maybe this will help someone out here.

**Comment by resloved** [comment]
Weird to see my fork in this thread, but I wouldn't really suggest it to anyone. When I originally made the changes I knew essentially nothing about X or Cairo so the implementation is really naive. Might have to look into it again since shape is finally here.

**Comment by resloved** [comment]
Got it to work!

![preview](https://i.imgur.com/ByQZ168.png)
 
It's just a reimplementation of this bspwm patch: https://github.com/Javyre/bspwm/commit/6ccad79a927387780e497c4c613067286989984b

You can find my changes here: https://github.com/resloved/i3/commit/3a60c56087cc0f981f5b62f73d22697d9a4cca0d

I'm sure there are quite of few issues that still need to be handled (I can think of full screen windows), but for the most part it's the same aliased rounded corner implementation most window managers have.

**Comment by Trollwut** [comment]
Well if that isn't a Happy Easter present! Those borders look awesome-sexy! Thanks for your work

Rounded corners still look a bit cut-off when using a high-contrast color and a small border width:

- [border pixel 4](https://i.imgur.com/SvBOZYU.png) - rather ok
- [border pixel 2](https://i.imgur.com/UYEZhnv.png) - whoopsie!

Anything with a border width higher than 3 or simply a color that doesn't have a strong contrast looks delicious, though.

Maybe add another x-pixel-smaller circle in the favored color?

Man am I happy to see this progress!

**Comment by DomHudson** [comment]
Thank you very much for implementing this - it looks great! I've noticed that in "tabbed" mode, the tabs are above the rounded window.

![Screenshot from 2019-04-18 19-42-02](https://user-images.githubusercontent.com/10864294/56383716-726a1900-6212-11e9-8c42-ae12c2078dbf.png)

**Comment by santos-j** [comment]
From one side, this makes sense. The window itself has rounded corners, but the window decoration remains unchanged. The same would happen if the containers were stacked. 

Therefore, the bottom of the windows should always be rounded, but the top should only be rounded if not in tabbed or stacked modes, and the decoration should have rounded corners accordingly.

**Comment by resloved** [comment]
Just pushed an update that removes the rounded corners on full-screen: https://github.com/resloved/i3/commit/b9e7a0bdf9d9baed15581e2950ef3b48ef07e96c

The issue @DomHudson mentioned happens whenever a window has a title bar, not just in tabbed mode. It would make sense to just round the decoration like @facocalj suggested, but what if the title bar is smaller then the set radius?

![Issue](https://i.imgur.com/4uL0k9X.png)

Is there a container that includes both the window and decorations? That would make this much easier.

**Comment by Demonstrandum** [comment]
Why do the corners look so incredibly jagged in almost all rounded-corner implementations I've seen, except from on macOS? How could one even anti-alias window borders?

![2019-04-21-153956_97x73_scrot](https://user-images.githubusercontent.com/26842759/56470943-4930cf00-6444-11e9-8049-9e55d49f6d64.png)

![2019-04-21-155304_140x98_scrot](https://user-images.githubusercontent.com/26842759/56470991-f0156b00-6444-11e9-9346-f04671a373e4.png)

**Comment by resloved** [comment]
@Demonstrandum The shape extension uses an array of 1s and 0s (1-bit pixmap) to define what pixels are supposed to be masked or kept. It doesn't allow for any level of transparency that would be needed to anti-alias the edge. From what I've read it seems to just be a limitation of X.

**Comment by nirvdrum** [comment]
@resloved Nice work! FYI, you may want to disable rounded corners when in tabbed mode, too. They look a little strange below the tab bar, but certainly not unusable.

**Comment by weilbith** [comment]
Can we draw only the bottom two corners round for the tabbed mode? 🤔

**Comment by resloved** [comment]
I've pushed an update that prevents the top corners from being rounded when there is a title bar. This includes stacked and tabbed layouts, as well as when the border is set to 'normal' instead of 'pixel'.

![Stacked](https://i.imgur.com/X3GDlB6.png)

![Tabbed](https://i.imgur.com/SJ9u0jo.png)

![Normal Border](https://i.imgur.com/7eCqyNS.png)

If you notice any issues let me know! I guess rounding the title bar itself is next on the list.

**Comment by weilbith** [comment]
@resloved this is just awesome! Do you already have a solution approach with a higher configured corner radius than the title bar is height?

**Comment by santos-j** [comment]
First of all, thanks to @resloved for all his efforts!
I forked his repository and played a bit with roundness, check what I've got here:

![screenshot_20190427_222539](https://user-images.githubusercontent.com/8865676/56855233-d63fc080-693b-11e9-8e6b-ee9b5bc62f04.png)
![screenshot_20190427_222533](https://user-images.githubusercontent.com/8865676/56855234-d6d85700-693b-11e9-9fe0-7f5b42fc31b1.png)
![screenshot_20190427_222527](https://user-images.githubusercontent.com/8865676/56855235-d770ed80-693b-11e9-9357-31c43d0a33ed.png)

The important bits are here: https://github.com/facocalj/i3/commit/a9af5b595b3665c2c1d576e3c69cb6a587426677
But please check the latest commit for a fully working version.

@resloved You added shaping to the containers inside the recursive call to draw decorations (x_deco_recurse), I added shaping to the titles right after the recursive call, so all the decorations are in place. I tried to use a single function to shape both, but for some reason, the shaping to containers has to be applied inside this recursive call, otherwise stacked containers don't get the bottom round corners.

Please let me know what you guys think!

**Comment by DomHudson** [comment]
Great job @facocalj!

With your fork, I noticed that it is possible to accidentally end up with a window with the top square but the bottom rounded. If you create two windows, change them to tabbed/tiled, then close one of the windows - the remaining window doesn't have the top rounded. Believe this is due to the cache.

**Comment by resloved** [comment]
I've pushed a new update based on @facocalj implementation: https://github.com/resloved/i3/commit/81ae7b0363c8686545afe6011d6de5c039ea956e

![Small Title Bar](https://i.imgur.com/4NV9LG9.png)

I've reworked `x_shape_window` to position the rounded corner based on the decoration height. In the case of a title bar the rounded corner is outside the frame and will not be drawn, if the title bar has no height the rounded corner will be drawn normally, if the height of the title bar is in between it will draw partially for both the title and window. In other words -- you can use whatever font size for your title now.

I have encountered issues still:
+ I believe there is a 1px difference between no title bar and tabbed mode with a single window, will have to look into it more
+ I was also able to break the windows through a combination of stacks and tabs. 
I assume the combination just changes the decoration height in a way I wouldn't expect.

![Broken](https://i.imgur.com/Xg8NiIB.png)

**Comment by santos-j** [comment]
I played a bit with @resloved's updated fork and I got a somewhat similar broken result:

![screenshot_20190428_142402](https://user-images.githubusercontent.com/8865676/56865039-696f0980-69c1-11e9-9b33-3325103a3e2c.png)
(compton helped me to see the distinction between containers)

What should be the excepted behaviour of the rounded corners in a more complex tabbed/stacked + split layout? 
Should we only round the top and bottom corners of a window, or should we round all the corners of all containers regardless of their placement?  

The former option could potentially be achieved with a new flag in `con_state`, to indicate whether the given container is already inside a rounded parent, and therefore skip the shaping.
The latter option raises a new question, how should we fill the rounded corner "gap"? Transparency, solid color?

**Comment by santos-j** [comment]
I fixed the rounding of the inner titles, as well as the top edge of containers:
![screenshot_20190428_174304](https://user-images.githubusercontent.com/8865676/56867471-73066a80-69dd-11e9-8390-76ab5d27d84d.png)
But I couldn't find a way **not** to round the bottom edge of a container in case there is a title bar below the container.

The commit https://github.com/facocalj/i3/commit/4632608346395d93fc4d311d934030062947e7bb might fix the issue raised by @resloved

**Comment by janleskovec** [comment]
How does it look with borders?

**Comment by resloved** [comment]
@slole Borders look like this:

![Borders](https://i.imgur.com/zhOS45x.png)

This does bring up the issue of using borders that are smaller then the corner radius allows for:

![Small](https://i.imgur.com/afoBRPY.png)

The simplest solution I could think of was drawing the border corner over the window, but I'm not sure if that's always appropriate.

**Comment by janleskovec** [comment]
What about drawing the border around the curve (both the border and window would be curved)? Or would that require drawing over the window?

**Comment by resloved** [comment]
From my understanding, that would require the border to be a separate window and I'd rather not restructure how it's handled currently.

**Comment by janleskovec** [comment]
Thanks for the clear-up

**Comment by Trollwut** [comment]
@Airblader Do you have intentions to re-open this issue? I think it's now in active development and being open it maybe attracts more people to it. If this feature is not going to be implemented in i3-gaps anyway, maybe @resloved should consider having issues on his fork :)

**Comment by Airblader** [comment]
I will reopen for now, but would suggest that @resloved either opens a Draft PR or maintains it in a fork (whichever they prefer) as reviewing linked commits is a bit tedious. I'm happy to give it a quick look in a PR where we can see all changes and comment on individual parts.

My main concern is keeping the changes local enough to make sure i3-gaps can be synchronized from upstream easily enough (this is my No. 1 goal with i3-gaps). So all of the Shape logic could be moved to a separate file as this avoids merge conflicts. In terms of how the shaping is hooked into rendering I'd have to think & review it still.

**Comment by santos-j** [comment]
Thanks for reconsidering!

Regarding the hooks, that is actually something that I started to wonder over the weekend. Playing with the corners inside `x.c` doesn't feel quite right, as we are doing a lot of effort to handle edge cases of title bars and splits. Maybe something called in `render.c`, e.g., inside `render_con` like the gaps, would be the right way to go.

**Comment by resloved** [comment]
I was going to wait until we squashed some of the larger issues, but you're right its getting a bit messy in here.

Here's the draft pull request: https://github.com/Airblader/i3/pull/294

**Comment by DomHudson** [comment]
Are you finding that the shadows are drawn beneath the tabs on tabbed/stacked mode? This is on resloved's most recent commit. Had a quick look and haven't worked out why this has started happening yet.

![Screenshot from 2019-05-01 21-41-02](https://user-images.githubusercontent.com/10864294/57041427-0e0b7880-6c5a-11e9-8662-cf53dfd00d9f.png)

**Comment by Airblader** [comment]
Shadows are likely gonna be difficult to support properly given the unconventional way i3 renders decorations.

**Comment by OblongCheese** [comment]
I have installed the Arch package i3-gaps-rounded-git and removed the old i3-gaps package, yet my corners are not round. Is there something I need to configure in i3config?

**Comment by resloved** [comment]
@OblongCheese As of 001816781d591bd0038fb8a3e637743b16987aa9 you can set the corner radius via i3config. Just use `border_radius x` where x is the size of the radius (People seem to like 4).

In the future if anyone needs support related to rounded corners DM me on reddit (/u/resloves) or make an issue on my [fork](https://github.com/resloved/i3) instead of adding more clutter to this issue.

**Comment by GrbavaCigla** [comment]
Hi, I have issue that some of configuration (including `border_radius`) doesn't work.
I am on arch and I installed `i3-gaps`
```
gaps inner all set 20
gaps outer top 5
border_radius 5
```
All of these 3 don't work, but when I install `i3-gaps-rounded-git`, `border_radius` works, but again `gaps inner all set 20` and `gaps outer top 5` doesn't. Also it works when I set it to `gaps inner 20`, but I don't know how to set it to top-only gap.

Thanks in advance.

**Comment by seniorm0ment** [comment]
It would be really nice to have this integrated directly into i3-gaps

**Comment by resloved** [comment]
@GrbavaCigla I assume this is a result of my fork being out of date compared to upstream. I'm not really in a place where I want to automatically update my fork in case a merge goes south, so for the time being I would suggest forking resloved/i3 and merging with the up to date airblader/i3 yourself.

@grravity From my understanding airblader is still working on getting i3-gaps merged into core i3, so he isn't merging any pull requests (which is totally reasonable).

**Comment by g00nix** [comment]
Why don't you guys just merge it into this project, instead of keeping border_radius on a separate fork?

**Comment by Airblader** [comment]
Closing this issue now that the PR has been closed as well. Please find the rationale I gave there.

**Comment by g00nix** [comment]
@Airblader no matter if you close the ticket or the PR, people still want this and they will still request it. This issue will probably get comments for the next years, even if it is closed.

**Comment by Airblader** [comment]
That's fine, but if I have no intention of merging such a feature anymore then there's no point in keeping the issue open.

**Comment by emad-elsaid** [comment]
I like that you're clear about your intention and I respect that, although it's a nice feature to have but it's up to you to decide if you want to merge it :wave:

**Comment by Airblader** [comment]
Right, and part of the reason I'm closing it is that picom is moving towards supporting rounded borders independent of window manager and in a much more powerful way using shaders. That's just far superior to patching in border with Shape and the like, and more importantly just renders it unnecessary to put this into i3-gaps.

**Comment by g00nix** [comment]
> and part of the reason I'm closing it is that picom is moving towards supporting rounded borders

you could have lead with that

**Comment by JonnyHaystack** [comment]
@g00nix he did.. He said see the rationale he gave in the PR, which is exactly that.

**Comment by g00nix** [comment]
> @g00nix he did.. He said see the rationale he gave in the PR, which is exactly that.

I am sorry, I initially didn't find the PR, but I did read through everything now and I found the PR and the message about picom in the PR. I initially thought he didn't care about the request and about the people who want this (as the atmosphere of this ticket has been over the years) and that he was just closing the ticket as there was no resolution in sight.

Now I understand it was just poorly understood by me, as I didn't also read all the comments in the PR. So again, my apologies.

**Comment by Airblader** [comment]
> I initially thought he didn't care about the request and about the people who want this

So just to go on record here, it's not that I don't get that people want certain features or that I don't care. I just set the priority at being able to keep i3-gaps up to date with i3 (being the only maintainer, particularly), as otherwise we end up being stuck at i3-gaps 4.8 while i3 is at 4.34, sort to speak, and ultimately I think that's just more important to / for the larger group of people. 

That isn't to say a single feature makes things unbearable to maintain, but there's always another feature or config option someone wants, and importantly it's not just merging a PR, it's making sure this feature is maintained for years to come.

On top of that after years of pushback we now have the general OK to get i3-gaps features — including gaps — into i3 itself, which is all the more reason not to keep adding features. Admittedly there hasn't been progress on this in a long time either, but that's because contributions towards that haven't really come up yet and I myself don't have the time to do that.

**Comment by g00nix** [comment]
@Airblader thank you for the clarification

**Comment by jorhelp** [comment]
> I don't really see a point for that in a tiling WM, but tastes differ. However, I'm not looking to add something like that to i3-gaps, no. If you do write a patch for it feel free to show it here anyway though, if it turns out to be surprisingly easy to implement I might reconsider.

It's too fuck!
