### ISSUE TITLE
Unable to install from AUR: cannot load docbook.xsl

### ISSUE THREAD

**Issue by mathpunk** [Airblader/i3#168]
My error is similar to that in #161. However, I am using the AUR repo, and it doesn't appear to be a network issue, as I am able to retrieve the resource from docbook.sourceforge.net using a browser.

warning: failed to load external entity "http://docbook.sourceforge.net/release/xsl/current/manpages/docbook.xsl"
compilation error: file /tmp/xmlto-xsl.UKNJTx line 4 element import
xsl:import : unable to load http://docbook.sourceforge.net/release/xsl/current/manpages/docbook.xsl
make[1]: *** [Makefile:3803: man/i3.1] Error 5
make[1]: Leaving directory '/tmp/packerbuild-1000/i3-gaps/i3-gaps/src/i3-4.14/build'
make: *** [Makefile:1247: all] Error 2
==> ERROR: A failure occurred in build().
    Aborting...
The build failed.

**Comment by Airblader** [comment]
Does this also happen when building `i3-git`? I'm not sure what to do against this, it just strikes me as a user-side configuration problem of some sort.

**Comment by mathpunk** [comment]
It does happen with i3-git, and I found similar errors turning up in other contexts. I installed `docbook-xsl` and `xorg-docs` using pacman, and I was able to install i3-gaps after that.
