### ISSUE TITLE
System clock not sane with a sane clock

### ISSUE THREAD

**Issue by Redrield** [Airblader/i3#173]
https://hasteb.in/yofolafaho.coffee

**What I did:**

I tried to install i3-gaps from the Arch Linux AUR package

**What I saw:**

Configure continued as normal until it checked build environment sanity, at which point it complained that newly created files were older than distributed files. The system clock was sane at the time of compilation

**What I expected instead:**
Configure to proceed correctly, and to compile the package.

**Comment by Airblader** [comment]
Can you reproduce this with the build of vanilla i3 as well?

**Comment by Redrield** [comment]
Yes

**Comment by Airblader** [comment]
Thanks, that's what I've figured. i3-gaps doesn't change the build system in any way. Can you please report this issue over at i3/i3, directly, so we can fix it upstream? I'll close this one here. Thanks!
