### ISSUE TITLE
Why does focusing a floating window cause it to raise to the top now?

### ISSUE THREAD

**Issue by Hubro** [Airblader/i3#174]
One of the things I noticed immediately when switching from i3 to i3-gaps was that any time I mouse-over a window (which focuses it) it raises to the top. This is bothering me constantly now, as it hides prompts and dialog windows under the parent window when I move my mouse to click a button.

I don't know for certain if this has something to do with i3-gaps, or if it has to do with the fact that I upgraded from Debian stretch's packaged i3 (version 4.13-1) to i3-gaps which is version 4.14.1.

I have searched the user manual for a setting that affects whether or not floating windows are raised to the top when they receive focus, but I'm unable to find anything.

The old behavior was that windows were focused when moused over (controlled by the [`focus_follows_mouse`](https://i3wm.org/docs/userguide.html#_focus_follows_mouse) setting) but they weren't raised to the top of the floating windows until I actually clicked within the window. Has this behavior been changed in i3-gaps, or just a newer version of i3? Can it be configured?

**Comment by Airblader** [comment]
This is a change in i3 between 4.14 and 4.14.1. It wasn't exactly intended that way and is planned to be fixed, see https://github.com/i3/i3/issues/2990

**Comment by Airblader** [comment]
Side note: no, there's no configuration for it; you can revert the commit that brought the change for now, though, if you want.

**Comment by Hubro** [comment]
Excellent, thanks for the quick and perfect reply! I will be reverting to 4.14 for now.
