### ISSUE TITLE
Artefacts in gaps when opening gl contexts

### ISSUE THREAD

**Issue by ColombianViking** [Airblader/i3#175]
Whenever i open a opengl program in a container, the parent of the container produced weird behavior.
This only happens in normal tiling mode, does not happened in stacked or tabbed mode.
[I've taken some screenshots of the weirdness](https://imgur.com/a/y0Doy)

**Comment by Airblader** [comment]
https://github.com/Airblader/i3/blob/gaps-next/README.md#gaps
