### ISSUE TITLE
Additional mode for `smart_borders`

### ISSUE THREAD

**Issue by paulbdavis** [Airblader/i3#177]
Is it possible for `smart_borders` to have a third option (maybe `on_no_gaps`) that combines the behaviour of the other two? Meaning that it hides the borders only if it is a solo container *and* gaps are 0 to the edge?

- solo container && gap > 0: show border
- solo container && gaps == 0: hide border
- many containers && gaps >= 0: show border

~~If this is something you would merge but not want to work on yourself, I can start looking into the codebase (though it's probably a bit beyond my abilities)~~

**Comment by Airblader** [comment]
I don't think we need a new mode, we just need to fix the logic. At some point we also added `hide_edge_borders smart` to vanilla i3, which is (currently) a synonym for `smart_borders on`. So we essentially have two different options:

* smart_borders off | no_gaps → if set, only draw borders if the outer gaps are 0.
* hide_edge_borders smart → draw borders only if it's the only container

So if *both* are set, those two conditions should be united, leading to the behavior you want. Right?

**Comment by paulbdavis** [comment]
That seems like it would be just as easy for me to implement, but would it make explaining how the setting interact more complex, versus simply having a new option for `smart_borders`?

Alternatively, what about adding `no_gaps` to the `hide_edge_borders` option? That would explicitly tie it to the edge borders only (vs the more general `smart_borders`)

**Comment by Airblader** [comment]
> Alternatively, what about adding no_gaps to the hide_edge_borders option? That would explicitly tie it to the edge borders only (vs the more general smart_borders)

I think I like this the most. Thanks for the PRs, even with tests. Awesome!
