### ISSUE TITLE
Can't get transparency to work

### ISSUE THREAD

**Issue by ghost** [Airblader/i3#183]
I have compton and have added -t but it still doesn't greets me with transparency

here's my config file: https://paste.pound-python.org/show/Qf2JAlso0UjvaGprL29U/

(isn't pretty, but it *kinda* works)

**Comment by Airblader** [comment]
There's not a single RGBA color in your config. If you don't tell i3bar to use a partially transparent color, it won't do so. That is assuming (guessing, really) that that is what you are trying to do.

**Comment by ghost** [comment]
So what would be a partially transparent color? Which one do you think it's pretty?

**Comment by Airblader** [comment]
I'll leave the decision of your colors to you. If you want full transparency, use `#00000000`.

**Comment by ghost** [comment]
Thanks, it worked

You're the best! <3
