### ISSUE TITLE
Getting relative coordinates in i3bar for click events.

### ISSUE THREAD

**Issue by pallavagarwal07** [Airblader/i3#184]
Output of `i3 --moreversion 2>&- || i3 --version`:

```
Binary i3 version:  4.14.1-227-g13ca7830 (2017-12-12, branch "gaps-next") © 2009 Michael Stapelberg and contributors
Running i3 version: 4.14.1-227-g13ca7830 (2017-12-12, branch "gaps-next") (pid 1230)
Loaded i3 config: /home/pallav/.config/i3/config (Last modified: Thu 14 Dec 2017 01:40:30 AM IST, 573656 seconds ago)

The i3 binary you just called: /nix/store/bn7rh8sh335j512z9wqzrjxvwfc6a0lx-i3-gaps/bin/i3
The i3 binary you are running: /nix/store/bv08nzkkzcaqbb1w0dyfc90njik1z33g-i3-gaps/bin/i3
```

Hi, I have my own version of status_command script for i3bar. However, for click events, I noticed that the coordinates received in stdin are absolute coordinates wrt to the screen corner.
How do I get the relative coordinates of the click (wrt to the block clicked)? Since the block may shift due to addition of icons at the end (chrome, deluge, nm-applet etc), I can't really use the click position to do anything meaningful.
For now, I have patched the i3bar code on my local machine to also provide the coordinates in the json for click events in stdin.

**Comment by Airblader** [comment]
See https://github.com/i3/i3/issues/2767

Feel free to send a PR to i3!

**Comment by pallavagarwal07** [comment]
Done :smile:
https://github.com/i3/i3/pull/3095
