### ISSUE TITLE
Dead link in wiki

### ISSUE THREAD

**Issue by DougBeney** [Airblader/i3#185]
[In this part of the wiki](https://github.com/Airblader/i3/wiki/Compiling-&-Installing), under Arch, the [i3-gaps-git](https://aur.archlinux.org/packages/i3-gaps-git/) link is dead. I think you meant to link to this: https://aur.archlinux.org/packages/i3-gaps.

Cheers.

**Comment by Airblader** [comment]
Yes, fixed. Thank you!
