### ISSUE TITLE
Enhancement - Allow Outer Gap to be set to a Lower Value than Inner Gap. 

### ISSUE THREAD

**Issue by stshow** [Airblader/i3#186]
Output of `i3 --moreversion 2>&- || i3 --version`:

Binary i3 version:  4.14.1 (2017-09-24) © 2009 Michael Stapelberg and contributors
Running i3 version: 4.14.1 (2017-09-24) (pid 904) abort…)
Loaded i3 config: /home/steven/.config/i3/config (Last modified: Thu 28 Dec 2017 11:38:07 AM EST, 10395 seconds ago)

The i3 binary you just called: /usr/bin/i3
The i3 binary you are running: i3

**What I did:**

i3 config contains:

```
gaps outer 0
gaps inner 5
```
**What I saw:**
Outer gap is not able to be set to a value lower than the inner gap. Both gaps appear to be 5 px. 

**What I expected instead:**
The outer gap is 0 px, while the inner gap is 5 px.

**Comment by Airblader** [comment]
The outer gap is an additional gap that only applies on the outside. However, the inner gap applies around all edges of a window, so also outside. Which means the total gap at the edge is the sum of both. This is intended.
