### ISSUE TITLE
Put mouse on center of new focused window

### ISSUE THREAD

**Issue by ghost** [Airblader/i3#187]
Whenever I focus a new window, I'd like the mouse to be moved to the center of that window.

I only found the option `focus_follows_mouse` which does the opposite.
I looked at the wrapping and warping, but neither did the job.

Any hints?

**Comment by Airblader** [comment]
There's no option to do this in i3. However, it should be easy enough to write a script yourself. Here's a quick version:

```
#!/usr/bin/env bash
# vim:ts=4:sw=4:expandtab

xprop -root -spy _NET_ACTIVE_WINDOW | while read win; do
    eval $(xdotool getactivewindow getwindowgeometry --shell)
    X=$((X + (WIDTH / 2)))
    Y=$((Y + (HEIGHT / 2)))

    xdotool mousemove ${X} ${Y}
done
```
