### ISSUE TITLE
Hide tabs

### ISSUE THREAD

**Issue by chiguiredev** [Airblader/i3#188]
Allow to hide tabs on tablayout and stack layout

**Comment by Airblader** [comment]
I'm willing to consider merging if someone shows a PR which isn't too complex.

**Comment by minawk** [comment]
Additional to that, allow also to change the position of the tab.

**Comment by Airblader** [comment]
Please no piggy-backing on feature requests. That's a completely different feature.

**Comment by Airblader** [comment]
I now think if the is worth the effort, we should find a way to do this upstream.
