### ISSUE TITLE
i3-msg 'exec echo "," '

### ISSUE THREAD

**Issue by raingart** [Airblader/i3#192]
Output of `i3 --moreversion 2>&- || i3 --version`:

`i3 version 4.14.1 (2017-09-24) © 2009 Michael Stapelberg and contributors`

I try to print the text in status bar and which has a comma - `,`

but see error:

```
ERROR: Your command: exec echo "," 
ERROR:                           ^^
ERROR: Expected one of these tokens: <end>, '[', 'move', 'exec', 'exit', 'restart', 'reload', 'shmlog', 'debuglog', 'border', 'layout', 'append_layout', 'workspace', 'focus', 'kill', 'open', 'fullscreen', 'sticky', 'split', 'floating', 'mark', 'unmark', 'resize', 'rename', 'nop', 'scratchpad', 'swap', 'title_format', 'mode', 'bar', 'gaps'
[{"success":true},{"success":false,"parse_error":true,"error":"Expected one of these tokens: <end>, '[', 'move', 'exec', 'exit', 'restart', 'reload', 'shmlog', 'debuglog', 'border', 'layout', 'append_layout', 'workspace', 'focus', 'kill', 'open', 'fullscreen', 'sticky', 'split', 'floating', 'mark', 'unmark', 'resize', 'rename', 'nop', 'scratchpad', 'swap', 'title_format', 'mode', 'bar', 'gaps'","input":"exec echo \",\" ","errorposition":"            ^^"}]
```
How can I fix this?

**Comment by Airblader** [comment]
> I try to print the text in status bar and which has a comma

I don't know why you'd need `exec` for that. You haven't shown your config, so it's impossible to tell what you are trying to do for me.

**Comment by raingart** [comment]
@Airblader 
I use https://github.com/ultrabug/py3status/ (this is a status bar written on a python)

example bit config py3status:
```
deadbeef2 {
	    format = 'Diddy feat. Keyshia Cole, Pharrell & T.I. - Last Night (Remix)' #example
            on_click 1 = 'exec echo "$OUTPUT" | xclip -selection c && notify-send "Copied to clipboard" "$OUTPUT"'
}
```
The point is that when you click on it, it's copied to the clipboard _format_

but an error occurs:
![screenshot from 2018-01-26 14-49-56](https://user-images.githubusercontent.com/13064767/35440528-78bdcdc6-02a8-11e8-9e2b-62dff5164dfb.png)

since _i3-msg_ refers to _i3_ (but not to py3status)  i decided to write here.

**Comment by Airblader** [comment]
I think you're looking for https://github.com/i3/i3/issues/2122

**Comment by raingart** [comment]
@Airblader Thank you. It really looks like.
But I tried to sort out different types of combinations and not one led to success

```
i3-msg "exec echo \\"asd,\\""
i3-msg exec "echo \\"asd,\\""
i3-msg exec echo \"asd,\" 
i3-msg exec echo \\"asd,\\"
i3-msg 'exec echo \",asd\" '  
```
In what I'm wrong. I also used different types of quotes. I'm too dumb to understand what's wrong and find a working option. Do you have time to help me? if not, I understand

**Comment by Airblader** [comment]
My position on these quoting issues is this one:

> In general, I’d recommend creating small shell scripts that contain commands where you’d need to worry about quoting.
