### ISSUE TITLE
[BUG]Wrong interpreting of colon in config file 

### ISSUE THREAD

**Issue by Kyczan** [Airblader/i3#193]
Output of `i3 --moreversion 2>&- || i3 --version`:

Binary i3 version:  4.14.1 (2017-09-24) © 2009 Michael Stapelberg and contributors
Running i3 version: 4.14.1 (2017-09-24) (pid 20923)bort…)
Loaded i3 config: /home/kowal/.config/i3/config (Last modified: Sat 03 Feb 2018 01:24:58 PM CET, 166 seconds ago)

The i3 binary you just called: /usr/bin/i3
The i3 binary you are running: i3

**What I did:**

I'm pressing $mod+d
`Mod4+d exec --no-startup-id rofi -modi 'drun,window,run' -show drun`
It works when it is run from terminal

**What I saw:**

ERROR: Received ConfigureNotify for unknown window 0x00800000
ERROR: Received ConfigureNotify for unknown window 0x00800001
ERROR: Received ConfigureNotify for unknown window 0x00800002
ERROR: Received ConfigureNotify for unknown window 0x00800003
ERROR: Received ExposeEvent for unknown window 0x00800003
ERROR: Received ConfigureNotify for unknown window 0x00800003
ERROR: Expected one of these tokens: <end>, '[', 'move', 'exec', 'exit', 'restart', 'reload', 'shmlog', 'debuglog', 'border', 'layout', 'append_layout', 'workspace', 'focus', 'kill', 'open', 'fullscreen', 'sticky', 'split', 'floating', 'mark', 'unmark', 'resize', 'rename', 'nop', 'scratchpad', 'swap', 'title_format', 'mode', 'bar', 'gaps'
ERROR: Your command: exec --no-startup-id rofi -modi 'drun,window,run' -show drun
ERROR:                                                            ^^^^^^^^^^^^^^^
ERROR: Expected one of these tokens: <end>, '[', 'move', 'exec', 'exit', 'restart', 'reload', 'shmlog', 'debuglog', 'border', 'layout', 'append_layout', 'workspace', 'focus', 'kill', 'open', 'fullscreen', 'sticky', 'split', 'floating', 'mark', 'unmark', 'resize', 'rename', 'nop', 'scratchpad', 'swap', 'title_format', 'mode', 'bar', 'gaps'
ERROR: Your command: exec --no-startup-id rofi -modi 'drun,window,run' -show drun
ERROR:                                                            ^^^^^^^^^^^^^^^
(END)

**What I expected instead:**
Rofi should run

**Comment by Airblader** [comment]
This is not a gaps specific problem so it should be opened against upstream. However, you don't need to do that either. We know this is how it behaves and don't want to change it for compatibility reasons. You need to quote and escape the arguments correctly which will become pretty unreadable, so my actual suggestion would be to put it in a script and execute that script.

You can find this issue in the i3 issue tracker. I don't have time to search for it right now, sorry.

**Comment by Kyczan** [comment]
Thanks for respond. I also analysed source code of Rofi and find out that there is another valid separator `#`. So below command works:
`Mod4+d exec --no-startup-id rofi -modi 'drun#window#run' -show drun`
