### ISSUE TITLE
Can't install i3-gaps, install fails

### ISSUE THREAD

**Issue by ghost** [Airblader/i3#194]
Output of `i3 --moreversion 2>&- || i3 --version`:

URL to a logfile as per https://i3wm.org/docs/debugging.html:

https://logs.i3wm.org/logs/5677239974756352.bz2

**What I did:**

make logs: https://my.mixtape.moe/uxxzgm

**What I saw:**

Nothing happened

**What I expected instead:**
An actual working version if i3-gaps

**Comment by Airblader** [comment]
https://github.com/Airblader/i3/wiki/Compiling-&-Installing#basics
