### ISSUE TITLE
during Make i3-nagbar errors with undefined references

### ISSUE THREAD

**Issue by VuiMuich** [Airblader/i3#197]
Hi,
I'm fairly new to building things from source. I got i3 installed via apt-get on raspbian.
After cumbersome fixing dependencies I am a bit lost how to fix this build error.

configure output (last bit):
--------------------------------------------------------------------------------
build configured:

  i3 version:             4.14.1-256-gfadacdcf (2018-01-15, branch "gaps-next")
  is release version:     no

  build manpages:         no
  build docs:             no
  enable debug flags:     yes
  code coverage:          no
  enabled sanitizers:

make output (partially):
i3-nagbar/i3_nagbar-main.o: In function `get_window_position':
/home/pi/GitRepos/i3-gaps/build/../../i3-gaps/i3-nagbar/main.c:270: undefined reference to `xcb_randr_get_screen_resources_current'
/home/pi/GitRepos/i3-gaps/build/../../i3-gaps/i3-nagbar/main.c:271: undefined reference to `xcb_randr_get_output_primary'
/home/pi/GitRepos/i3-gaps/build/../../i3-gaps/i3-nagbar/main.c:276: undefined reference to `xcb_randr_get_output_primary_reply'
/home/pi/GitRepos/i3-gaps/build/../../i3-gaps/i3-nagbar/main.c:281: undefined reference to `xcb_randr_get_screen_resources_current_reply'
/home/pi/GitRepos/i3-gaps/build/../../i3-gaps/i3-nagbar/main.c:286: undefined reference to `xcb_randr_get_output_info'
/home/pi/GitRepos/i3-gaps/build/../../i3-gaps/i3-nagbar/main.c:285: undefined reference to `xcb_randr_get_output_info_reply'
/home/pi/GitRepos/i3-gaps/build/../../i3-gaps/i3-nagbar/main.c:293: undefined reference to `xcb_randr_get_crtc_info'
/home/pi/GitRepos/i3-gaps/build/../../i3-gaps/i3-nagbar/main.c:292: undefined reference to `xcb_randr_get_crtc_info_reply'
collect2: error: ld returned 1 exit status
Makefile:1625: recipe for target 'i3-nagbar/i3-nagbar' failed
make[1]: *** [i3-nagbar/i3-nagbar] Error 1
make[1]: *** Waiting for unfinished jobs....
/usr/bin/ld: i3bar/src/i3bar-xcb.o: undefined reference to symbol 'xcb_xkb_id'
//usr/lib/arm-linux-gnueabihf/libxcb-xkb.so.1: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
Makefile:1656: recipe for target 'i3bar/i3bar' failed
make[1]: *** [i3bar/i3bar] Error 1
/usr/bin/ld: src/i3-main.o: undefined reference to symbol 'xcb_xkb_id'
//usr/lib/arm-linux-gnueabihf/libxcb-xkb.so.1: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
Makefile:1562: recipe for target 'i3' failed
make[1]: *** [i3] Error 1
make[1]: Leaving directory '/home/pi/GitRepos/i3-gaps/build'
Makefile:1312: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by Airblader** [comment]
Why are you building from source?

**Comment by VuiMuich** [comment]
Basically I ran into the i3-gaps via some nice rices that mentioned it and liked the clean look.
And as well I like the kind of a puzzle challenge to get something compiled.
Despite the basic i3 package I figured no way to get it onto my pi other than building it.

**Comment by Airblader** [comment]
Please refer to the wiki on here for why I'm closing the issue. I'd recommend you to post it on the i3wm subreddit for the community to help.

**Comment by VuiMuich** [comment]
thanks for your advice. 
I tired to compile the original i3 and it worked out of the box, then I trie i3-gaps and it did so as well.
