### ISSUE TITLE
[feature request] Assign scratchpad to monitor

### ISSUE THREAD

**Issue by k1sul1** [Airblader/i3#198]
I've been using i3(-gaps) for a little over 6 months now, and the one thing that's bugging me is that the scratchpad follows my cursor.  I've put a terminal emulator on it, and I show & hide it with a hotkey. It doesn't follow the cursor immediately, but if the scratchpad is open on my primary monitor, and I move my mouse to the secondary and then try to hide it with the hotkey, it will instead pop to my secondary monitor.

`bindsym $mod+minus scratchpad show`

That is the hotkey combination I'm using.

If my monitors were the same resolution, the scratchpad following wouldn't be an issue, but the terminal is unreadable on my laptop monitor when I'm using it on the primary monitor. I've tried searching the documentation but I haven't found anything on the subject. 

Something like this is what I'd want to do. 

```
workspace 1 output $external_monitor
workspace 2 output $external_monitor
workspace 3 output $external_monitor

scratchpad output $external_monitor

workspace 11 output $laptop_monitor
workspace 12 output $laptop_monitor
workspace 13 output $laptop_monitor
```
I'm not sure if the original i3 dev is willing to do such a feature, so I'm posting it here.

Output of `i3 --moreversion 2>&- || i3 --version`:

Binary i3 version:  4.14.1 (2017-09-24) © 2009 Michael Stapelberg and contributors
Running i3 version: 4.14.1 (2017-09-24) (pid 959) abort…)
Loaded i3 config: /home/k1sul1/.config/i3/config (Last modified: Wed 07 Mar 2018 12:49:30 PM EET, 144 seconds ago)

The i3 binary you just called: /usr/bin/i3
The i3 binary you are running: i3

Installed using https://www.archlinux.org/packages/community/x86_64/i3-gaps/.

**Comment by Airblader** [comment]
Thanks for the detailed report! I'll close this because it's not related specifically to i3-gaps, but more to i3 itself, so please open the issue there (if you still need to).

However, the behavior you're describing is explicitly intended:

```
    /* If this was 'scratchpad show' without criteria, we check if there is a
     * visible scratchpad window on another workspace. In this case we move it
     * to the current workspace. */
    focused_ws = con_get_workspace(focused);
    TAILQ_FOREACH(walk_con, &all_cons, all_cons) {
        Con *walk_ws = con_get_workspace(walk_con);
        if (!con && walk_ws &&
            !con_is_internal(walk_ws) && focused_ws != walk_ws &&
            (floating = con_inside_floating(walk_con)) &&
            floating->scratchpad_state != SCRATCHPAD_NONE) {
            DLOG("Found a visible scratchpad window on another workspace,\n");
            DLOG("moving it to this workspace: con = %p\n", walk_con);
            con_move_to_workspace(walk_con, focused_ws, true, false, false);
            return;
        }   
    }         
```

I guess what you'd be asking for is some kind of flexibility, e.g. via additional flags to the command.

**Comment by k1sul1** [comment]
I'll open a ticket there. 

I get that the behaviour is intended, but I don't like it, hence I'd like to do something about it. 🙂
