### ISSUE TITLE
Can't compile on Debian

### ISSUE THREAD

**Issue by alex-bender** [Airblader/i3#199]
Hi!
I've tried to compile from the latest commit -- fadacdc but no luck.
Debian version is 8.9
Dependencies are installed from the list here: https://github.com/Airblader/i3/wiki/Compiling-&-Installing
Commands to compile also from that page.
Here is the error:

```
/home/tools/i3/build $ make
...
[SKIP]
  CC       src/i3-ipc.o
In file included from ../../i3/src/ipc.c:12:0:
../../i3/src/ipc.c: In function ‘handle_get_version’:
../../i3/include/yajl_utils.h:19:50: error: expected expression before ‘)’ token
 #define y(x, ...) yajl_gen_##x(gen, ##__VA_ARGS__)
                                                  ^
../../i3/src/ipc.c:941:5: note: in expansion of macro ‘y’
     y(integer, MAJOR_VERSION);
     ^
../../i3/include/yajl_utils.h:19:50: error: expected expression before ‘)’ token
 #define y(x, ...) yajl_gen_##x(gen, ##__VA_ARGS__)
                                                  ^
../../i3/src/ipc.c:944:5: note: in expansion of macro ‘y’
     y(integer, MINOR_VERSION);
     ^
Makefile:2277: recipe for target 'src/i3-ipc.o' failed
make[1]: *** [src/i3-ipc.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make[1]: Leaving directory '/home/alex/tools/i3/build'
Makefile:1251: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by Airblader** [comment]
Why are you compiling from source?

**Comment by alex-bender** [comment]
Well, I didn't find a .deb package. I've checked [releases](https://github.com/Airblader/i3/releases) page and following this link (Please refer to the wiki to see how i3-gaps can be installed and for which distributions there are packages available.) didn't find packages as well. So I've decided to compile it.

**Comment by Airblader** [comment]
Then please refer to https://github.com/Airblader/i3/wiki/Compiling-&-Installing#basics for why I'm going to close this issue. You can ask for help in the community on the i3wm subreddit, for example.

**Comment by alex-bender** [comment]
I saw the line "Other questions regarding how to compile will be closed."
The reason why I've opened issue -- is a part in a parentheses: "**rather than a bug in the compilation**."
But anyway -- thanks for a fast response.

**Comment by Airblader** [comment]
For what it's worth, this is likely an issue with the recency of packages on Debian.

A good bet would be checking out how i3 is built for Debian. The same will work for i3-gaps.

**Comment by alex-bender** [comment]
Got it, thanks!

**Comment by kuceb** [comment]
For anyone experiencing this issue, **make sure you're not cloning the repo with `--depth 1`**

**Comment by alex-bender** [comment]
probably it was the reason! I like that `--depth` option.
