### ISSUE TITLE
Activate smart borders only if there are no gaps

### ISSUE THREAD

**Issue by nim-** [Airblader/i3#20]
Hi again

It would be wonderful to have smart border to only activate if there are no gaps. A single window with gaps looks silly without borders.

I don't know the scope of this project, though; whether if would be feasible to implement.

**Comment by Airblader** [comment]
I got nothing against adding this. I'll try to check it out, shouldn't be too hard.

**Comment by Airblader** [comment]
I've played around with this. Can you check out the branch `feature-no-gaps-smart-borders` and try it to see if it's what you expected it to be?

```
git fetch --all && git checkout feature-no-gaps-smart-borders
make && sudo make install
```

You can then use this in your config: `smart_borders no_gaps`

Note that the syntax for gaps has changed lately. If you haven't updated yet, your old gaps configuration won't work anymore, so make sure to update it first (see Readme for new syntax).

You can go back to the main branch by replacing `feature-no-gaps-smart-borders` with `gaps` in the above commands (and undo the config change!).

**Comment by nim-** [comment]
This works beautifully.

No bugs or anything, at least not on my end. Great job :)

**Comment by Airblader** [comment]
Awesome. It's now merged into `gaps` and `gaps-next`, so you can check that branch out again now without reverting your config change.

```
git checkout gaps && git pull
make && sudo make install
```
