### ISSUE TITLE
Error 127 status_command not found

### ISSUE THREAD

**Issue by ghost** [Airblader/i3#200]
I get this error even if I have i3status installed. 

I'm on Kali Linux

**Comment by ghost** [comment]
hmm... Why is this closed? @Airblader

**Comment by Airblader** [comment]
That issue template text you see when creating an issue isn't decorative. Your report contains no useful information, hence I closed it.

**Comment by ghost** [comment]
Oh, ok then :) I'll make another issue with the template

**Comment by Airblader** [comment]
Please do so in the upstream repository (i3) since this doesn't seem to be an issue specific to i3-gaps.

**Comment by ghost** [comment]
I installed i3 after I got the error and everything was alright.... Anyway, I've reinstalled all dependencies and i3blocks just in case is needed and the problem is fixed now ^^
