### ISSUE TITLE
configure: error: cannot run C compiled programs

### ISSUE THREAD

**Issue by vojislav** [Airblader/i3#201]
I was trying to compile i3-gaps on Linux Mint 18.3 and even after installing all of the required dependencies and several tries, it still doesn't work.
I just get this error and it says to look at the [config.log](https://github.com/Airblader/i3/files/1794379/config.log) file, but I couldn't figure out what I was doing wrong based on it.

Any help would be greatly appreciated.

**Comment by Airblader** [comment]
Please see https://github.com/Airblader/i3/wiki/Compiling-&-Installing#basics. As in the other recently closed issues I'd suggest asking the question in the community, such as the i3 subreddit.
