### ISSUE TITLE
i3bar transparency on two monitors

### ISSUE THREAD

**Issue by nycex** [Airblader/i3#202]
Output of `i3 --moreversion 2>&- || i3 --version`:

Binary i3 version:  4.14.1-291-g12a4ae32 (2018-03-09, branch "gaps-next") © 2009 Michael Stapelberg and contributors
Running i3 version: 4.14.1-291-g12a4ae32 (2018-03-09, branch "gaps-next") (pid 3280)
Loaded i3 config: /home/user/.config/i3/config (Last modified: Sat 03 Mar 2018 15:45:41 CET, 608394 seconds ago)

The i3 binary you just called: /usr/bin/i3
The i3 binary you are running: i3

**What I did:**
Set the transparency of the i3bar. (With compton)

**What I saw:**
On the monitor, that isn't focused at the moment, the active workspace's transparency doesn't work.

**What I expected instead:**
That it is transparent like on the focused monitor.

**Comment by Airblader** [comment]
Can you please be more specific and share config files for i3 and compton? A screenshot would also be good.

**Comment by nycex** [comment]
Okay, [here is my i3](https://hastebin.com/goroyomole.bash) config and [here my compton config](https://hastebin.com/ozidarumiz.ini).

**Comment by Airblader** [comment]
Can you please also add the screenshot so we are clear about what we are talking about?

**Comment by nycex** [comment]
[Here](https://imgur.com/a/4bbRf) is the comparison

**Comment by Airblader** [comment]
Aren't you just missing a configuration for `active_workspace` in the i3bar config?

**Comment by nycex** [comment]
Oh, you're right. That actually solved my problem. I thought focuses would set the color for the active aswell. Thank You.
