### ISSUE TITLE
i3-gaps not starting after updating to latest commit.

### ISSUE THREAD

**Issue by denisse-dev** [Airblader/i3#203]
Output of `i3 --moreversion 2>&- || i3 --version`: 4.15-1

**What I did:**
I booted my system after updating i3-gaps to the latest version.

**What I saw:**
My system boots normally but i3-gaps is not starting, no error is shown, I get dumped to the Windows Manager, i3-wm and Openbox work fine.

**What I expected instead:**
To start i3-gaps normally.

**Comment by Airblader** [comment]
To clarify, when you say i3 works, does that mean i3 4.15?

What happens if you start i3 manually via startx or similar?

**Comment by denisse-dev** [comment]
Yes, I mean i3 4.15 works without issues, but i3-gaps was not working.

However, after changing to `gaps next` branch and now everything works as expected.

**Comment by Airblader** [comment]
See https://github.com/Airblader/i3/issues/204
