### ISSUE TITLE
Disable Window Border

### ISSUE THREAD

**Issue by bogstefan** [Airblader/i3#206]
The description says that we have to disable window borders by adding `for_window [class="^.*"] border pixel 0` in the config file.
However the line `default_border pixel 3` also removes the titlebar but leaves the frame with size of 3 pixels. Is this also a viable option instead of `for_window [class="^.*"] border pixel 0` ?

**Comment by Airblader** [comment]
Yes, using a pixel border is fine, just the normal border (including the title bar) causes issues.
