### ISSUE TITLE
`assign [tiling] $ws` is ignored.

### ISSUE THREAD

**Issue by crocket** [Airblader/i3#208]
**Output of `i3 --moreversion 2>&- || i3 --version`:**

```
Binary i3 version:  4.15-non-git © 2009 Michael Stapelberg and contributors
Running i3 version: 4.15-non-git (pid 27087)-c to abort…)
Loaded i3 config: /home/guardian/.config/i3/config (Last modified: Wed 04 Apr 2018 09:38:55 AM KST, 773 seconds ago)

The i3 binary you just called: /usr/bin/i3
The i3 binary you are running: /usr/bin/i3
```

**URL to a logfile as per https://i3wm.org/docs/debugging.html:**

https://logs.i3wm.org/logs/5652096565116928.bz2

**What I did:**

I added `assign [tiling] $ws2`

**What I saw:**

Tiled windows don't go to `$ws2`.

**What I expected instead:**

Tiled windows should go to `$ws2`.
`assign [floating] $ws` is ignored as well.

**Comment by Airblader** [comment]
Thanks for the issue! As this isn't specific to i3-gaps, please report it over at https://github.com/i3/i3/. Thanks!
