### ISSUE TITLE
Allow setting gap size for a specific workspace

### ISSUE THREAD

**Issue by Airblader** [Airblader/i3#21]
`gaps inner|outer workspace number <name> set|plus|minus <px>`

It'd be wonderful to also allow `for_workspace [number = <number>] gaps …`, but that probably needs to be its own issue.

**Comment by Airblader** [comment]
Probably a better idea would be

```
workspace $ws gaps …
```

similar to http://i3wm.org/docs/userguide.html#workspace_screen

**Comment by Airblader** [comment]
`feature-workspace-gaps` contains a first draft for `workspace $ws gaps inner|outer <px>`.

Problem: it currently only works correctly if the global `gaps` command was used _before_ this directive.

**Comment by Airblader** [comment]
The branch should now hopefully work as intended. Was a bit more effort than I anticipated, but it's worth it. I'll use it for a while before merging it, though.

**Comment by Airblader** [comment]
Merged now.

**Comment by japhir** [comment]
Sorry to open up this old issue, but is it possible to set both inner and outer gaps on a specific workspace?

i.e.

    workspace 1 gaps inner 0
    workspace 1 gaps outer 0

currently, it seems like it only takes the last option.

**Comment by Airblader** [comment]
This is supposed to work, yes, so if it doesn't that'd be a bug. Feel free to open one (and send a PR :-) )

**Comment by japhir** [comment]
I must have done something wrong, it works now!

I guess I already had the workspace open before reloading my config or something like that.

Thanks for the superfast reply!

**Comment by thexavier666** [comment]
Sorry for replying on such an old post. 
But to enable per workspace gap, I had to logout and login, instead of `i3-msg restart`. I was stuck with this for an hour.

Using `i3 version 4.18.2-229-g234d6855`

**Comment by Airblader** [comment]
@thexavier666 Logging out and in shouldn't be necessary, but you need to recreate the workspace, ie make sure it gets destroyed and then switch to it again. Logging out and in obviously achieves that as well.

**Comment by OopsYao** [comment]
Sorry to reopen this again, is there any way to set gaps for a specific workspace from command? The current gap command only allows for setting of `current` and `all` workspaces, while the configuration file allows a specific workspace. Or is this on purpose?

**Comment by Airblader** [comment]
There's no command to set the gaps for a specific workspace at runtime, but you can always do

```
workspace --no-auto-back-and-forth foo, gaps inner current plus 5, workspace back_and_forth
```

**Comment by OopsYao** [comment]
Thanks for the reply! It's a great workaround and satisfies my needs! But in my opinion it would be better to implement a command like that, it is more intuitive.
