### ISSUE TITLE
LCD sub-pixel anti-aliasing for text

### ISSUE THREAD

**Issue by Ropid** [Airblader/i3#212]
```
$ i3 --moreversion 2>&- || i3 --version
Binary i3 version:  4.15.0.1 (03-13-2018) © 2009 Michael Stapelberg and contributors
Running i3 version: 4.15.0.1 (03-13-2018) (pid 773)bort…)
Loaded i3 config: /home/user/.config/i3/config (Last modified: 2018-04-28T16:10:13 CEST, 377890 seconds ago)

The i3 binary you just called: /usr/bin/i3
The i3 binary you are running: i3
```

I don't quite know if this here is a feature request or a bug report.

In the normal i3-gaps (also normal i3), there's no sub-pixel rendering getting used for the text in title bars or in i3bar. You can see this by taking a screenshot and zooming in: there's no color-fringes anywhere. It's all grayscale anti-aliasing.

Trying to research this and stabbing into the dark, I found out that this behavior might have to do with these lines here in the source:

```
$ rg cairo_set_operator
libi3/font.c
109:    cairo_set_operator(cr, CAIRO_OPERATOR_SOURCE);

libi3/draw_util.c
157:    cairo_set_operator(surface->cr, CAIRO_OPERATOR_SOURCE);
182:    cairo_set_operator(surface->cr, CAIRO_OPERATOR_SOURCE);
208:    cairo_set_operator(dest->cr, CAIRO_OPERATOR_SOURCE);
```

I changed all of those lines to using CAIRO_OPERATOR_OVER instead of ..._SOURCE, and now sub-pixel rendering apparently works.

The problem is, I don't really know what I'm doing here. The documentation is here:

https://www.cairographics.org/manual/cairo-cairo-t.html#cairo-operator-t

https://www.cairographics.org/operators/

It doesn't mention anything about LCD sub-pixel rendering for text working or not-working for certain settings. It says the "OVER" operator is the default, but i3 explicitly sets "SOURCE", so maybe there's a good reason to do this and everything works like intended?

**Comment by Airblader** [comment]
> maybe there's a good reason to do this and everything works like intended?

Yes, the reason is explained in `libi3/draw_util.c`. :-) However, that reason only applies once the color with which something is drawn is not opaque but at least partially transparent.

In any case, this issue is not specific to i3-gaps. Can you please open it upstream in i3 for discussion there?
