### ISSUE TITLE
not working in ubuntu 18.**

### ISSUE THREAD

**Issue by NicTanghe** [Airblader/i3#213]
When i try to install i3 gaps on ubuntu 18.04 on starting the desktop i get just my background picture and nothing else.

It's late now i and i'm to tired to think about what logs you might need.
Anny wanted logs and i'll provide them.

(ps. pressing alt+Enter doesnt open a terminal)

**Comment by Airblader** [comment]
Please open issues when you're not too tired to provide basic information like correct versions (of i3-gaps) and logs. Thanks! Please keep in mind that Ubuntu has been going back and forth between X and Wayland as well.
