### ISSUE TITLE
black screen on external monitor

### ISSUE THREAD

**Issue by AdrienLemaire** [Airblader/i3#214]
Output of `i3 --moreversion 2>&- || i3 --version`:

Binary i3 version:  4.15.0.1-131-g8cfcab8f (2018-04-19, branch "gaps-next") © 2009 Michael Stapelberg and contributors
Running i3 version: 4.15.0.1-131-g8cfcab8f (2018-04-19, branch "gaps-next") (pid 21699)
Loaded i3 config: /home/dori/.config/i3/config (Last modified: Fri 18 May 2018 09:50:14 AM JST, 3744 seconds ago)

The i3 binary you just called: /usr/bin/i3
The i3 binary you are running: i3

URL to a logfile as per https://i3wm.org/docs/debugging.html:

https://logs.i3wm.org/logs/5644572721938432.bz2

**What I did:**

Upgraded my packages yesterday, and removed the xf86-video-intel-git  package that became a conflict with xorg-server.
When restarting my system this morning, I noticed that the external monitor stayed black.
I updated my screen names from eDP1&DP1 to the new eDP-1 and DP-1, and it looks like xrandr and i3 got it right

```
$ xrandr -q | grep -e "[+-]"   
eDP-1 connected primary 3200x1800+320+2160 (normal left inverted right x axis y axis) 294mm x 165mm
   3200x1800     59.98*+  59.96    59.94    47.99  
DP-1 connected 3840x2160+0+0 (normal left inverted right x axis y axis) 527mm x 296mm
   1920x1080     60.00*+  50.00    59.94  
HDMI-1 disconnected (normal left inverted right x axis y axis)
DP-2 disconnected (normal left inverted right x axis y axis)
HDMI-2 disconnected (normal left inverted right x axis y axis)
```
Pressed $mod+2 to go to the DP-1 workspace

**What I saw:**

mouse is located in DP-1. Browser automatically opened there, testing $mod+Shift+3 to send chrome to workspace 3 on eDP-1 works fine.
But external monitor shows a black screen, workspace 2 (and others located on DP-1) are not visible.

**What I expected instead:**
External monitor shows workspace 2.
Cannot revert back to xf86-video-intel-git, because one of its dependencies (X_ABI_VIDEODRV_VERSION) disappeared from AUR ([yay related thread](https://github.com/Jguer/yay/issues/424))

**Comment by Airblader** [comment]
So what makes you think this is an i3 issue? Doesn't it seem pretty clear that it's an issue with X or the video driver?

**Comment by AdrienLemaire** [comment]
Ok. sorry for the disturb, I'll search more
