### ISSUE TITLE
Failed at compiling

### ISSUE THREAD

**Issue by nishimi-ya** [Airblader/i3#215]
The issue happening when i try `autoreconf --force --install`. The output says:
`Can't exec "aclocal": No such file or directory at /usr/share/autoconf/Autom4te/FileUtils.pm line 326.`
`autoreconf: failed to run aclocal: No such file or directory`

Am i missing something or i must to install some dependencies?

**Comment by Airblader** [comment]
Please refer to the wiki on this repo.
