### ISSUE TITLE
Having Trouble Scaling the DPI for a 4k Display with Xrandr, i3wm, & Arch Linux

### ISSUE THREAD

**Issue by zimmertr** [Airblader/i3#216]
Hello i3-gaps team, I have a 4k display on my laptop and I'm sure you're all aware of some of the issues that i3 has with HiDPI. Two of the solutions I've seen presented so far are:

    1) Use xrandr to scale the display in your `.xinitrc` file.
    
    2) Use xrandr to set the DPI of your system in your `.xinitrc` file. 
    
    3) Use `.Xresources` to set the DPI for your system when the X server is spawned. 
    
Options 1 and 3 above yield the same result for me unfortunately. Which can be seen [here](https://i.imgur.com/O5SYss8.jpg). As you can see, `xrandr` does in fact scale something. But it's not the entire display. It's just `i3`. After scaling has occurred, `xrandr` should fill the entire display with the newly scaled image, yeah? 

Option 2 does not appear to impact i3. However, setting the DPI with xrandr does change some other elements. Such as the warning message that i3 spawns when you try and exit your session (mod+shift+e). For example, [this](https://i.imgur.com/9htXJpQ.png) would become [this](https://i.imgur.com/JmnNyN9.png).

Do you have any idea what's going on with my system? Thank you for your time. 

**EDIT: Added Hardware/Software Specs Below:**  

        Graphics Card: _Nvidia Quadro M1200 Mobile (GM107GLM)
        Operating System: Arch Linux x64 Fully Updated
        xrandr Version: 1.5.0  
        RandR Version: 1.5  
        i3 Version: 4.15.0.1
        i3 Packages: `i3-gaps-next-git`, `i3blocks-git`, `i3-status-git`  
        xrandr Scaling Mode: _Full aspect_  

**EDIT2: Added link to xrandr --prop Output Below:** 

https://gist.githubusercontent.com/zimmertr/717229291648dad6aa09a4f1d249d25d/raw/1b897445151e7d31aab6f79d16420c370baf210a/gistfile1.txt

**EDIT3: Added link to config files for i3, i3blocks, i3status, xorg, and xinitrc Below:**

https://gist.github.com/zimmertr/c2ea4b0e959655cdbbf48263e3278a59

**Comment by Airblader** [comment]
Hi,

for support requests please use https://www.reddit.com/r/i3wm/. The issue tracker is for bug reports and feature requests. On reddit you'll have more people reading along anyway, here's it's pretty much just me :-) Thanks!
