### ISSUE TITLE
retain the cwd on exec

### ISSUE THREAD

**Issue by 0ax1** [Airblader/i3#218]
## I'm submitting a…

<pre>
[ ] Bug
[x] Feature Request
[ ] Documentation Request
[ ] Other (Please describe in detail)
</pre>

## Current Behavior

`exec` does not retain the current working dir of the focused window. The cwd is always set to `$home`.

## Desired Behavior

Applications can be launched retaining the cwd (e.g. ``bindsym .. exec "terminal --working-directory `pwd`"``). Existing solutions such as `xcwd` do not work all of the time and are somewhat brittle. Ideally, the new behavior would be like `#{pane_current_path}` in `tmux` (e.g. `bind .. split-window -h -c "#{pane_current_path}"`).

## Environment

<pre>
i3 version: 4.15.0.1
</pre>

**Comment by Airblader** [comment]
Thanks for reporting the issue. Can you please report this in the i3/i3 repository instead? Thank you!

**Comment by 0ax1** [comment]
Sure, thanks for having a look. (issue was moved here: https://github.com/i3/i3/issues/3312)
