### ISSUE TITLE
Compiling failed on raspbian

### ISSUE THREAD

**Issue by Karmenzind** [Airblader/i3#219]
```
# uname -a
Linux raspberrypi 4.14.50-v7+ #1122 SMP Tue Jun 19 12:26:26 BST 2018 armv7l GNU/Linux
# lsb_release -d -s
Raspbian GNU/Linux 9.4 (stretch)
```

The result of configure:
![image](https://user-images.githubusercontent.com/17923071/42144127-0bf8b8c6-7dec-11e8-8fb8-5e917fb045e3.png)

Then I tried `make` and `make -j8`
![image](https://user-images.githubusercontent.com/17923071/42144152-362d0d9a-7dec-11e8-8ec7-1da19beae7b6.png)
![image](https://user-images.githubusercontent.com/17923071/42144160-46264900-7dec-11e8-848b-eec6bbbee8a6.png)

**Comment by Karmenzind** [comment]
Here is the `config.log`:
[config.log](https://github.com/Airblader/i3/files/2153707/config.log)

**Comment by Airblader** [comment]
https://github.com/Airblader/i3/wiki/Compiling-&-Installing
https://github.com/Airblader/i3/issues/199

**Comment by Karmenzind** [comment]
awkward......
Thank you.
