### ISSUE TITLE
Dual monitor freeze on xrandr call

### ISSUE THREAD

**Issue by gammison** [Airblader/i3#220]
## I'm submitting a…

<pre>
[ ] Bug
[ ] Feature Request
[ ] Documentation Request
[x] Other (Please describe in detail)

This may be a bug with i3 but I'm not completely sure. It does not occur on gnome wayland or gnome xorg.

It does not happen if compton is killed before hand. restarting compton does not reintroduce the problem. It does not happen at all whether or not compton is enabled in gnome xorg.
</pre>

## Current Behavior
When calling xrandr to move a display to the left or right, one monitor freezes. Display unfreezes if the other monitor is disconnected or xrandr is called to duplicate the displays. Mouse movement does not freeze, nor does the status bar displaying the focused window of the frozen display ie if the mouse is moved over the frozen display the windows on it will still show up on the status bar. Frozen windows can be moved to the other monitor but the screen will not update. 

## Expected Behavior
Properly extending the display left or right.

## Reproduction Instructions
make an xrandr call like ''' xrandr --output HDMI1 --left-of eDP ''' where eDP is the primary display.

## Environment

Output of `i3 --moreversion 2>&-`:
<pre>
i3 version: i3 version 4.15.0.1-202-g6d2d6322 (2018-07-12, branch "gaps-next")
</pre>

<pre>
- Antergos: kernel 4.17.5-1-ARCH
- Are you using a compositor (e.g., xcompmgr or compton): compton
</pre>

**Comment by Airblader** [comment]
Hi,

Thanks for opening this issue. Can you install vanilla i3 and see if the problem exists there as well? Thanks!

**Comment by gammison** [comment]
Yeah it happens with vanilla i3, also when compton is restarted the background on the frozen monitor is corrupted and has to be reset again.

**Comment by gammison** [comment]
The background reset only happens the first time compton is killed then restarted. I don't know, this may be a bug in compton not i3.

**Comment by Airblader** [comment]
Does the issue happen when compton isn't running? If not, it's a compton issue. If it does still persist, please open the issue on i3/i3 since it's not related to i3-gaps, specifically. Thanks!
