### ISSUE TITLE
Add ability to get the current gap level

### ISSUE THREAD

**Issue by brookskindle** [Airblader/i3#221]
## I'm submitting a…

<pre>
[ ] Bug
[x] Feature Request
[ ] Documentation Request
[ ] Other (Please describe in detail)
</pre>

## Current Behavior

i3 (gaps version) allows the inner and outer gap level to be set via the i3-msg command
> i3-msg gaps {outer, inner} {current, all} {set, plus, minus} {amount}

## Expected Behavior

But it doesn't let users query the current gap level
> i3-msg gaps {outer, inner} {current, all} {set, **get**, plus, minus} {amount}

This means you cannot have an application that displays the current gap level, unless it is also the application to set the gap level, but this is a very shaky and unreliable method of doing so.

I realize this probably won't be a straightforward feature, since workspaces can have different gap levels, So getting the gap level for all workspaces  (`i3-msg gaps outer all get`) would either have to list the gap levels for all workspaces or be disallowed altogether

## Environment

Output of `i3 --moreversion 2>&-`:
<pre>
$ i3 --moreversion 2>&-
Binary i3 version:  4.15-19-g2c1d8c4a (2018-03-11, branch "gaps-next") © 2009 Michael Stapelberg and contributors
Running i3 version: 4.15-19-g2c1d8c4a (2018-03-11, branch "gaps-next") (pid 1172)
Loaded i3 config: /home/bkindle/.i3/config (Last modified: Fri 20 Jul 2018 01:58:16 PM PDT, 3640 seconds ago)

The i3 binary you just called: /usr/bin/i3
The i3 binary you are running: i3
</pre>

<pre>
- Linux Distribution & Version: Ubuntu 17.10
- Are you using a compositor (e.g., xcompmgr or compton): compton
</pre>

**Comment by Airblader** [comment]
Hi,

The gaps are listed in the GET_TREE reply for each workspace. Is there any reason why that isn't sufficient?

**Comment by brookskindle** [comment]
I didn't realize the gap level could be listed under `i3-msg -t get_tree`,
```json
...
              "name": "1: Web",
              "num": 1,
              "gaps": {
                "inner": 0,
                "outer": 10
              },
...
```

Which solves my problem.

---

Curious though, the gaps listed are offset by 10 pixels for both `outer` and `inner`. ~~Does this have something to do with the bar?~~

[edit] It looks like the gap value as listed in `get_tree` is relative to the whatever gap level is set in your i3 config.

With a default gap level of 10 for inner and outer, as set in `~/.i3/config`
```
brooks@greenie:~$ grep gaps ~/.i3/config 
gaps inner 10
gaps outer 10
```
```
brooks@greenie:~$ i3-msg gaps inner current set 0
[{"success":true}]
brooks@greenie:~$ i3-msg gaps outer current set 5
[{"success":true}]
brooks@greenie:~$ i3-msg -t get_tree | jq . -C | grep -A 5 "Web"
              "name": "1: Web",
              "num": 1,
              "gaps": {
                "inner": -10,
                "outer": -5
              },
```

With a default gap level of 30 for both inner and outer
```
brooks@greenie:~$ grep gaps ~/.i3/config 
gaps inner 30
gaps outer 30
```
```
brooks@greenie:~$ i3-msg gaps inner current set 0
[{"success":true}]
brooks@greenie:~$ i3-msg gaps outer current set 5
[{"success":true}]
brooks@greenie:~$ i3-msg -t get_tree | jq . -C | grep -A 5 "Web"                                        
              "name": "1: Web",
              "num": 1,
              "gaps": {
                "inner": -30,
                "outer": -25
              },
```

Regardless, thanks for answering my initial question.

**Comment by Airblader** [comment]
Yes, the gaps reported in there are essentially the accumulation of outer and inner gaps (effective gaps).

**Comment by vdumitraskovic** [comment]
@Airblader Is there a way to query gaps previously set with 'all' parameter? On Archlinux, i3-gaps version 4.16 I only get `{ inner: 0, outer: 0}` when using `get_tree`.

**Comment by Airblader** [comment]
@smesko85 In that case the gaps on workspace level are reset to 0 and instead the config is changed. Since the currently running config is not exposed on the IPC – no, there isn't.
