### ISSUE TITLE
I cannot make mpv borderless via my rule

### ISSUE THREAD

**Issue by Hund** [Airblader/i3#222]
This rule doesn't work for me:
```
for_window [class="mpv"] border none
```

But this rule does work for me:
```
for_window [class="VirtualBox Machine"] border none
```

I did replace `border none` to `fullscreen` and it then spawned mpv in fullscreen, but there's no way to make it borderless?

```
$ i3 --moreversion 2>&-
Binary i3 version:  4.15.0.1 (03-13-2018) © 2009 Michael Stapelberg and contributors
Running i3 version: 4.15.0.1 (03-13-2018) (pid 578)bort…)
Loaded i3 config: /home/johan/.config/i3/config (Last modified: Sun 22 Jul 2018 06:35:54 PM CEST, 1301 seconds ago)

The i3 binary you just called: /usr/bin/i3
The i3 binary you are running: i3
```

I'm running Arch Linux with the package`1:0.28.2-2` of mpv.

Am I doing something wrong? If so, I blame the excessive heat we have in Sweden now. :(

**Comment by Hund** [comment]
It doesn't seem to work with KeePassXC or Geany either.

**Comment by Airblader** [comment]
Can you post a screenshot of those apps? My assumption is that they draw their own borders. In that case there's nothing i3 can do.

**Comment by Hund** [comment]
Sure. But shouldn't I not be able to manually hide their borders (with the keybinding `bindsym $mod+t border none`) then?

**Comment by Hund** [comment]
It seems like I can't attach images, so here you go: https://framapic.org/Xi4p7QD2HJbx/rmvt1a4yJPaQ.png

**Comment by Airblader** [comment]
What does your current i3 config for borders look like? Does changing it to something ridiculous like 20px also affect these apps?

**Comment by Hund** [comment]
I tried changing it to 30 and it worked. It also looked a bit retro. :D I tried with Firefox now as well and I can't hide border there either.

`for_window [class="^.*"] border pixel 3`

**Comment by Hund** [comment]
I tried qutebrowser as well and same thing there. And I'm sorry for the double posts, GitHub won't let me edit comments in qutebrowser.

**Comment by Airblader** [comment]
Can you post a log file where you reproduce the problem with a simple setup of just Firefox?

**Comment by Hund** [comment]
https://dpaste.de/2VSS/raw

**Comment by Airblader** [comment]
You have this line in your config (and after the other ones):

    for_window [class="^.*"] border pixel 3

This matches everything and thus overrides the settings for Firefox.

**Comment by Hund** [comment]
Ohhh... I copied that from the docs, so I never gave it any thoughts. Thanks! :)

**Comment by Airblader** [comment]
I mean the line has its purpose for i3-gaps, but you should have it before other border rules at least.
