### ISSUE TITLE
Windows "freeze" unless they are defocused and refocused

### ISSUE THREAD

**Issue by ilo-3a29** [Airblader/i3#223]
## I'm submitting a…

<pre>
[x] Bug
[ ] Feature Request
[ ] Documentation Request
[ ] Other (Please describe in detail)
</pre>

## Current Behavior
If a program is left focused (or unfocused) for a time, it will "freeze" (keep running, just stop rendering to the screen) unless I then refocus it. This is potentially only with openGL programs, as I have tested it with mpv and various games.

## Expected Behavior
Programs don't freeze.

## Reproduction Instructions
Run a program (maybe only with openGL programs), leave it for a few minutes. This has happened with mpv, Stepmania, Enter the gungeon, and other programs, mainly games.

## Environment

Output of `i3 --moreversion 2>&-`:
<pre>
i3 version: 
Binary i3 version:  4.15.0.1 (03-13-2018) © 2009 Michael Stapelberg and contributors
Running i3 version: 4.15.0.1 (03-13-2018) (pid 807)bort…)
Loaded i3 config: /home/luke/.config/i3/config (Last modified: Wed 25 Jul 2018 17:44:09 BST, 588 seconds ago)

The i3 binary you just called: /usr/bin/i3
The i3 binary you are running: i3

</pre>

Config file: https://gitgud.io/lukeoftheaura/dotfiles/blob/master/i3/.config/i3/config

Logfile: https://logs.i3wm.org/logs/5718607623356416.bz2

<pre>
- Linux Distribution & Version: Arch linux (64 bit)
- compositor (e.g., xcompmgr or compton): Compton
</pre>

**Comment by Airblader** [comment]
Generally speaking, what happens inside a window is not the window manager's business. Does the issue go away if you don't use compton? I believe this is a compositing issue.

**Comment by ilo-3a29** [comment]
It seems to. Sorry to bother you, I  thought this might be an issue with how i3 handles window focusing (although I don't really know about things like this)

**Comment by Airblader** [comment]
For what it's worth, I haven't change my compton config in a while and a few months back started having this issue, though in my case only for fullscreen windows. Given that compton is essentially dead it might be some video driver update.

Playing with compton settings is likely to help here, but can also just cause other issues. :-)
