### ISSUE TITLE
[FR] can we get an event on window resize

### ISSUE THREAD

**Issue by laur89** [Airblader/i3#226]
## I'm submitting a…

<pre>
[ ] Bug
[X] Feature Request
[ ] Documentation Request
[ ] Other (Please describe in detail)
</pre>

Would it be possible to get a `window::resize` event over IPC?

**Comment by Airblader** [comment]
Please submit requests not specific to gaps to upstream i3, thanks!

**Comment by laur89** [comment]
For anyone stumbling upon this issue, upstream counterpart is located [here](https://github.com/i3/i3/issues/3351)
