### ISSUE TITLE
Cursor offset on text hover in certain applications

### ISSUE THREAD

**Issue by themanifold** [Airblader/i3#227]
## I'm submitting a…

<pre>
[ x] Bug
[ ] Feature Request
[ ] Documentation Request
[ ] Other (Please describe in detail)
</pre>

## Current Behavior
When hovering over text in firefox or my sakura terminal UI, my cursor jumps to an offset a few pixels to the left and down - meaning I have a terrible time trying to click or highlight things.

## Expected Behavior
The cursor should stop jumping to an offset

## Reproduction Instructions
Highlight things in firefox/sakura (or probably other applications)

## Environment

Output of `i3 --moreversion 2>&-`:
```
Binary i3 version:  4.15.0.1 (03-13-2018) © 2009 Michael Stapelberg and contributors
Running i3 version: 4.15.0.1 (03-13-2018) (pid 865)bort…)
Loaded i3 config: /home/admin/.i3/config (Last modified: Fri 13 Jul 2018 07:44:07 BST, 2095174 seconds ago)

The i3 binary you just called: /usr/bin/i3
The i3 binary you are running: i3
```
https://pastebin.com/raw/h9HL0gGe
<pre>
https://pastebin.com/raw/h9HL0gGe
</pre>

<pre>
Logfile URL:
</pre>

<pre>
- https://manjaro.org/category/community-editions/i3/
- Using `compton`
- I found this article: https://bbs.archlinux.org/viewtopic.php?id=195995 but the solution there does not help
- I'm using VirtualBox Version 5.2.12 r122591 (Qt5.6.2)
</pre>

**Comment by Airblader** [comment]
Hi,

thanks for filing this issue. Is there any reason why you believe this is i3's fault? i3 doesn't know anything about the contents of a window, so it sounds unlikely to me.

**Comment by themanifold** [comment]
Well, I went onto google which linked me to the article in the original ticket. Then I went to the archlinux IRC channel who then pointed me at the manjaro IRC channel, who then pointed me here.

**Comment by Airblader** [comment]
Can you try running

    xev -event mouse | grep -A2 ButtonPress

and then clicking in the very upper left corner of the window that opens? Does the output show coordinates (0, 0) when you do that?

**Comment by themanifold** [comment]
ButtonPress event, serial 25, synthetic NO, window 0x3c00001,
    root 0x3ad, subw 0x0, time 15816081, (0,0), root:(2238,9),
    state 0x0, button 1, same_screen YES

It's pretty hard to get 0x0, and my mouse technically is off the black border that pops up when I do find 0x0.

**Comment by Airblader** [comment]
This issue somewhat fell through the cracks – sorry. Can you reproduce this under vanilla i3? If so, we should re-open the issue there (though I still very much think this isn't an i3 issue). This would likely increase visibility of the issue.

**Comment by Airblader** [comment]
I'm going to close this for now. Please reproduce in vanilla i3 latest version and reopen there.
