### ISSUE TITLE
[feature] setting gap size per window

### ISSUE THREAD

**Issue by plexigras** [Airblader/i3#228]
## I'm submitting a…

<pre>
[ ] Bug
[x] Feature Request
[ ] Documentation Request
[ ] Other (Please describe in detail)
</pre>

## Current Behavior

only per `current|all` workspace setting of gaps is supported

## Expected Behavior

allow per window setting aswell

**Comment by Airblader** [comment]
Hi,

thanks for filing this. I'm not really looking into doing this because it adds a lot of complexity for no real use case (what's the point of this?). We do have #54 which addresses the only real use case I can think of. Thanks for understanding.

**Comment by mitchmcdee** [comment]
I would also love a per-window adjustment, my use case would be to highlight the currently active window :)
