### ISSUE TITLE
i3bar - Transparency shows black bar

### ISSUE THREAD

**Issue by winghugs** [Airblader/i3#229]
## I'm submitting a…

<pre>
[X] Bug
[ ] Feature Request
[ ] Documentation Request
[ ] Other (Please describe in detail)
</pre>

## Current Behavior
When setting the status command to i3status -t and using background #0000000, the bar does not become transparent, it instead shows as black.
Compton is running.

## Expected Behavior
The background of the bar becomes transparent. 

## Reproduction Instructions
i3 config: https://hastebin.com/ilexexazuw.bash
compton config: https://hastebin.com/xatucuruje.shell
i3status config: https://hastebin.com/moquvocobi.pl

## Environment
Binary i3 version:  4.15.0.1 (03-13-2018) © 2009 Michael Stapelberg and contributors
Running i3 version: 4.15.0.1 (03-13-2018) (pid 28844)rt…)
Loaded i3 config: /home/bradyn/.config/i3/config (Last modified: Wed 08 Aug 2018 12:00:32 PM PDT, 983 seconds ago)

The i3 binary you just called: /usr/bin/i3
The i3 binary you are running: i3

- Linux Distribution & Version: Solus 3
- Are you using a compositor: compton

**Comment by Airblader** [comment]
The flag belongs on i3bar, not i3status.
