### ISSUE TITLE
Layout doesn't swallow terminals on startup

### ISSUE THREAD

**Issue by mifrandir** [Airblader/i3#230]
## I'm submitting a…

<pre>
[x] Bug
[ ] Feature Request
[ ] Documentation Request
[ ] Other (Please describe in detail)
</pre>

## Current Behavior

After startup the three terminals don't get swallowed by the layout (ws2.json). Yet, when I execute those commands manually I get the behaviour I wanted.

## Expected Behavior

When these terminals are created, they should be swallowed by the layout.

## Reproduction Instructions

See config below.
Content of ws2.json:
```
// vim:ts=4:sw=4:et
{
    // splitv split container with 2 children
    "border": "none",
    "floating": "auto_off",
    "layout": "splitv",
    "percent": 0.5,
    "type": "con",
    "nodes": [
        {
            // splith split container with 1 children
            "border": "none",
            "floating": "auto_off",
            "layout": "splith",
            "percent": 0.8,
            "type": "con",
            "nodes": [
                {
                    "border": "pixel",
                    "current_border_width": 0,
                    "floating": "auto_off",
                    "geometry": {
                       "height": 472,
                       "width": 852,
                       "x": 0,
                       "y": 0
                    },
                    "name": "fish  /home/vrelda",
                    "percent": 1,
                    "swallows": [
                       {
                       //"class": "^Termite$"
                       "instance": "^terminal$"
                       // "title": "^fish\\ \\ \\/home\\/vrelda$",
                       // "transient_for": "^$"
                       }
                    ],
                    "type": "con"
                }
            ]
        },
        {
            "border": "pixel",
            "current_border_width": 0,
            "floating": "auto_off",
            "geometry": {
               "height": 472,
               "width": 852,
               "x": 0,
               "y": 0
            },
            "name": "fish  /home/vrelda",
            "percent": 0.2,
            "swallows": [
               {
               //"class": "^Termite$"
               "instance": "^update$"
               // "title": "^fish\\ \\ \\/home\\/vrelda$",
               // "transient_for": "^$"
               }
            ],
            "type": "con"
        }
    ]
}

{
    "border": "pixel",
    "current_border_width": 0,
    "floating": "auto_off",
    "geometry": {
       "height": 472,
       "width": 852,
       "x": 0,
       "y": 0
    },
    "name": "ranger:~",
    "percent": 0.5,
    "swallows": [
       {
       // "class": "^Termite$",
       "instance": "^ranger$"
       //"title": "^ranger\\:\\~$"
       // "transient_for": "^$"
       }
    ],
    "type": "con"
}
```
## Environment

Output of `i3 --moreversion 2>&-`:
<pre>
i3 version:
Binary i3 version:  4.15.0.1-209-ge589ca7f (2018-08-04, branch "gaps-next") © 2009 Michael Stapelberg and contributors
(Getting version from running i3, press ctrl-c to abort…)
Running i3 version: 4.15.0.1-209-ge589ca7f (2018-08-04, branch "gaps-next") (pid 377)
Loaded i3 config: /home/vrelda/.config/i3/config (Last modified: Fri 10 Aug 2018 03:33:31 CEST, 273 seconds ago)

The i3 binary you just called: /usr/bin/i3
The i3 binary you are running: i3
</pre>

<pre>
font pango:Input Mono 11
### VARIABLES ###
# Mod Key
set $mod Mod4
set $terminal termite -e fish
set $wallpaper bg.jpg

# VIM directions
set $up l
set $down k
set $left j
set $right semicolon

#MONITORS
set $rmonitor HDMI-0
set $lmonitor DVI-0

# Workspaces
set $workspace1 "1:web"
set $workspace2 "2:terminal"
set $workspace3 "3:tools"
set $workspace4 "4:code"
set $workspace6 "6:other"
set $workspace5 "5:other"
set $workspace7 "7:other"
set $workspace8 "8:other"
set $workspace9 "9:other"
set $workspace10 "10:other"

# Modes
set $modepower ""

# COLORS
set $bg-color            #272822aa
set $inactive-bg-color	 #272822aa
set $text-color		 #f8f8f2
set $inactive-text-color #75715e
set $urgent-bg-color	 #f92672aa
set $urgent-text-color   #f9f8f5
set $white               #ffffffff
set $transparent         #00000000

## KEYBINDINGS

# Numbers
bindsym $mod+1                                  workspace $workspace1
bindsym $mod+Shift+1                            move container to workspace $workspace1
bindsym $mod+2                                  workspace $workspace2
bindsym $mod+Shift+2                            move container to workspace $workspace2
bindsym $mod+3                                  workspace $workspace3
bindsym $mod+Shift+3                            move container to workspace $workspace3
bindsym $mod+4                                  workspace $workspace4
bindsym $mod+Shift+4                            move container to workspace $workspace4
bindsym $mod+5                                  workspace $workspace5
bindsym $mod+Shift+5                            move container to workspace $workspace5
bindsym $mod+6                                  workspace $workspace6
bindsym $mod+Shift+6                            move container to workspace $workspace6
bindsym $mod+7                                  workspace $workspace7
bindsym $mod+Shift+7                            move container to workspace $workspace7
bindsym $mod+8                                  workspace $workspace8
bindsym $mod+Shift+8                            move container to workspace $workspace8
bindsym $mod+9                                  workspace $workspace9
bindsym $mod+Shift+9                            move container to workspace $workspace9
bindsym $mod+0                                  workspace $workspace10
bindsym $mod+Shift+0                            move container to workspace $workspace10
        

# Letters
bindsym $mod+a                                  focus parent
#bindsym $mod+Shift+a
#bindsym $mod+b
#bindsym $mod+Shift+b
#bindsym $mod+c
bindsym $mod+Shift+c                            reload
bindsym $mod+d                                  exec rofi -show run -show-icons -drun-icon-theme Papere -auto-select
bindsym $mod+Shift+d                            exec code
bindsym $mod+e                                  layout toggle split
#bindsym $mod+Shift+e                            
bindsym $mod+f                                  fullscreen toggle
bindsym $mod+Shift+f                            exec firefox                                  
#bindsym $mod+g
#bindsym $mod+Shift+g
bindsym $mod+h                                  split h
#bindsym $mod+Shift+h                                  
bindsym $mod+i                                  resize shrink height 10 px or 10 ppt
bindsym $mod+Shift+i                            resize shrink height 20 px or 20 ppt
#bindsym $mod+m                                  
#bindsym $mod+Shift+m
#bindsym $mod+n
#bindsym $mod+Shift+n
bindsym $mod+o                                  resize grow height 10 px or 10 ppt
bindsym $mod+Shift+o                            resize grow height 20 px or 20 ppt
bindsym $mod+p                                  resize grow width 10 px or 10 ppt
bindsym $mod+Shift+p                            resize grow width 20 px or 20 ppt
bindsym $mod+q                                  kill
#bindsym $mod+Shift+q
#bindsym $mod+r
bindsym $mod+Shift+r                            restart
bindsym $mod+s                                  layout stacking
bindsym $mod+Shift+s                            exec gnome-screenshot
#bindsym $mod+t
#bindsym $mod+Shift+t
bindsym $mod+u                                  resize shrink width 10 px or 10 ppt
bindsym $mod+Shift+u                            resize shrink width 20 px or 20 ppt
bindsym $mod+v                                  split v
#bindsym $mod+Shift+v                                  
bindsym $mod+w                                  layout tabbed
#bindsym $mod+Shift+w                                  
#bindsym $mod+x
#bindsym $mod+Shift+x
#bindsym $mod+y
#bindsym $mod+Shift+y
#bindsym $mod+z                                 
#bindsym $mod+Shift+z

# Other
bindsym $mod+Return                             exec $terminal
bindsym $mod+Shift+Return                       exec $terminal -e ranger
bindsym $mod+$left                              focus left
bindsym $mod+Shift+$left                        move left
bindsym $mod+$down                              focus down
bindsym $mod+Shift+$down                        move down
bindsym $mod+$up                                focus up
bindsym $mod+Shift+$up                          move up
bindsym $mod+$right                             focus right
bindsym $mod+Shift+$right                       move right

bindsym $mod+space                              focus mode_toggle
bindsym $mod+Shift+space                        floating toggle
bindsym $mod+minus                              scratchpad show
bindsym $mod+Shift+minus                        move scratchpad

bindsym $mod+Escape                             mode $modepower

bindsym XF86AudioRaiseVolume                    exec --no-startup-id pactl set-sink-volume 0 +5% #increase sound volume
bindsym XF86AudioLowerVolume                    exec --no-startup-id pactl set-sink-volume 0 -5% #decrease sound volume
bindsym XF86AudioMute                           exec --no-startup-id pactl set-sink-mute 0 toggle # mute sound

bindsym XF86MonBrightnessUp                     exec xbacklight -inc 20 # increase screen brightness
bindsym XF86MonBrightnessDown                   exec xbacklight -dec 20 # decrease screen brightness
bindsym XF86TouchpadToggle                      exec ~/.i3/toggletouchpad.sh # toggle touchpad
bindsym XF86AudioPlay                           exec playerctl play
bindsym XF86AudioPause                          exec playerctl pause
bindsym XF86AudioNext                           exec playerctl next
bindsym XF86AudioPrev                           exec playerctl previous
 
mode $modepower {
        bindsym j mode "default",               exec --no-startup-id betterlockscreen -l dimblur 
        bindsym k mode "default",               exit
        bindsym l mode "default",               exec --no-startup-id shutdown now
        bindsym semicolon mode "default",       exec --no-startup-id reboot

        bindsym Escape mode "default"
        bindsym Return mode "default"
}

#mode vim {	
	#bindsym $mod+1 workspace 2:web; layout tabbed; exec [ $(ps h -C vimb | wc -l) = 0 ] && /usr/bin/vimb -s
	#mode "default"
#}

bindsym $mod+Tab workspace next
bindsym $mod+Shift+Tab workspace prev

### ASSIGNS

workspace $workspace1 output $lmonitor
workspace $workspace2 output $lmonitor
workspace $workspace3 output $lmonitor
workspace $workspace4 output $rmonitor
workspace $workspace5 output $rmonitor
workspace $workspace6 output $rmonitor
workspace $workspace7 output $rmonitor
workspace $workspace8 output $rmonitor
workspace $workspace9 output $rmonitor
workspace $workspace10 output $rmonitor

default_border                                  none

#assign [class="^.*"]                            workspace $workspace5
for_window [class="Firefox"]                    move to workspace $workspace1
#for_window [class="Termite"]                    move to workspace $workspace2
for_window [class="Code"]                       move to workspace $workspace4
for_window [class="Texmaker"]                   move to workspace $workspace4
for_window [class="Thunderbird"]                move to workspace $workspace3
for_window [class="Spotify"]                    move to workspace $workspace3    
for_window [class="^.*"]                        border pixel 0
focus_follows_mouse no

### COLOR ASSIGNMENT

client.focused          $bg-color          $bg-color          $text-color          #00ff00
client.unfocused        $inactive-bg-color $inactive-bg-color $inactive-text-color #00ff00
client.focused_inactive $inactive-bg-color $inactive-bg-color $inactive-text-color #00ff00
client.urgent           $urgent-bg-color   $urgent-bg-color  $urgent-text-color   #00ff00

### GAPS

gaps inner 15
gaps outer 0
floating_modifier $mod
### STARTUP
exec --no-startup-id i3-msg "workspace 2:terminal; append_layout ~/.config/i3/ws2.json"
exec_always "setxkbmap -layout us,de"
exec_always "setxkbmap -option 'grp:win_space_toggle'"
exec_always ~/.config/screenlayout.sh

#exec_always --no-startup-id ~/.config/polybar/launch.sh
exec_always feh --bg-fill ~/.config/wallpapers/$wallpaper
exec_always compton 
exec code
exec firefox 
exec thunderbird
exec spotify

exec polybar -r default
exec xmodmap -e "clear lock" #disable caps lock switch
exec xmodmap -e "keysym Caps_Lock = Escape" #set caps_lock as escape

exec --no-startup-id $terminal --name "update"
exec --no-startup-id $terminal --name "terminal"
exec --no-startup-id $terminal --name "ranger" -e ranger 
</pre>

<pre>
Logfile URL: None
</pre>

<pre>
- Linux Distribution & Version: Ubuntu 18.04 bionic, Kernel: x86_64 Linux 4.15.0-30-generic
- Compositor: Yes, compton. The bug is still there when compton hasn't been started.
</pre>

**Comment by Airblader** [comment]
Maybe the emulators open their window »too quickly«? Already open windows won't be swallowed. Can you try chaining the commands in order?

If that doesn't work, we'll need to look at the log file. I'm closing this issue here since this isn't specific to gaps, so please report it upstream against i3 including log file and we'll look at it there. Thanks!

**Comment by mifrandir** [comment]
It's probably to quickly. Now I run the following script on startup:
<pre>
#!/usr/bin/env bash

i3-msg "workspace 2:terminal; append_layout ~/.config/i3/ws2.json" 
termite --name "update" -e fish &
termite --name "terminal" -e fish &
termite --name "ranger" -e ranger & 
</pre>

Everything works fine! Thanks for your help!

**Comment by mifrandir** [comment]
It's probably too quickly. Now I run the following script on startup:
<pre>
#!/usr/bin/env bash

i3-msg "workspace 2:terminal; append_layout ~/.config/i3/ws2.json" 
termite --name "update" -e fish &
termite --name "terminal" -e fish &
termite --name "ranger" -e ranger & 
</pre>

Everything works fine! Thanks for your help!
