### ISSUE TITLE
Please allow enabling/disabling manpages and docs separately with individual --enable-xx arguments

### ISSUE THREAD

**Issue by yurivict** [Airblader/i3#234]
## I'm submitting a…

<pre>
[ ] Bug
[X] Feature Request
[ ] Documentation Request
[ ] Other (Please describe in detail)
</pre>

## Current Behavior
Can't leave manpages and remove docs

## Expected Behavior
Need to be able to enable docs independently from manpages.
Please have separate enable/disable arguments for both.

Version 4.15.0.1 on FreeBSD.

**Comment by Airblader** [comment]
Thanks for opening this issue. I'm not looking to have i3-gaps deviate from i3 whenever it can be avoided. So please open this request against upstream i3 :-)

As a general rule, when asking for a change, please don't just describe what change you want to see but why you want to see it. Without a rationale its very unlikely and unreasonable to make a change.

**Comment by yurivict** [comment]
https://github.com/i3/i3/issues/3378
