### ISSUE TITLE
Memory leak with i3bar

### ISSUE THREAD

**Issue by ghost** [Airblader/i3#235]
## I'm submitting a…
<pre>
[x] Bug
[ ] Feature Request
[ ] Documentation Request
[ ] Other (Please describe in detail)
</pre>

## Current Behavior
i3bar seems to allocate (via mmap according to strace) about 700KB-1MB per second, according to htop.

## Expected Behavior
i3bar memory to stay stable

## Reproduction Instructions
1. Run i3bar

## Environment
Output of `i3 --moreversion 2>&-`:
<pre>
Binary i3 version:  4.15.0.1-306-gfd3ed3f1 (2018-09-16, branch "gaps-next") © 2009 Michael Stapelberg and contributors
Running i3 version: 4.15.0.1-306-gfd3ed3f1 (2018-09-16, branch "gaps-next") (pid 862)
Loaded i3 config: /home/m712/.config/i3/config (Last modified: Mon 17 Sep 2018 12:03:59 PM +03, 16657 seconds ago)

The i3 binary you just called: /usr/local/bin/i3
The i3 binary you are running: i3 
</pre>

Snipped the unrelated parts from the config.
<pre>
# Font for window titles. Will also be used by the bar unless a different font
# is used in the bar {} block below.
font pango:Terminus,Font Awesome 5 Free,Font Awesome 5 Brands 8
#...
# Start i3bar to display a workspace bar (plus the system information i3status
# finds out, if available)
bar {
        status_command i3blocks
}
</pre>

i3blocks config:
<pre>
# i3blocks config file
# *snip*

# Global properties
command=/home/m712/.config/i3blocks/widgets/$BLOCK_NAME
separator_block_width=10
markup=none

# Volume indicator
#
# The first parameter sets the step (and units to display)
# The second parameter overrides the mixer selection
# See the script for details.
[volume]
label=
instance=Master
interval=once
signal=10
separator=false
separator_block_width=5

[backlight]
label=
interval=once
signal=10

# Memory usage
#
# The type defaults to "mem" if the instance is not specified.
[memory]
label=
separator=false
separator_block_width=5
interval=30

[memory]
label=+
instance=swap
separator=false
interval=30

# Disk usage
[disk]
label=
interval=30

# Network interface monitoring
[iface]
color=#00FF00
interval=10
separator=false
separator_block_width=0

[wifi]
label=,
instance=wlp1s0
interval=10
separator=false
separator_block_width=5

[bandwidth]
interval=5

# CPU usage
[load_average]
label=
interval=5
separator=false
separator_block_width=5

[cpu_usage]
label=
interval=3
min_width= 99%

# Battery indicator
[battery]
label=
interval=30

# Date Time
[time]
command=date '+%Y-%m-%d %H:%M:%S'
interval=1

# Key indicators
[keyindicator]
instance=CAPS
interval=once
signal=11

[keyindicator]
instance=NUM
interval=once
signal=11
</pre>

<pre>
- Linux Distribution & Version: Debian Sid 20180917
- Are you using a compositor (e.g., xcompmgr or compton): compton 0.1~beta2
</pre>

**Comment by orestisfl** [comment]
Did you compile i3-gaps your self? If yes, did you make sure to compile with `--disable-sanitizers`?

**Comment by ghost** [comment]
I don't think I added `--disable-sanitizers`, I will try to build with it.

**Comment by ghost** [comment]
`--disable-sanitizers` did indeed fix the issue. Maybe a warning should be added to wiki?

**Comment by Airblader** [comment]
The wiki already says that users shouldn't compile from source. I don't want to turn the Wiki into even more of a reason for people to ignore this. :-)

**Comment by Airblader** [comment]
That said, the current instructions already mention `--disable-sanitizers`

**Comment by ghost** [comment]
There is no version for Debian Sid. Are there plans for this?

**Comment by Airblader** [comment]
You'd have to ask the package maintainers for Debian. I only provide the project, I cannot maintain packages for all distros :-)

**Comment by ghost** [comment]
Alright, I'll do that, thanks for the project!
