### ISSUE TITLE
Compiling in WSL - Ubuntu 16.04

### ISSUE THREAD

**Issue by cgxeiji** [Airblader/i3#238]
## I'm submitting a…

<pre>
[ ] Bug
[ ] Feature Request
[ ] Documentation Request
[ x ] Other (Please describe in detail)
</pre>

## Current Behavior

When building Airblader/i3@52240a0, the compiler does not find the definition of `g_utf8_make_valid()`.
Compilation with Airblader/i3@fdf5d3a works without problems, as suggested by Xyene ([here](https://github.com/Xyene/wsl-dotfiles/issues/1)).

## Expected Behavior

The build should compile without problems.

## Reproduction Instructions

Downloaded dependencies for Ubuntu 16.04, and build as per [wiki].(https://github.com/Airblader/i3/wiki/Compiling-&-Installing)

## Environment

Output of `i3 --moreversion 2>&-`:
<pre>
i3 version: 4.13-116-gfdf5d3aa (2017-03-28, branch "tags/4.13-116-gfdf5d3aa") (pid 4730)
</pre>

<pre>
- Linux Distribution & Version:
Description:	Ubuntu 16.04.5 LTS
Release:	16.04
Codename:	xenial
</pre>

**Comment by orestisfl** [comment]
https://github.com/i3/i3/pull/3415

**Comment by cgxeiji** [comment]
Thank you for the information.

I am closing this because it is an `i3` issue, not `i3-gaps`.

**Comment by cgxeiji** [comment]
~~Leaving this for someone else who may have the same problem, until this issue gets resolved, it is possible to build with 3595bdadf38c382c9a7f8cd983989644e67a0baf.~~

Looks like the fix has been merged into the latest PR.
