### ISSUE TITLE
no_focus doesn't work properly

### ISSUE THREAD

**Issue by mac1202** [Airblader/i3#239]
Hi I have added this line in config files to avoid notification stealing focus
`
no_focus [window_type="notification"]`

The issue I got is that it only work when I have two or more windows open on the workspace. If I only have 1 windows open the notification get the focus.

Screenshot with only 1 window open notification got the focus (blue border)
https://ptpb.pw/aJhX.png
with 2 windows no focus (no blue border)
https://ptpb.pw/-lkR.png

Curently using i3-gaps 4.15.0.1, also tested on i3-gaps-next-git and the issue is there too.

**Comment by Airblader** [comment]
From the issue template you ignored and deleted:

> IMPORTANT NOTE: If your issue is not specific to any feature provided by i3-gaps but
>                to i3 in general, please open the issue upstream against i3/i3.
