### ISSUE TITLE
cannot exit i3

### ISSUE THREAD

**Issue by jjn2009** [Airblader/i3#24]
I try using $mod+shift+e
then I attempt to click "yes, exit i3"
nothing happens
however I can hit the close button

**Comment by Airblader** [comment]
Does this work for you with vanilla i3? Seems unlikely to be an issue of my fork as I haven't changed the behavior there. And I've just tried it on my laptop and it works just fine.

Please try doing this on a normal i3 install and if it fails there as well, submit it at bugs.i3wm.org.

**Comment by Airblader** [comment]
Without further activity I'll close this issue after 1 week (friday).

**Comment by jjn2009** [comment]
I've messed around with the config a bit, not sure if that's what changed things but at this point neither the vanilla or your repo cause the behavior anymore.
