### ISSUE TITLE
ASan runtime error on Ubuntu 18.04

### ISSUE THREAD

**Issue by Staberinde** [Airblader/i3#241]
## I'm submitting a…

<pre>
[x] Bug
[ ] Feature Request
[ ] Documentation Request
[ ] Other (Please describe in detail)
</pre>

## Current Behavior
* i3-gaps doesn't launch successfully
## Expected Behavior
* i3-gaps launches successfully
## Reproduction Instructions
1. Install i3-gaps on Ubuntu 16.04 via https://github.com/unix121/i3wm-themer/blob/master/install_ubuntu.sh#L32
2. Upgrade to Ubuntu 18.04
3. Reinstall i3-gaps via script mentioned in point 1

So i've also had issues with running `i3-gaps` on 18.04 (4.15 gaps-next I think, installed via this script https://github.com/unix121/i3wm-themer/blob/master/install_ubuntu.sh#L32) In my case the error that showed up in my `~/.xsession-errors` was `ASan runtime does not come first in initial library list; you should either link runtime to your application or manually preload it with LD_PRELOAD`. Removing i3 gaps and replacing it with i3 4.14 fixes the issue.

**Comment by Airblader** [comment]
Please see the wiki for installing from source. Thanks!

**Comment by Airblader** [comment]
Addendum: if you have the same issue building i3 from source (which you should, since i3-gaps doesn't modify the build at all), you can report an issue there.
