### ISSUE TITLE
When open vim, it has a gap on the right of the vim.

### ISSUE THREAD

**Issue by GoodlPlus** [Airblader/i3#242]
## I'm submitting a…

<pre>
[x] Bug
[ ] Feature Request
[ ] Documentation Request
[ ] Other (Please describe in detail)
</pre>

## Current Behavior

When I open vim. I found there is always a gap on the right of vim.At first, I think it may caused by my terminal, my terminal is xfce4-terminal, but I change my terminal, like urxvt, xterm. I found them also has this behavior.
## Expected Behavior

I want to remove this gap.
## Reproduction Instructions

Just open the vim in terminal.

## Environment

Output of `i3 --moreversion 2>&-`:
<pre>
i3 version: 4.15.0.1
</pre>
![2018-10-04-173526_1920x1080_scrot](https://user-images.githubusercontent.com/42902526/46465670-ccb60600-c7fb-11e8-9a34-2d1508f90369.png)

look at the right of the vim. You can find that there has a gap.Although is little.

**Comment by BeikerxD** [comment]
this not a bug of gaps... Is vim with your form to work with space, you can test resize window of vim and you can see like persist the gaps depending of width and height on the window, is vim not i3-gaps... I have not a good english but I try help community

**Comment by Airblader** [comment]
Thanks, BeikerxD. That's absolutely right, this is due to the fact that the terminal emulator wants its size to be in steps of a certain size, so i3 has to make it fit as much as possible while respecting that.
