### ISSUE TITLE
upgrade i3-gaps on debian  Documentation Request

### ISSUE THREAD

**Issue by ycf83** [Airblader/i3#244]
## I'm submitting a…

[x] Documentation Request 

## Reproduction Instructions

<pre>
- Linux Distribution & Version:  debian sid
- Are you using a compositor (e.g., xcompmgr or compton): compton
</pre>

hi i use debian sid , i wont to know how to upgrade i3-gaps , i don't find information about this, i just need the correct way to do, thnk's you

**Comment by Airblader** [comment]
I don't know what you mean, to be honest. If you have a package for i3-gaps, update it like any other package. If you installed from source, just do the same thing again with an updated clone of the repository.

**Comment by ycf83** [comment]
Sorry for my bad English, yes i  installed from source, can you plz give me command line to update , i3-gaps it's not included in debian

**Comment by Airblader** [comment]
As described in the wiki I do not support requests regarding compilation unless you're working to provide a package for your distribution. Please ask these questions on the i3 subreddit or similar places.
