### ISSUE TITLE
Crashing window on resizing

### ISSUE THREAD

**Issue by iceychris** [Airblader/i3#245]
## I'm submitting a…

<pre>
[x] Bug
[ ] Feature Request
[ ] Documentation Request
[ ] Other (Please describe in detail)
</pre>

## Current Behavior

When resizing the width of one of two non-floating windows until one is covered by the other or its width is too small (?), the window with the smaller width starts to consume large amounts of memory which leads to either
- the window getting killed (OOM killer) or
- a freeze of your system (swap enabled)

## Expected Behavior

The window with the smaller width should not get killed / start to consume a large amount of memory.

## Reproduction Instructions

- open an empty i3 workspace
- open two windows (tested with lxappearance and alacritty) in vertical split mode
- resize (grow) the right window in the direction of the left one, e.g. do this:
    ```
    $ i3-msg resize grow width 10 px
    ```
    until the right window completely covers the left one.
- watch memory consumption of the left window app instance rise ad infinitum using e.g. top:
    ```
      PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND
    28159 chris     20   0 8853752   4.1g   1456 S   0.0  71.1   0:07.99 alacritty
    28254 chris     20   0  440568   9380   6736 S   0.0   0.2   0:00.57 alacritty
    ```

## Environment

Output of `i3 --moreversion 2>&-`:
<pre>
i3 version: 
Binary i3 version:  4.15.0.1 (2018-03-13) © 2009 Michael Stapelberg and contributors
Running i3 version: 4.15.0.1 (2018-03-13) (pid 3440)ort…)
Loaded i3 config: /home/chris/.config/i3/config (Last modified: Wed 17 Oct 2018 12:39:10 AM CEST, 5368 seconds ago)
The i3 binary you just called: /nix/store/1cnb8qwqfyzhvwcvjxn458c20q5b50m9-i3-gaps-4.15.0.1/bin/i3
The i3 binary you are running: /nix/store/1cnb8qwqfyzhvwcvjxn458c20q5b50m9-i3-gaps-4.15.0.1/bin/i3
</pre>

[i3 config](https://pastebin.com/nxq5wMwM)

<pre>
- Linux Distribution & Version:
NixOS 18.09
- Are you using a compositor (e.g., xcompmgr or compton):
compton
  but reproduced without it
</pre>

~/.xsession-errors
```
...
(lxappearance:14093): Gtk-WARNING **: 02:55:14.072: gtk_widget_size_allocate(): attempt to allocate widget with width -2 and height 17
(lxappearance:14093): Gtk-WARNING **: 02:55:14.076: gtk_widget_size_allocate(): attempt to allocate widget with width -5 and height 17
...
```

I could not reproduce this using two chromium instances, so this might not even be related to i3?

**Comment by Airblader** [comment]
From the issue template:

> IMPORTANT NOTE: If your issue is not specific to any feature provided by i3-gaps but
                to i3 in general, please open the issue upstream against i3/i3.

Note that this has been fixed in https://github.com/i3/i3/pull/3389 so please make sure you reproduce with a current git checkout of i3 before filing a new issue. Thanks!

**Comment by Airblader** [comment]
That said, if it happens *only* using gaps, please let me know!
