### ISSUE TITLE
Compilation of i3 Fails when following install guide

### ISSUE THREAD

**Issue by xmaayy** [Airblader/i3#246]
## I'm submitting a…

<pre>
[x] Bug
[ ] Feature Request
[ ] Documentation Request
[ ] Other (Please describe in detail)
</pre>

## Current Behavior
Following the install script here - https://github.com/Airblader/i3/wiki/Compiling-&-Installing
I get this error

`make && sudo make install
make  all-am
make[1]: Entering directory '/home/xmay/Downloads/i3-gaps/build'
  CC       src/i3-floating.o
../../i3-gaps/src/floating.c: In function ‘floating_reposition’:
../../i3-gaps/src/floating.c:910:9: error: too few arguments to function ‘render_con’
         render_con(con, false);
`

## Expected Behavior
A successful build

## Reproduction Instructions
Follow that install guide and copy paste each step.

## Environment

Output of `i3 --moreversion 2>&-`:
<pre>
i3 version: Not installed / Latest from repo
</pre>

**TEMP FIX** : Rolled back to b971c0e50f00756227bb27d2fc5f7087310f3927 via git checkout. This install works so changes made today are the culprit

**Comment by Airblader** [comment]
It's from a merge, sorry about that. I'll fix it soon!

**Comment by Airblader** [comment]
Should be fixed now. Sorry for that and thanks for reporting it. Let me know if it doesn't work yet still!
