### ISSUE TITLE
Resizing (with cursor) is based on the center of gaps rather than edge of container, but mouse snaps to container.

### ISSUE THREAD

**Issue by aksel** [Airblader/i3#247]
## I'm submitting a…

<pre>
[x] Bug
[ ] Feature Request
[ ] Documentation Request
[ ] Other (Please describe in detail)
</pre>

## Current Behavior

[Here's a video showing what I'm talking about, because I have a hard time describing the issue.](https://youtu.be/V8q9JVMYssc)

Resizing is based on the center of the gap, i.e. the center point between two containers. But when resizing, the cursor snaps to the indicator of one of the containers.

This means the layout resizes after you release the button, because it will snap the indicator to the center of the gap.

The video shows this. All I'm doing is continually clicking and releasing.

## Expected Behavior

Resizing should account for gaps. When releasing, the layout should change.

## Reproduction Instructions

Enable gaps, and resize with your cursor. Don't move it, just click and release.

## Environment

Output of `i3 --moreversion 2>&-`:
<pre>
Binary i3 version:  4.15.0.1-323-gccb19472 (2018-09-28, branch "gaps-next") © 2009 Michael Stapelberg and contributors
Running i3 version: 4.15.0.1-323-gccb19472 (2018-09-28, branch "gaps-next") (pid 659)
Loaded i3 config: /home/aksel/.config/i3/config (Last modified: mán 17 sep 2018 22:25:17 CEST, 3244180 seconds ago)

The i3 binary you just called: /usr/bin/i3
The i3 binary you are running: i3
</pre>

[i3 config](https://github.com/aksel/dotfiles/blob/master/.config/i3/config)

<pre>
- Linux Distribution & Version: Arch, 4.18.14-arch1-1-ARCH
- Are you using a compositor (e.g., xcompmgr or compton): The issue happens with and without compositor.
</pre>

**Comment by Airblader** [comment]
Yeah, this is just somewhat due to the hacky nature of gaps. If it can be fixed with minor changes (which it probably can), I'm happy to accept a PR for it.

**Comment by aksel** [comment]
I don't really know C, but I'd like to give it a shot! :smile:

**Comment by orestisfl** [comment]
Probably start from `resize_graphical_handler` in https://github.com/Airblader/i3/blob/gaps-next/src/resize.c

**Comment by aksel** [comment]
Thank you guys for your help! :smile:
