### ISSUE TITLE
Version 4.16 broke click events for i3blocks

### ISSUE THREAD

**Issue by mna** [Airblader/i3#255]
## I'm submitting a…

<pre>
[x] Bug
[ ] Feature Request
[ ] Documentation Request
[ ] Other (Please describe in detail)
</pre>

## Current Behavior

With version 4.16 installed on Arch Linux (via pacman), `i3blocks` no longer works for mouse button click events. I identified this commit as introducing the issue: https://github.com/Airblader/i3/commit/3745e6f4843b638fcc73c3b499bdae4bc6f6132c

I compiled a local version with this commit reverted and `i3blocks` is back to working as usual.

## Expected Behavior

Clicking on a "blocklet" triggers the associated command with env vars for the `$button` and coordinates (`$x`, `$y`). 

## Reproduction Instructions

With `i3blocks` installed and a click-aware `blocklet`, try clicking on it, nothing happens.

## Environment

Output of `i3 --moreversion 2>&-`:
<pre>
i3 version:
Binary i3 version:  4.16 (2018-11-04) © 2009 Michael Stapelberg and contributors
Running i3 version: 4.16 (2018-11-04) (pid 7447)o abort…)
Loaded i3 config: /home/m/.config/i3/config (Last modified: Mon 12 Nov 2018 07:13:53 PM EST, 731 seconds ago)

The i3 binary you just called: /usr/bin/i3
The i3 binary you are running: i3 
</pre>

https://gist.github.com/mna/e208076952d8c66ea636ba0dd0f4521e

But not really relevant here (except for the fact it uses i3blocks).

<pre>
Logfile URL:
</pre>

<pre>
- Linux Distribution & Version: Arch Linux
- Are you using a compositor (e.g., xcompmgr or compton): compton
</pre>

**Comment by Airblader** [comment]
Since this issue isn't specific to i3-gaps, please report it upstream in i3. Thanks!
