### ISSUE TITLE
Fedora copr repository doesn't work on Fedora 29

### ISSUE THREAD

**Issue by niklassc-xyz** [Airblader/i3#256]
## I'm submitting a…

<pre>
[x] Bug
[ ] Feature Request
[ ] Documentation Request
[ ] Other (Please describe in detail)
</pre>

## Current Behavior

The copr repository gregw/i3desktop linked in the wiki for Fedora 25+ does not work on Fedora 29. It can be added but when it gets accessed it gives the error that the repository cannot be synchronised and that it will be ignored (Zwischenspeicher für Paketquelle »gregw-i3desktop« konnte nicht synchronisiert werden, irgnoring this repo).

## Reproduction Instructions

This bug appeared on a version of Fedora that I upgraded from 28 to 29 but it also appeared on a newly installed version of Fedora 29.

<pre>
- Linux Distribution & Version: Fedora 29
</pre>

**Comment by Airblader** [comment]
Do you know of a replacement? Otherwise feel free to remove it from the list. I don't maintain these packages, to get them to work you'll have to contact the maintainer.

**Comment by niklassc-xyz** [comment]
Okay, thanks! I was not sure who was maintaining it. Unfortunately I don't know of a replacement.
