### ISSUE TITLE
Difficult to uninstall

### ISSUE THREAD

**Issue by reikdas** [Airblader/i3#259]
I was unsure where to ask for support regarding this, so I figured this might be the safest bet. 

I installed i3-gaps using this script - https://gist.github.com/dabroder/813a941218bdb164fb4c178d464d5c23

How do I uninstall it now?

**Comment by Airblader** [comment]
This is part of why you should install things through a package manager and not through random scripts. Please see the wiki on Github here on why I don't do support for these questions. You can go to the i3wm subreddit and ask it there. Thanks for understanding.
