### ISSUE TITLE
No package 'xcb-shape' found

### ISSUE THREAD

**Issue by jarbus** [Airblader/i3#261]
## I'm submitting a…

<pre>
[x] Bug
[ ] Feature Request
[ ] Documentation Request
[ ] Other (Please describe in detail)
</pre>

## Current Behavior

'No package 'xcb-shape' found', even though libxcb-xrm-dev is installed.
## Expected Behavior

Expected to configure but instead package unavailable
## Reproduction Instructions

Uncertain, attempting to install on plain Ubuntu 18.04.1 LTS
## Environment

Output of `i3 --moreversion 2>&-`:
<pre>
i3 version: Binary i3 version:  4.14.1 (2017-09-24) © 2009 Michael Stapelberg and contributors

</pre>

<pre>
Default config
</pre>

<pre>
Logfile URL:
</pre>

<pre>
- Linux Distribution & Version:
- Are you using a compositor (e.g., xcompmgr or compton):
</pre>

**Comment by Airblader** [comment]
Since shape support is coming from upstream, please reproduce with i3 and open an issue against i3. Thanks! 

Please make sure to include how you're trying to install.

**Comment by austerj** [comment]
I am having the same issue on Debian Stretch. Regular i3 still works fine, configure complains about not finding various xcb packages (including xcb-shape), but all dependencies including libxcb-shape0 are installed.

I'm installing using the instructions and i3-gaps was working previously. Suddenly i3 started spitting errors about my config file, and from the log it was all features coming from i3-gaps. Tried installing i3-gaps again and ran into the same issue above.

**Comment by Airblader** [comment]
When you say regular i3 is fine, do you mean you are also installing i3 from the latest source of the `next` branch?

**Comment by austerj** [comment]
Thanks for the quick reply! What I meant was that my current installation of i3 from the Debian repos is still working fine once I disable all features from gaps. The gaps branch was installed before and working completely fine until today, and trying to install it again I get the above complaint about missing dependencies when running configure. I have been following the install instructions on the wiki and these have worked fine for me before, but for whatever reason it seems unable to locate the xcb packages now.

**Comment by Airblader** [comment]
Of course packaged versions will work, shape support is not released anywhere yet, so comparing a build from source of i3-gaps and a packaged version of i3 makes little sense. Please try building i3's "next" branch from source with the same instructions you are building i3-gaps with.

**Comment by orestisfl** [comment]
Maybe you are missing the `-dev` shape package? libxcb-shape0-dev

**Comment by austerj** [comment]
> Maybe you are missing the `-dev` shape package? libxcb-shape0-dev

Thank you so much! I have no idea what happened to break things in the first place, but now the gaps branch installed completely fine and my previous config works again.

**Comment by AlvaroSpain1987** [comment]
Hello I’m having same issue, running rasbpian in raspberry pi, I don’t really know what to do
