### ISSUE TITLE
Setting negative gap with a 'set' command

### ISSUE THREAD

**Issue by guest73** [Airblader/i3#262]
## I'm submitting a…

<pre>
[x] Bug
[ ] Feature Request
[ ] Documentation Request
[ ] Other (Please describe in detail)
</pre>

## Current Behavior
bindsym $mod+u gaps top current set -6
Setting a negative top (and other) gaps does not work.

## Expected Behavior
A negative gap has to be applied.
It works correctly when read from config file. Setting this in config file works
gaps top -6

## Environment
Output of `i3 --moreversion 2>&-`:
<pre>
i3 version:
Binary i3 version:  4.16-51-gbfba56b1 (2018-11-17, branch "gaps-next") © 2009 Michael Stapelberg and contributors
Running i3 version: 4.16-51-gbfba56b1 (2018-11-17, branch "gaps-next") (pid 18609)
Loaded i3 config: /home/winters/.config/i3/config-xfce4-services (Last modified: Tue 11 Dec 2018 02:04:33 EET, 325 seconds ago)

The i3 binary you just called: /usr/bin/i3
The i3 binary you are running: i3 
</pre>

<pre>
- Linux Distribution & Version: Linux Mint Tara
- Are you using a compositor (e.g., xcompmgr or compton): compton
</pre>

**Comment by Airblader** [comment]
Thanks for filing the issue. Why exactly *should* this work in the first place?

**Comment by guest73** [comment]
Well. I am trying to accoplish somethig ... :)
What I want is to use some kind of a transparent status bar Polybar or tint2. I am still in process of setting up my system, but saw examples on the Internat. And with that transparent bar I decided I do not need the top gap so all the other gaps are kind of a continuation of that transparent bar. 
With this configuration in place

```
set $default_gaps_inner 7
set $default_gaps_top -6 # maybe will put -5 here, the Idea is to shorten the top inner gap
set $default_gaps_outer 0
...
gaps inner $default_gaps_inner
gaps top $default_gaps_top
gaps right $default_gaps_outer
gaps bottom $default_gaps_outer
gaps left $default_gaps_outer

```
I am able to get what I want.
But, as always, I want more :) I've put some kaybindins to remove any gaps for current workspace if I decide I need more space and do not want to waste it.

```
bindsym $mod+Shift+g mode "$mode_gaps"
mode "$mode_gaps" {
    bindsym 0      mode "default", exec --no-startup-id i3-msg "gaps inner current set 0" && i3-msg "gaps outer current set 0"
    bindsym d      mode "default", exec --no-startup-id i3-msg "gaps inner current set $default_gaps_inner" && i3-msg "gaps outer current set $default_gaps_outer" && i3-msg "gaps top current set $default_gaps_top" # $default_gaps_top is -6 - negative number

    bindsym Return mode "default"
    bindsym Escape mode "default"
}
```
So 
$mod+Shift+g 0 - removes any gaps
$mod+Shift+g d - puts it to default with all inner gaps equals to 7, top equals to -6 and all the rest outer geps - 0
The later does not work and seems it puts top to 0.
I tried with 
i3-msg "gaps top current set -6"
and
i3-msg "gaps top current minus 6"
Nothing worked.
I consider it strange I can achieve the desired layout with simple configuration but not being able to restore it with any i3-msg "gaps top ..." command.

**Comment by Airblader** [comment]
> I consider it strange I can achieve the desired layout with simple configuration but not being able to restore it with any i3-msg "gaps top ..." command.

Agreed, but I think there's an argument to be made that it's not that the latter is missing, but that the former shouldn't be possible… ;-)

If you want to file a PR and this doesn't raise the complexity significantly, it'd be fine with me, I think. I trust users choosing sane values for their gaps.
