### ISSUE TITLE
[feature request] slide animation on workspace switching

### ISSUE THREAD

**Issue by thegoldgoat** [Airblader/i3#265]
I think it would be great if there were some kind of animation during workspace switching, maybe disabled by default but configurable via the config file

**Comment by Airblader** [comment]
I'm closing this without commenting too much simply because I do not appreciate issues that ignore the issue template, but I will say as much as that this will never happen in i3 or i3-gaps because it is just way too complex to do.

**Comment by thegoldgoat** [comment]
I am really sorry for my bad issue.
Thanks anyway for your answer.
