### ISSUE TITLE
xrdb .Xressources messes with gaps

### ISSUE THREAD

**Issue by adriencarbonaro** [Airblader/i3#268]
## I'm submitting a…

<pre>
[x] Bug
[ ] Feature Request
[ ] Documentation Request
[ ] Other (Please describe in detail)
</pre>

## Current Behavior
When I put the line `exec-always --no-startup-id xrdb -merge $HOME/.Xresources` in my config, the gaps change by themselves.

## Expected Behavior
I would like just to merge my X resources to get colors for example, without changing the gaps

## Reproduction Instructions
Put `exec-always --no-startup-id xrdb -merge $HOME/.Xresources` in i3 config and `Ctrl+Shift+r`

## Environment
<pre>
Binary i3 version:  4.15.0.1-323-gccb19472 (2018-09-28, branch "gaps-next") © 2009 Michael Stapelberg and contributors
Running i3 version: 4.15.0.1-323-gccb19472 (2018-09-28, branch "gaps-next") (pid 1262)
Loaded i3 config: /home/adrien/.config/i3/config (Last modified: mer. 19 déc. 2018 12:36:49 CET, 233 seconds ago)
</pre>

<pre>
My config : https://pastebin.com/BTitjYAK
</pre>

<pre>
- Linux Distribution & Version: Ubuntu 18.04.1 LTS x86_64
- Are you using a compositor (e.g., xcompmgr or compton): compton
</pre>

**Comment by Airblader** [comment]
Can you try again, spelling `exec_always` correctly (underscore, not hyphen)?

**Comment by adriencarbonaro** [comment]
Sorry about the bad spelling but it was correctly spelled in the config

**Comment by Airblader** [comment]
Alright, then please provide your Xresources and an i3 log file (see debugging docs on the website).

Also, what exactly do you mean by "gaps change by themselves"? They disappear? Are smaller / bigger? 

Also, if you remove that line again and restart i3 once more, everything is back to normal?

**Comment by adriencarbonaro** [comment]
I'll provide the log files when I'm home.

I mean that they are bigger and the border around my windows are also bigger.

When I `xrdb .Xbackup` everything goes back to normal. `.Xbackup` is the file I create when my computer boot, so it is the default file. It is different than my `.Xdefault` I don't know why. It only has the line `*customization = -color`

my i3 log file when the bug exists : https://logs.i3wm.org/logs/5645316556587008.bz2

I'm pretty sure the problem comes from the fact that my `.Xdefaults` file is only one line ...

**Comment by adriencarbonaro** [comment]
my i3 log file when the bug exists : https://logs.i3wm.org/logs/5645316556587008.bz2

**Comment by Airblader** [comment]
> When I xrdb .Xbackup everything goes back to normal.

Even if you don't restart i3?

Can you maybe show a screenshot of the "broken" and the non-broken case?

**Comment by Airblader** [comment]
@adriencarbonaro Do you have the screenshots? Also, does this perhaps affect only a specific application or type of toolkit maybe?
