### ISSUE TITLE
feature request: sending user defined signals to ipc clients

### ISSUE THREAD

**Issue by erisdev** [Airblader/i3#270]
## I'm submitting a…

<pre>
[ ] Bug
[x] Feature Request
[ ] Documentation Request
[ ] Other (Please describe in detail)
</pre>

## Current Behavior

there's no easy way for ipc clients to e.g. act on key presses without talking to the display server or something ridiculous like giving the client its _own_ ipc interface.

## Desired Behavior

i want a mechanism to signal ipc clients from bindings and probably other ways i havent thought of yet. my thought was to add a new ipc event type and a command that triggers that event. if you'd like specifics, i've already implemented it: erisdev@15eae92ba394720a0bb2c79e593df56be103e43d. ~~i've also got a patch ready for i3ipc-python but i havent put it on github yet.~~

## Environment

Output of `i3 --moreversion 2>&-`:
<pre>
Binary i3 version:  4.16 (2018-11-04) © 2009 Michael Stapelberg and contributors
Running i3 version: 4.16 (2018-11-04) (pid 2798)o abort…)
Loaded i3 config: /home/eris/.config/i3/config (Last modified: Sun 30 Dec 2018 02:45:50 AM EST, 76121 seconds ago)

The i3 binary you just called: /usr/bin/i3
The i3 binary you are running: i3
</pre>

<pre>
- Linux Distribution & Version: manjaro... i don't know how to answer "version" meaningfully for rolling releases
- Are you using a compositor (e.g., xcompmgr or compton): nope
</pre>

**Comment by Airblader** [comment]
> or something ridiculous like giving the client its own ipc interface.

Why is that so ridiculous? You want to talk to some client, so why should i3 act as a messenger here if it has nothing to do with the message? 

Establishing a socket isn't all that much work, and you can even use a simpler mechanism such as sending a signal to the process — if you have a limited set of events (and if you don't, abusing i3 for this instead of writing a protocol sounds even stranger).

**Comment by erisdev** [comment]
idk it feels weirder to me to bother with a second communications channel and a third program to send the message when my actual end goal is to get something to happen to i3's window tree in response to a keypress and i3 is already listening for keypresses and sending events to my script

**Comment by Airblader** [comment]
So if it's about key presses, doesn't https://i3wm.org/docs/ipc.html#_binding_event do what you're looking for? You can bind your key to `nop "my_message"` and parse that in your script.

**Comment by erisdev** [comment]
that hadn't occurred to me when i was looking at the docs. i hate that it works. good enough i guess

**Comment by Airblader** [comment]
Great, then let's close this.
