### ISSUE TITLE
Cycle windows only on focused monitor/output

### ISSUE THREAD

**Issue by Davidj361** [Airblader/i3#271]
## I'm submitting a…

<pre>
[ ] Bug
[x] Feature Request
[ ] Documentation Request
[ ] Other (Please describe in detail)
</pre>

## Current Behavior

When cycling windows through focus movement keys like mod+jkl; (or whatever is bounded) you are able to focus windows windows from other monitors.

## Desired Behavior

When cycling windows through focus movement keys like mod+jkl; (or whatever is bounded) you are only able to focus the windows in the monitor/output that has focus.
Would work well when you are using focus output binds like this: 
```
bindsym $mod+bracketright focus output right
bindsym $mod+bracketleft focus output left
```

## Environment

Output of `i3 --moreversion 2>&-`:
<pre>
i3 version: 4.16 (2018-11-04)
</pre>

<pre>
- Linux Distribution & Version: Arch Linux 4.19.12
- Are you using a compositor (e.g., xcompmgr or compton): No
</pre>

**Comment by orestisfl** [comment]
Not gaps-specific: https://github.com/i3/i3/issues/2180
