### ISSUE TITLE
Tiling new windows on the left instead of the right. Is it possible?

### ISSUE THREAD

**Issue by impascal** [Airblader/i3#272]
## I'm submitting a…

<pre>
[ ] Bug
[x] Feature Request
[ ] Documentation Request
[ ] Other (Please describe in detail)
</pre>

## Environment

Output of `i3 --moreversion 2>&-`:
<pre>
i3 version: 
</pre>

<pre>
- Linux Distribution & Version:
- Are you using a compositor (e.g., xcompmgr or compton):
</pre>

**Comment by Airblader** [comment]
https://github.com/i3/i3/issues/1767
