### ISSUE TITLE
Setting gaps that are not inner or outer cause errors

### ISSUE THREAD

**Issue by The-Demon-Prosecutor** [Airblader/i3#273]
## I'm submitting a…

<pre>
[x] Bug
[ ] Feature Request
[ ] Documentation Request
[ ] Other (Please describe in detail)
</pre>

## Current Behavior
Inner and outer gaps work fine, but any other form of gaps as described in the README result in errors when starting/restarting i3-gaps.

## Expected Behavior
Able to set specific gaps such as `top`, `horizontal`, etc.

## Reproduction Instructions
Have a single window, add value, say `gaps top 10` to the config, and restart i3 in place.

## Environment

Output of `i3 --moreversion 2>&-`:
<pre>
i3 version: Binary i3 version:  4.16 (2018-11-04) © 2009 Michael Stapelberg and contributors
Running i3 version: 4.16 (2018-11-04) (pid 24821) abort…)
Loaded i3 config: /home/$USER/.config/i3/config (Last modified: Wed 09 Jan 2019 11:42:30 PM TIMEZONE, X seconds ago)

The i3 binary you just called: /usr/bin/i3
The i3 binary you are running: i3
</pre>

i3-gaps config: https://privatebin.net/?e1b6ff5f56378198#sleBc54EFp23bOP1KQgY/k97BNaL+Jmmijxj8BsSfAc=

<pre>
ERROR: CONFIG: Expected one of these tokens: 'inner', 'outer'
ERROR: CONFIG: (in file /home/$USER/.config/i3/config)
ERROR: CONFIG: Line  90: gaps inner 7
ERROR: CONFIG: Line  91: gaps outer 7
ERROR: CONFIG: Line  92: gaps top 21
ERROR: CONFIG:                ^^^^^^
ERROR: CONFIG: Line  93: gaps bottom 10
ERROR: CONFIG: Line  94: 
ERROR: CONFIG: Expected one of these tokens: 'inner', 'outer'
ERROR: CONFIG: (in file /home/$USER/.config/i3/config)
ERROR: CONFIG: Line  91: gaps outer 7
ERROR: CONFIG: Line  92: gaps top 21
ERROR: CONFIG: Line  93: gaps bottom 10
ERROR: CONFIG:                ^^^^^^^^^
ERROR: CONFIG: Line  94: 
ERROR: CONFIG: Line  95: # start rofi (a program launcher)
</pre>

<pre>
- Linux Distribution & Version: Arch Linux (4.20.0-arch1-1-ARCH)
- Are you using a compositor (e.g., xcompmgr or compton): compton
</pre>

Also similar to [#251](https://github.com/Airblader/i3/issues/251) except on the main release and not on a source build.

**Comment by Airblader** [comment]
> Also similar to #251 except on the main release and not on a source build.

Not just similar, duplicate :-) Again, 4.16 does *not* contain this feature. There hasn't been a release yet.

**Comment by The-Demon-Prosecutor** [comment]
I have not compiled from source though. I'm using the package [i3-gaps](https://www.archlinux.org/packages/community/x86_64/i3-gaps/). 
And the i3 binary version claims to be the release from the 4th of November, 2018.

**Comment by Airblader** [comment]
And this feature has been merged on November 5, the day after.

**Comment by The-Demon-Prosecutor** [comment]
It just puzzles me then. I have no clue how I'm affected.

Sorry for being too abrasive before. I'll try to figure out what's the issue and downgrade if required.

Thanks

EDIT: Sorry! I was being extremely stupid. I thought this was already a feature in 4.16 and have been completely misunderstanding you. My apologies.

**Comment by Airblader** [comment]
No worries!

**Comment by jmriddell** [comment]
Somehow I'm having this problem with a newer version.
Installed `i3-gaps` in Arch with `pacman`.

In the log file:
```
ERROR: CONFIG: Expected one of these tokens: 'inner', 'outer'
ERROR: CONFIG: (in file /home/myuser/.config/i3/config)
```
```
ERROR: CONFIG: Line  16: gaps horizontal 5
ERROR: CONFIG:                ^^^^^^^^^^^^
```
```
ERROR: FYI: You are using i3 version 4.16.1 (2019-01-27)
```

**Comment by Airblader** [comment]
Again, 4.16 does not include this. It will only be released in 4.17. 4.16.1 is a bugfix on 4.16, it doesn't ship features.

**Comment by Galicarnax** [comment]
Using v. 4.17.1, the same problem. Only `inner` and `outer` gaps are accepted. `horizontal`, `current`, etc. all lead to errors.

**Comment by Airblader** [comment]
Please open a new issue with full information.
