### ISSUE TITLE
smart_borders option to show borders if there are multiple monitors

### ISSUE THREAD

**Issue by RatanRSur** [Airblader/i3#276]
## I'm submitting a…

<pre>
[ ] Bug
[x] Feature Request
[ ] Documentation Request
[ ] Other (Please describe in detail)
</pre>

## Current Behavior
With `smart_borders on` it does not show the border when there are multiple monitors.

## Desired Behavior
Borders are drawn when multiple windows are visible, be they multiple in a workspace or multiple because there are multiple monitors. I think this would be very useful because the use case of this option is essentially to resolve ambiguity of which window is focused.

## Environment
`i3 version 4.16 (2018-11-04) © 2009 Michael Stapelberg and contributors`

Output of `i3 --moreversion 2>&-`:
Binary i3 version:  4.16 (2018-11-04) © 2009 Michael Stapelberg and contributors
(Getting version from running i3, press ctrl-c to abort…)
Running i3 version: 4.16 (2018-11-04) (pid 1580)
Loaded i3 config: /home/ratan/.config/i3/config (Last modified: Tue 15 Jan 2019 01:41:02 AM EST, 130173 seconds ago)

The i3 binary you just called: /usr/bin/i3
The i3 binary you are running: i3

Linux 4.20.1-arch1-1-ARCH #1 SMP PREEMPT Wed Jan 9 20:25:43 UTC 2019 GNU/Linux
compton

**Comment by Airblader** [comment]
In i3 the way to distinguish focus is border color, not border width / presence. There's also other indicators such as i3bar etc. I'm not looking to add a bunch more options to these features and piling onto their complexity even more – if you want borders to emphasize focus, I suggest just using borders. If you really insist on doing it like this there's always the option to just do it via the IPC. Sorry, but thanks for understanding :-)
