### ISSUE TITLE
autoreconf gives error

### ISSUE THREAD

**Issue by obayit** [Airblader/i3#277]
## I'm submitting a…

<pre>
[x] Bug
[ ] Feature Request
[ ] Documentation Request
[ ] Other (Please describe in detail)
</pre>

Running the command "autoreconf --force --install" as described in docs for installation gives this error/output:
Makefile.am:229: warning: '%'-style pattern rules are a GNU make extension

my machine is running Ubuntu 16.04, and I wanted to update my i3-gaps after a long time not using this machine, but after "git pull" the mentioned command is not working!

**Comment by obayit** [comment]
I don't even know what this is but...
following [this stackoverflow answer](https://stackoverflow.com/questions/27975545/how-to-deal-with-autoconf-warning-style-pattern-rules-are-a-gnu-make-extens) solved the problem by making this change:
EDIT: changes are [here](https://github.com/Airblader/i3/pull/278)
Ignore this:
>>>>diff --git a/Makefile.am b/Makefile.am
>>>>index ee71b7f..71bb5f3 100644
>>>>--- a/Makefile.am
>>>>+++ b/Makefile.am
>>>>@@ -226,7 +226,7 @@ $(asciidoc_MANS): man/%.1: man/%.xml man/$(dirstamp)
>>>>        $(AM_V_GEN) out='$@'; @PATH_XMLTO@ man -o "$${out%/*}" $<
>>>>        @stamp='$@'; $(MKDIR_P) "$${stamp%/*}"

**Comment by Airblader** [comment]
Thanks for the issue & PR. First off, this isn't an error, but just a warning. :-) In theory it should work fine.

Anyhow, this is 1:1 with upstream i3, i3-gaps makes no changes here. So if there's an issue, please report it upstream. Thank you.
