### ISSUE TITLE
Restoring specific layout causes i3 to crash

### ISSUE THREAD

**Issue by TheSilvus** [Airblader/i3#279]
## I'm submitting aâ€¦

<pre>
[x] Bug
[ ] Feature Request
[ ] Documentation Request
[ ] Other (Please describe in detail)
</pre>

## Current Behavior

Creating a layout with at least two windows, one of them being Discord (only program I've been able to reproduce this with), and launching the layout and the programs within the i3 config causes an i3 crash. If Discord is already running in the background this does not happen. It does not make a difference if the other program is running already or not.

I'm reporting this to the i3-gaps repo because I'm currently unable to test it with i3 itself. If someone can reproduce it with i3 I can file this issure there.

## Expected Behavior

i3-gaps should not crash.

## Reproduction Instructions

To reproduce on Linux Arch

1. Install discord (I'm using the discord-ptb AUR package) and firefox
2. Insert the config and layout files
3. Ensure Discord is not started already
4. Restart/Reload i3 (Mod-Shift-R is enough)

## Environment
Output of `i3 --moreversion 2>&-`:
<pre>
Binary i3 version:  4.16.1 (2019-01-27) Â© 2009 Michael Stapelberg and contributors
Running i3 version: 4.16.1 (2019-01-27) (pid 911) abortâ€¦)
Loaded i3 config: /home/silvus/.config/i3/config (Last modified: Sat Feb  2 13:25:05 2019, 446 seconds ago)

The i3 binary you just called: /usr/bin/i3
The i3 binary you are running: i3
</pre>

<pre>
# Essentially default config until here

exec_always --no-startup-id "i3-msg 'workspace 3; append_layout /home/silvus/.config/i3/layouts/workspace-3.json'"
exec_always --no-startup-id firefox
exec_always --no-startup-id /usr/bin/discord-ptb
</pre>

Layout file:
<pre>

{
    // tabbed split container with 4 children
    "border": "normal",
    "floating": "auto_off",
    "layout": "tabbed",
    "percent": null,
    "type": "con",
    "nodes": [
        {
            "border": "pixel",
            "current_border_width": 0,
            "floating": "auto_off",
            "geometry": {
               "height": 1009,
               "width": 1892,
               "x": 0,
               "y": 0
            },
            "name": "Abos - YouTube - Mozilla Firefox",
            "percent": 0.25,
            "swallows": [
               {
               "class": "^Firefox$"
               // "instance": "^Navigator$",
               // "title": "^Abos\\ \\-\\ YouTube\\ \\-\\ Mozilla\\ Firefox$",
               // "window_role": "^browser$"
               }
            ],
            "type": "con"
        },
        {
            "border": "pixel",
            "current_border_width": 0,
            "floating": "auto_off",
            "geometry": {
               "height": 1009,
               "width": 1892,
               "x": 14,
               "y": 57
            },
            "name": "Discord",
            "percent": 0.25,
            "swallows": [
               {
               "class": "^discord$"
               // "instance": "^discord$",
               // "title": "^Discord$",
               // "window_role": "^browser\\-window$"
               }
            ],
            "type": "con"
        }
    ]
}

</pre>

<pre>
- Linux Distribution & Version: Linux Arch 
- No Compositor
</pre>

**Comment by Airblader** [comment]
Hi,

thanks for the issue. If you can't reproduce with upstream i3, can you maybe create a backtrace of the crash (see debugging docs on the i3 website)? Knowing where the crash occurs would be extremely helpful.

**Comment by TheSilvus** [comment]
I have been able to reproduce the issue using upstream i3. I will create an issue there. Thank you for your help!
