### ISSUE TITLE
Difference in emoji rendering between i3-wm and i3-gaps

### ISSUE THREAD

**Issue by wooque** [Airblader/i3#282]
## I'm submitting a…
<pre>
[x] Bug
[ ] Feature Request
[ ] Documentation Request
[ ] Other (Please describe in detail)
</pre>

## Current Behavior
Emojis are rendered like this (don't have good description, so here is the screenshot)
![2019-02-19-234258_154x21_scrot](https://user-images.githubusercontent.com/1936195/53053056-a3430180-34a0-11e9-9343-7f0bb197d93c.png)

## Expected Behavior
This is how they are rendered on i3, they are like more full?
![2019-02-19-234108_157x22_scrot](https://user-images.githubusercontent.com/1936195/53053112-ca99ce80-34a0-11e9-87ec-b11342c128fb.png)

## Reproduction Instructions
On Arch Linux, install noto-fonts-emoji, add some of the emojis to status bar 🔊, 🔌, ☀️, alternate between i3-gaps and i3-wm packages and notice the difference in the rendered emojis.

## Environment
Output of `i3 --moreversion 2>&-`:
<pre>
i3 version: 
Binary i3 version:  4.16.1 (2019-01-27) © 2009 Michael Stapelberg and contributors
Running i3 version: 4.16.1 (2019-01-27) (pid 979) abort…)
Loaded i3 config: /home/vuk/.config/i3/config (Last modified: Tue 19 Feb 2019 11:40:03 PM CET, 723 seconds ago)

The i3 binary you just called: /usr/bin/i3
The i3 binary you are running: i3
</pre>

i3 config
<pre>
# This file has been auto-generated by i3-config-wizard(1).
# It will not be overwritten, so edit it as you like.
#
# Should you change your keyboard layout some time, delete
# this file and re-run i3-config-wizard(1).
#

# i3 config file (v4)
#
# Please see https://i3wm.org/docs/userguide.html for a complete reference!

set $mod Mod4

# Font for window titles. Will also be used by the bar unless a different font
# is used in the bar {} block below.
font pango:monospace 8.5

# This font is widely installed, provides lots of unicode glyphs, right-to-left
# text rendering and scalability on retina/hidpi displays (thanks to pango).
#font pango:DejaVu Sans Mono 8

# Before i3 v4.8, we used to recommend this one as the default:
# font -misc-fixed-medium-r-normal--13-120-75-75-C-70-iso10646-1
# The font above is very space-efficient, that is, it looks good, sharp and
# clear in small sizes. However, its unicode glyph coverage is limited, the old
# X core fonts rendering does not support right-to-left and this being a bitmap
# font, it doesn’t scale on retina/hidpi displays.

# Use Mouse+$mod to drag floating windows to their wanted position
floating_modifier $mod

# start a terminal
bindsym $mod+Return exec --no-startup-id i3-sensible-terminal

# kill focused window
bindsym $mod+Shift+q kill

# start dmenu (a program launcher)
bindsym $mod+d exec --no-startup-id rofi -show drun
bindsym $mod+Tab exec --no-startup-id rofi -show window
# There also is the (new) i3-dmenu-desktop which only displays applications
# shipping a .desktop file. It is a wrapper around dmenu, so you need that
# installed.
# bindsym $mod+d exec --no-startup-id i3-dmenu-desktop

# change focus
bindsym $mod+j focus left
bindsym $mod+k focus down
bindsym $mod+l focus up
bindsym $mod+semicolon focus right

# alternatively, you can use the cursor keys:
bindsym $mod+Left focus left
bindsym $mod+Down focus down
bindsym $mod+Up focus up
bindsym $mod+Right focus right

# move focused window
bindsym $mod+Shift+j move left
bindsym $mod+Shift+k move down
bindsym $mod+Shift+l move up
bindsym $mod+Shift+colon move right

# alternatively, you can use the cursor keys:
bindsym $mod+Shift+Left move left
bindsym $mod+Shift+Down move down
bindsym $mod+Shift+Up move up
bindsym $mod+Shift+Right move right

# split in horizontal orientation
bindsym $mod+h split h

# split in vertical orientation
bindsym $mod+v split v

# enter fullscreen mode for the focused container
bindsym $mod+f fullscreen toggle

# change container layout (stacked, tabbed, toggle split)
bindsym $mod+s layout stacking
bindsym $mod+w layout tabbed
bindsym $mod+e layout toggle split

# toggle tiling / floating
bindsym $mod+Shift+space floating toggle

# change focus between tiling / floating windows
bindsym $mod+space focus mode_toggle

# focus the parent container
bindsym $mod+a focus parent

# focus the child container
#bindsym $mod+d focus child

# Define names for default workspaces for which we configure key bindings later on.
# We use variables to avoid repeating the names in multiple places.
set $ws1 " 1 "
set $ws2 " 2 "
set $ws3 " 3 "
set $ws4 " 4 "
set $ws5 " 5 "
set $ws6 " 6 "
set $ws7 " 7 "
set $ws8 " 8 "
set $ws9 " 9 "
set $ws10 " 10 "

# switch to workspace
bindsym $mod+1 workspace $ws1
bindsym $mod+2 workspace $ws2
bindsym $mod+3 workspace $ws3
bindsym $mod+4 workspace $ws4
bindsym $mod+5 workspace $ws5
bindsym $mod+6 workspace $ws6
bindsym $mod+7 workspace $ws7
bindsym $mod+8 workspace $ws8
bindsym $mod+9 workspace $ws9
bindsym $mod+0 workspace $ws10

# move focused container to workspace
bindsym $mod+Shift+1 move container to workspace $ws1; workspace $ws1
bindsym $mod+Shift+2 move container to workspace $ws2; workspace $ws2
bindsym $mod+Shift+3 move container to workspace $ws3; workspace $ws3
bindsym $mod+Shift+4 move container to workspace $ws4; workspace $ws4
bindsym $mod+Shift+5 move container to workspace $ws5; workspace $ws5
bindsym $mod+Shift+6 move container to workspace $ws6; workspace $ws6
bindsym $mod+Shift+7 move container to workspace $ws7; workspace $ws7
bindsym $mod+Shift+8 move container to workspace $ws8; workspace $ws8
bindsym $mod+Shift+9 move container to workspace $ws9; workspace $ws9
bindsym $mod+Shift+0 move container to workspace $ws10; workspace $ws10

# reload the configuration file
bindsym $mod+Shift+c reload
# restart i3 inplace (preserves your layout/session, can be used to upgrade i3)
bindsym $mod+Shift+r restart
# exit i3 (logs you out of your X session)
bindsym $mod+Shift+e exec "pkill redshift; pkill xss-lock; i3-msg exit"

bindsym Control+$mod+Left resize shrink width 10 px or 10 ppt
bindsym Control+$mod+Down resize grow height 10 px or 10 ppt
bindsym Control+$mod+Up resize shrink height 10 px or 10 ppt
bindsym Control+$mod+Right resize grow width 10 px or 10 ppt

bindsym $mod+Shift+M move scratchpad
bindsym $mod+Shift+S scratchpad show

set_from_resource $background   URxvt.background
set_from_resource $darkblack    URxvt.color0
set_from_resource $black        URxvt.color8
set_from_resource $darkred      URxvt.color1
set_from_resource $red          URxvt.color9
set_from_resource $darkblue     URxvt.color4
set_from_resource $blue         URxvt.color12
set_from_resource $darkmagenta  URxvt.color5
set_from_resource $magenta      URxvt.color13
set_from_resource $darkwhite    URxvt.color7
set_from_resource $white        URxvt.color15

#                       BORDER          BACKGROUND      TEXT        INDICATOR   CHILD_BORDER
client.focused          $background     $background     $white      $black      $background
client.focused_inactive $darkblack      $darkblack      $darkwhite  $darkblack  $darkblack
client.unfocused        $darkblack      $darkblack      $darkwhite  $darkblack  $darkblack
client.urgent           $darkred        $darkred        $white      $red        $darkred

client.background       $background

# Start i3bar to display a workspace bar (plus the system information i3status
# finds out, if available)
bar {
    i3bar_command i3bar
    status_command i3status_ext
    position top

    colors {
        background          $background
        statusline          $white
        separator           $background

        focused_workspace   $darkblue       $darkblue       $white
        active_workspace    $darkmagenta    $darkmagenta    $white
        inactive_workspace  $background     $background     $darkwhite
        urgent_workspace    $darkred        $darkred        $white
    }
}

for_window [class="^.*"] border pixel 1
hide_edge_borders smart
#gaps inner 6
#smart_gaps on

exec --no-startup-id urxvtd -o
exec --no-startup-id redshift
exec --no-startup-id feh --bg-fill --randomize ~/.local/share/wallpapers
exec --no-startup-id xss-lock -- i3lock -c 000000
exec_always --no-startup-id alternating_layouts

bindsym $mod+B exec --no-startup-id chromium
bindsym $mod+I exec --no-startup-id chromium --incognito
bindsym $mod+P exec --no-startup-id i3-sensible-terminal -e pulsemixer
bindsym $mod+C exec --no-startup-id i3-sensible-terminal -e python -q
bindsym $mod+T exec --no-startup-id i3-sensible-terminal -e htop
bindsym $mod+M exec --no-startup-id i3-sensible-terminal -e ranger
bindsym $mod+N exec --no-startup-id i3-sensible-terminal -e nmtui
bindsym $mod+Y exec --no-startup-id i3-sensible-terminal -e caly
bindsym $mod+U workspace $ws10; exec --no-startup-id i3-sensible-terminal -e cmus
bindsym $mod+Z exec --no-startup-id pulseaudio-equalizer-gtk
bindsym $mod+Q exec --no-startup-id clipboardqr
bindsym $mod+O exec --no-startup-id change_output
bindsym Control+$mod+C exec --no-startup-id cmus-remote -u && i3status_refresh
bindsym Control+$mod+B exec --no-startup-id cmus-remote -n && i3status_refresh
bindsym Control+$mod+Q exec --no-startup-id pkill cmus && i3status_refresh
bindsym --release Print exec --no-startup-id scrot -s
bindsym Control+Print exec --no-startup-id scrot

bindsym Control+$mod+L exec --no-startup-id i3lock -c 000000
bindsym Control+$mod+R exec --no-startup-id systemctl reboot
bindsym Control+$mod+P exec --no-startup-id systemctl poweroff
bindsym Control+$mod+S exec --no-startup-id systemctl suspend

bindsym XF86AudioMute exec --no-startup-id pulsemixer --toggle-mute
bindsym XF86AudioLowerVolume exec --no-startup-id pulsemixer --change-volume -5
bindsym XF86AudioRaiseVolume exec --no-startup-id pulsemixer --change-volume +5
bindsym XF86MonBrightnessDown exec --no-startup-id xbacklight -dec 10 -time 0 && i3status_refresh
bindsym XF86MonBrightnessUp exec --no-startup-id xbacklight -inc 10 -time 0 && i3status_refresh
bindsym Menu exec --no-startup-id i3status_refresh
</pre>

<pre>
- Linux Distribution & Version: Arch Linux
- Are you using a compositor (e.g., xcompmgr or compton): No
</pre>

**Comment by wooque** [comment]
i3-gaps in Arch Linux does not apply same drawing patch as i3-wm, filled bug in Arch

**Comment by Airblader** [comment]
i3-gaps not applying this patch is intentional, so I hope you won't convince the maintainer to apply it. :-)

**Comment by wooque** [comment]
@Airblader I applied same patch to i3-gaps locally and I don't see any problems, connected pull request mentioned text not showing for urgent windows, workspaces, but I can't reproduce that. 
Truly transparent text has glitches anyway (tested with compton).
![2019-02-20-103846_170x29_scrot](https://user-images.githubusercontent.com/1936195/53081737-bafba380-34fb-11e9-8c4c-2e92650c1381.png)
patch can be reverted if transparent text is glitch free in the future.
