### ISSUE TITLE
[Bug report] i3-gaps freezes on login

### ISSUE THREAD

**Issue by kiedtl** [Airblader/i3#284]
## I'm submitting a…
<pre>
[x] Bug
[ ] Feature Request
[ ] Documentation Request
[ ] Other (Please describe in detail)
</pre>

## Current Behavior
On login, with `i3` selected as DE/WM, top bar appears but no further action. Computer stays frozen indefinitely and does not respond at all.

## Expected Behavior
???

## Reproduction Instructions
On the Manjaro login screen, select `i3` as the Desktop type. Then enter the password for the user and hit enter.

## Environment

Output of `i3 --moreversion 2>&-`:
<pre>
Binary i3 version:  4.16.1 (2019-01-27) © 2009 Michael Stapelberg and contributors

Running version: < 4.2-200
</pre>

Configuration: (completely stolen from [here](https://www.reddit.com/r/unixporn/comments/ax52pl/i3gaps_first_rice/))
<pre>
#* This file has been auto-generated by i3-config-wizard(1).
# It will not be overwritten, so edit it as you like.
#
# Should you change your keyboard layout some time, delete
# this file and re-run i3-config-wizard(1).
#

# i3 config file (v4)
#
# Please see https://i3wm.org/docs/userguide.html for a complete reference!

set $mod Mod4

# ==================================================
# Custom Variables
# ==================================================

set $term st

# Set colors from Xresources
# Change 'color7' and 'color2' to whatever colors you want i3 to use 
# from the generated scheme.
# NOTE: The '#f0f0f0' in the lines below is the color i3 will use if
# it fails to get colors from Xresources.
set_from_resource $fg i3wm.color7 #f0f0f0
set_from_resource $bg i3wm.color2 #f0f0f0
set_from_resource $border_inactive i3wm.color1 #f0f0f0
set_from_resource $border_active i3wm.color6 #f0f0f0

# class                 border  			backgr. text 	indicator child_border
client.focused          $border_active     	$bg     $fg  	$bg       $border_active
client.focused_inactive $border_inactive   	$bg     $fg  	$bg       $border_inactive
client.unfocused        $border_inactive	$bg     $fg  	$bg       $border_inactive
client.urgent           $border_inactive   	$bg     $fg  	$bg       $border_inactive
client.placeholder      $border_inactive 	$bg     $fg  	$bg       $border_inactive

client.background       $bg

# Font for window titles. Will also be used by the bar unless a different font
# is used in the bar {} block below.
#font pango:monospace 10

# This font is widely installed, provides lots of unicode glyphs, right-to-left
# text rendering and scalability on retina/hidpi displays (thanks to pango).
font pango:DejaVu Sans Mono 8

# Before i3 v4.8, we used to recommend this one as the default:
# font -misc-fixed-medium-r-normal--13-120-75-75-C-70-iso10646-1
# The font above is very space-efficient, that is, it looks good, sharp and
# clear in small sizes. However, its unicode glyph coverage is limited, the old
# X core fonts rendering does not support right-to-left and this being a bitmap
# font, it doesn’t scale on retina/hidpi displays.

# Use Mouse+$mod to drag floating windows to their wanted position
floating_modifier $mod

# focus the parent container

# focus the child container
#bindsym $mod+d focus child

# Define names for default workspaces for which we configure key bindings later on.
# We use variables to avoid repeating the names in multiple places.
set $ws1 "1"
set $ws2 "2"
set $ws3 "3"
set $ws4 "4"
set $ws5 "5"
set $ws6 "6"
set $ws7 "7"
set $ws8 "8"
set $ws9 "9"
set $ws10 "10"

#bindsym $mod+Shift+e exec "i3-nagbar -t warning -m 'You pressed the exit shortcut. Do you really want to exit i3? This will end your X session.' -b 'Yes, exit i3' 'i3-msg exit'"

# i3 gaps
gaps inner 5
gaps outer 0

# Remove window borders
for_window [class="^.*"] border pixel 1
for_window [class="(?i)gsimplecal"] floating enable, move position, move down $height px

# Scripts to be executed on startup
#exec compton -cCGf -b -i 0.75 --vsync opengl --opacity-rule '99:name *= "Firefox"'
exec --no-startup-id compton -b
exec wal -i /home/rwithik/wallpapers/Landscapes/
exec xrdb ~/.Xresources
exec redshift -O 5000
#exec ~/.config/polybar/launch.sh
#exec --no-startup-id $term -n dropdown &
#exec --no-startup-id volumeicon
exec --no-startup-id clipit
exec --no-startup-id nm-applet
exec --no-startup-id xfce4-power-manager

# bindsym F1 [instance="dropdown"] scratchpad show, move position center

# for_window [instance="dropdown"] floating enable, resize set 800 600, move scratchpad

# ================================================
# KEYBINDINGS
# ================================================

# Workspace controls

bindsym $mod+1 workspace $ws1
bindsym $mod+Shift+1 move container to workspace $ws1

bindsym $mod+2 workspace $ws2
bindsym $mod+Shift+2 move container to workspace $ws2

bindsym $mod+3 workspace $ws3
bindsym $mod+Shift+3 move container to workspace $ws3

bindsym $mod+4 workspace $ws4
bindsym $mod+Shift+4 move container to workspace $ws4

bindsym $mod+5 workspace $ws5
bindsym $mod+Shift+5 move container to workspace $ws5

bindsym $mod+6 workspace $ws6
bindsym $mod+Shift+6 move container to workspace $ws6

bindsym $mod+7 workspace $ws7
bindsym $mod+Shift+7 move container to workspace $ws7

bindsym $mod+8 workspace $ws8
bindsym $mod+Shift+8 move container to workspace $ws8

bindsym $mod+9 workspace $ws9
bindsym $mod+Shift+9 move container to workspace $ws9

bindsym $mod+0 workspace $ws10
bindsym $mod+Shift+0 move container to workspace $ws10

# --------------------------------------------------------

bindsym $mod+Shift+q kill
bindsym $mod+Shift+r restart
bindsym $mod+Shift+c reload

bindsym $mod+a focus parent

bindsym $mod+s layout stacking
bindsym $mod+w layout tabbed
bindsym $mod+e layout toggle split

bindsym $mod+f fullscreen toggle

bindsym $mod+d exec rofi -show run
bindsym $mod+Shift+d exec dmenu_run

bindsym $mod+h split h
bindsym $mod+v split v

bindsym $mod+Shift+h resize shrink width 5 px or 5 ppt
bindsym $mod+Shift+k resize grow height 5 px or 5 ppt
bindsym $mod+Shift+j resize shrink height 5 px or 5 ppt
bindsym $mod+Shift+l resize grow width 5 px or 5 ppt

bindsym $mod+plus gaps inner all plus 10
bindsym $mod+Shift+plus gaps outer all plus 10

bindsym $mod+minus gaps inner all minus 10
bindsym $mod+Shift+minus gaps outer all minus 10

bindsym $mod+Shift+a gaps inner all set 6, gaps outer all set 0

bindsym $mod+Shift+e exec prompt "Are you sure you want to shutdown?" "shutdown now"
bindsym $mod+l exec prompt "Lock Screen?" "/home/rwithik/Desktop/Scripts/lockscreen.sh"
#bindsym $mod+l exec prompt "Lock Screen?" "betterlockscreen -l blur"

bindsym $mod+Shift+w exec --no-startup-id /home/rwithik/Desktop/Scripts/wallpaperScript.sh

bindsym $mod+t exec ~/Desktop/Scripts/todoScript
bindsym $mod+Shift+t exec todo -d
for_window [instance=TODO] floating enable, set position center

bindsym $mod+r exec $term -n floatterm -e ranger
#bindsym $mod+F3 exec $term -e "zsh -c '~/Desktop/Scripts/rangerScript'"
bindsym $mod+F3 exec ~/Desktop/Scripts/rangerScript
bindsym $mod+Shift+F3 exec ~/Desktop/Scripts/pcmanScript
bindsym $mod+Shift+i exec $term -n floatterm -e ranger ~/wallpapers

bindsym $mod+b exec --no-startup-id firefox
bindsym $mod+Shift+b exec --no-startup-id firefox --private-window
bindsym $mod+i exec ~/Desktop/Scripts/firefoxScript

bindsym $mod+m exec $term -n music -e '/home/rwithik/Desktop/Scripts/music'
#for_window[instance="music"] floating enable, set position center, move scratchpad, [instance=music] scratchpad show
for_window[instance="music"] floating enable, move position 400 0, resize set 566 45, move scratchpad

# Brightness controls
bindsym XF86MonBrightnessDown exec xbacklight -dec 10
bindsym XF86MonBrightnessUp exec xbacklight -inc 10

# Volume controls. Don't need this on Manjaro i3.
# bindsym XF86AudioMute exec amixer set Master toggle
# bindsym XF86AudioRaiseVolume exec amixer set Master 5%+
# bindsym XF86AudioLowerVolume exec amixer set Master 5%-

# Scratchpad controls
bindsym $mod+Shift+grave move scratchpad
bindsym $mod+asciitilde scratchpad show

# Screenshot
bindsym Print exec --no-startup-id i3-scrot
bindsym $mod+Print --release exec --no-startup-id i3-scrot -w
bindsym $mod+Shift+Print exec --no-startup-id i3scrot -s

# toggle tiling / floating
bindsym $mod+Shift+space floating toggle 
# change focus between tiling / floating windows
bindsym $mod+space focus mode_toggle 

bindsym $mod+Shift+s sticky toggle

bindsym $mod+Return exec $term
bindsym $mod+Shift+Return exec $term -n floatterm

bindsym $mod+Left focus left
bindsym $mod+Down focus down
bindsym $mod+Up focus up
bindsym $mod+Right focus right

bindsym $mod+Shift+Left move left
bindsym $mod+Shift+Down move down
bindsym $mod+Shift+Up move up
bindsym $mod+Shift+Right move right

bindsym $mod+p exec $term -n pipterm
bindsym $mod+Shift+p floating enable, resize set 600 340, move position 750 30, sticky enable

bindsym $mod+z exec $term -n boxterm 
bindsym $mod+Shift+z floating enable, resize set 535 160, move position 800 30

bindsym $mod+Shift+m move position center

bindsym $mod+c exec --no-startup-id ~/Desktop/Scripts/sublime.sh

for_window [instance=floatterm] floating enable, resize set 780 520, move position center
for_window [instance=boxterm] floating enable, resize set 535 160, move position 800 30
for_window [instance=pipterm] floating enable, resize set 600 340, move position 750 30

bar {
	font pango:DejaVu Sans Mono, FontAwesome 9
	i3bar_command i3bar
	status_command i3blocks -c .config/i3blocks/i3blocks.conf
#	status_command i3blocks -c .config/i3blocks.conf
#	status_command ~/.config/polybar/launch.sh
	position top

## please set your primary output first. Example: 'xrandr --output eDP1 --primary'
#tray_output primary
#	tray_output eDP1

	bindsym button4 nop
	bindsym button5 nop
#   font xft:URWGothic-Book 11
	strip_workspace_numbers yes

    colors {
        background #283339
        statusline #F9FAF9
        separator  #454947

#                    	   border  backgr. text
        focused_workspace  #F9FAF9 #16a085 #292F34
        active_workspace   #595B5B #353836 #FDF6E3
        inactive_workspace #595B5B #283339 #EEE8D5
        binding_mode       #16a085 #2C2C2C #F9FAF9
        urgent_workspace   #16a085 #FDF6E3 #E5201D
    }
}
</pre>

<pre>
- Linux Distribution & Version: Manjaro Linux x86_64 (v18.0)
- Are you using a compositor (e.g., xcompmgr or compton): nope
</pre>

**Comment by lbibass** [comment]
Did you ever fix this? I am having the same issue.

**Comment by kiedtl** [comment]
Yeah. Unfortunately, I haven't the tiniest notion of how I fixed it.
