### ISSUE TITLE
Compile Fails on DragonflyBSD

### ISSUE THREAD

**Issue by streaml1ne555** [Airblader/i3#285]
## I'm submitting a…

<pre>
[x] Bug
[ ] Feature Request
[ ] Documentation Request
[ ] Other (Please describe in detail)
</pre>

## Current Behavior
Compiling fails with the following error:

`cc -Wunused-value -Wunused-value -I/usr/local/include  -I/usr/local/include  -I/usr/local/include  -I/usr/local/include  -I/usr/local/include/cairo -I/usr/local/include/glib-2.0 -I/usr/local/lib/glib-2.0/include -I/usr/local/include -I/usr/local/include/pixman-1 -I/usr/local/include/freetype2 -I/usr/local/include/libdrm -I/usr/local/include/libpng16 -I/usr/local/include/pango-1.0 -I/usr/local/include/fribidi -D_THREAD_SAFE -I/usr/local/include/harfbuzz  -I/usr/local/include/startup-notification-1.0  -I/usr/local/include  -I/usr/local/include   -I/usr/local/include  -I/usr/local/include  -I/usr/local/include  -I/usr/local/include  -I/usr/local/include  -pthread  -pipe -DLIBICONV_PLUG -O2 -isystem /usr/local/include -fno-strict-aliasing  -Wall   -o i3   src/i3-assignments.o src/i3-bindings.o src/i3-click.o src/i3-commands.o src/i3-commands_parser.o src/i3-con.o src/i3-config.o src/i3-config_directives.o src/i3-config_parser.o src/i3-display_version.o src/i3-ewmh.o src/i3-fake_outputs.o src/i3-floating.o src/i3-handlers.o src/i3-ipc.o src/i3-key_press.o src/i3-load_layout.o src/i3-log.o src/i3-main.o src/i3-manage.o src/i3-match.o src/i3-move.o src/i3-output.o src/i3-randr.o src/i3-regex.o src/i3-render.o src/i3-resize.o src/i3-restore_layout.o src/i3-scratchpad.o src/i3-sd-daemon.o src/i3-sighandler.o src/i3-startup.o src/i3-sync.o src/i3-tree.o src/i3-util.o src/i3-version.o src/i3-window.o src/i3-workspace.o src/i3-x.o src/i3-xcb.o src/i3-xcursor.o src/i3-xinerama.o ./libi3.a -L/usr/local/lib -lxcb -lxcb-xkb -lxcb-xinerama -lxcb-randr  -L/usr/local/lib -lxcb-util -lxcb  -L/usr/local/lib -lxcb-xrm -lxcb  -L/usr/local/lib -lyajl  -L/usr/local/lib -lpangocairo-1.0 -lpango-1.0 -lgobject-2.0 -lglib-2.0 -lintl -lcairo -lpthread  -L/usr/local/lib -lstartup-notification-1  -L/usr/local/lib -lxcb -lxcb-xkb -lxcb-xinerama -lxcb-randr  -L/usr/local/lib -lxcb-cursor -lxcb  -L/usr/local/lib -lxcb-keysyms -lxcb  -L/usr/local/lib -lxcb-icccm -lxcb  -L/usr/local/lib -lxcb-xrm -lxcb  -L/usr/local/lib -lxkbcommon-x11 -lxkbcommon  -L/usr/local/lib -lyajl  -L/usr/local/lib -lpcre  -L/usr/local/lib -lpangocairo-1.0 -lpango-1.0 -lgobject-2.0 -lglib-2.0 -lintl -lcairo -lpthread    -lev -lm -L/usr/local/lib
src/i3-log.o:log.c:function open_logbuffer: error: undefined reference to 'posix_fallocate'
collect2: error: ld returned 1 exit status
gmake[3]: *** [Makefile:1583: i3] Error 1
gmake[3]: Leaving directory '/usr/obj/dports/x11-wm/i3-gaps/.build'
gmake[2]: *** [Makefile:1328: all] Error 2
gmake[2]: Leaving directory '/usr/obj/dports/x11-wm/i3-gaps/.build'
*** Error code 1`

## Expected Behavior

i3-gaps compiles cleanly on FreeBSD via the ports tree. DragonFlyBSD uses the FreeBSD ports tree as a base for their own dports with many ports compiling without modification including base i3.

## Reproduction Instructions

Install DragonflyBSD 5.4.1

log in
pkg install subversion
cd /usr/
make dports-create-shallow
cd /usr/dports/x11-wm
mkdir i3-gaps
cd i3-gaps
svn co svn://svn.freebsd.org/ports/head/x11-wm/i3-gaps/ .
make install

**Comment by Airblader** [comment]
Are you the maintainer of this package/port (I don't know how ports work)?

**Comment by streaml1ne555** [comment]
The port doesn't currently exist on the Dragonfly side I'm trying to get it working so I can submit it to them to include in their ports tree. Typically they bring in the entire FreeBSD ports tree and remove  ones that do not work for whatever reason. The ports tree downloads/configures/installs, from source, the software you specify including all build and run dependencies. 

While looking at this further I apparently missed patches that the base i3 port had for Dragonfly. I'll try applying those patched to gaps and see if they fix the build. They look like they might. I'll close this for now and I'll reopen if I run into new errors, thanks.
