### ISSUE TITLE
Wiki doesn't explain how to install i3-gaps

### ISSUE THREAD

**Issue by jackwootton** [Airblader/i3#286]
## I'm submitting a…

<pre>
[ ] Bug
[ ] Feature Request
[x] Documentation Request
[ ] Other (Please describe in detail)
</pre>

## Current Behavior
[How do I install i3-gaps?](https://github.com/Airblader/i3#how-do-i-install-i3-gaps) states:

> Please refer to the [wiki](https://github.com/Airblader/i3/wiki).

...which doesn't explain how to install i3-gaps.

## Expected Behavior
The [wiki](https://github.com/Airblader/i3/wiki) explains how to install i3-gaps.

**Comment by Airblader** [comment]
The information was in the page describing compilation, but admittedly that doesn't make sense since I very much don't want normal users to go to that page. I've extracted a separate page now (https://github.com/Airblader/i3/wiki/Installation) and linked it from the wiki's home. Thanks!
