### ISSUE TITLE
ERROR: Your command: gaps horizontal all set 5

### ISSUE THREAD

**Issue by dog5tar** [Airblader/i3#287]
## I'm submitting a…

<pre>
[x] Bug
[ ] Feature Request
[ ] Documentation Request
[ ] Other (Please describe in detail)
</pre>

## Current Behavior

$ i3-msg gaps horizontal all set 5
ERROR: Your command: gaps horizontal all set 5
ERROR:                    ^^^^^^^^^^^^^^^^^^^^
ERROR: Expected one of these tokens: 'inner', 'outer'
[{"success":false,"parse_error":true,"error":"Expected one of these tokens: 'inner', 'outer'","input":"gaps horizontal all set 5","errorposition":"     ^^^^^^^^^^^^^^^^^^^^"}]

## Expected Behavior

To work.

## Reproduction Instructions

Run the CLI command whilst:

$ uname -ro
5.0.0-arch1-1-ARCH GNU/Linux

$ i3 --version
i3 version 4.16.1 (2019-01-27) © 2009 Michael Stapelberg and contributors

$ pacman -Si i3-gaps              
Repository      : community
Name            : i3-gaps
Version         : 4.16.1-1
Description     : A fork of i3wm tiling window manager with more features, including gaps
Architecture    : x86_64
URL             : https://github.com/Airblader/i3

## Environment

Output of `i3 --moreversion 2>&-`:
<pre>
i3 --moreversion 2>&-
Binary i3 version:  4.16.1 (2019-01-27) © 2009 Michael Stapelberg and contributors
Running i3 version: 4.16.1 (2019-01-27) (pid 6064)abort…)
Loaded i3 config: /home/$USER/.config/i3/config (Last modified: Sun 31 Mar 2019 17:11:43 BST, 1031 seconds ago)

The i3 binary you just called: /usr/bin/i3
The i3 binary you are running: i3
</pre>

<pre>
No config file, the error is being thrown while performing CLI command:
$ i3-msg gaps horizontal all set 5
</pre>

<pre>
Not using devel.
</pre>

<pre>
- Linux Distribution & Version: 5.0.0-arch1-1-ARCH
- Are you using a compositor (e.g., xcompmgr or compton): No
</pre>

**Comment by Airblader** [comment]
#273

**Comment by dog5tar** [comment]
@Airblader could you please expand on the close? I saw #273 prior to creating this issue, however my build is Jan 27th, 2019 aka newest build where #273 was 4 months ago. Wasn't the fix included in 4.16.1? Would I still have this issue if I'll build from source?

**Comment by Airblader** [comment]
This feature is not in 4.16.1. While it's true that 4.16.1 was released after this has been merged, 4.16.1 was a bugfix release on 4.16 and this feature is only merged into the major release branch, not the bugfix branch.

In other words it's only available once 4.17 is released (or you build the gaps-next branch from source).
