### ISSUE TITLE
Inner gaps leave bar at the top of the screen undrawn

### ISSUE THREAD

**Issue by s-ol** [Airblader/i3#29]
This seems to be the spot that would normally be occupied either by a titlebar or i3bar. I am running without i3bar and `gaps inner 30`. The bar in the image is [BAR](https://github.com/LemonBoy/bar); looks the same (except the weird area starts at the top of the screen) with BAR at the bottom.

![](http://i.imgur.com/LWisDIa.png)

**Comment by s-ol** [comment]
note that this is a vmware screenshot without vmware-tools so this might also be graphics driver related

**Comment by Airblader** [comment]
Do you have the titlebars disabled? You need

```
for_window [class="^.*"] border pixel 0
```

in your config. This is a known issue and won't change. Gaps and titlebars just don't play nicely together because of the way i3 handles titlebars.

**Comment by s-ol** [comment]
Oh, I see. Though the way titlebars almost work looked pretty okay...

**Comment by Aniket-Pradhan** [comment]
An old issue, but if I run `xcompmgr`, then the "background cut" also disappears. Maybe some important information.

**Comment by finex** [comment]
> An old issue, but if I run `xcompmgr`, then the "background cut" also disappears. Maybe some important information.

Same here, running `xcompmgr` fix the glitch but only if I've one monitor enabled. If I enable both monitors the glitch appears again.
