### ISSUE TITLE
Can't exit i3 on Kubuntu 18.10

### ISSUE THREAD

**Issue by abers** [Airblader/i3#290]
## I'm submitting a…

<pre>
[x] Bug
[ ] Feature Request
[ ] Documentation Request
[ ] Other (Please describe in detail)
</pre>

## Current Behavior

On clicking 'Yes, exit i3' on the exit nag message i3 stops but doesn't exit. For example, bindings and tiling no longer works.

## Expected Behavior

Exit i3 back to SDDM.

## Reproduction Instructions

Issue did not exist on i3, only appeared on moving to i3 gaps. Only change to config file was adding gaps. 

## Environment

Output of `i3 --moreversion 2>&-`:
<pre>
Binary i3 version:  4.16.1-166-g007218a8 (2019-04-03, branch "gaps-next") © 2009 Michael Stapelberg and contributors
</pre>

<pre>
[Config](https://pastebin.com/5Mj3uThC)
</pre>

<pre>
Logfile URL:
</pre>

<pre>
- Linux Distribution & Version: Kubuntu 18.10
- Are you using a compositor (e.g., xcompmgr or compton): compton
</pre>

**Comment by Airblader** [comment]
Did you install i3 and i3-gaps in different ways?

There's absolutely no difference in the shutdown code between the two, so I really doubt this is an i3-gaps issue.

**Comment by abers** [comment]
Installed i3 via repo and installed i3-gaps from source (also purged i3 before installing i3-gaps). Perhaps something has changed between repo version and version currently on github? Or is there something I may have missed when compiling? There's a couple of other reports of not being able to exit i3-gaps from [Kubuntu](https://www.reddit.com/r/i3wm/comments/anu2lv/cannot_exit_i3gaps_on_clean_install_of_kubuntu/) - though they don't always specify whether they could exit in vanilla i3.

**Comment by Airblader** [comment]
Can you build and install i3 from source the way you did i3-gaps and reproduce with that? Also, what version of i3 is Kubuntu shipping?

**Comment by abers** [comment]
The repo version is 4.15-1. It is possible to make uninstall i3-gaps and i3block-gaps? If so, I can uninstall i3-gaps and install i3 from source later in the week to see if the issue is reproduced. Edit: If not I can try install from source on a virtual machine at the weekend.

Edit: Another difference I've noticed is that pulseaudio needs to be killed and restarted after logging in on the built from source i3-gaps. With exact same config it was working fine on the repo version of i3.

**Comment by Airblader** [comment]
You can just install over as it generates the same files that will be replaced.

You also shouldn't install from a source build without going through a package for exactly the kinds of reasons. Packaging an app makes it easy to remove the files through your package manager. :-)

**Comment by Airblader** [comment]
@abers Any updates?
