### ISSUE TITLE
Custom border width for each side

### ISSUE THREAD

**Issue by gabrielpetry** [Airblader/i3#291]
## I'm submitting a…

<pre>
[ ] Bug
[x] Feature Request
[ ] Documentation Request
[ ] Other (Please describe in detail)
</pre>

## Current Behavior

Borders of the windows need to have the same width.
## Desired Behavior

The desire behaviour should be like this: https://imgur.com/jX7hWBL, border left, bot, right are 0, border top 3 pixels.
## Environment

Output of `i3 --moreversion 2>&-`:
<pre>
 ➜ i3 --moreversion 2>&-
Binary i3 version:  4.16.1-173-ge0a9e36e (2019-04-21, branch "gaps-next") © 2009 Michael Stapelberg and contributors
Running i3 version: 4.16.1-173-ge0a9e36e (2019-04-21, branch "gaps-next") (pid 1106)
Loaded i3 config: /home/petry/.config/i3/config (Last modified: Tue 23 Apr 2019 08:18:09 AM -03, 271 seconds ago)

The i3 binary you just called: /usr/bin/i3
The i3 binary you are running: i3

</pre>

<pre>
- Linux 4.19.34-1-MANJARO
- compton
</pre>

I created a fork of the project to play arround with, the file that need modifications is src/con.c in line 1633.
> result = (Rect){border_width, border_width, -(2 * border_width), -(2 * border_width)};

Add a posibility to set in the i3 config file something like
<pre>
custom_border on
border_top 3
# Default for border_top, border_right, border_left, border_bottom are 0, no need to reasign here ;) 
# in case of custom_border off, keep the same behaviour that actually exists.
</pre>

**Comment by Airblader** [comment]
I'm not opposed to the idea, but I dislike the syntax proposal. Maybe we could instead extend the border command to take four arguments in which case that's top, left, bottom, right border (similar to CSS). The same for `default_border`, I guess.

**Comment by gabrielpetry** [comment]
That could work better, much simpler.

**Comment by syslino** [comment]
That looks _really_ neat! I'd appreciate it!

**Comment by coderkalyan** [comment]
Is anyone working on this? Is it something a newcomer could work on?

**Comment by Airblader** [comment]
I'm closing this issue has i3-gaps is being migrated into i3. If this issue still applies, please reopen it in i3.
