### ISSUE TITLE
Allow (at least one) floating window to be placed behind everything else

### ISSUE THREAD

**Issue by Ingvix** [Airblader/i3#292]
## I'm submitting a…

<pre>
[ ] Bug
[x] Feature Request
[ ] Documentation Request
[ ] Other (Please describe in detail)
</pre>

## Current Behavior
You can't put floating windows behind tiled/stacked/tabbed windows.

## Desired Behavior
Allow inserting floating window behind everything. This would provide a great and easy way to create cool and maybe even useful backgrounds. First thing I had in mind was running a terminal window with some audio visualizer so it would show nicely behind my slightly transparent terminals with background blurring. You could also use some other animation scripts, videos, gifs or what ever you wish to be on your background.

I was trying to achieve this with third party solutions but none I found seemed to work with i3. So then I wondered if it could be adapted to the wm itself. Original i3's devs don't care for such visual gimmicks but maybe for gaps..?

## Environment

Output of `i3 --moreversion 2>&-`:
<pre>
i3 version: 4.16.1-161-g4f69ed9d (2019-03-29, branch "gaps-next")
</pre>

<pre>
- Linux Distribution & Version: Debian GNU/Linux buster/sid x86_64 
- Are you using a compositor (e.g., xcompmgr or compton): compton
</pre>

**Comment by Airblader** [comment]
Sorry, I don't want to deviate from the i3 behavior here because it's such a core assumption. If there was some specification, this could be implemented in i3, but the only one I know of is a KDE proprietary one (though there used to be some fork that implemented it).

I'm fairly sure this could be achieved using override_redirect windows, since those aren't managed, but of course your average terminal emulator doesn't run as override_redirect.

**Comment by Ingvix** [comment]
So I figured but never hurts to ask. Urxvt seems to be able to use override-redirect but I have no idea how to get it behind i3.

**Comment by Airblader** [comment]
There's an i3-kde fork, but it appears even they removed the handling I mentioned a while back:

https://github.com/sLite/i3/commit/0444d117f0a4ffa6271587f8ff5fe336b749dde3

You could maybe talk to @sLite about more specifics if you want. This patch essentially does what an override_redirect window would have to do here.

**Comment by Ingvix** [comment]
Actually, it seems I only need to start urxvt before i3 and then it's in the background. Not sure if this is the only way but it works. This provides me everything I need for now. Thanks anyway.
