### ISSUE TITLE
Wiki missing Ubuntu installation instructions (They were there before)

### ISSUE THREAD

**Issue by muniter** [Airblader/i3#295]
## I'm submitting a…

<pre>
[ ] Bug
[ ] Feature Request
[x] Documentation Request
[ ] Other (Please describe in detail)
</pre>

## Current Behavior
Installation instructions for Ubuntu have been removed from the wiki, they used to be there and worked flawlessly

## Expected Behavior
Wiki instructions for Ubuntu 18.04 should be shown in the wiki. As It was before

## Reproduction Instructions
Go to wiki, instructions.

**Comment by Airblader** [comment]
There never was a package for Ubuntu because still no one feels like creating one. If there is one, please do let me know and I will add it.

What I think you are referring to is building from source, that information has moved here: https://github.com/Airblader/i3/wiki/Building-from-source

**Comment by muniter** [comment]
Indeed, those were the instructions I was referring to, couldn't find them. Thank you very much for pointing me into that direction, and for this great program. Sorry for the inconvenience.
