### ISSUE TITLE
i3-msg reload resetting value of gaps bottom

### ISSUE THREAD

**Issue by diwasx** [Airblader/i3#297]
## I'm submitting a…

<pre>
[x] Bug
[ ] Feature Request
[ ] Documentation Request
[ ] Other (Please describe in detail)
</pre>

## Current Behavior

"i3-msg restart/reload" : reset the value of gaps bottom

## Expected Behavior

It doesn't reset the value of inner and outer gap. So i think, bottom value also shouldn't be.
I use i3-msg restart in some of my script. 

## Environment

Output of `i3 --moreversion 2>&-`:
<pre>
i3 version: 
Binary i3 version:  4.16.1-178-g31c0f1b8 (2019-05-14, branch "gaps-next") © 2009 Michael Stapelberg and contributors
Running i3 version: 4.16.1-178-g31c0f1b8 (2019-05-14, branch "gaps-next") (pid 2426)
Loaded i3 config: /home/lanaya/.config/i3/config (Last modified: Wed 22 May 2019 07:12:13 PM +0545, 2031 seconds ago)

The i3 binary you just called: /usr/bin/i3
The i3 binary you are running: i3

</pre>

<pre>
https://github.com/diwasx/i3wm/blob/master/.config/i3/config
</pre>

<pre>
- Linux Distribution & Version:5.0.13-arch1-1-ARCH
- Are you using a compositor (e.g., xcompmgr or compton):I am using compton
</pre>

**Comment by Airblader** [comment]
Please provide your config.

**Comment by diwasx** [comment]
https://github.com/diwasx/i3wm/blob/master/.config/i3/config

**Comment by Airblader** [comment]
Are you running any kind of script from the config that modifies gaps? Can you give exact reproduction steps?

For me it works fine.

**Comment by diwasx** [comment]
I couldn't find any scripts affecting gaps. 
bindsym mod1+Shift+grave gaps bottom all set 70
I use pywal to change background and color. It restart i3 and reset bottom gaps

**Comment by Airblader** [comment]
Ah, the important thing here is that you use `all` and not `current`. `all` actually overwrites the in-memory config, but the config is not part of the IPC dump/restore process and thus you lose the setting.

I understand that this is a little inconvenient, but it is by design. I don't think there's much to be done with reasonable effort.

**Comment by diwasx** [comment]
Ah, "current" did the trick. Thanks for your time :)
