### ISSUE TITLE
Cannot toggle gaps

### ISSUE THREAD

**Issue by NomisIV** [Airblader/i3#299]
## I'm submitting a…

<pre>
[x] Bug
[ ] Feature Request
[ ] Documentation Request
[ ] Other (Please describe in detail)
</pre>

## Current Behavior

The command `bindsym $mod+F gaps outer current toggle 60` gives the following error when pressing `$mod+F`:
```
ERROR: Expected one of these tokens: 'plus', 'minus', 'set'
ERROR: Your command: gaps outer current toggle 60
ERROR:                                  ^^^^^^^^^
```
despite being referenced in the documentation at the very bottom of the code block seen [here](https://github.com/Airblader/i3#commands). Am I missing something important or is this a bug?

## Expected Behavior

I expected the outer gaps to toggle between 60px and 0px on the current workspace.

## Reproduction Instructions

Put `bindsym $mod+F gaps outer current toggle 60` in `.config/i3/config` and press `$mod+F`.
This also works in the default configuration file.

## Environment

Output of `i3 --moreversion 2>&-`:
```
Binary i3 version:  4.16.1 (2019-01-27) © 2009 Michael Stapelberg and contributors
Running i3 version: 4.16.1 (2019-01-27) (pid 818) abort…)
Loaded i3 config: /home/simon/.config/i3/config (Last modified: Sat 08 Jun 2019 04:34:09 PM CEST, 898 seconds ago)

The i3 binary you just called: /usr/bin/i3
The i3 binary you are running: i3
```
<pre>
i3 version: 4.16.1 (2019-01-27)
</pre>

<pre>
- Linux Distribution & Version: Arch Linux 
- Are you using a compositor (e.g., xcompmgr or compton): Compton-Tryone
</pre>

**Comment by Airblader** [comment]
This feature was merged in December (https://github.com/Airblader/i3/pull/264), but 4.16 is from November (4.16.1 is a bugfix release and does not contain features), so this is not yet in a released version but only on the gaps-next branch.

**Comment by Airblader** [comment]
To be specific, you should read the README of the gaps branch rather than gaps-next to see it in its version of the latest release.

**Comment by NomisIV** [comment]
Makes sense, thank you.
Looking forward to the update! 👍
