### ISSUE TITLE
Mouse movement should set focus

### ISSUE THREAD

**Issue by Airblader** [Airblader/i3#30]
Imagine two containers with the mouse being over container 1 and that container being focused. Now switch the workspace, move the mouse so that it would, in theory, be over container 2, and switch back to the first workspace.

Container 1 is still focused and focus will only change on a click or when leaving the container and entering it again. Not updating the focus when switching the workspace is fine, but once the mouse starts moving, it'd be nice to set the focus.

**Comment by nochiel** [comment]
@airblader: Was this ever implemented? I run into this related problem constantly:

# Steps
- with `focus_follows_mouse yes`
- Set up container0 tiled, container1 floating.
- Move mouse over container1.  container1 now has focus.
- Using the keyboard, switch focus to container0 (mouse is still over container1)
- Move mouse within container1.

# Observed
Focus remains on container0.

# Expected
Moving the mouse should focus container1 even if mouse is already over container1.

**Comment by Airblader** [comment]
No, this is intentionally not implemented in i3. This ticket in i3-gaps is from a time when I wasn't yet too familiar with the i3 codebase. :-)

**Comment by nochiel** [comment]
Ah. Please could you tell me a little more about the intent behind it not being implemented (or point me in the right direction of a discussion if it was documented elsewhere)?

**Comment by nochiel** [comment]
Were you referring to this: https://github.com/i3/i3/issues/2990 ?

**Comment by Airblader** [comment]
No, that's a completely separate issue because it's more about raising the window rather than focusing it. I'm thinking more of https://github.com/i3/i3/issues/2171. I'm sure we discussed it a few times in the past, not just once.

**Comment by nochiel** [comment]
Thank you.
