### ISSUE TITLE
Provide link to Ubuntu PPA for packaged version of i3-gaps

### ISSUE THREAD

**Issue by kgilmer** [Airblader/i3#300]
## I'm submitting a…
[ ] Bug
[ ] Feature Request
[x] Documentation Request
[ ] Other (Please describe in detail)
</pre>

From https://www.reddit.com/r/i3wm/comments/by0lyc/i3gaps_consumes_way_more_i3/:
```
The list isn't overwhelming: https://launchpad.net/ubuntu/+ppas?name_filter=i3-gaps. The most recent package is provided by https://launchpad.net/~jonathonf/+archive/ubuntu/i3. I took a brief glance at the package metadata and don't see anything like custom patches (as Regolith has) so this may be generally usable.
```

**Comment by Airblader** [comment]
Thanks for the issue. What do you know, after getting some people going to package i3-gaps on Debian we now have much more exciting news: https://www.reddit.com/r/i3wm/comments/c1r58x/we_may_finally_bring_gaps_into_i3/

For the time being I added this to the wiki, though. Thanks again!

**Comment by kgilmer** [comment]
You're very welcome and I look forward to the day I can mothball the i3-gaps variant I maintain for Regolith! :smile:
