### ISSUE TITLE
Artifacts in gaps

### ISSUE THREAD

**Issue by al-caveman** [Airblader/i3#301]
## I'm submitting a…

<pre>
[x] Bug
[ ] Feature Request
[ ] Documentation Request
[ ] Other (Please describe in detail)
</pre>

## Current Behavior
When I stack/unstack, the gaps will end up containing artifacts based on what used to appear on them.  E.g. gaps will contain title bars.  But non-usable title bars.  Can't click on them.  They are just images left behind.  Some kind of artifacts.

## Expected Behavior
No artifacts in gaps.

## Reproduction Instructions
1. In an empty workspace, create a tile --- call this tile _Parent_.
2. Create a tile underneath _Parent_ --- call this tile _Child 1_.
3. Create a tile on the right side of tile _Child 1_ --- call it _Child 2_.  It should look like as in **Figure 1**.
4. Go to _Parent_, and press `mod+s` to stack them.  They will get stacked all nice and lovely.
5. While still on_Parent_, unstack them again (by pressing `mod+e`).  Boom! Artifacts visible!  See **Figure 2**.

**Figure 1 (before stacking/unstacking):**
![img](https://i.imgur.com/OoifB2s.png)

**Figure 2 (after unstacking - note blue bar and other stuff, i.e. artifacts,  appearing on top):**
![img](https://i.imgur.com/i04xAdK.png)

## Environment

Output of `i3 --moreversion 2>&-`:
<pre>
Binary i3 version:  4.16.1 (2019-01-27) © 2009 Michael Stapelberg and contributors
Running i3 version: 4.16.1 (2019-01-27) (pid 10485)bort…)
Loaded i3 config: /home/caveman/.config/i3/config (Last modified: Thu Jul 11 00:54:54 2019, 9476 seconds ago)

The i3 binary you just called: /usr/bin/i3
The i3 binary you are running: i3
</pre>

<pre>
# This file has been auto-generated by i3-config-wizard(1).
# It will not be overwritten, so edit it as you like.
#
# Should you change your keyboard layout some time, delete
# this file and re-run i3-config-wizard(1).
#

# i3 config file (v4)
#
# Please see http://i3wm.org/docs/userguide.html for a complete reference!

set $mod Mod4

# Font for window titles. Will also be used by the bar unless a different font
# is used in the bar {} block below.
font pango:monospace 8

# This font is widely installed, provides lots of unicode glyphs, right-to-left
# text rendering and scalability on retina/hidpi displays (thanks to pango).
#font pango:DejaVu Sans Mono 8

# Before i3 v4.8, we used to recommend this one as the default:
# font -misc-fixed-medium-r-normal--13-120-75-75-C-70-iso10646-1
# The font above is very space-efficient, that is, it looks good, sharp and
# clear in small sizes. However, its unicode glyph coverage is limited, the old
# X core fonts rendering does not support right-to-left and this being a bitmap
# font, it doesn’t scale on retina/hidpi displays.

#
#
# my stuff start
#
#

#
# i3 theme
#

# color class           border  backgr. text    indicator child_border
client.focused          #0088ff #0088ff #ffffff #000000   #0088ff
client.focused_inactive #000000 #000000 #888888 #000000   #000000
client.unfocused        #000000 #000000 #888888 #000000   #000000
client.urgent           #a00000 #a00000 #ffffff #000000   #900000
client.placeholder      #000000 #000000 #ffffff #000000   #0c0c0c

# start i3bar + i3status, change i3bar colour -- note: remove other bar {}s
bar {
        status_command i3status
        colors {
            focused_workspace: #0088ff #ffffff
        }
}

# manually assign initial workspace numbers to monitors
#workspace 1 output DisplayPort-1
#workspace 2 output HDMI-0
#workspace 3 output DVI-0

#
# stuff to execute on startup 
#

# disable mouse movement when shuffling monitors
mouse_warping none

# compositor (e.g. for transparency)
exec compton

# border thickness
new_window pixel 2

# language
exec setxkbmap us,ar -option 'grp:alt_shift_toggle'

# bg
exec feh --bg-fill ~/Pictures/dumbbells.jpg --bg-fill ~/Pictures/darksouls.jpg --bg-fill ~/Pictures/blacksmith_hammer.jpg

# screen saver
exec xautolock -time 5 -locker 'i3lock -c 000000'

#
# bindsyms -- make sure to remove dublicates if any
#

# volume control
#bindsym XF86AudioRaiseVolume exec --no-startup-id pactl set-sink-volume 0 -- +10% && killall -SIGUSR1 i3status
#bindsym XF86AudioLowerVolume exec --no-startup-id pactl set-sink-volume 0 -- -10% && killall -SIGUSR1 i3status

# shuffle screen's workspaces 
bindsym $mod+n workspace next_on_output
bindsym $mod+p workspace prev_on_output

# shuffle screens
bindsym $mod+BackSpace focus output left
bindsym $mod+Shift+BackSpace focus output right

# scratchpad
bindsym $mod+Up move scratchpad
bindsym $mod+Down scratchpad show

# lock
bindsym $mod+Delete exec i3lock -c 000000

# map and color dmenu_run -- note: remove other duplicate dmenu_run bindsyms
bindsym $mod+d exec dmenu_run -nb black -nf white -sb '#0088ff' -sf white

#
#
# my stuff end
#
#

# Use Mouse+$mod to drag floating windows to their wanted position
floating_modifier $mod

# start a terminal
bindsym $mod+Return exec konsole

# kill focused window
bindsym $mod+Shift+q kill

# There also is the (new) i3-dmenu-desktop which only displays applications
# shipping a .desktop file. It is a wrapper around dmenu, so you need that
# installed.
# bindsym $mod+d exec --no-startup-id i3-dmenu-desktop

# change focus
bindsym $mod+h focus left
bindsym $mod+j focus down
bindsym $mod+k focus up
bindsym $mod+l focus right

# alternatively, you can use the cursor keys:
#bindsym $mod+Left focus left
#bindsym $mod+Down focus down
#bindsym $mod+Up focus up
#bindsym $mod+Right focus right

# move focused window
bindsym $mod+Shift+h move left
bindsym $mod+Shift+j move down
bindsym $mod+Shift+k move up
bindsym $mod+Shift+l move right

# alternatively, you can use the cursor keys:
bindsym $mod+Shift+Left move left
bindsym $mod+Shift+Down move down
bindsym $mod+Shift+Up move up
bindsym $mod+Shift+Right move right

# split in horizontal orientation
bindsym $mod+o split h

# split in vertical orientation
bindsym $mod+u split v

# enter fullscreen mode for the focused container
bindsym $mod+f fullscreen toggle

# change container layout (stacked, tabbed, toggle split)
bindsym $mod+s layout stacking
bindsym $mod+w layout tabbed
bindsym $mod+e layout toggle split

# toggle tiling / floating
bindsym $mod+Shift+space floating toggle

# change focus between tiling / floating windows
bindsym $mod+space focus mode_toggle

# focus the parent container
bindsym $mod+a focus parent

# focus the child container
#bindsym $mod+d focus child

# switch to workspace
bindsym $mod+1 workspace 1
bindsym $mod+2 workspace 2
bindsym $mod+3 workspace 3
bindsym $mod+4 workspace 4
bindsym $mod+5 workspace 5
bindsym $mod+6 workspace 6
bindsym $mod+7 workspace 7
bindsym $mod+8 workspace 8
bindsym $mod+9 workspace 9
bindsym $mod+0 workspace 10

# move focused container to workspace
bindsym $mod+Shift+1 move container to workspace 1
bindsym $mod+Shift+2 move container to workspace 2
bindsym $mod+Shift+3 move container to workspace 3
bindsym $mod+Shift+4 move container to workspace 4
bindsym $mod+Shift+5 move container to workspace 5
bindsym $mod+Shift+6 move container to workspace 6
bindsym $mod+Shift+7 move container to workspace 7
bindsym $mod+Shift+8 move container to workspace 8
bindsym $mod+Shift+9 move container to workspace 9
bindsym $mod+Shift+0 move container to workspace 10

# reload the configuration file
bindsym $mod+Shift+c reload
# restart i3 inplace (preserves your layout/session, can be used to upgrade i3)
bindsym $mod+Shift+r restart
# exit i3 (logs you out of your X session)
bindsym $mod+Shift+e exec "i3-nagbar -t warning -m 'You pressed the exit shortcut. Do you really want to exit i3? This will end your X session.' -b 'Yes, exit i3' 'i3-msg exit'"

# resize window (you can also use the mouse for that)
mode "resize" {
        # These bindings trigger as soon as you enter the resize mode

        # Pressing left will shrink the window’s width.
        # Pressing right will grow the window’s width.
        # Pressing up will shrink the window’s height.
        # Pressing down will grow the window’s height.
        bindsym h resize shrink width 10 px or 10 ppt
        bindsym l resize grow width 10 px or 10 ppt
        bindsym k resize grow height 10 px or 10 ppt
        bindsym j resize shrink height 10 px or 10 ppt

        # same bindings, but for the arrow keys
        bindsym Left resize shrink width 10 px or 10 ppt
        bindsym Down resize grow height 10 px or 10 ppt
        bindsym Up resize shrink height 10 px or 10 ppt
        bindsym Right resize grow width 10 px or 10 ppt

        # back to normal: Enter or Escape
        bindsym Return mode "default"
        bindsym Escape mode "default"
}

bindsym $mod+r mode "resize"

</pre>

<pre>
- Linux Distribution & Version: Linux cavebox 5.1.16-arch1-1-ARCH #1 SMP PREEMPT Wed Jul 3 20:23:07 UTC 2019 x86_64 GNU/Linux
- Are you using a compositor (e.g., xcompmgr or compton): yes, compton.  but I also tried with `pkill compton` and still the same outcome.
</pre>

**Comment by al-caveman** [comment]
Hmmm, if I enable title bars for all windows, even those that are not stacked/tabbed (i.e. those just plainly titled in the open), then the artifact does not appear.  But it's not space efficient this way, specially for my small-monitored laptop.

**Comment by Airblader** [comment]
Hi,

yes, gaps and titlebars (which are forced for stacking containers) are known to not play well. You can try using a compositor if you aren't already or playing with its settings, that does help quite often.

There isn't really anything we can do in i3-gaps because of how gaps are implemented, and changing that would likely make it very hard to stay up to date with upstream. I think all effort is better invested in https://github.com/i3/i3/issues/3724.
