### ISSUE TITLE
Query current gaps from the IPC 

### ISSUE THREAD

**Issue by patrick-motard** [Airblader/i3#302]
## I'm submitting a…

<pre>
[ ] Bug
[x] Feature Request
[ ] Documentation Request
[ ] Other (Please describe in detail)
</pre>

## Current Behavior

To the best of my knowledge, there is no way to use i3-msg to get the current gaps. You can only modify them.
``` 
i3-msg gaps top current
ERROR: Your command: gaps top current
ERROR:                               
ERROR: Expected one of these tokens: 'plus', 'minus', 'set'
[{"success":false,"parse_error":true,"error":"Expected one of these tokens: 'plus', 'minus', 'set'","input":"gaps top current","errorposition":"                "}]
```
## Desired Behavior

I need to be able to fetch the current gaps and hold them in memory in the application I am writing. My application switches between multiple desktop environment themes. I3 gaps is one of the settings themes can specify, if they do not specify a gap size, I want to fall back on the current gap size (as defined in the i3 config file). For now I can parse the i3 config file for keywords, but it's not ideal.

## Environment

Output of `i3 --moreversion 2>&-`:
<pre>
i3 version: 
Binary i3 version:  4.16-56-g56ea3afe (2018-12-03, branch "gaps-next") © 2009 Michael Stapelberg and contributors
Running i3 version: 4.16-56-g56ea3afe (2018-12-03, branch "gaps-next") (pid 1310)
Loaded i3 config: /home/han/.config/i3/config (Last modified: Sat 13 Jul 2019 05:39:11 PM CDT, 20212 seconds ago)

The i3 binary you just called: /usr/bin/i3
The i3 binary you are running: i3

</pre>

<pre>
- Linux Distribution & Version:
- Are you using a compositor (e.g., xcompmgr or compton): compton.
</pre>

**Comment by Airblader** [comment]
You can get *some* information in the GET_TREE response, unfortunately this excludes outer gaps at the moment. You're absolutely right that this should be possible, but I will not be implementing this in i3-gaps as further efforts should go towards https://github.com/i3/i3/issues/3724 instead where this is already listed.

I'll leave this issue open purely for visibility.

**Comment by patrick-motard** [comment]
Wow, had no idea merging to i3 was being discussed. That's amazing to hear! Bummer on not being able to get the current gaps, but it's okay. I'm glad it's being considered in the merge.

**Comment by Airblader** [comment]
I'm closing this issue has i3-gaps is being migrated into i3. If this issue still applies, please reopen it in i3.
