### ISSUE TITLE
"resize grow" shrinks (not grows) window

### ISSUE THREAD

**Issue by jaimet** [Airblader/i3#304]
## I'm submitting a…

<pre>
[x] Bug
[ ] Feature Request
[ ] Documentation Request
[ ] Other (Please describe in detail)
</pre>

## Current Behavior

With gaps, `resize grow height 5 px` shrinks the window height.

## Expected Behavior

With gaps, "resize grow height 5 px" should grow the window height (by 5 pixels).

## Reproduction Instructions

Start with a fresh new (default) .config (with *no* gaps specifier), create 2 vertically-tiled terminal windows. Enter `i3-msg resize grow height 5 px` and watch the selected window height grow by 5 pixels. All is good.

Now edit the (default) config file and just add the single line: "gaps inner 10". Either restart i3 or reload your new config. Again, create 2 vertically-tiled terminal windows. Again, enter `i3-msg resize grow height 5 px` and watch the selected window height shrink. All is not good.

## Environment

Output of `i3 --moreversion 2>&-`:
<pre>
Binary i3 version:  4.16.1-1-g341fcf99 (2019-01-27, branch "gaps") © 2009 Michael Stapelberg and contributors
Running i3 version: 4.16.1-1-g341fcf99 (2019-01-27, branch "gaps") (pid 16792)
Loaded i3 config: /home/nonroot/.config/i3/config (Last modified: Tue 23 Jul 2019 17:08:38 BST, 6123 seconds ago)

The i3 binary you just called: /usr/bin/i3
The i3 binary you are running: x-window/i3
</pre>

Understandably, you ask for the complete i3 config so here it is. This is just the default config (produced on first run) with a single added line ("gaps inner 10"):

<pre>
gaps inner 10

# This file has been auto-generated by i3-config-wizard(1).
# It will not be overwritten, so edit it as you like.
#
# Should you change your keyboard layout some time, delete
# this file and re-run i3-config-wizard(1).
#

# i3 config file (v4)
#
# Please see https://i3wm.org/docs/userguide.html for a complete reference!

set $mod Mod4

# Font for window titles. Will also be used by the bar unless a different font
# is used in the bar {} block below.
font pango:monospace 8

# This font is widely installed, provides lots of unicode glyphs, right-to-left
# text rendering and scalability on retina/hidpi displays (thanks to pango).
#font pango:DejaVu Sans Mono 8

# Before i3 v4.8, we used to recommend this one as the default:
# font -misc-fixed-medium-r-normal--13-120-75-75-C-70-iso10646-1
# The font above is very space-efficient, that is, it looks good, sharp and
# clear in small sizes. However, its unicode glyph coverage is limited, the old
# X core fonts rendering does not support right-to-left and this being a bitmap
# font, it doesn’t scale on retina/hidpi displays.

# Use Mouse+$mod to drag floating windows to their wanted position
floating_modifier $mod

# start a terminal
bindsym $mod+Return exec i3-sensible-terminal

# kill focused window
bindsym $mod+Shift+q kill

# start dmenu (a program launcher)
bindsym $mod+d exec dmenu_run
# There also is the (new) i3-dmenu-desktop which only displays applications
# shipping a .desktop file. It is a wrapper around dmenu, so you need that
# installed.
# bindsym $mod+d exec --no-startup-id i3-dmenu-desktop

# change focus
bindsym $mod+j focus left
bindsym $mod+k focus down
bindsym $mod+l focus up
bindsym $mod+semicolon focus right

# alternatively, you can use the cursor keys:
bindsym $mod+Left focus left
bindsym $mod+Down focus down
bindsym $mod+Up focus up
bindsym $mod+Right focus right

# move focused window
bindsym $mod+Shift+j move left
bindsym $mod+Shift+k move down
bindsym $mod+Shift+l move up
bindsym $mod+Shift+semicolon move right

# alternatively, you can use the cursor keys:
bindsym $mod+Shift+Left move left
bindsym $mod+Shift+Down move down
bindsym $mod+Shift+Up move up
bindsym $mod+Shift+Right move right

# split in horizontal orientation
bindsym $mod+h split h

# split in vertical orientation
bindsym $mod+v split v

# enter fullscreen mode for the focused container
bindsym $mod+f fullscreen toggle

# change container layout (stacked, tabbed, toggle split)
bindsym $mod+s layout stacking
bindsym $mod+w layout tabbed
bindsym $mod+e layout toggle split

# toggle tiling / floating
bindsym $mod+Shift+space floating toggle

# change focus between tiling / floating windows
bindsym $mod+space focus mode_toggle

# focus the parent container
bindsym $mod+a focus parent

# focus the child container
#bindsym $mod+d focus child

# Define names for default workspaces for which we configure key bindings later on.
# We use variables to avoid repeating the names in multiple places.
set $ws1 "1"
set $ws2 "2"
set $ws3 "3"
set $ws4 "4"
set $ws5 "5"
set $ws6 "6"
set $ws7 "7"
set $ws8 "8"
set $ws9 "9"
set $ws10 "10"

# switch to workspace
bindsym $mod+1 workspace $ws1
bindsym $mod+2 workspace $ws2
bindsym $mod+3 workspace $ws3
bindsym $mod+4 workspace $ws4
bindsym $mod+5 workspace $ws5
bindsym $mod+6 workspace $ws6
bindsym $mod+7 workspace $ws7
bindsym $mod+8 workspace $ws8
bindsym $mod+9 workspace $ws9
bindsym $mod+0 workspace $ws10

# move focused container to workspace
bindsym $mod+Shift+1 move container to workspace $ws1
bindsym $mod+Shift+2 move container to workspace $ws2
bindsym $mod+Shift+3 move container to workspace $ws3
bindsym $mod+Shift+4 move container to workspace $ws4
bindsym $mod+Shift+5 move container to workspace $ws5
bindsym $mod+Shift+6 move container to workspace $ws6
bindsym $mod+Shift+7 move container to workspace $ws7
bindsym $mod+Shift+8 move container to workspace $ws8
bindsym $mod+Shift+9 move container to workspace $ws9
bindsym $mod+Shift+0 move container to workspace $ws10

# reload the configuration file
bindsym $mod+Shift+c reload
# restart i3 inplace (preserves your layout/session, can be used to upgrade i3)
bindsym $mod+Shift+r restart
# exit i3 (logs you out of your X session)
bindsym $mod+Shift+e exec "i3-nagbar -t warning -m 'You pressed the exit shortcut. Do you really want to exit i3? This will end your X session.' -B 'Yes, exit i3' 'i3-msg exit'"

# resize window (you can also use the mouse for that)
mode "resize" {
        # These bindings trigger as soon as you enter the resize mode

        # Pressing left will shrink the window’s width.
        # Pressing right will grow the window’s width.
        # Pressing up will shrink the window’s height.
        # Pressing down will grow the window’s height.
        bindsym j resize shrink width 10 px or 10 ppt
        bindsym k resize grow height 10 px or 10 ppt
        bindsym l resize shrink height 10 px or 10 ppt
        bindsym semicolon resize grow width 10 px or 10 ppt

        # same bindings, but for the arrow keys
        bindsym Left resize shrink width 10 px or 10 ppt
        bindsym Down resize grow height 10 px or 10 ppt
        bindsym Up resize shrink height 10 px or 10 ppt
        bindsym Right resize grow width 10 px or 10 ppt

        # back to normal: Enter or Escape or $mod+r
        bindsym Return mode "default"
        bindsym Escape mode "default"
        bindsym $mod+r mode "default"
}

bindsym $mod+r mode "resize"

# Start i3bar to display a workspace bar (plus the system information i3status
# finds out, if available)
bar {
        status_command i3status
}
</pre>

<pre>
No logfile
</pre>

<pre>
- Linux Distribution & Version:
Debian Buster
- Are you using a compositor (e.g., xcompmgr or compton):
No compositor
</pre>

If I increase the numeric parameter in the  `resize grow height <n> px` call, the window shrinks by less and less until, if I increase it to 15 (i.e. `resize grow height 15 px`) then the window doesn't shrink at all - it stays the same size. So this is probably just a calculation issue - the parameter is out by a value of 15 (remember: I'm using "gaps inner 10").

Also, if this isn't easy to fix, I suggest just closing this issue *without* fixing it - I'd rather the time was spent on [pushing gaps upstream](https://github.com/i3/i3/issues/3724).

Thank you!

**Comment by jaimet** [comment]
I've just found something else that's a bit weird (this *MUST* be related to the original problem!):

with gaps 0 (no border):
```
i3-msg resize set width 562
xwininfo -id $WINDOWID | grep -i width
  Width: 562
```

with gaps 10 (no border):
```
i3-msg resize set width 562
xwininfo -id $WINDOWID | grep -i width
  Width: 547
```

It's that magic number 15 again!

**Comment by Airblader** [comment]
Hi, thanks for posting this. I agree that this behavior is incorrect, but I think there is little we can do here in i3-gaps that keeps the patch small-ish, so I would prefer to address this through https://github.com/i3/i3/issues/3724 instead. I'll leave this issue open, though (and if someone can prove me wrong with a PR, go for it :-) )

**Comment by Airblader** [comment]
I'm closing this issue has i3-gaps is being migrated into i3. If this issue still applies, please reopen it in i3.
