### ISSUE TITLE
Borders present even when window not focused

### ISSUE THREAD

**Issue by StarrKiss** [Airblader/i3#306]
![Screenshot from 2019-07-27 11-35-14](https://user-images.githubusercontent.com/13007697/61997692-c9c62380-b062-11e9-9187-0d4fbd3c32c9.png)

As you can see in this screenshot, both Firefox and Terminator have borders around them even though firefox is the only one that is focused. This can sometimes be solved by moving the mouse quickly between windows, but normally needs a closing of both apps and re-opening. I have no idea for the reason of this as it occurs randomly. It may be worth noting this is running on Ubuntu 19.04 inside virtualbox.

**Comment by Airblader** [comment]
I'm closing this again and will continue doing so until you manage to follow the issue template, providing all required information.
