### ISSUE TITLE
Borders present even when window not focused

### ISSUE THREAD

**Issue by StarrKiss** [Airblader/i3#307]
## I'm submitting a…

<pre>
[x] Bug
[ ] Feature Request
[ ] Documentation Request
[ ] Other (Please describe in detail)
</pre>

## Current Behavior

Currently, when I switch applications, sometimes the borders indicating which app is focused remain on the unfocused app. This requires a restart of both apps to fix or sometimes can be fixed by moving mouse to a third window.

Screenshot:

![Screenshot from 2019-07-27 11-35-14](https://user-images.githubusercontent.com/13007697/61997746-a2238b00-b063-11e9-9163-5e323924dc84.png)
As you can see here, despite Terminator being unfocused and firefox focused, it still has a border around the exterior.

## Expected Behavior

I expect the border on windows to appear and disappear on the windows being refocused.
## Reproduction Instructions
As this error occurs at seemingly random conditions, it is impossible for me to include detailed reproduction errors. These errors occur most freqequntly with Terminator and Firefox, but I use those two programs the most so it is possible it is just bias that they seem to occur more frequently with them.

## Environment

I am running Ubuntu 19.04 in virtualBox.

Output of `i3 --moreversion 2>&-`:
<pre>
i3 version:  
Binary i3 version:  4.16.1-195-g90385edc (2019-07-21, branch "gaps-next") © 2009 Michael Stapelberg and contributors
Running i3 version: 4.16.1-195-g90385edc (2019-07-21, branch "gaps-next") (pid 1400)
Loaded i3 config: /home/gregorystarr/.config/i3/config (Last modified: Fri 26 Jul 2019 10:02:59 AM MDT, 92543 seconds ago)

</pre>

i3 config is here:
https://github.com/StarrKiss/dotfile/tree/master/i3

In my dotfiles Repo.
<pre>
- Linux Distribution & Version: Ubuntu 19.04, Pop_OS! in VirtualBox
- Are you using a compositor (e.g., xcompmgr or compton): Compton
</pre>

**Comment by StarrKiss** [comment]
This error is now verified on Manjaro i3 on a ThinkPad T480, as the error continues there.

**Comment by Airblader** [comment]
I'll post the same as in #311:

> Can you try to reproduce this on vanilla i3 and if that is successful, open the issue upstream? i3-gaps makes no changes in this area, so I assume this issue is not related to i3-gaps.

Also closing this for #311 since it's really the same issue.
