### ISSUE TITLE
[Feature Request] Avoiding Windows

### ISSUE THREAD

**Issue by MatthewCroughan** [Airblader/i3#308]
The idea for this comes from my desire to have a video playing on my Thinkpad's 1366x768 monitor, meanwhile getting some work done. This takes up far too much of the screen, even when small. Currently I use `mpv` and just drag the window away when it's in the way. 

However.. It would be absolutely amazing if I could set a window class to have a pixel radius around its container, that when crossed by the mouse would move the window to the opposite corner of the screen it's on. I've wanted this for quite some time, I just don't know how to implement it, and haven't had any help from the IRC since it's too niche. Thanks!

**Comment by Airblader** [comment]
This is something you can do outside of i3 by writing a script, either using the IPC or even in a way that is agnostic to i3.

I would recommend you ask on the /r/i3wm subreddit as that has much more traffic than IRC.
