### ISSUE TITLE
[feature request] Double borders

### ISSUE THREAD

**Issue by GeriatricJacob** [Airblader/i3#309]
Double borders like in 2bwm are really cool, it would be great if we could have them in i3. There is a patch for an old version of i3 [here](https://github.com/max-lv/i3), could this happen upstream?

**Comment by Airblader** [comment]
No, this isn't gonna happen in i3 and neither in i3-gaps, sorry.

**Comment by tosti007** [comment]
@Airblader considering this issue is now ±1,5 years old, did things change so it might be considered? Also if not; what's the rationale (for anyone looking at this issue in 1,5 years and wondering the same as me now)?

**Comment by Airblader** [comment]
No things haven't changed, and the rationale is that I'm not looking to make such further changes to i3-gaps die to maintenance considerations, sorry.

**Comment by tosti007** [comment]
That's fine! Having to maintain additional features can result in a fair amount of work. Thank you for the reply
