### ISSUE TITLE
How to hide title bar on certain application? (title bar no border pixel)

### ISSUE THREAD

**Issue by ahloiscreamo** [Airblader/i3#310]
Hi,

Yesterday while browsing i3wm wiki i found out that i can set 0 pixel on border and keep the titlebar, so i decide to try it on i3-gaps .
To my surprised, everything work like flawless, i can even set to toggle the titlebar on/off on runtime with shortcut. So i went on to disable titlebar on certain app that i wanted to (Firefox)
This is the problem began, no matter what value i put on the config, it wont hide my titlebar (i mean i can hide through shortcut, but i have no idea how to to make it automatically hide)
on the wiki, the related guide is 
```
border normal|pixel|toggle [<n>]
border none
# legacy syntax, equivalent to "border pixel 1"
border 1pixel

```
This one did not work for me,
i try to set `for_window [class="Firefox"] border none`
it doesn't work either
for now what is set in my config is 
```
# disable border
for_window [class="^.*"] border normal 0
for_window [class="Firefox"] border pixel 0
```
So to be clear my issues is i don't have any idea how to set the titlebar hide on certain apps, 
my [config](https://github.com/ahloiscreamo/BobbyBoy/blob/master/i3/config)
```
⋊> ~ i3 --version                                                                                                                                  17:01:17
i3 version 4.16.1 (2019-01-27) © 2009 Michael Stapelberg and contributors
```
and picture for reference 
![Screenshot from 2019-08-02 16-32-50](https://user-images.githubusercontent.com/9318372/62359047-9bf04b80-b548-11e9-9596-3849f98f8897.png)

**Comment by Airblader** [comment]
For support questions, please use the subreddit https://reddit.com/r/i3wm. Please also make sure you read this first: https://github.com/Airblader/i3/wiki/Frequently-Asked-Questions#when-using-gaps-i-get-visual-glitches

**Comment by ahloiscreamo** [comment]
Thanks, i didn't aware of the issues.
I will visit the sub-reddit.
