### ISSUE TITLE
i3 crashes after upgrade to 4.17

### ISSUE THREAD

**Issue by dio4ev** [Airblader/i3#312]
## I'm submitting a…

<pre>
[x] Bug
[ ] Feature Request
[ ] Documentation Request
[ ] Other (Please describe in detail)
</pre>

## Current Behavior

I just put my Laptop into the docking station and set some settings with xrandr.
After that if I restart i3, with $mod+Shift+r, it crashes.
If I don't set the xrandr settings it works.
A Window appears, with:
"i3 has just crashed. Please report a bug for this.
To debug this problem,..."

## Expected Behavior

No crash, just a normal inplace restart of i3.

## Reproduction Instructions

I just started my Laptop, executed some xrandr commands (to have the correct layout for my monitors), restart i3 and it crashes.

## Environment

Output of `i3 --moreversion 2>&-`:
<pre>
I encountered this bug in 4.17 and now I downgraded to 4.16.1 and it works.
i3 version: 
Binary i3 version:  4.17 (2019-08-04) © 2009 Michael Stapelberg and contributors
Running i3 version: 4.17 (2019-08-04) (pid 1162)abort…)
Loaded i3 config: ~/.config/i3/config (Last modified: Tue 11 Jun 2019 07:25:29 AM CEST, 5450683 seconds ago)

The i3 binary you just called: /usr/bin/i3
The i3 binary you are running: i3

</pre>

<pre>
</pre>

<pre>
Logfile URL:
</pre>

<pre>
- Linux Distribution & Version:
Arch Linux 
Linux 5.2.8-arch1-1-ARCH #1 SMP PREEMPT Fri Aug 9 21:36:07 UTC 2019 x86_64 GNU/Linux

- Are you using a compositor (e.g., xcompmgr or compton):
compton
</pre>

**Comment by orestisfl** [comment]
https://github.com/i3/i3/issues/3764

**Comment by Airblader** [comment]
Yes, closing since this is upstream. Thanks @orestisfl
