### ISSUE TITLE
Transparent borders don't work on all windows

### ISSUE THREAD

**Issue by hacooke** [Airblader/i3#313]
## I'm submitting a…

<pre>
[x] Bug
[ ] Feature Request
[ ] Documentation Request
[ ] Other (Please describe in detail)
</pre>

## Current Behavior

Borders around applications including Firefox, Nautilus, Spotify, Chrome (pretty much everything except URxvt) appear as black when set to transparent.

## Expected Behavior

Borders should be transparent on all applications.

I am using compton, and transparency is working for my polybar, the background of my URxvt terminals and their borders.

## Environment

Output of `i3 --moreversion 2>&-`:
<pre>
i3 version: 
Binary i3 version:  4.16.1-189-gb573a610 (2019-06-22, branch "gaps-next") © 2009 Michael Stapelberg and contributors
Running i3 version: 4.16.1-189-gb573a610 (2019-06-22, branch "gaps-next") (pid 1981)
Loaded i3 config: /home/harry/.config/i3/config (Last modified: Thu 15 Aug 2019 10:57:44 BST, 215 seconds ago)

The i3 binary you just called: /usr/bin/i3
The i3 binary you are running: i3
</pre>

<pre>
# This file has been auto-generated by i3-config-wizard(1).
# It will not be overwritten, so edit it as you like.
#
# Should you change your keyboard layout some time, delete
# this file and re-run i3-config-wizard(1).
#

# i3 config file (v4)
#
# Please see https://i3wm.org/docs/userguide.html for a complete reference!

set $mod Mod4

# Font for window titles. Will also be used by the bar unless a different font
# is used in the bar {} block below.
font pango:System San Francisco Display 10

# This font is widely installed, provides lots of unicode glyphs, right-to-left
# text rendering and scalability on retina/hidpi displays (thanks to pango).
#font pango:DejaVu Sans Mono 8

# Before i3 v4.8, we used to recommend this one as the default:
# font -misc-fixed-medium-r-normal--13-120-75-75-C-70-iso10646-1
# The font above is very space-efficient, that is, it looks good, sharp and
# clear in small sizes. However, its unicode glyph coverage is limited, the old
# X core fonts rendering does not support right-to-left and this being a bitmap
# font, it doesn’t scale on retina/hidpi displays.

# Use Mouse+$mod to drag floating windows to their wanted position
floating_modifier $mod

# start a terminal
bindsym $mod+Return exec urxvt #i3-sensible-terminal
#start a browser
bindsym $mod+numbersign exec firefox

# kill focused window
bindsym $mod+Shift+q kill

# change focus
bindsym $mod+h focus left
bindsym $mod+j focus down
bindsym $mod+k focus up
bindsym $mod+l focus right

# alternatively, you can use the cursor keys:
bindsym $mod+Left focus left
bindsym $mod+Down focus down
bindsym $mod+Up focus up
bindsym $mod+Right focus right

# move focused window
bindsym $mod+Shift+h move left
bindsym $mod+Shift+j move down
bindsym $mod+Shift+k move up
bindsym $mod+Shift+l move right

# alternatively, you ca# This file has been auto-generated by i3-config-wizard(1).
# It will not be overwritten, so edit it as you like.
#
# Should you change your keyboard layout some time, delete
# this file and re-run i3-config-wizard(1).
#

# i3 config file (v4)
#
# Please see https://i3wm.org/docs/userguide.html for a complete reference!

set $mod Mod4

# Font for window titles. Will also be used by the bar unless a different font
# is used in the bar {} block below.
font pango:System San Francisco Display 10

# This font is widely installed, provides lots of unicode glyphs, right-to-left
# text rendering and scalability on retina/hidpi displays (thanks to pango).
#font pango:DejaVu Sans Mono 8

# Before i3 v4.8, we used to recommend this one as the default:
# font -misc-fixed-medium-r-normal--13-120-75-75-C-70-iso10646-1
# The font above is very space-efficient, that is, it looks good, sharp and
# clear in small sizes. However, its unicode glyph coverage is limited, the old
# X core fonts rendering does not support right-to-left and this being a bitmap
# font, it doesn’t scale on retina/hidpi displays.

# Use Mouse+$mod to drag floating windows to their wanted position
floating_modifier $mod

# start a terminal
bindsym $mod+Return exec urxvt #i3-sensible-terminal
#start a browser
bindsym $mod+numbersign exec firefox

# kill focused window
bindsym $mod+Shift+q kill

# change focus
bindsym $mod+h focus left
bindsym $mod+j focus down
bindsym $mod+k focus up
bindsym $mod+l focus right

# alternatively, you can use the cursor keys:
bindsym $mod+Left focus left
bindsym $mod+Down focus down
bindsym $mod+Up focus up
bindsym $mod+Right focus right

# move focused window
bindsym $mod+Shift+h move left
bindsym $mod+Shift+j move down
bindsym $mod+Shift+k move up
bindsym $mod+Shift+l move right

# alternatively, you can use the cursor keys:
bindsym $mod+Shift+Left move left
bindsym $mod+Shift+Down move down
bindsym $mod+Shift+Up move up
bindsym $mod+Shift+Right move right

# split in horizontal orientation
bindsym $mod+o split h

# split in vertical orientation
bindsym $mod+v split v

# enter fullscreen mode for the focused container
bindsym $mod+f fullscreen toggle

# change container layout (stacked, tabbed, toggle split)
#bindsym $mod+s layout stacking
bindsym $mod+w layout tabbed
bindsym $mod+e layout toggle split

# toggle tiling / floating
bindsym $mod+Shift+space floating toggle

# change focus between tiling / floating windows
bindsym $mod+space focus mode_toggle

# focus the parent container
bindsym $mod+a focus parent

# focus the child container
#bindsym $mod+d focus child

# Define names for default workspaces for which we configure key bindings later on.
# We use variables to avoid repeating the names in multiple places.
#set $ws1 "1:" 
#set $ws2 "2:" 
#set $ws3 "3:" 
#set $ws4 "4:" 
##set $ws5 "5:<span font='SVGFont1 12' rise='-2000'>a</span>"
#set $ws5 "5:%{T2}a%{T-}"
#set $ws6 "6:"
#set $ws7 "7:"
#set $ws8 "8:"
#set $ws9 "9:"
#set $ws10 "10:"
#set $ws11 "11:"
set $ws1 "1" 
set $ws2 "2" 
set $ws3 "3" 
set $ws4 "4" 
set $ws5 "5"
set $ws6 "6"
set $ws7 "7"
set $ws8 "8"
set $ws9 "9"
set $ws10 "10"
set $ws11 "11"

# switch to workspace
bindsym $mod+1 workspace $ws1
bindsym $mod+2 workspace $ws2
bindsym $mod+3 workspace $ws3
bindsym $mod+4 workspace $ws4
bindsym $mod+5 workspace $ws5
bindsym $mod+6 workspace $ws6
bindsym $mod+7 workspace $ws7
bindsym $mod+8 workspace $ws8
bindsym $mod+9 workspace $ws9
bindsym $mod+0 workspace $ws10
bindsym $mod+minus workspace $ws11

# move focused container to workspace
bindsym $mod+Shift+1 move container to workspace $ws1
bindsym $mod+Shift+2 move container to workspace $ws2
bindsym $mod+Shift+3 move container to workspace $ws3
bindsym $mod+Shift+4 move container to workspace $ws4
bindsym $mod+Shift+5 move container to workspace $ws5
bindsym $mod+Shift+6 move container to workspace $ws6
bindsym $mod+Shift+7 move container to workspace $ws7
bindsym $mod+Shift+8 move container to workspace $ws8
bindsym $mod+Shift+9 move container to workspace $ws9
bindsym $mod+Shift+0 move container to workspace $ws10
bindsym $mod+Shift+minus move container to workspace $ws11

# reload the configuration file
bindsym $mod+Shift+c reload
# restart i3 inplace (preserves your layout/session, can be used to upgrade i3)
bindsym $mod+Shift+r restart
# exit i3 (logs you out of your X session)
bindsym $mod+Shift+e exec "i3-nagbar -t warning -m 'You pressed the exit shortcut. Do you really want to exit i3? This will end your X session.' -B 'Yes, exit i3' 'i3-msg exit'"

# resize window (you can also use the mouse for that)
mode "resize" {
        # These bindings trigger as soon as you enter the resize mode

        # Pressing left will shrink the window’s width.
        # Pressing right will grow the window’s width.
        # Pressing up will shrink the window’s height.
        # Pressing down will grow the window’s height.
        bindsym h resize shrink width 10 px or 10 ppt
        bindsym j resize grow height 10 px or 10 ppt
        bindsym k resize shrink height 10 px or 10 ppt
        bindsym l resize grow width 10 px or 10 ppt

        # same bindings, but for the arrow keys
        bindsym Left resize shrink width 10 px or 10 ppt
        bindsym Down resize grow height 10 px or 10 ppt
        bindsym Up resize shrink height 10 px or 10 ppt
        bindsym Right resize grow width 10 px or 10 ppt

        # back to normal: Enter or Escape or $mod+r
        bindsym Return mode "default"
        bindsym Escape mode "default"
        bindsym $mod+r mode "default"
}

bindsym $mod+r mode "resize"

set $bg-color 	         #ffbc42aa
set $border-color        #ffbc42aa
set $indicator-color 	 #008cff50
set $inactive-bg-color   #ffffff00
set $text-color          #f3f4f5
set $inactive-text-color #676E7D
set $urgent-bg-color     #E53935
set $ws-focused-bg 	 #000000

# window colors
#                       border              background         text                 indicator
client.focused          $border-color       $bg-color          $text-color          $indicator-color
client.unfocused        $inactive-bg-color  $inactive-bg-color $inactive-text-color $inactive-bg-color
client.focused_inactive $inactive-bg-color  $inactive-bg-color $inactive-text-color $inactive-bg-color
client.urgent 		$urgent-bg-color    $urgent-bg-color   $text-color 	    $urgent-bg-color

set $term-bg #D7003042

#ROFI MENUS:
bindsym $mod+d exec rofi -show run -config ~/.config/rofi/config_bubbly
bindsym $mod+c exec "SEL=$(ls -1 ~/.linkconfigs/ | rofi -dmenu -p 'config-selector:') && urxvt -e vim ~/.linkconfigs/$SEL"
bindsym $mod+s exec rofi -show ssh

#-lines 5 -eh 1 -width 40 -padding 10 -opacity "85" -bw 0 -bc "$term-bg" -bg "$term-bg" -fg "$text-color" -hlbg "$bg-color" -hlfg "#9575cd" -font "System San Francisco Display 18"

# There also is the (new) i3-dmenu-desktop which only displays applications
# shipping a .desktop file. It is a wrapper around dmenu, so you need that
# installed.
# bindsym $mod+d exec --no-startup-id i3-dmenu-desktop
# Start i3bar to display a workspace bar (plus the system information i3status
# finds out, if available)
#bar {
#	strip_workspace_numbers yes
#	status_command i3status
#	colors {
#		   background $bg-color
#	           separator #757575
##                  		      border             background         text
#		   focused_workspace  $ws-focused-bg     $ws-focused-bg	    $text-color
#	 	   inactive_workspace $inactive-bg-color $inactive-bg-color $inactive-text-color
#		   urgent_workspace   $urgent-bg-color   $urgent-bg-color   $text-color
#		}
#}
exec_always --no-startup-id $HOME/.config/polybar/launch.sh
exec compton -f -I 0.06 -O 0.6

exec_always xrdb -merge ~/.Xresources

#GAPS!!!
gaps inner 5
gaps outer 2
gaps vertical -2
smart_borders on
for_window [class=".*"] border pixel 4
#for_window [instance="__focused__"] border pixel 0
#title_align center
#for_window [class=".*"] title_format "<span>%title</span>"

#touchpad touch-ups:
exec_always "~/.config/i3/touchpad_options"

#key swaps:
exec_always ~/.config/i3/key_mappings

#media
# Pulse Audio controls
bindsym XF86AudioRaiseVolume exec --no-startup-id pactl set-sink-volume alsa_output.pci-0000_00_1f.3.analog-stereo +5% #increase sound volume
bindsym XF86AudioLowerVolume exec --no-startup-id pactl set-sink-volume alsa_output.pci-0000_00_1f.3.analog-stereo -5% #decrease sound volume
bindsym XF86AudioMute exec --no-startup-id pactl set-sink-mute alsa_output.pci-0000_00_1f.3.analog-stereo toggle # mute sound

# Screen brightness controls
bindsym XF86MonBrightnessUp exec xbacklight -inc 10 # increase screen brightness
bindsym XF86MonBrightnessDown exec xbacklight -dec 10 # decrease screen brightness

# Media player controls
bindsym XF86AudioPlay exec playerctl play-pause
#bindsym XF86AudioPause exec playerctl pause
bindsym XF86AudioNext exec playerctl next
bindsym XF86AudioPrev exec playerctl previous

#HARRY'S COMMANDS:
#desktop background
exec_always feh --bg-fill ~/Pictures/desktop-photos/eventdisplay.jpg

#lock shortcut:
bindsym $mod+shift+x exec i3lock -c 222222

#set dpi for i3 toolbars
exec_always xrdb -merge ~/.Xresources
exec_always xrandr --dpi 120

bindsym Print exec "scrot ~/.screenshot.png && xclip ~/.screenshot.png"
# && rm ~/.screenshot.pngn use the cursor keys:
bindsym $mod+Shift+Left move left
bindsym $mod+Shift+Down move down
bindsym $mod+Shift+Up move up
bindsym $mod+Shift+Right move right

# split in horizontal orientation
bindsym $mod+o split h

# split in vertical orientation
bindsym $mod+v split v

# enter fullscreen mode for the focused container
bindsym $mod+f fullscreen toggle

# change container layout (stacked, tabbed, toggle split)
#bindsym $mod+s layout stacking
bindsym $mod+w layout tabbed
bindsym $mod+e layout toggle split

# toggle tiling / floating
bindsym $mod+Shift+space floating toggle

# change focus between tiling / floating windows
bindsym $mod+space focus mode_toggle

# focus the parent container
bindsym $mod+a focus parent

# focus the child container
#bindsym $mod+d focus child

# Define names for default workspaces for which we configure key bindings later on.
# We use variables to avoid repeating the names in multiple places.
#set $ws1 "1:" 
#set $ws2 "2:" 
#set $ws3 "3:" 
#set $ws4 "4:" 
##set $ws5 "5:<span font='SVGFont1 12' rise='-2000'>a</span>"
#set $ws5 "5:%{T2}a%{T-}"
#set $ws6 "6:"
#set $ws7 "7:"
#set $ws8 "8:"
#set $ws9 "9:"
#set $ws10 "10:"
#set $ws11 "11:"
set $ws1 "1" 
set $ws2 "2" 
set $ws3 "3" 
set $ws4 "4" 
set $ws5 "5"
set $ws6 "6"
set $ws7 "7"
set $ws8 "8"
set $ws9 "9"
set $ws10 "10"
set $ws11 "11"

# switch to workspace
bindsym $mod+1 workspace $ws1
bindsym $mod+2 workspace $ws2
bindsym $mod+3 workspace $ws3
bindsym $mod+4 workspace $ws4
bindsym $mod+5 workspace $ws5
bindsym $mod+6 workspace $ws6
bindsym $mod+7 workspace $ws7
bindsym $mod+8 workspace $ws8
bindsym $mod+9 workspace $ws9
bindsym $mod+0 workspace $ws10
bindsym $mod+minus workspace $ws11

# move focused container to workspace
bindsym $mod+Shift+1 move container to workspace $ws1
bindsym $mod+Shift+2 move container to workspace $ws2
bindsym $mod+Shift+3 move container to workspace $ws3
bindsym $mod+Shift+4 move container to workspace $ws4
bindsym $mod+Shift+5 move container to workspace $ws5
bindsym $mod+Shift+6 move container to workspace $ws6
bindsym $mod+Shift+7 move container to workspace $ws7
bindsym $mod+Shift+8 move container to workspace $ws8
bindsym $mod+Shift+9 move container to workspace $ws9
bindsym $mod+Shift+0 move container to workspace $ws10
bindsym $mod+Shift+minus move container to workspace $ws11

# reload the configuration file
bindsym $mod+Shift+c reload
# restart i3 inplace (preserves your layout/session, can be used to upgrade i3)
bindsym $mod+Shift+r restart
# exit i3 (logs you out of your X session)
bindsym $mod+Shift+e exec "i3-nagbar -t warning -m 'You pressed the exit shortcut. Do you really want to exit i3? This will end your X session.' -B 'Yes, exit i3' 'i3-msg exit'"

# resize window (you can also use the mouse for that)
mode "resize" {
        # These bindings trigger as soon as you enter the resize mode

        # Pressing left will shrink the window’s width.
        # Pressing right will grow the window’s width.
        # Pressing up will shrink the window’s height.
        # Pressing down will grow the window’s height.
        bindsym h resize shrink width 10 px or 10 ppt
        bindsym j resize grow height 10 px or 10 ppt
        bindsym k resize shrink height 10 px or 10 ppt
        bindsym l resize grow width 10 px or 10 ppt

        # same bindings, but for the arrow keys
        bindsym Left resize shrink width 10 px or 10 ppt
        bindsym Down resize grow height 10 px or 10 ppt
        bindsym Up resize shrink height 10 px or 10 ppt
        bindsym Right resize grow width 10 px or 10 ppt

        # back to normal: Enter or Escape or $mod+r
        bindsym Return mode "default"
        bindsym Escape mode "default"
        bindsym $mod+r mode "default"
}

bindsym $mod+r mode "resize"

set $bg-color 	         #ffbc42aa
set $border-color        #ffbc42aa
set $indicator-color 	 #008cff50
set $inactive-bg-color   #ffffff00
set $text-color          #f3f4f5
set $inactive-text-color #676E7D
set $urgent-bg-color     #E53935
set $ws-focused-bg 	 #000000

# window colors
#                       border              background         text                 indicator
client.focused          $border-color       $bg-color          $text-color          $indicator-color
client.unfocused        $inactive-bg-color  $inactive-bg-color $inactive-text-color $inactive-bg-color
client.focused_inactive $inactive-bg-color  $inactive-bg-color $inactive-text-color $inactive-bg-color
client.urgent 		$urgent-bg-color    $urgent-bg-color   $text-color 	    $urgent-bg-color

set $term-bg #D7003042

#ROFI MENUS:
bindsym $mod+d exec rofi -show run -config ~/.config/rofi/config_bubbly
bindsym $mod+c exec "SEL=$(ls -1 ~/.linkconfigs/ | rofi -dmenu -p 'config-selector:') && urxvt -e vim ~/.linkconfigs/$SEL"
bindsym $mod+s exec rofi -show ssh

#-lines 5 -eh 1 -width 40 -padding 10 -opacity "85" -bw 0 -bc "$term-bg" -bg "$term-bg" -fg "$text-color" -hlbg "$bg-color" -hlfg "#9575cd" -font "System San Francisco Display 18"

# There also is the (new) i3-dmenu-desktop which only displays applications
# shipping a .desktop file. It is a wrapper around dmenu, so you need that
# installed.
# bindsym $mod+d exec --no-startup-id i3-dmenu-desktop
# Start i3bar to display a workspace bar (plus the system information i3status
# finds out, if available)
#bar {
#	strip_workspace_numbers yes
#	status_command i3status
#	colors {
#		   background $bg-color
#	           separator #757575
##                  		      border             background         text
#		   focused_workspace  $ws-focused-bg     $ws-focused-bg	    $text-color
#	 	   inactive_workspace $inactive-bg-color $inactive-bg-color $inactive-text-color
#		   urgent_workspace   $urgent-bg-color   $urgent-bg-color   $text-color
#		}
#}
exec_always --no-startup-id $HOME/.config/polybar/launch.sh
exec compton -f -I 0.06 -O 0.6

exec_always xrdb -merge ~/.Xresources

#GAPS!!!
gaps inner 5
gaps outer 2
gaps vertical -2
smart_borders on
for_window [class=".*"] border pixel 4
#for_window [instance="__focused__"] border pixel 0
#title_align center
#for_window [class=".*"] title_format "<span>%title</span>"

#touchpad touch-ups:
exec_always "~/.config/i3/touchpad_options"

#key swaps:
exec_always ~/.config/i3/key_mappings

#media
# Pulse Audio controls
bindsym XF86AudioRaiseVolume exec --no-startup-id pactl set-sink-volume alsa_output.pci-0000_00_1f.3.analog-stereo +5% #increase sound volume
bindsym XF86AudioLowerVolume exec --no-startup-id pactl set-sink-volume alsa_output.pci-0000_00_1f.3.analog-stereo -5% #decrease sound volume
bindsym XF86AudioMute exec --no-startup-id pactl set-sink-mute alsa_output.pci-0000_00_1f.3.analog-stereo toggle # mute sound

# Screen brightness controls
bindsym XF86MonBrightnessUp exec xbacklight -inc 10 # increase screen brightness
bindsym XF86MonBrightnessDown exec xbacklight -dec 10 # decrease screen brightness

# Media player controls
bindsym XF86AudioPlay exec playerctl play-pause
#bindsym XF86AudioPause exec playerctl pause
bindsym XF86AudioNext exec playerctl next
bindsym XF86AudioPrev exec playerctl previous

#HARRY'S COMMANDS:
#desktop background
exec_always feh --bg-fill ~/Pictures/desktop-photos/eventdisplay.jpg

#lock shortcut:
bindsym $mod+shift+x exec i3lock -c 222222

#set dpi for i3 toolbars
exec_always xrdb -merge ~/.Xresources
exec_always xrandr --dpi 120

bindsym Print exec "scrot ~/.screenshot.png && xclip ~/.screenshot.png"
# && rm ~/.screenshot.png
</pre>

<pre>
- Linux Distribution & Version: Fedora 30
- Are you using a compositor (e.g., xcompmgr or compton): compton
</pre>

**Comment by Ploppz** [comment]
Same for me! It's really annoying, as I can't get clear feedback which window is focused in my setup.
For me though it does not only happen for graphical applications. But perhaps only consistently for graphical applications and randomly for terminals.
I'm on Arch Linux, using compton and relevant config:
```
for_window [class=".*"] border pixel 8
smart_gaps on
gaps inner 3
gaps outer 2
hide_edge_borders both

# ...

# class                 border  backgr. text    indicator child_border
client.focused_inactive #333333 #5f676a #ffffff #B2C6E6   #CEE6B200
client.unfocused        #333333 #222222 #888888 #B2C6E6   #CEE6B200
client.focused          #4c7899 #285577 #ffffff #B2C6E6   #000000

client.urgent           #2f343a #900000 #ffffff #900000   #900000
client.placeholder      #000000 #0c0c0c #ffffff #000000   #0c0c0c
```

**Comment by hacooke** [comment]
I 'solved' this issue by using non-transparent borders, and I picked an inactive border colour that was close to my desktop background in colour. Not an ideal solution for sure, it would be good to have proper support for transparent borders.

**Comment by johantiden** [comment]
Maybe a related workaround would be to change how the blending is done for windows that don't support transparency.
Currently border color `#ffffffff` would be white on all windows. `#ffffff00` would be _black_ on non-transparent windows and fully transparent on supported windows. I think a nicer behavior would be to ignore the alpha values on the non-transparent windows, resulting in white.

This way, one could use transparency where supported and "fallback" to what @Hazza4569 does.

This effect is more apparent when using alpha values inbetween 0 and ff. `#ffffff88` would result in _gray_, which is probably not what you want.

This behavior is based on my limited experience on `i3-gaps`
```
$ i3 --version    
i3 version 4.18.2 (2020-07-26) © 2009 Michael Stapelberg and contributors
```

**Comment by FancyFurret** [comment]
Any updates on this? It seems transparent borders also work in kitty, fyi

**Comment by Tuuuukka** [comment]
Would like to hear if this is being looked at? It's visually annoying when you get black borders on some windows when they should be transparent. You could turn off the borders completely, but that would mess up the highlighting of the active window too.

**Comment by Airblader** [comment]
@Tuuuukka No, sorry, for me personally i3-gaps is now purely a "keep it up to date with upstream" project. If someone wants to look into this and can find a simple fix, that'd be great, of course.

**Comment by Tuuuukka** [comment]
> @Tuuuukka No, sorry, for me personally i3-gaps is now purely a "keep it up to date with upstream" project. If someone wants to look into this and can find a simple fix, that'd be great, of course.

Ok, thanks. Might have to look into it myself when I got the time.

**Comment by Airblader** [comment]
I'm closing this issue has i3-gaps is being migrated into i3. If this issue still applies, please reopen it in i3.
