### ISSUE TITLE
Sluggish performance after a few hours of use. Extremely high memory usage (500MB). 

### ISSUE THREAD

**Issue by alienbogart** [Airblader/i3#314]
## I'm submitting a…

<pre>
[x] Bug
[ ] Feature Request
[ ] Documentation Request
[ ] Other (Please describe in detail)
</pre>

## Current Behavior

After a few hours of use, i3 always slow down on me, forcing me to log-out. So I took a look at the `xfce4-taskmanager` yesterday: it was using more than 1 gigabyte of memory! Today I took [this screenshot](http://i.imgur.com/Z6srgQD.png). A lot less, but still very concerning. And the performance hit is real. I switched to the `gaps` fork to see if the issue would be fixed, but it remained the same. I mess a lot with my configurations, and I wonder if restarting/reloading a lot can lead to this exaggerated memory consumption. Yesterday, there was something about a **restart state** in the process string. Am I missing something? Should I simply avoid restarting/reloading too much? (To be clear, I'm not even sure if that is the issue). 

**EDIT**: [this is how much i3 is spending now, without any reloads or restarts](http://i.imgur.com/gK44rrO.png). 

## Expected Behavior

i3 should stay performant during usage, without requiring an absurd amount of resources. 

## Reproduction Instructions

Use i3 for more than three hours. Possibly `i3-msg restart` and/or `i3-msg reload` a few times. 

## Environment

- OS: MX Linux 18.3
- [dotfiles](https://github.com/mrbig033/dotfiles)
- Output of `i3 --moreversion 2>&-`:
<pre>
Binary i3 version:  4.17-2-g9df9e62b (2019-08-04, branch "gaps-next") © 2009 Michael Stapelberg and contributors
(Getting version from running i3, press ctrl-c to abort…)
Running i3 version: 4.17-2-g9df9e62b (2019-08-04, branch "gaps-next") (pid 3454)
Loaded i3 config: /home/my_username/.config/i3/config (Last modified: Fri 16 Aug 2019 11:59:42 AM -03, 10551 seconds ago)

The i3 binary you just called: /usr/local/bin/i3
The i3 binary you are running: i3
</pre>

<pre>
- [i3/config](https://github.com/mrbig033/dotfiles/blob/master/i3/config)
</pre>

<pre>

</pre>

<pre>
- Linux Distribution & Version: MX Linux 18.3
- Are you using a compositor (e.g., xcompmgr or compton): compton
</pre>

**Comment by Airblader** [comment]
How did you install i3?

**Comment by alienbogart** [comment]
I first installed it using the following command on MX Linux 18.3:

`sudo aptitude -y install i3`

After experiencing the issue for a long time on regular i3, in the hopes of solving if I built `i3-gaps` from source [using these instructions](https://github.com/Airblader/i3/wiki/Building-from-source).

**Comment by alienbogart** [comment]
Here's how much it is spending with the default config (the covered up process is from `i3-bar`):

![Screenshot](https://user-images.githubusercontent.com/36245777/63190006-a546e100-c03b-11e9-895d-864e9432b636.png)

**Comment by orestisfl** [comment]
Did you make sure that sanitizers where disabled?

**Comment by alienbogart** [comment]
Okay, I was not sure, so I followed all the steps again and made sure to include the line to disable the sanitizers. As of this moment, i3 is using ~~213.5MiB~~ `395.1MiB` or RAM.

**Comment by alienbogart** [comment]
I couldn't wait any longer so I reinstalled MX Linux 18 with the default `i3 version 4.13`. Everything is working perfectly now, and i3 is only consuming `19MB` of RAM at the most. The reason I tried i3-gaps was to solve performance issues that the reinstall seems to have solved, and also so I could use a properly supported version. At least for now, i3-gaps is not for me.  I'm closing the issue since  I won't pursue the issue any longer. Feel free to reopen if deemed appropriate. Thanks.
