### ISSUE TITLE
exec not using $PATH

### ISSUE THREAD

**Issue by jhessin** [Airblader/i3#315]
## I'm submitting a…

<pre>
[x] Bug
[ ] Feature Request
[ ] Documentation Request
[ ] Other (Please describe in detail)
</pre>

## Current Behavior

When loading my config that contains this:
bindsym $mod+Escape exec --no-startup-id blacklock

I press $mod+Escape and nothing happens.

## Expected Behavior

I expect my $PATH variable to be used to run my custom script that is in $HOME/.local/bin/blacklock
This simply runs i3lock -c 000000

## Reproduction Instructions

I am using fish as my shell, so I set my $PATH using it's method:
/home/jhessin/.cargo/bin /home/linuxbrew/.linuxbrew/sbin /home/linuxbrew/.linuxbrew/bin /home/jhessin/.local/bin /home/jhessin/.gem/ruby/2.3.0/bin /home/jhessin/.yarn/bin /usr/local/bin /usr/bin /bin /usr/local/sbin /usr/bin/site_perl /usr/bin/vendor_perl /usr/bin/core_perl

I also added /home/jhessin/.local/bin to the path in my .profile file just to be certain.

Then I created the file /home/jhessin/.local/bin/blacklock:
```bash
#!/bin/bash

i3lock -c 000000
```

typing `blacklock` at a command prompt works as expected, however running exec blacklock inside my config does nothing.

## Environment

Output of `i3 --moreversion 2>&-`:
<pre>Binary i3 version:  4.17 (04.08.2019) © 2009 Michael Stapelberg and contributors
Running i3 version: 4.17 (04.08.2019) (pid 777)to abort…)
Loaded i3 config: /home/jhessin/.config/i3/config (Last modified: Tue 27 Aug 2019 10:31:26 AM MDT, 1188 seconds ago)

The i3 binary you just called: /usr/bin/i3
The i3 binary you are running: i3

</pre>

<pre>
http://ix.io/1TCF

NOTE: I tried:
`
set $SHELL /usr/bin/fish
`
to fix the issue (I remember reading somewhere this variable was used by exec) but it solved nothing.

This is based off of the default config installed by Manjaro-i3
</pre>

<pre>
Logfile URL:
</pre>

<pre>
- Linux Distribution & Version: 
Manjaro-i3
Kernel 4.19.66-1
- Are you using a compositor (e.g., xcompmgr or compton): No
</pre>

**Comment by orestisfl** [comment]
i3 doesn't do anything related to $PATH, make sure that the variable is modified (and exported) before executing i3, eg in your xinitrc.

https://superuser.com/questions/121261/how-can-i-set-environment-variables-for-a-graphical-login-on-linux

**Comment by jhessin** [comment]
#Facepalm
I found my issue. I needed to set the path in the ~/.profile and I did, but I accidentally used a ; instead of a : to delimit it. 

Thanks for your help!

- Jim Hessin

**Comment by Airblader** [comment]
Thanks for the feedback!
