### ISSUE TITLE
move workspace doesn't work on 4.17.x version

### ISSUE THREAD

**Issue by LKlemens** [Airblader/i3#316]
## I'm submitting a…

<pre>
[x] Bug
[ ] Feature Request
[ ] Documentation Request
[ ] Other (Please describe in detail)
</pre>

## Current Behavior

I have set `bindsym $mod+m move workspace to output left` in config to moving workspace. 
After upgrade i3-gaps to 4.17.x it stops working - press mod+x doesn't move workspace.
I've double check it and on 4.16.1 works well. 
## Expected Behavior

After press $mod+m workspace moves left.

## Reproduction Instructions

add this line to i3-config `bindsym $mod+m move workspace to output left`
Restart i3
Open two workspaces,
Focus on first workspace.
Press `$mod+m` combination.
On 4.17 nothing happen. 
On 4.16 works. 

## Environment

Output of `i3 --moreversion 2>&-`:
```
Binary i3 version:  4.17.1 (2019-08-30) © 2009 Michael Stapelberg and contributors
Running i3 version: 4.17.1 (2019-08-30) (pid 4486)abort…)
Loaded i3 config: /home/klemens/.config/i3/config (Last modified: Mon 02 Sep 2019 06:40:11 AM CEST, 692 seconds ago)

The i3 binary you just called: /usr/bin/i3
The i3 binary you are running: i3
```
<pre>
i3 version: 4.17.1
</pre>

<pre>

# force_xinerama yes
# popup_during_fullscreen ignore
for_window [class="^.*"] border pixel 1
workspace_layout tabbed
mouse_warping none
# focus_follows_mouse no
workspace_auto_back_and_forth yes
# sticky no

# Start i3bar to display a workspace bar (plus the system information i3status
# finds out, if available)
bar {
        # status_command i3status
        status_command polybar Bar
        tray_output primary
        separator_symbol '//"
        position bottom
        strip_workspace_numbers yes
        mode invisible
}

# border none

# i3 config file (v4)
#
# Please see http://i3wm.org/docs/userguide.html for a complete reference!

set $mod Mod4

# Use Mouse+$mod to drag floating windows to their wanted position
floating_modifier $mod

# start a terminal
bindsym $mod+Return   exec termite # -t shell -e tmux

# kill focused window
bindsym $mod+q kill

# reload the configuration file
bindsym $mod+Shift+c reload
#clipmenu
bindsym $mod+Shift+v exec clipmenu
# restart i3 inplace (preserves your layout/session, can be used to upgrade i3)
bindsym $mod+Shift+r restart
# exit i3 (logs you out of your X session)
bindsym $mod+Shift+e exec "i3-msg exit"

bindsym $mod+m move workspace to output left

gaps inner 3
gaps outer 3

</pre>

<pre>
Logfile URL: https://logs.i3wm.org/logs/5708401665376256.bz2
</pre>

<pre>
- Linux Distribution & Version: Arch Linux 5.2.9-arch1-1-ARCH
- Are you using a compositor (e.g., xcompmgr or compton): I use compton
</pre>

**Comment by Airblader** [comment]
Can you reproduce this on vanilla i3?

**Comment by LKlemens** [comment]
I've checked, and it is reproduce on vanilla i3 either.

**Comment by Airblader** [comment]
Thanks, in that case please report the issue upstream directly. Thanks!
