### ISSUE TITLE
Centos7 package

### ISSUE THREAD

**Issue by Phibonacci** [Airblader/i3#317]
## I'm submitting a…

<pre>
[ ] Bug
[x] Feature Request
[ ] Documentation Request
[ ] Other (Please describe in detail)
</pre>

There is no Centos7 package for i3gaps. There is however an i3 package for the version 4.12 in the EPEL repository.

Would you consider adding one ?

**Comment by Airblader** [comment]
I provide software, I cannot be the one to provide packages on all possible distros that I don't even use. Please either write to the responsible people in your distro or provide the package yourself. :-) I'm happy to link to it once it's created.

**Comment by Phibonacci** [comment]
I perfectly understand. I was following the [wiki advices](https://github.com/Airblader/i3/wiki/Installation) on missing packages.

Is there a documentation somewhere to compile i3gaps?

Configure does not work so I guess I'm missing something:
```

$ ./configure
configure: error: cannot find install-sh, install.sh, or shtool in "." "./.." "./../.."
```

Would you like me to open a new ticket?

**Comment by Airblader** [comment]
Did you delete your latest comment or is GitHub tricking me? :-)

**Comment by Phibonacci** [comment]
My evil plan was perfect!

Actually I realized I do not have enough time to work on this and so I thought it is unnecessary to bother you with my questions.

**Comment by Airblader** [comment]
No worries about bothering me. :-)
