### ISSUE TITLE
Missing tarball asset for 4.17.1 release

### ISSUE THREAD

**Issue by avindra** [Airblader/i3#318]
doing the usual upgrade chores for opensuse, noticed the expected assets (with baseline build root) aren't up (`i3-gaps-4.17.1.tar.bz2`)

```
 .../space/OBS/X11:windowmanagers/i3-gaps $ osc service lr download_files
ERROR: Failed to download "https://github.com/Airblader/i3/releases/download/4.17.1/i3-4.17.1.tar.bz2#/i3-gaps-4.17.1.tar.bz2"
Aborting: service call failed:  /usr/lib/obs/service/download_files --outdir /mnt/space/OBS/X11:windowmanagers/i3-gaps/tmpqxxu4s4b.download_files.service
```

**Comment by Airblader** [comment]
Hey, thanks for letting me know and sorry about that! I'll upload it as soon as I'm back on my laptop and will let you know here.

**Comment by Airblader** [comment]
@avindra I uploaded the tarball now: https://github.com/Airblader/i3/releases/download/4.17.1/i3-4.17.1.tar.bz2

Thanks again for reporting it :-) If there's further issues, let me know.

**Comment by avindra** [comment]
thanks @Airblader now on the way for Suse https://build.opensuse.org/request/show/730826
