### ISSUE TITLE
Text not aligned properly horizontally

### ISSUE THREAD

**Issue by nim-** [Airblader/i3#32]
Hi again

I don't know if the issue is on my end, but I just reinstalled Arch and set up my wm. The usual routine etc.

Now, after a reboot, the text in my i3bar (but not the icons) are not centered horizontally and it's driving me nuts. I usually use i3blocks but I also tested with i3status to make sure:

i3status:
http://imgur.com/uNJTV2q

i3blocks:
http://i.imgur.com/uKP8yJ5.png

Have I done something wrong or is this a bug?

Thanks a lot!

**Comment by nim-** [comment]
Okay, apparently this is related to how i3bar handles infinality (which explains why it happened after a reboot, as I probably installed it and then rebooted)

https://bbs.archlinux.org/viewtopic.php?pid=1396682

I don't know if this bug belongs here then.

**Comment by Airblader** [comment]
I don't necessarily want to read through that entire thread. Can you give me a quick outline of what the issue is?

**Comment by nim-** [comment]
Oh, sorry, I was meant to refer to a specific post.

Post #985 posts the specific part of the i3 code that's responsible:

"Sorry, but that is the problem. i3bar walks through all textblocks. Each textblock is measured with pango as a whole to fix its position and then drawn on the bar. As a result the whole text for the memory block is drawn wrong.
Most likely the infinality patches change the behaviour of the line spacing/height calculation when fonts are mixed or this is done in the configuration files.

Here is the code in i3bar: http://code.stapelberg.de/git/i3/tree/i3bar/src/xcb.c#n176"

I find it kind of sad, as infinality really is necessary to make i3 look good. Funny though, I used infinality on Fedora (before I went back to arch yesterday) and didn't get this bug.

**Comment by Airblader** [comment]
Okay, that sounds reasonable. I don't know too much about the font rendering code, but I really doubt that this can be solved within i3. I'm not sure I understand everything correctly, but if those infinality patches change the way combined fonts are calculated, it seems like the bug lies there. At the end of the day, i3 only has "one" font (however that one came into existence) and in order to vertically align it, I have to rely on the font telling me it's height.

Is there any way to file this bug against those patches?

**Comment by nim-** [comment]
I'm not sure, the website seems pretty dead.

**Comment by Airblader** [comment]
It'd be a little hacky but if you want I can add a flag to position the font not vertically centered but  at the top of the bar. Unless you use the `height` command that I've added, this would probably fix the issue for you.

**Comment by nim-** [comment]
That would be wonderful!

**Comment by Airblader** [comment]
Just before I do that, let's try and see if it even works. Try this:

```
git checkout feature-i3bar-alignment
make && sudo make install
i3-msg reload
```

And let me know whether the alignment is better that way. After that go back by doing the same, but replace `feature-i3bar-alignment` with `gaps`.

**Comment by nim-** [comment]
Looks like this now:
http://imgur.com/0cB2vJF

**Comment by Airblader** [comment]
How odd. Let's try something crazy. Do the following and then screenshot it (don't worry if it looks super weird, it's supposed to)

```
git checkout feature-i3bar-alignment
git pull && make && sudo make install
i3-msg reload
```

And to revert the same as above.

**Comment by nim-** [comment]
Hi

I'm terribly sorry and I feel like I have wasted your time, but earlier today I fixed the issue.
I was using the package "infinality-bundle", as recommended by the wiki, so I uninstalled it and installed the packages "fontconfig-infinality" and "freetype2-infinality" instead as I would've done on another distro, and now I have smooth fonts without the alignment issue.

If you still want me to test the above I'd be happy to reinstall infinality-bundle and do that, but for now I feel guilty for wasting your time as the issue indeed (as you said) belongs to infinality and not i3, and in this case to a specifically packaged version of it.

**Comment by Airblader** [comment]
No worries, I'm just glad we could sort it out. Makes it easier for me if I don't have to try and chase down this bug. :)

FYI, I'll try to get back on the resize thing. I'm just horribly busy right now, so I didn't have much time for anything but the two line patches for this issue. I'll wirte a comment there as soon as I got news on it.

**Comment by nim-** [comment]
Sounds wonderful but no stress :)

**Comment by Airblader** [comment]
Possibly related: https://github.com/i3/i3/pull/1495/files
