### ISSUE TITLE
visual hint for focused window.

### ISSUE THREAD

**Issue by AdrienLemaire** [Airblader/i3#320]
## I'm submitting a…

<pre>
[ ] Bug
[x] Feature Request
[ ] Documentation Request
[ ] Other (Please describe in detail)
</pre>

## Current Behavior
gaps makes the window decoration transparent. There is no visual way to figure out what window is focused.

## Desired Behavior

gaps still makes the window decoration transparent (that's the point of this fork!). There is a visual way to see what window is focused.

I'm ashamed to say I only realized today about the new features show_marks, smart_gaps and smart_borders.
Would it be difficult to show "hints" like marks and focused in a visually appealing way? (eg rounded icons in the top-right side of the window).
Otherwise, or until then, what is everybody's prefered way to show what window is (or isn't) focused? I suppose there's a way to play with compton to reduce opacity of non-focused windows, but I'm worried about performances.

## Environment

Output of `i3 --moreversion 2>&-`:
<pre>
i3 version: 
Binary i3 version:  4.17.1-23-gf07e171c (2019-08-30, branch "gaps-next") © 2009 Michael Stapelberg and contributors
Running i3 version: 4.17.1-23-gf07e171c (2019-08-30, branch "gaps-next") (pid 6517)
Loaded i3 config: /home/dori/.config/i3/config (Last modified: Thu 03 Oct 2019 10:00:07 AM JST, 346 seconds ago)

The i3 binary you just called: /usr/bin/i3
The i3 binary you are running: i3
</pre>

<pre>
- Linux Distribution & Version: Arch linux
- Are you using a compositor (e.g., xcompmgr or compton): compton
</pre>

**Comment by AdrienLemaire** [comment]
~I found a solution with `mouse_warping output`. My mouse location can now serve as visual hint for the focused mode.~
~This issue's priority is therefore lowered, but still a nice-to-have thingy :heart_eyes_cat:~

Somehow, mouse_warping only works when switching workspace, not when going to a different window within the same workspace :(

**Comment by Airblader** [comment]
Gaps do not make window decorations transparent, but you do have to disable titlebars. However, you can use pixel borders which display the usual colors, so you can use that for indication.

I don't want to change how things like marks are shown in a major way because this would be too big of a deviation from upstream.
