### ISSUE TITLE
smart_borders causes desktop background to flash

### ISSUE THREAD

**Issue by mklpiening** [Airblader/i3#321]
## I'm submitting a…

<pre>
[x] Bug
[ ] Feature Request
[ ] Documentation Request
[ ] Other (Please describe in detail)
</pre>

## Current Behavior

When using smart_borders and screen compositing the wallpaper is shown for one frame every time another workspace is being selected.

## Expected Behavior

The wallpaper should not show when switching between workspaces.

## Reproduction Instructions

Install and run a screen compositing service like compton or xcompmgr and enable smart_borders with "smart_borders on" in your i3 config.
When switching between workspaces now the wallpaper will be shown for one frame.

## Environment

Output of `i3 --moreversion 2>&-`:
<pre>
i3 version: 4.17.1-64-g4c464e63 (2019-10-11, branch "gaps-next")
</pre>

[my i3config](https://pastebin.com/PYh20zac)

<pre>
- Linux Distribution & Version: Bedrock Linux 0.7.9 Poki x86_64 (Hijacked Arch)
- Are you using a compositor (e.g., xcompmgr or compton): yes, the problem perists with both of them
</pre>

**Comment by Airblader** [comment]
I doubt that this is specific to i3-gaps and probably occurs in i3 as well. It could be that you have fading activated in your compositor(?) or it's just an artifact of how i3 switches workspaces by unmapping windows on one and mapping windows on the other workspace.

I will leave this issue open, but I doubt there's anything we can do about it.

**Comment by mklpiening** [comment]
I have fading disabled in my compositor so this is not the cause of the problem. The flashing does not occur when having smart_borders disabled.
I also noticed that the wallpaper only flashes when switching to electron or gtk applications. With other applications like chromium or urxvt this artifact is not shown.

**Comment by Airblader** [comment]
I'm closing this issue has i3-gaps is being migrated into i3. If this issue still applies, please reopen it in i3.
