### ISSUE TITLE
Removing borders on created windows breaks resizing

### ISSUE THREAD

**Issue by Doonut** [Airblader/i3#324]
## I'm submitting a…

<pre>
[x] Bug
[ ] Feature Request
[ ] Documentation Request
[ ] Other (Please describe in detail)
</pre>

## Current Behavior

when removing window borders with something like 
bindsym $mod+Shift+space floating enable, border none
it breaks window resizing with mouse or resize mode. This is not just floating windows, but tiled ones too

## Expected Behavior

window should redraw after resizing it

## Reproduction Instructions

remove borders from a window and resize it
## Environment

arch linux AUR latest version
<pre>
</pre>

<pre>
Logfile URL:
</pre>

<pre>
- Linux Distribution & Version: Arch
- Are you using a compositor (e.g., xcompmgr or compton): compton
</pre>

heres a screenshot https://i.imgur.com/pqgcMB8.png

**Comment by Airblader** [comment]
1. Are you sure this is specific to i3-gaps and doesn't occur with i3?
2. Are you running a compositor? What if you disable it? 

i3 does not render windows, that's the job of the server. I doubt that this is an issue with i3.

**Comment by Doonut** [comment]
this is specific to i3-gaps-rounded. installing i3-gaps fixes the issue.

**Comment by Airblader** [comment]
i3-gaps-rounded does not reflect i3-gaps, it reflects the open PR, so please address it there: https://github.com/Airblader/i3/pull/294
