### ISSUE TITLE
Centos 7 (RPM) Packaging for i3-gaps

### ISSUE THREAD

**Issue by DanielAHaller** [Airblader/i3#326]
## I'm submitting a…

<pre>
[ ] Bug
[ ] Feature Request
[ ] Documentation Request
[x] Other (Packaging Request)
</pre>

## Current Behavior
yum install -y i3-gaps yields nothing, even with the EPEL repos enabled.

## Desired Behavior
I read the documentation with regards to installing - I'd really like to install through my Centos 7 package manager (yum), but I can't find a working repo/rpm for i3-gaps.

I'd love an official package for this for CentOS/RHEL. If there is one and I'm unaware of it, please let me know.

## Environment

Output of `i3 --moreversion 2>&-`:
<pre>
i3 version: 
</pre>

<pre>
- Linux Distribution & Version:
- Are you using a compositor (e.g., xcompmgr or compton):
</pre>

**Comment by Airblader** [comment]
See my answer in the other issue.
