### ISSUE TITLE
Config doesn't load properly when certain commands aren't bound

### ISSUE THREAD

**Issue by BanchouBoo** [Airblader/i3#328]
I use `sxhkd` to bind my keys, so I removed all the `bindsym`'s in my i3 config. Doing so prevented my config from loading properly and instead loads what seems to be the default config. After this I narrowed it down by commenting out each keybind one by one and found that if I don't have at least one command bound from a specific set of commands (see below) it breaks my config. The keys themselves don't matter, but at least one of the commands must be bound.

```
bindsym $mod+h focus left
bindsym $mod+j focus down
bindsym $mod+k focus up
bindsym $mod+l focus right

bindsym $mod+Shift+space floating toggle

bindsym $mod+1 workspace number $ws1
bindsym $mod+2 workspace number $ws2
bindsym $mod+3 workspace number $ws3
bindsym $mod+4 workspace number $ws4
bindsym $mod+5 workspace number $ws5
bindsym $mod+6 workspace number $ws6
bindsym $mod+7 workspace number $ws7
bindsym $mod+8 workspace number $ws8
bindsym $mod+9 workspace number $ws9
bindsym $mod+0 workspace number $ws10
```

Output of `i3 --moreversion 2>&-`:
<pre>
Binary i3 version:  4.17.1 (2019-08-30) © 2009 Michael Stapelberg and contributors

Running version: < 4.2-200
</pre>

<pre>
- Linux Distribution & Version: Manjaro 18.1.3 Juhraya
- Are you using a compositor (e.g., xcompmgr or compton): No
</pre>

**Comment by Airblader** [comment]
Can you try to reproduce this on vanilla i3? i3-gaps doesn't really have any modifications in this area so I doubt this issue is specific to it.

You can also try `i3 -C` on the "broken" config to see if it complains about anything.

In theory the only required entry is the `font` setting.

**Comment by BanchouBoo** [comment]
Opened an issue @ i3/i3#3870 and added some additional information to it.
