### ISSUE TITLE
Make bar configurably transparent

### ISSUE THREAD

**Issue by alecdtatum** [Airblader/i3#33]
This would be pretty nifty, if it's possible.

**Comment by Airblader** [comment]
This is funny. I was thinking the same thing just yesterday. :) I'll have to take a look. My best guess: it's either trivial or really hard.

**Comment by Airblader** [comment]
Since xcb doesn't support this, the only viable option would probably be to render the bar to a Cairo surface and then pass it as a pixmap to X. I'm honestly not sure how easy this will be but I'll at least try to look into it.

**Comment by Airblader** [comment]
Cairo is currently only used for font rendering. I think that changing this might introduce too much of a maintenance effort for a too little gain (besides, I have absolutely no clue about cairo). So I'll have to close this, sorry.

**Comment by alecdtatum** [comment]
Guess this wasn't really closed after all :)

**Comment by Airblader** [comment]
Yeah, well, the patch for transparency in i3 will be reverted, though, but I have decided to actually do make this configurable in i3-gaps. Anyone using it will have to be OK with the fact that tray icons always have full transparency, though, plus I might refuse to fix other bugs related to it – it just depends on the effort. I really don't want too big of a change between i3 and i3-gaps.
