### ISSUE TITLE
[Feature request]: Command to automatically balance window sizes after manually resizing

### ISSUE THREAD

**Issue by atreyasha** [Airblader/i3#330]
## I'm submitting a…

<pre>
[ ] Bug
[x] Feature Request
[ ] Documentation Request
[ ] Other (Please describe in detail)
</pre>

## Current Behavior
All is well in terms of the current behaviour. Under my current configuration, I can go into a resizing mode and manually resize heights/widths of windows.

## Desired Behavior
It would be good to develop a command which can automatically re-balance the sizes of windows after having manually resized them. This would be useful when dealing with multiple windows.

I can imagine developing a script to do this manually, for example getting the current window distributions on the current workspace with `i3-msg -t get_tree | jq`, and then computing the ideal balanced widths/heights and executing this with resizing commands. However, this might be costly in terms of processing speed.

I would be happy to receive other suggestions, and could submit a PR if this would be of interest.

## Environment

Output of `i3 --moreversion 2>&-`:
<pre>
Binary i3 version:  4.17.1 (2019-08-30) © 2009 Michael Stapelberg and contributors
Running i3 version: 4.17.1 (2019-08-30) (pid 1053)abort…)
Loaded i3 config: /home/shankar/.config/i3/config (Last modified: Sun 01 Dec 2019 01:21:46 AM CET, 715471 seconds ago)

The i3 binary you just called: /usr/bin/i3
The i3 binary you are running: i3
</pre>

<pre>
- Linux Distribution & Version: Arch Linux, 5.4.2-arch1-1
- Are you using a compositor (e.g., xcompmgr or compton): picom v7.5
</pre>

**Comment by Airblader** [comment]
This has been requested upstream in i3 a few times before and declined. In one of those issues you can find a script that does it, and our stance is that a script is appropriate and sufficient (it's not costly since you don't run it a thousand times per second). Thanks for understanding.
