### ISSUE TITLE
"Fibonacci"-like layout

### ISSUE THREAD

**Issue by jzbor** [Airblader/i3#331]
## I'm submitting a…

<pre>
[ ] Bug
[x] Feature Request
[ ] Documentation Request
[ ] Other (Please describe in detail)
</pre>

I think a feature that a lot of i3gaps users would appreciate is a "fibonacci" layout like you have in bspwm.

## Current Behavior

The only way to achieve a fibonacci/spiral like layout is to manually layout it or to use some weird and error-prone workarounds.

## Desired Behavior

It would be great having an option to bind a "fibonacci" layout to a key similar to the tabbed, stacked or "regular" layout. I think a way to realize this would be telling each container to use kind of the opposite orientation of its parent.

## Environment

Output of `i3 --moreversion 2>&-`:
<pre>
i3 version: 4.17.1
</pre>

<pre>
- Linux Distribution & Version: Manjaro with Linux 5.4
- Are you using a compositor (e.g., xcompmgr or compton): Currently picom
</pre>

**Comment by Airblader** [comment]
We have discussed this upstream already and rejected it. You can use something like https://github.com/olemartinorg/i3-alternating-layout
