### ISSUE TITLE
i3bar - Transparency doesn't work.

### ISSUE THREAD

**Issue by discapes** [Airblader/i3#333]
## I'm submitting a…

<pre>
[x] Bug
[ ] Feature Request
[ ] Documentation Request
[ ] Other (Please describe in detail)
</pre>

## Current Behavior

The bar background is not transparent when the alpha is set to 00

## Expected Behavior

It should be transparent

## Reproduction Instructions

Try my config.

## Environment

Output of `i3 --moreversion 2>&-`:
<pre>
i3 version: Binary i3 version:  4.17.1-117-gf130dece (2019-12-03, branch "gaps-next") © 2009 Michael Stapelberg and contributors
Running i3 version: 4.17.1-117-gf130dece (2019-12-03, branch "gaps-next") (pid 9350)
Loaded i3 config: /home/miika/.config/i3/config (Last modified: Mon 16 Dec 2019 09:09:02 PM EET, 660 seconds ago)

The i3 binary you just called: /usr/bin/i3
The i3 binary you are running: i3
</pre>

It doesn't work on the latest stable version of i3-gaps either. 

Important part of config:
<pre>
bar {
        colors {
           background #00000000
        }
        font xft:mono:size=12, FontAwesome 12
        status_command i3blocks
}

</pre>

<pre>
- Linux Distribution: Arch Linux
- Are you using a compositor: tryone-compton but it doesn't affect anything
</pre>

<pre>
Screenshot: 
https://user-images.githubusercontent.com/48839377/70940400-e505ef80-2052-11ea-8422-853907f87fc1.png

Full i3 config: 
https://pastebin.com/nt1AtaXG
</pre>

**Comment by Airblader** [comment]
Please read the documentation first. Also, i3bar transparency has since landed upstream in i3:

https://i3wm.org/docs/userguide.html#_transparency

**Comment by discapes** [comment]
Thanks man for the really fast reply! Really appreciate you work. Btw, do you happen to know how I can enable blur behind the i3bar, just like behind the windows in compton?

**Comment by Airblader** [comment]
That is a topic for the compositor. Perhaps it's excluded from the blur for some reason, but I can't say much to that.
