### ISSUE TITLE
1 package for building i3-gaps on debian is currently missing in the wiki

### ISSUE THREAD

**Issue by dataCobra** [Airblader/i3#334]
## I'm submitting a…

<pre>
[ ] Bug
[ ] Feature Request
[X] Documentation Request
[ ] Other (Please describe in detail)
</pre>

Link: https://github.com/Airblader/i3/wiki/Building-from-source#Debian

## Current Behavior
gcc make dh-autoreconf libxcb-keysyms1-dev libpango1.0-dev libxcb-util0-dev xcb libxcb1-dev libxcb-icccm4-dev libyajl-dev libev-dev libxcb-xkb-dev libxcb-cursor-dev libxkbcommon-dev libxcb-xinerama0-dev libxkbcommon-x11-dev libstartup-notification0-dev libxcb-randr0-dev libxcb-xrm0 libxcb-xrm-dev libxcb-shape0

## Expected Behavior
gcc make dh-autoreconf libxcb-keysyms1-dev libpango1.0-dev libxcb-util0-dev xcb libxcb1-dev libxcb-icccm4-dev libyajl-dev libev-dev libxcb-xkb-dev libxcb-cursor-dev libxkbcommon-dev libxcb-xinerama0-dev libxkbcommon-x11-dev libstartup-notification0-dev libxcb-randr0-dev libxcb-xrm0 libxcb-xrm-dev libxcb-shape0 libxcb-shape0-dev

## Reproduction Instructions
Use `configure` without install the package libxcb-shape0-dev before

**Comment by Airblader** [comment]
Thanks, I've updated it!
