### ISSUE TITLE
Using a Vertical and a Horizontal Monitor

### ISSUE THREAD

**Issue by Arszilla** [Airblader/i3#335]
## I'm submitting a…
[ ] Bug
[ ] Feature Request
[ ] Documentation Request
[X ] Other: Dealing with multiple displays; specifically a vertical and a horizontal monitor
</pre>

## Current Behavior
I am trying to setup my workspaces on my dual monitor desktop. Right now, upon login one of my monitors has `Workspace 1` while the other has `Workspace 2`. This limits the amount of (fullscreen) windows I can open in a `Workspace` while being counterproductive.

## Expected Behavior
I am trying to get each workspace to span across both monitors. From there, the workspace should be split into 2 "parts" so that I can spawn/control/manage my windows on each one of my monitors; per their `xrandr` positons and all. This will also double the amount of maximum number of (fullscreen) windows I can have open at once. Basically "merging" the 2 monitors to have 1 workspace, but only to have that workspace split into 2 (per monitor). 

Right now I have a `DVI-D-0` and `HDMI-0`. I load them via:
```
exec --no-startup-id xrandr --output DVI-D-0 --primary --mode 1920x1080 --pos 1080x515 --rotate normal -r 144 --output DP-2 --mode 1920x1080 --pos 0x0 --rotate left -r 60
```
`Workspace 1` usually ends up on `DVI-D-0` while `Workspace 2` is on `HDMI-0`. Instead `Workspace 1` should be on both` HDMI-0` and `DVI-D-0` but the windows on the workspace should be able to transfer between the monitors while being in the same workspace. An example of this is the [following](https://prnt.sc/qt6nm5) image that I've created with an inaccurate polybar config (Please discard the excess space above the polybar. Those are not meant to be there)

## Environment
Output of `i3 --moreversion`:
<pre>
i3 version:  4.17.1
</pre>

<pre>
- Linux Distribution & Version: Manjaro i3 18.1.15
- Are you using a compositor (e.g., xcompmgr or compton): Compton is installed but there is no config present as of now
</pre>

**Comment by Airblader** [comment]
Please use the i3 subreddit (https://www.reddit.com/r/i3wm) for such questions as you'll actually have the community see your question there. :-) 

Just reading it here, however, I have to say I don't really understand what you're trying to achieve. What I can tell you is that independent workspaces per monitor is just how i3 works and this cannot be changed. You could at most use the fake_outputs directive, but this is considered internal and unsupported and you lose all RandR functionality.
