### ISSUE TITLE
Broken title bar and i3status bar

### ISSUE THREAD

**Issue by leo-mao** [Airblader/i3#340]
## I'm submitting a…

<pre>
[x] Bug
[ ] Feature Request
[ ] Documentation Request
[ ] Other (Please describe in detail)
</pre>

## Current Behavior

The title bar and status bar are cropped out to broken undesired like [this](https://imgur.com/a/MKZBC7C)

## Expected Behavior

normal appearancetructions

## Environment

Output of `i3 --moreversion 2>&-`:
<pre>
i3 version: Binary i3 version:  4.18-30-gfac60001 (2020-02-24, branch "gaps-next") © 2009 Michael Stapelberg and contributors
Running i3 version: 4.18-30-gfac60001 (2020-02-24, branch "gaps-next") (pid 759)
Loaded i3 config: /home/Mao/.config/i3/config (Last modified: Tue 03 Mar 2020 03:12:33 PM CET, 218 seconds ago)

The i3 binary you just called: /usr/bin/i3
The i3 binary you are running: i3

</pre>

<pre>
</pre>

<pre>
Logfile URL:
</pre>

<pre>
- Linux Distribution & Version:Linux iParadox.dev 5.5.6-arch1-1 #1 SMP PREEMPT Mon, 24 Feb 2020 12:20:16 +0000 x86_64 GNU/Linux

- Are you using a compositor (e.g., xcompmgr or compton):no
</pre>

**Comment by Airblader** [comment]
Can you reproduce this on normal i3?

**Comment by leo-mao** [comment]
let me have a try

**Comment by leo-mao** [comment]
![screenshot](https://user-images.githubusercontent.com/5745570/75785190-9f101c00-5d63-11ea-8245-b9b2e881db22.png)
![screenshot](https://user-images.githubusercontent.com/5745570/75785212-a8998400-5d63-11ea-9d8e-caf529149646.png)
I think so,  the errors here are due to the new options for i3-gaps-next

**Comment by Airblader** [comment]
In that case I'll close here. Can you please reopen over at i3/i3?

My guess is that the font config is somehow broken. You may want to try a different font, maybe also one without pango, to see what might make it work again. Just a guess, of course.

**Comment by leo-mao** [comment]
Bro, your intuition is unbelievably precise! It works after change the font setting to `font -misc-fixed-medium-r-normal--13-120-75-75-C-70-iso10646-1` . A lot thanks

**Comment by leo-mao** [comment]
Should reopen it and close in i3 thread though?

**Comment by Airblader** [comment]
If it's fixed then no reason to open anything :-)
