### ISSUE TITLE
cursor teleporting when moving across monitors with last focused floating off screen

### ISSUE THREAD

**Issue by C34A** [Airblader/i3#341]
## I'm submitting a…

<pre>
[x] Bug
[ ] Feature Request
[ ] Documentation Request
[ ] Other (Please describe in detail)
</pre>

## Current Behavior

If i open something on my right display, switch it to floating mode, and move it partially (at least halfway?) vertically off of the screen moving the cursor to the left display then back to the right one will teleport my cursor to the center of the floating window. If the half-occluded floating window is not the last window focused this doesn't seem to happen.

## Expected Behavior

The cursor should move across smoothly, maintaining vertical position.

## Reproduction Instructions

1. open a window on one display.
2. make it a floating window.
3. move it so it is halfway occluded off the screen vertically.
4. move the cursor across to another display without focusing any other windows.
5. move the cursor back to the previous display, anywhere.

## Environment

Output of `i3 --moreversion 2>&-`:
<pre>
i3 version: 
</pre>
Binary i3 version:  4.18 (2020-02-18) © 2009 Michael Stapelberg and contributors
Running i3 version: 4.18 (2020-02-18) (pid 512)to abort…)
Loaded i3 config: /home/theo/.config/i3/config (Last modified: Wed 04 Mar 2020 08:52:03 PM UTC, 5104 seconds ago)

The i3 binary you just called: /usr/bin/i3
The i3 binary you are running: i3

<pre>
Config:
</pre>
https://controlc.com/b62e45d2

<pre>
Logfile URL: https://logs.i3wm.org/logs/5713841375674368.bz2
Sorry if I did the logging wrong, I am still new to this kind of thing :)
</pre>

<pre>
- Linux Distribution & Version: Arch Linux 2020.02.01
- Are you using a compositor (e.g., xcompmgr or compton): Yes, Picom (compton).
</pre>

**Comment by Airblader** [comment]
Closing since this is not specific to i3-gaps. Please open this upstream at i3. But first please read https://i3wm.org/docs/userguide.html#_mouse_warping. If disabling this doesn't help or you believe it to be an issue in the logic of that feature feel free to open the issue.
