### ISSUE TITLE
sorting named workspaces + numbered workspaces after named workspaces

### ISSUE THREAD

**Issue by rsgowman** [Airblader/i3#343]
## I'm submitting a…

<pre>
[ ] Bug
[x] Feature Request
[ ] Documentation Request
[ ] Other (Please describe in detail)
</pre>

## Current Behavior

Named workspaces are sorted by oldest to newest within i3bar.
Numbered workspaces cannot be placed after named workspaces.

## Desired Behavior

Named workspaces are sorted alphabetically.
Numbered workspaces can be placed after named workspaces.

## Environment

Output of `i3 --moreversion 2>&-`:
<pre>
i3 version: 
Binary i3 version:  4.18-30-gfac60001 (2020-02-24, branch "gaps-next") © 2009 Michael Stapelberg and contributors
Running i3 version: 4.18-30-gfac60001 (2020-02-24, branch "gaps-next") (pid 23948)
Loaded i3 config: /home/rich/.config/i3/config (Last modified: Fri 20 Mar 2020 10:59:36 PM EDT, 4010 seconds ago)

The i3 binary you just called: /home/rich/opt/i3-gaps/bin/i3
The i3 binary you are running: /home/rich/opt/i3-gaps/bin/i3

</pre>

<pre>
- Linux Distribution & Version: ubuntu 18.04lts
- Are you using a compositor (e.g., xcompmgr or compton): compton
</pre>

## More Context:

I've recently started using i3, and my workflow generally revolves around a few fixed workspaces (i.e. '1: mail', '2: calendar', '10: music') and then some additional named workspaces that I create dynamically (i3-msg workspace NameOfFeatureImCurrentlyImplementing). But it's bothered me that the named workspaces aren't ordered alphabetically. Unreasonably so. (I suppose I could name my new workspace with a number prefix, but then I'd have to figure out the sort order manually.)

Additionally, I wanted a way to keep my music workspace to the right of all the rest.

Basically, this:

```
$ git diff
diff --git a/src/con.c b/src/con.c
index a17e75ea..09d3e058 100644
--- a/src/con.c
+++ b/src/con.c
@@ -107,7 +107,7 @@ static void _con_attach(Con *con, Con *parent, Con *previous, bool ignore_focus)
      * right position. */
     if (con->type == CT_WORKSPACE) {
         DLOG("it's a workspace. num = %d\n", con->num);
-        if (con->num == -1 || TAILQ_EMPTY(nodes_head)) {
+        if (TAILQ_EMPTY(nodes_head)) {
             TAILQ_INSERT_TAIL(nodes_head, con, nodes);
         } else {
             current = TAILQ_FIRST(nodes_head);
@@ -115,7 +115,8 @@ static void _con_attach(Con *con, Con *parent, Con *previous, bool ignore_focus)
                 /* we need to insert the container at the beginning */
                 TAILQ_INSERT_HEAD(nodes_head, con, nodes);
             } else {
-                while (current->num != -1 && con->num > current->num) {
+                while (con->num > current->num ||
+                        (current->num == con->num && strcmp(current->name, con->name) <= 0)) {
                     current = TAILQ_NEXT(current, nodes);
                     if (current == TAILQ_END(nodes_head)) {
                         current = NULL;
diff --git a/src/util.c b/src/util.c
index 3544297c..e3b9ca3f 100644
--- a/src/util.c
+++ b/src/util.c
@@ -115,7 +115,7 @@ int ws_name_to_number(const char *name) {
     errno = 0;
     long long parsed_num = strtoll(name, &endptr, 10);
     if (errno != 0 || parsed_num > INT32_MAX || parsed_num < 0 || endptr == name) {
-        parsed_num = -1;
+        parsed_num = 1000;  // hack... but it gets the job done.
     }
 
     return parsed_num;
```

With the above, I can rename my music workspace to '1001: music' and everything works the way I'd like. Is there any appetite to upstream either of these two features?

As implemented here, even I'm not wild about the 'numbered-workspace-to-the-right-of-named-workspaces' as that raw `1000` sure is ugly. Though I suppose it could be migrated to a configuration variable. But the sorting thing seems like it could be more generally useful almost as is, if protected behind a conf flag.

Standard caveats apply: I haven't really tested this much. (This is a FR, not a PR.)

**Comment by Airblader** [comment]
Thanks for opening the issue. Before I go into the details: I'll close this as this is not specific to i3-gaps and i3-gaps isn't currently looking to add more features or deviations from upstream. Thanks for understanding! 

---

> Named workspaces are sorted by oldest to newest within i3bar.
> Named workspaces are sorted alphabetically.

That would be a change in long-standing i3 behavior, so it can only even be consdiered if there is some very convincing argument in favor of it usability-wise. We cannot and will not change it out of preference as the tens of thousands of users have different preferences. Note that if the situation was reversed, the very same argument would hold – it's not so much about what my preference is, but simply about preserving behavior and only changing it for really good reasons.

It's also not big enough of an issue to warrant the complexity of additional configuration, particularly because you can achieve custom ordering by using numbered workspaces. If you don't want to see the numbers, you can use `strip_workspace_numbers` for i3bar.

> Numbered workspaces cannot be placed after named workspaces.
> Numbered workspaces can be placed after named workspaces.

Essentially the same as above; if you want control over the order, use numbered workspaces throughout.

**Comment by rsgowman** [comment]
> because you can achieve custom ordering by using numbered workspaces. 

To be clear, you can't achieve the same, or at least, *I* can't. I use `strip_workspace_numbers` (as you suggest) which means I don't know what the numbers are on my custom workspaces, and there's no way I'd be able to remember that (eg) I assigned workspace `aaa` as number `111`. (As it happens, this is exactly the approach I took before discovering that it was unworkable; at least for me. I also tried leaving `strip_workspace_numbers` off, only to discover that, well, lets just say that computers are better at sorting than I am.)

But regardless, I figured the odds of being able to upstream this was... limited. :)

Thanks for the project!

**Comment by Airblader** [comment]
You can write a script that is smart enough to do it. A script that inserts a workspace C between A and B finds their numbers and figures out a number between them and then does it. Worst case it needs to rename a bunch of workspaces to "make room".

**Comment by rsgowman** [comment]
Yeah, I guess I could do that. (Pretty good idea, really. Had I thought of that, I might've tried that route first.) But that seems more complicated than just patching the source, especially due to to the reshuffling. And since the patch for both "features" is only 3 lines... well, I think I know which path I'm going to take. :)

**Comment by Airblader** [comment]
Running a local patch is obviously also fine. Patching it upstream requires a bit more care. ;-)
