### ISSUE TITLE
no_focus directive is not respected for KDE notifications

### ISSUE THREAD

**Issue by matejdro** [Airblader/i3#344]
## I'm submitting a…

<pre>
[x] Bug
[ ] Feature Request
[ ] Documentation Request
[ ] Other (Please describe in detail)
</pre>

## Current Behavior
Mouse jumps to the notification when it opens on another screen.

## Expected Behavior
Focus should not change since notification is under `no_focus` directive

## Reproduction Instructions
1. Have two monitors
2. Use KDE Plasma as default display manager
3. Install `i3-gaps`
4. Replace KDE WM with i3 by appending `export KDEWM=/usr/bin/i3` to `~/.config/plasma-workspace/env`
5. Add `no_focus [class="plasmashell"]` to the bottom of i3 config
6. Restart/relog to apply all settings
7. Open https://www.bennish.net/web-notifications.html in Firefox on non-primary monitor
8. Press Show button couple of times
9. Eventually notifications will start to pop up on another monitor and mouse will jump to the notification. 

## Environment
Output of `i3 --moreversion 2>&-`:
<pre>
Binary i3 version:  4.18 (2020-02-18) © 2009 Michael Stapelberg and contributors
Running i3 version: 4.18 (2020-02-18) (pid 11227) abort…)
Loaded i3 config: /home/matej/.config/i3/config (Last modified: sob 21 mar 2020 07:51:35, 242 seconds ago)

The i3 binary you just called: /usr/bin/i3
The i3 binary you are running: i3
</pre>

Config is default, except for above mentioned `no_focus` line. It even happens with `no_focus [class=".*"]` which, to my understanding, is supposed to block focus stealing for every window.

Logs of me opening Firefox and pressing the notification button (mouse jumps to the notification): 
[i3.log](https://github.com/Airblader/i3/files/4362556/i3.log)

<pre>
- Linux Distribution & Version: Linux komp 5.5.8-1-MANJARO #1 SMP PREEMPT Thu Mar 5 20:29:51 UTC 2020 x86_64 GNU/Linux
- Are you using a compositor (e.g., xcompmgr or compton): No
</pre>

Output of xprop for the notification window:

```
WM_STATE(WM_STATE):
                window state: Normal
                icon window: 0x0
I3_FLOATING_WINDOW(CARDINAL) = 1
_NET_WM_USER_TIME(CARDINAL) = 2593173
_KDE_NET_WM_SHADOW(CARDINAL) = 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
_KDE_NET_WM_BACKGROUND_CONTRAST_REGION(_KDE_NET_WM_BACKGROUND_CONTRAST_REGION0, 0x5d, 0x1, 0x5e, 0x14e, 0x1, 0x3dfe2535, 0xbc430fb5, 0xbc430fb5, 0x0, 0xbdb847cd3, 0xbb847cd3, 0x3e071faf, 0x0, 0x3e23d70b, 0x3e23d70b, 0x3e23d70b, 0x3
_KDE_NET_WM_BLUR_BEHIND_REGION(CARDINAL) = 1, 0, 334, 1, 0, 1, 336, 93, 1, 94
_NET_WM_DESKTOP(CARDINAL) = 4294967295
_NET_WM_STATE(ATOM) = _NET_WM_STATE_SKIP_TASKBAR, _NET_WM_STATE_SKIP_PAGER
_KDE_NET_WM_DESKTOP_FILE(UTF8_STRING) = "org.kde.plasmashell"
XdndAware(ATOM) = BITMAP
WM_NAME(STRING) = 
_NET_WM_NAME(UTF8_STRING) = "Plasma"
_MOTIF_WM_HINTS(_MOTIF_WM_HINTS) = 0x2, 0x1, 0x0, 0x0, 0x0
_NET_WM_WINDOW_TYPE(ATOM) = _NET_WM_WINDOW_TYPE_NOTIFICATION, _KDE_NET_WM_WINORMAL
_XEMBED_INFO(_XEMBED_INFO) = 0x0, 0x1
WM_CLIENT_LEADER(WINDOW): window id # 0x2800015
WM_HINTS(WM_HINTS):
                Client accepts input or input focus: False
                window id # of group leader: 0x2800015
WM_CLIENT_MACHINE(STRING) = "komp"
_NET_WM_PID(CARDINAL) = 12815
_NET_WM_SYNC_REQUEST_COUNTER(CARDINAL) = 41943305
WM_CLASS(STRING) = "plasmashell", "plasmashell"
WM_PROTOCOLS(ATOM): protocols  WM_DELETE_WINDOW, WM_TAKE_FOCUS, _NET_WM_PING,
WM_NORMAL_HINTS(WM_SIZE_HINTS):
                user specified location: 3148, 1124
                user specified size: 336 by 95
                window gravity: Static
```

**Comment by Airblader** [comment]
Thanks for the detailed report! I will close this issue here since this is not specific to i3-gaps, so please feel free to reopen it upstream at i3. :-)

From a quick look at the file, no_focus works correctly:

> 21. 03. 2020 08:25:35 - manage.c:manage_window:626 - no_focus was set for con = 0x556a015b27f0, not setting focus.

The focus is actually set slightly later on for different reasons (which I have not yet traced back):

> 21. 03. 2020 08:25:35 - workspace.c:workspace_show:529 - old = 0x556a01593b00 / 1
> 21. 03. 2020 08:25:35 - focused now = 0x556a015b27f0 / (null)

Note that no_focus only works upon managing a window, it does not prevent the window from being focused through other means. Since this notification is not override redirect, it is actually managed which means to i3 it is a normal window and my guess is that the window is focused when switching to that workspace. But like I said, feel free to reopen upstream for investigation.

**Comment by matejdro** [comment]
Thanks for your answer. Will reopen.
