### ISSUE TITLE
Can't configure gaps from config file

### ISSUE THREAD

**Issue by kamou** [Airblader/i3#345]
## I'm submitting a…

<pre>
[x] Bug
[ ] Feature Request
[ ] Documentation Request
[ ] Other (Please describe in detail)
</pre>

## Current Behavior

when I try setting gaps in my config file I get this error:
```
ERROR: CONFIG: Expected one of these tokens: <number>                               
ERROR: CONFIG: (in file /home/ak42/.config/i3/config)
ERROR: CONFIG: Line 216: exec --no-startup-id /home/ak42/Downloads/Telegram/Telegram
ERROR: CONFIG: Line 217: 
ERROR: CONFIG: Line 218: gaps inner all set 10
ERROR: CONFIG:                      ^^^^^^^^^^
```
But when I use `i3-msg` everything works fine:
```
i3-msg gaps inner all set 10
```

## Expected Behavior
obviously the expected behaviour is that the parsing of `gaps inner all set 10` does not fail and sets the correct gaps configuration

## Reproduction Instructions
just put `gaps inner all set 10` in the end of the config file and restart i3

## Environment

Output of `i3 --moreversion 2>&-`:
<pre>
Binary i3 version:  4.17.1 (2019-08-30) © 2009 Michael Stapelberg and contributors
Running i3 version: 4.17.1 (2019-08-30) (pid 15908)bort…)
Loaded i3 config: /home/ak42/.config/i3/config (Last modified: Mon 23 Mar 2020 01:43:48 PM CET, 300 seconds ago)

The i3 binary you just called: /usr/bin/i3
The i3 binary you are running: i3-with-/i3
</pre>

<pre>
</pre>

<pre>
Logfile URL: https://logs.i3wm.org/logs/5641267635552256.bz2
</pre>

<pre>
- Linux Distribution & Version: Fedora 30
- Are you using a compositor (e.g., xcompmgr or compton): no
</pre>

**Comment by kamou** [comment]
FYI, I'm using copr

**Comment by kamou** [comment]
same behaviour with gaps-next:
```
Binary i3 version:  4.18-30-gfac60001 (2020-02-24, branch "gaps-next") © 2009 Michael Stapelberg and contributors
Running i3 version: 4.18-30-gfac60001 (2020-02-24, branch "gaps-next") (pid 3558)
Loaded i3 config: /home/ak42/.config/i3/config (Last modified: Mon 23 Mar 2020 01:43:48 PM CET, 888 seconds ago)

The i3 binary you just called: /usr/bin/i3
The i3 binary you are running: i3-with-/i3

```

**Comment by Airblader** [comment]
```
gaps inner all set 10
```

is not a valid config directive and that is what the error is telling you. Please read https://github.com/Airblader/i3/blob/gaps-next/README.md#configuration to see how to configure gaps from the config.

**Comment by kamou** [comment]
oh ok thanks !
I always thought i3-msg commands were exactly the same as config directives...
