### ISSUE TITLE
 i3 window draw over the compositer shadow

### ISSUE THREAD

**Issue by sucrecacao** [Airblader/i3#346]
## I'm submitting a…

<pre>
[] Bug
[] Feature Request
[ ] Documentation Request
[X] Other (Please describe in detail)
I don't believe it's really a bug, maybe just a question about the i3 implementation.
</pre>

## Current Behavior
When using a compositer like picom, the shadow doesn't display properly all around the current window, but only on 1 or 2 borders. See pictures : the blue shadow only display on one border of the terminal window. When the top left terminal is focused, it doesn't render any shadow.
![topmid](https://user-images.githubusercontent.com/55893070/78508464-619a1680-7787-11ea-994f-90e380a09f61.png)
![midmid](https://user-images.githubusercontent.com/55893070/78508466-62cb4380-7787-11ea-8736-b2ea1611d9e7.png)
![topleft](https://user-images.githubusercontent.com/55893070/78508465-62cb4380-7787-11ea-97d8-2d0739e13773.png)

## Desired Behavior
The shadow should display all arround the focused window, like this floating window:
![float](https://user-images.githubusercontent.com/55893070/78508550-ed13a780-7787-11ea-9cea-b06850411e69.png)
Or like the bottom right window:
![bot_right](https://user-images.githubusercontent.com/55893070/78508589-4e3b7b00-7788-11ea-8dad-362192e48c49.png)

## Environment

Output of `i3 --moreversion 2>&-`:
<pre>
i3 version: i3-gaps 4.17.1-1ubuntu1~ppa5
</pre>

<pre>
- Linux Distribution & Version: ubuntu 19
- Are you using a compositor (e.g., xcompmgr or compton): picom
</pre>

## Other
I believe this is related to i3 drawing window in a specific order ( from top left to bottom right ). The window  at the right and at the bottom of the current focused window will draw over the focused window shadow because they are rendered after the current focused window. 

If my assumption is correct, would making the focused window render last solve the bug ? And where should I look in the code to modify it ?

**Comment by Airblader** [comment]
Thanks for opening this issue. This is indeed a consequence of the i3 rendering process and the stacking order, see duplicate issue https://github.com/i3/i3/issues/3676. You can patch this locally but at this time I am not looking to make further changes to i3-gaps. Leaving this open for visibility.

**Comment by Airblader** [comment]
I'm closing this issue has i3-gaps is being migrated into i3. If this issue still applies, please reopen it in i3.
