### ISSUE TITLE
Add INSTALL.md with explanation for building from source

### ISSUE THREAD

**Issue by dataCobra** [Airblader/i3#349]
## I'm submitting a…

<pre>
[ ] Bug
[x] Feature Request
[ ] Documentation Request
[ ] Other (Please describe in detail)
</pre>

## Current Behavior
Every time I build i3-gaps from source. I need to check in the repository wiki for the steps.

## Desired Behavior
It would be great to have a INSTALL file in the repository that explains the build from source. Then all that is needed is a terminal for building and information about building. This would make life much easier.

**Comment by Airblader** [comment]
Hi,

this is semi-intentionally not done, please see https://github.com/Airblader/i3/wiki/Building-from-source where you can also find the instructions right now if you really want to go this route.
