### ISSUE TITLE
Window titel disbehaves when either gaps !=0

### ISSUE THREAD

**Issue by bvolkmer** [Airblader/i3#35]
Hey,
I just tried this fork for the fist time via AUR.
When I activate gaps, the window titles (most times) dissappear and leave some garbage on top where the gap should be. (Pictures above).
Sometimes it appears but with a gap between title and window.
It just appears if either inner or outer is set to a value != 0, so it isn't a general bug as I think.
It also appears in both gaps and gaps-next branches.
For floating windows it is always working as it should.

With `inner 10` and `outer 5`:
![Imgur](http://i.imgur.com/iSRTVWn.png)
With `inner 0` and `outer 5`:
![Imgur](http://i.imgur.com/2zJHFS4.png)
With `inner 10` and `outer 5`:
![Imgur](http://i.imgur.com/THW8jZK.png)
And finally with `inner 0` and `outer 0`
![Imgur](http://i.imgur.com/THW8jZK.png)
I made the backgound red, to see what is bg and what is garbage.
`new_window` and `new_float` is always set to `normal`
For `none` or `pixel` it is also working as it should.

**Comment by Airblader** [comment]
This is a known issue with the way the gaps work. Unfortunately there's no fix for it, you simply have to choose between window titles and gaps. You can disable window titles via

```
for_window [class="^.*"] border pixel 0
```

i3 just implements window titles in a pretty unusual way. It might, in theory, be fixable, but not without changing the way i3 sets up windows, which is a major change which 1) I probably could not do and 2) would make it close to impossible to merge upstream changes into the fork and maintain it.

Here's a description if you want to read about it: https://github.com/chjj/compton/wiki/faq#3-why-does-transparency-not-work-correctly-in-i3

**Comment by bvolkmer** [comment]
Ah.. Ok. A hint for this in README would be helpfull, though.

**Comment by Airblader** [comment]
Yes, that's probably a good idea. I'll add a warning about this in the README.

Edit: I've added it.
