### ISSUE TITLE
Error in documentation installation from source Debian

### ISSUE THREAD

**Issue by noopduck** [Airblader/i3#351]
## I'm submitting a…

<pre>
[] Bug
[ ] Feature Request
[x ] Documentation Request
[ ] Other (Please describe in detail)
</pre>

## Current Behavior

https://github.com/Airblader/i3/wiki/Building-from-source
Debian

gcc make dh-autoreconf libxcb.......

## Expected Behavior

apt install dh-autoreconf libxcb.......

## Reproduction Instructions

Look inside: https://github.com/Airblader/i3/wiki/Building-from-source

## Environment

Output of `i3 --moreversion 2>&-`:
<pre>
i3 version: i3 version 4.18.1-146
</pre>

<details><summary>Config file</summary><pre>
</pre>
</details>

<pre>
Logfile URL:
</pre>

<pre>
- Linux Distribution & Version:
- Are you using a compositor (e.g., xcompmgr or compton):
</pre>

**Comment by Airblader** [comment]
Thanks, I've changed it!
