### ISSUE TITLE
No i3 option to choose from on login screen after migrating from i3-wm to i3-gaps-wm (Ubuntu 18.04).

### ISSUE THREAD

**Issue by alcanie1** [Airblader/i3#353]
## I'm submitting a…

<pre>
[x] Bug
[ ] Feature Request
[ ] Documentation Request
[ ] Other (Please describe in detail)
</pre>

## Current Behavior
Clicking on the gear bellow the password input rectangle at the logging screen does not show an option to chose i3 or i3 (with debug log).
 
## Expected Behavior
When logging in you should be able to pick "i3" or "i3 (with debug log)" by clicking on the gear icon. After this and entering your password, you should be logged in with i3 running.

## Reproduction Instructions
Originally, I had i3-wm (`sudo apt install i3`) installed from the apt package manager and everything was working fine. I decided I wanted gaps so I ran the following commands to install i3-gaps-wm:
```
sudo add-apt-repository ppa:kgilmer/speed-ricer
sudo apt update
sudo apt install i3-gaps-wm
```
**Note:** _Running that last command removes the previously installed i3-wm installed from apt._
## Environment
```
Output of `i3 --moreversion 2>&-`:
Binary i3 version:  4.17.1 (2019-08-30) © 2009 Michael Stapelberg and contributors
Running i3 version: 4.17.1 (2019-08-30) (pid 1613)abort…)
Loaded i3 config: /home/javier/.config/i3/config (Last modified: Sat 16 May 2020 06:24:59 PM AST, 9559 seconds ago)

The i3 binary you just called: /usr/bin/i3
The i3 binary you are running: i3
```
<pre>
i3 version: 4.17.1
</pre>

<pre>
- Linux Distribution & Version: Ubuntu 18.04
- Compositor: compton
</pre>

## Fix/Solution
Create a backup of your ~/.config/i3 directory just in case, although nothing bad should happen. 
Remove i3 `sudo apt purge i3`, then run the following commands:
``` 
sudo add-apt-repository ppa:kgilmer/speed-ricer
sudo apt update
sudo apt install i3-gaps-wm
```
Create a file named _i3.desktop_ with the following content:
```
[Desktop Entry]
Name=i3
Comment=improved dynamic tiling window manager
Exec=i3
TryExec=i3
Type=Application
X-LightDM-DesktopName=i3
DesktopNames=i3
Keywords=tiling;wm;windowmanager;window;manager;

```
Create another file named _i3-with-shmlog.desktop_ with the following content:
```
[Desktop Entry]
Name=i3 (with debug log)
Comment=improved dynamic tiling window manager
Exec=i3-with-shmlog
Type=Application
Keywords=tiling;wm;windowmanager;window;manager;

```
Move both files to _/usr/share/xsessions/_ , then reboot.

**Comment by Airblader** [comment]
i3-gaps does not contain any changes regarding the desktop files from i3, so this is most likely an issue with the packaging process used by that PPA. Please contact the author of the PPA. Thanks!
