### ISSUE TITLE
Fedora copr Repo Out Of Date

### ISSUE THREAD

**Issue by seniorm0ment** [Airblader/i3#354]
## I'm submitting a…

<pre>
[] Bug
[ ] Feature Request
[ ] Documentation Request
[x ] Other 
</pre>

The Fedora `copr` repo is 5 months out of date as informed by someone in a group chat, ~~I have not confirmed myself~~ *(see edit)*, but upon looking up issues in this git in the past looks like the Fedora maintainer doesn't keep up so this is most likely accurate. 

Edit: https://copr.fedorainfracloud.org/coprs/gregw/i3desktop/builds/

**Comment by Airblader** [comment]
Thanks for letting me know! I've removed that entry now. If there's a different one I can add instead do let me know and I'll add that.
