### ISSUE TITLE
"You have an error in your i3 config file" even after changing to backup config

### ISSUE THREAD

**Issue by majorgamerjay** [Airblader/i3#356]
## I'm submitting a…

<pre>
[x] Bug
[ ] Feature Request
[ ] Documentation Request
[ ] Other (Please describe in detail)
</pre>

## Current Behavior

After installing polybar and then restarting i3 (MOD-SHIFT-R), it shows on the top, "You have an error in your i3 config file!" even though I did not change anything in config file after installing polybar. It also does not have any gaps. Uninstalled polybar and it still shows the same error and switched to backup config and it still shows the same error.

## Expected Behavior

Don't show errors and show gaps

## Reproduction Instructions

Set gaps on and then install polybar. Restart i3-gaps with MOD-SHIFT-R, then it will show the error and you will see no more gaps.

## Environment

Output of `i3 --moreversion 2>&-`:
Binary i3 version:  4.17.1 (2019-08-30) © 2009 Michael Stapelberg and contributors
Running i3 version: 4.17.1 (2019-08-30) (pid 2134)abort…)
Loaded i3 config: /home/majorgamerjay/.config/i3/config (Last modified: Fri 12 Jun 2020 01:05:06 AM +06, 736205 seconds ago)

The i3 binary you just called: /usr/bin/i3
The i3 binary you are running: i3

<pre>
i3 version: 4.17.1
</pre>

<details><summary>Config file</summary><pre>
Here is the PasteBin link: [Pastebin](https://pastebin.com/zhrSrNg4l)
</pre>
</details>

<pre>
Logfile URL: https://pastebin.com/EJ6keEii
</pre>

<pre>
- Linux Distribution & Version: Pop_OS 20.04
- Are you using a compositor (e.g., xcompmgr or compton): Showed error restarting i3 when both turning on compton and after turning off compton.
</pre>

**Comment by Airblader** [comment]
My guess is that your package manager removed i3-gaps when installing polybar and replaced it with normal i3. You can verify this and also try reinstalling i3-gaps.

**Comment by Airblader** [comment]
I'm closing for now. Let me know if it persists once you have verified you have i3-gaps installed rather than i3.

**Comment by jsamr** [comment]
Same error on brand new archlinux install. I checked that i3-gaps was installed with `pacman -Qi i3-gaps`. I just copy-pasted the following line from your readme in my config:

```
gaps inner all set 20
```

**Comment by Airblader** [comment]
That's a command, not a config directive.

**Comment by jsamr** [comment]
@Airblader Of course! Sorry about that.
