### ISSUE TITLE
i3bar - Transparency gives black background

### ISSUE THREAD

**Issue by DakshKK** [Airblader/i3#357]
## I'm submitting a…

<pre>
[x] Bug
[ ] Feature Request
[ ] Documentation Request
[ ] Other (Please describe in detail)
</pre>

## Current Behavior

Bar background becomes black when alpha is set to 00.

## Expected Behavior

According to documentation bar should become transparent.

## Reproduction Instructions

Can attach my config if required

## Environment

Output of `i3 --moreversion 2>&-`:
<pre>
i3 version: Binary i3 version:  4.17.1 (2019-08-30) © 2009 Michael Stapelberg and contributors
Running i3 version: 4.17.1 (2019-08-30) (pid 1823)abort…)
Loaded i3 config: /home/dakksh/.config/i3/config (Last modified: Saturday 20 June 2020 05:28:17 PM, 203 seconds ago)

The i3 binary you just called: /usr/bin/i3
The i3 binary you are running: i3
</pre>

Important part of config
<details><summary>Bar config</summary><pre>
bar {
	i3bar_command i3bar --transparency
	colors {
		background #00000000
		statusline #ffffff
		separator  #11cc99
		#Type              border  bg      font
		focused_workspace  #88ff99 #9d0434 #ffffff
		active_workspace   #333333 #5f676a #ffffff
		inactive_workspace #22aa99 #222222 #888888
		urgent_workspace   #aa0000 #990000 #ffffff
	}
	position bottom
	status_command i3status
	font pango:Quintessential 14
	separator_symbol "#"
	modifier Mod1+Mod4
	strip_workspace_numbers yes
}
</pre>
</details>

<pre>
- Linux Distribution & Version: Ubuntu 20.04
- Are you using a compositor (e.g., xcompmgr or compton): No
</pre>

<pre>
Screenshot:
https://user-images.githubusercontent.com/54723155/85201548-f986b580-b31d-11ea-85dc-05db981d9562.png

Config:
https://termbin.com/7pui
</pre>

**Comment by Airblader** [comment]
> - Are you using a compositor (e.g., xcompmgr or compton): No

Transparency requires a compositor. Let me know if it doesn't work once you have one running.

**Comment by DakshKK** [comment]
> Transparency requires a compositor. Let me know if it doesn't work once you have one running.

I am running compton, and even now my background is coming black.

**Comment by Airblader** [comment]
Just to be sure, your compositor is set up correctly, can you get something like window transparency with compton to work?

**Comment by DakshKK** [comment]
I am able to get my window transparency to work, with the opacity_rule, but when application name is i3bar, and i3bar_command has the transparency flag set, it doesn't always be transparent.

Sometimes I have to reload the wm multiple times before it shows any transparency.

Can transparency be achieved without a compositor? If not in i3, what about i3-gaps?

**Comment by Airblader** [comment]
> Can transparency be achieved without a compositor?

No, it cannot.

> If not in i3, what about i3-gaps?

I read this as »I'm not currently using i3-gaps«, which confuses me given that you opened this issue against i3-gaps?

I also just verified on my machine that on latest i3-gaps i3bar transparency works. Please make sure what it is you have installed and do so using the latest version (4.18.1).

**Comment by DakshKK** [comment]
That's my mistake. I opened the issue in the wrong place, I should've checked before posting the issue.

And afte checking, well, the latest version in the repo that I am getting is 4.17.1. Will build from source and install the latest version at earliest possible, and try it out.

But again, with compton, I am able to achieve terminal/window transparency perfectly, but my i3bar transparency does not always work.

**Comment by numToStr** [comment]
I am also facing this issue in Polybar. Compton is already running. I am running Manjaro i3 edition.

**Comment by Airblader** [comment]
@numToStr  Polybar is a completely different application.
