### ISSUE TITLE
debian install i3wm-gaps

### ISSUE THREAD

**Issue by yanglei802** [Airblader/i3#359]
how can i install i3wm-gaps in debian

**Comment by Airblader** [comment]
https://github.com/Airblader/i3/wiki/Installation

This lists all packages known to me. If Debian is not there it means no package exists (in this case please ping the packagers of your distribution) or no one has reported that it exists and what it is called (if you find it, please do so).

Packaging for distribution is something the people of the corresponding distributions have to do, I only provide the software.
