### ISSUE TITLE
Gaps cause i3 to draw memory content on the background.

### ISSUE THREAD

**Issue by crocket** [Airblader/i3#366]
## Current Behavior

![2020-08-24_Mon_23:36:26](https://user-images.githubusercontent.com/748856/91110358-9405cb00-e6b8-11ea-9b6e-3df240b32c5d.png)

![2020-08-24_Mon_23:36:30](https://user-images.githubusercontent.com/748856/91110361-9700bb80-e6b8-11ea-99eb-94968a4bfd77.png)

![2020-08-24_Mon_23:36:34](https://user-images.githubusercontent.com/748856/91110365-99631580-e6b8-11ea-9fda-dcab6df02c0b.png)

## Expected Behavior

There should be no weird tearing in the background.

## Reproduction Instructions

Enter tabbed layout, and enter a default layout.

## Environment

<pre>
i3 version: Binary i3 version:  4.18.1 (2020-04-23) © 2009 Michael Stapelberg and contributors
Running i3 version: 4.18.1 (2020-04-23) (pid 9035)abort…)
Loaded i3 config: /home/guardian/.config/i3/config (Last modified: Tue 25 Aug 2020 08:27:28 AM KST, 5265 seconds ago)

The i3 binary you just called: /usr/bin/i3
The i3 binary you are running: /usr/bin/i3
</pre>

<details><summary>Config file</summary>
Add the following lines to the default config
<pre>
gaps inner 15
gaps outer 3
smart_gaps on
</pre>
</details>

<pre>
- Linux Distribution & Version: Gentoo
- Are you using a compositor: the issue occurs with or without picom.
</pre>

**Comment by Airblader** [comment]
This is why the README says that title bars need to be disabled when using gaps. It's a known problem and a won't fix because of how i3 renders decorations.

**Comment by crocket** [comment]
I will remember to read README next time.

**Comment by crocket** [comment]
Does that mean it is not wise to use tabbed layout with gaps? Tabbed layout forces title bars.
