### ISSUE TITLE
Targeted mouse warping

### ISSUE THREAD

**Issue by raphaelreyna** [Airblader/i3#367]
## I'm submitting a…

<pre>
[ ] Bug
[x] Feature Request
[ ] Documentation Request
[ ] Other (Please describe in detail)
</pre>

## Current Behavior

When warping, the mouse currently warps right into the center of the window, this can be very distracting.

## Desired Behavior

Users should be able to provide a desired target within the container for the mouse to warp to.
Example config:
```
targeted_warping x_position 0
targeted_warping y_position 100
```
With this snippet in the config file, the mouse will warp to the bottom left corner of the container rather than to the center.

## Environment

Output of `i3 --moreversion 2>&-`:
<pre>
i3 version: 4.18.2-229-g234d6855+
</pre>

<pre>
- Linux Distribution & Version: Ubuntu 20.04
- Are you using a compositor (e.g., xcompmgr or compton): compton
</pre>

**Comment by raphaelreyna** [comment]
I've already implemented this in my own fork: [i3 - targeted warping](https://github.com/raphaelreyna/i3/tree/targeted-warping).

The docs make it sound like new features should be brought up as an issue first before submitting the pull-request but it's ready to go should anyone want to review it; thanks.

**Comment by Airblader** [comment]
Thanks for the feature request. In i3-gaps I'm not currently looking to add more features, hence I'll be closing this.

> The docs make it sound like new features should be brought up as an issue first

Indeed, but actually against upstream vanilla (i3/i3). You can bring it up upstream, but I don't think we'd be accepting this feature.
