### ISSUE TITLE
Error while building from source

### ISSUE THREAD

**Issue by galicky** [Airblader/i3#370]
<pre>
[x] Bug
</pre>

<pre>
- Linux Distribution & Version: Debian GNU/Linux 10 (buster) [amd64]
</pre>

Hi, when i try building from source, i get this error
```
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/8/../../../x86_64-linux-gnu/libcairo.so: undefined reference to `FT_Get_Var_Design_Coordinates'
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/8/../../../x86_64-linux-gnu/libcairo.so: undefined reference to `FT_Done_MM_Var'
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/8/../../../x86_64-linux-gnu/libcairo.so: undefined reference to `FT_Get_Var_Blend_Coordinates'
collect2: error: ld returned 1 exit status
make[1]: *** [Makefile:1419: i3] Error 1
make[1]: *** Waiting for unfinished jobs....
  GEN      man/i3-config-wizard.xml
make[1]: Leaving directory '/home/user/Downloads/i3/build'
make: *** [Makefile:1305: all] Error 2
```

**Comment by Airblader** [comment]
Please see https://github.com/Airblader/i3/wiki/Building-from-source as this seems to be a linking issue on your machine. Apart from that link when reporting compilation failures it'd also be helpful to know how you're compiling in the first place.

**Comment by galicky** [comment]
i'm compiling by instruction
https://github.com/Airblader/i3/wiki/Building-from-source#building

all dependencies for debian have been installed
https://github.com/Airblader/i3/wiki/Building-from-source#dependencies

**Comment by galicky** [comment]
> Please see https://github.com/Airblader/i3/wiki/Building-from-source as this seems to be a linking issue on your machine. Apart from that link when reporting compilation failures it'd also be helpful to know how you're compiling in the first place.

i'm compiling by instruction
https://github.com/Airblader/i3/wiki/Building-from-source#building

all dependencies for debian have been installed
https://github.com/Airblader/i3/wiki/Building-from-source#dependencies

**Comment by Airblader** [comment]
Please read the note at the top of that article. I recommend you take this to the i3 subreddit or similar channels, but I simply do not have the time to support individual compilation issues. i3-gaps compiles for me which most likely means this is an environment issue on your end.
