### ISSUE TITLE
Using border pixel > 0 results in unexpected mouse positions when attempting to script movements

### ISSUE THREAD

**Issue by adamws** [Airblader/i3#371]
## I'm submitting a…

<pre>
[x] Bug
[ ] Feature Request
[ ] Documentation Request
[ ] Other (Please describe in detail)
</pre>

## Current Behavior
When using border pixel > 0 moving cursor to position reported by `xdotool` does not result in correct placement.
Let's say I have `for_window [class="^.*"] border pixel 10`, in this situation I would expect that position of window is 10,10 but `xdotool` output is:
```
Window 14680412
  Position: 20,20 (screen: 0)
  Geometry: 1900x1060
```
Because of that setting mouse position based on window position `xdotool mousemove 20 20` (1) 
is not equivalent of setting it based on relative position `xdotool mousemove --window 14680412 0 0` (2)

(1)![image](https://user-images.githubusercontent.com/12676586/97369364-170bf300-18ad-11eb-8796-0976a2415597.png)(2)![image](https://user-images.githubusercontent.com/12676586/97369429-373bb200-18ad-11eb-9412-86417118b2d9.png)

## Expected Behavior
I think it should possible to use absolute mouse positions. I'm guessing some window property handled by i3 is confusing external tooling.
I've also checked output of `xwininfo -id 14680412` and there is:
```
  Absolute upper-left X:  10
  Absolute upper-left Y:  10
  Relative upper-left X:  10
  Relative upper-left Y:  10
  Width: 1900
  Height: 1060
  ...
  Corners:  +10+10  -1930+10  -1930-1090  +10-1090
  -geometry 1900x1060+0+0
```
which might be a lead (wrong corners?) - I have very limited knowledge about x11 and did not investigate further. 
## Environment
Output of `i3 --moreversion 2>&-`:
<pre>
Binary i3 version:  4.18.2 (2020-07-26) © 2009 Michael Stapelberg and contributors
</pre>
Default configuration with border pixel set:
```
for_window [class="^.*"] border pixel 10
```

<pre>
- Linux Distribution & Version:
archlinux,
Linux arch-nuc 5.9.1-arch1-1 #1 SMP PREEMPT Sat, 17 Oct 2020 13:30:37 +0000 x86_64 GNU/Linux
- Are you using a compositor (e.g., xcompmgr or compton):
no compositor
</pre>

**Comment by Airblader** [comment]
Please open this issue upstream in i3/i3 as I don't think that this is specific to i3-gaps. Thanks!
