### ISSUE TITLE
i3 Crashes on Startup after Building from Source on Fedora 33

### ISSUE THREAD

**Issue by MattNHanna** [Airblader/i3#372]
## I'm submitting a…

<pre>
[x] Bug
[ ] Feature Request
[ ] Documentation Request
[ ] Other (Please describe in detail)
</pre>

## Current Behavior

i3 crashes on startup
## Expected Behavior

i3 starts successfully
## Reproduction Instructions

start i3 from gdm
## Environment

Output of `i3 --moreversion 2>&-`:
<pre>
i3 version: 4.18.3 (2020-10-20) © 2009 Michael Stapelberg and contributors
</pre>

<details><summary>Config file</summary>
None! Using default config
</details>

<pre>
Logfile URL: https://logs.i3wm.org/logs/5758457059737600.bz2
</pre>

<pre>
- Linux Distribution & Version: Fedora 33
- Are you using a compositor (e.g., xcompmgr or compton): no
</pre>

**Comment by orestisfl** [comment]
Please open this issue on the vanilla i3 repo: https://github.com/i3/i3

Also, please include a stack trace if i3 crashed.
