### ISSUE TITLE
autoreconf fails on debian bullseye

### ISSUE THREAD

**Issue by ghost** [Airblader/i3#373]
`## I'm submitting a…
<pre>
[x] Bug
[ ] Feature Request
[ ] Documentation Request
[ ] Other (Please describe in detail)
</pre>

## Current Behavior
following the steps from wiki when building manually the output is the following when executing 
`autoreconf --force --install`

```
autoreconf: 'configure.ac' or 'configure.in' is required
```

## Expected Behavior
No error message

## Reproduction Instructions
- git clone https://www.github.com/Airblader/i3 i3-gaps
- cd i3-gaps
- autoreconf --force --install

## Environment
<pre>
Binary i3 version:  4.18 (2020-02-17) © 2009 Michael Stapelberg and contributors
Running version: < 4.2-200
</pre>

<pre>
- Linux Distribution & Version: Debian bullseye
</pre>

**Comment by ghost** [comment]
All Debian dependencies mentioned in the Wiki have been installed

**Comment by Airblader** [comment]
i3 (and thus i3-gaps) has switched from autotools to meson, see [Release Notes](https://i3wm.org/downloads/RELEASE-NOTES-4.19.txt). The wiki here is not updated to reflect that yet, I'll take care of that.

**Comment by ghost** [comment]
Thanks
