### ISSUE TITLE
Focus moves but keyboard input doesnt ?

### ISSUE THREAD

**Issue by bechampion** [Airblader/i3#374]
[x] Bug
[ ] Feature Request
[ ] Documentation Request
[ ] Other (Please describe in detail)
</pre>

## Current Behavior
Randomly moving focus between two terminals in 2 monitors ,  the focus moves over but the keyboard input remain captured in the non focused terminal/app
## Expected Behavior
Keyboard input should follow the focused window
## Reproduction Instructions
2 monitors 1 terminal in each and move back an forth until you see it (screenshot attached)

sorry about the awful picture ,  but it was the only way to capture it.
You can see the focus is on the screen on the left (surrounded by a pink border) but the cursor (and keyboard input ins on the right , full green square)

## Environment
Ubuntu 20.4
`i3 version 4.18.2-237-gcf7dd36e (2020-10-15, branch "gaps-next") © 2009 Michael Stapelberg and contributors`
![image](https://user-images.githubusercontent.com/4983875/99561978-78604700-29bf-11eb-80e3-eb0855f7c5b9.png)

**Comment by orestisfl** [comment]
Bugs are tracked on the upstream repo, you could update your comment here (https://github.com/i3/i3/issues/3518#issuecomment-729800163) to include the extra information of this post

**Comment by bechampion** [comment]
Hi there , that issue you linked is different , the one I describe here doesn’t happen when moving a windows from workspace a to b , the bug occurs when moving focus from a window in workspace a/monitor 1 ato workspace b/monitor 2

**Comment by orestisfl** [comment]
Then it sounds like https://github.com/i3/i3/issues/3609

What kind of terminal are you using?

**Comment by bechampion** [comment]
It happens on slack , urxvt ,browser ...
