### ISSUE TITLE
Ubuntu 18.04.2 LTS no gaps after successful installation from your PPA 

### ISSUE THREAD

**Issue by denisviklov** [Airblader/i3#375]
## I'm submitting a…

<pre>
[x] Bug
[ ] Feature Request
[ ] Documentation Request
[ ] Other (Please describe in detail)
</pre>

## Current Behavior

I'm doing installation according your manual and as it requires by https://github.com/unix121/i3wm-themer when I begin to restart my I3wm config checks fails on the i3-gaps.
If I try to find inside the system I got none both with ``which`` or ``locate`` commands.
**BUT**
``apt search i3-gaps`` gives me

```
$ apt search i3-gaps
Sorting... Done
Full Text Search... Done
i3-gaps/bionic,now 4.18.2-1~regolith2 amd64 [installed]
  metapackage (i3-gaps window manager, screen locker, menu, statusbar)

i3-gaps-session/bionic,now 4.18.2-1~regolith2 amd64 [installed,automatic]
  Xsession for i3-gaps

i3-gaps-wm/bionic,now 4.18.2-1~regolith2 amd64 [installed,automatic]
  improved dynamic tiling window manager
```

## Expected Behavior

I expected that it's appeared system-wide after installation 

## Environment

Output of `i3 --moreversion 2>&-`:
<pre>
i3 version: 
i3 --moreversion 2>&-
Binary i3 version:  4.18.2 (2020-07-26) © 2009 Michael Stapelberg and contributors
Running i3 version: 4.18.2 (2020-07-26) (pid 11366)bort…)
Loaded i3 config: /home/denis/.config/i3/config (Last modified: Friday, 27 November, 2020 09:04:33 PM PST, 2084 seconds ago)

The i3 binary you just called: /usr/bin/i3
The i3 binary you are running: i3
</pre>

<details><summary>Config file</summary><pre>
</pre>
</details>

<pre>
Logfile URL:
</pre>

<pre>
- Linux Distribution & Version:Ubuntu 18.04.2 LTS
- Are you using a compositor (e.g., xcompmgr or compton):
</pre>

**Comment by Airblader** [comment]
> from your PPA

I don't have or operate a PPA for i3-gaps, please contact the maintainer of that package directly.

> I'm doing installation according your manual

https://github.com/Airblader/i3/wiki/Building-from-source#important-note

**Comment by denisviklov** [comment]
Thank you for your answer, I'll try to build it from the sources.

**Comment by Airblader** [comment]
I linked that because you _shouldn't_ build from source. Contact the PPA maintainer.

**Comment by denisviklov** [comment]
Huh, but I've already done with sources and it works as planned. Thank you.
