### ISSUE TITLE
Chromium graphical glitch.

### ISSUE THREAD

**Issue by obayit** [Airblader/i3#376]
## I'm submitting a…

<pre>
[x] Bug
[ ] Feature Request
[ ] Documentation Request
[ ] Other (Please describe in detail)
</pre>

## Current Behavior

Chromium glitch on the top of the window.
I noticed that this started to happen after I upgraded to Ubuntu 20.04 and after using the chromium from `snap`.

![Screenshot from 2020-11-14 11-25-14](https://user-images.githubusercontent.com/20386024/100997183-a9657d80-3562-11eb-89d5-08df3ba8071d.png)

## Environment

Output of `i3 --moreversion 2>&-`:
<pre>
i3 version: 
</pre>
Binary i3 version:  4.18.3-258-g806104cf (2020-10-20, branch "gaps-next") © 2009 Michael Stapelberg and contributors
Running i3 version: 4.18.3-258-g806104cf (2020-10-20, branch "gaps-next") (pid 12297)
Loaded i3 config: /home/obi/.config/i3/config (Last modified: Mon 30 Nov 2020 07:03:39 AM CAT, 278153 seconds ago)

The i3 binary you just called: /usr/bin/i3
The i3 binary you are running: i3

## [Config file](https://pastebin.com/DCz1XmQ2)

<pre>
Logfile URL:
</pre>

<pre>
- Linux Distribution & Version: Ubuntu 20.04
- Are you using a compositor (e.g., xcompmgr or compton): No
</pre>

**Comment by Airblader** [comment]
What makes you think this is an issue specific to i3-gaps (versus i3) or even related to i3 at all? The window manager is not involved in rendering the client window.

**Comment by obayit** [comment]
I don't know if this is even related to i3 at all!

I just want a solution.
**Edit**

OK, I tried disabling the hardware acceleration in chromium as suggested from this [answer](https://askubuntu.com/a/1284326/428140). I hope that it works!

**Comment by Airblader** [comment]
If you're not running a compositor, you can also try if running one fixes it. If you recently updated graphics drivers, that's another possible culprit.

**Comment by obayit** [comment]
The disabling of the hardware acceleration fixed this.
Yeah, I recently upgraded from Ubuntu 18.04, and probably it included graphic driver updates.
