### ISSUE TITLE
error while loading shared libraries: libxcb-util.so.0

### ISSUE THREAD

**Issue by dsyates** [Airblader/i3#377]
## I'm submitting a…

<pre>
[x] Bug
[ ] Feature Request
[ ] Documentation Request
[ ] Other (Please describe in detail)
</pre>

## Current Behavior

startx command fails to start x with error while loading shared libraries: libxcb-util.so.0: cannot open shared object file: No such file or directory.
## Expected Behavior

startx starts i3 normally.
The problem goes away after libxcb-util.so.1.0.0 is symlinked to libxcb-util.so.0
## Reproduction Instructions

I3 requires libxcb-util0-dev; debian testing lists the following:
libxcb-util0-dev is installed and apt describes it as a dummy transitional package for utility libraries for X C Binding
## Environment

Output of `i3 --moreversion 2>&-`:
<pre>
i3 version: Binary i3 version:  4.19-6-g069edeb2 © 2009 Michael Stapelberg and contributors
Running i3 version: 4.19-6-g069edeb2 (pid 1990)
Loaded i3 config: /home/norris/.config/i3/config (Last modified: Sun 07 Jun 2020 03:59:29 PM EDT, 15958942 seconds ago)

The i3 binary you just called: /usr/bin/i3
The i3 binary you are running: x-sessio/i3
</pre>

<details><summary>Config file</summary><pre>
problem is not related to config file.
</pre>
</details>

<pre>
Logfile URL:
</pre>

<pre>
- Linux Distribution & Version: Debian testing
- Are you using a compositor (e.g., xcompmgr or compton): picom v8.2
</pre>

**Comment by dsyates** [comment]
This issue does not seem to exist on my debian sid machine as libxcb-util.so.0 exists and doesn't need to be symlinked, so maybe this is a debian testing issue.

**Comment by Airblader** [comment]
This seems like a packaging issue, please report it to the maintainer of (the package of) your distribution. Thanks!

**Comment by dsyates** [comment]
will do.

**Comment by crivotz** [comment]
I think it is due to the fact that in bullseye(your sid) there is libxcb-util1 I had to manually create a symlink to this version
