### ISSUE TITLE
Outer gaps show even though I don't have them enabled.

### ISSUE THREAD

**Issue by johnnynalley** [Airblader/i3#378]
## I'm submitting a…

<pre>
[x] Bug
[ ] Feature Request
[ ] Documentation Request
[ ] Other (Please describe in detail)
</pre>

## Current Behavior
 I do not have outer gaps enabled in my i3 config, but there is still an outer gap around all of my windows. I only have inner gaps enabled. You can see my configs at https://github.com/LiterallyJohnny/Dotfiles/blob/main/i3/config

## Expected Behavior
 There should be no gaps on the outside of my windows.

## Reproduction Instructions
 Enable inner gaps, not outer gaps.

## Environment

Output of `i3 --moreversion 2>&-`: `Binary i3 version:  4.19 (2020-11-15) © 2009 Michael Stapelberg and contributors
Running i3 version: 4.19 (2020-11-15) (pid 434)
Loaded i3 config: /home/johnny/.config/i3/config (Last modified: Tue 08 Dec 2020 07:32:46 PM CST, 86367 seconds ago)

The i3 binary you just called: /usr/bin/i3
The i3 binary you are running: i3`
<pre>
i3 version: 4.19
</pre>

<details><summary>Config file</summary><pre>
</pre>
</details>

<pre>
Logfile URL: https://github.com/LiterallyJohnny/Dotfiles/blob/main/i3/config
</pre>

<pre>
- Linux Distribution & Version: Arch Linux
- Are you using a compositor (e.g., xcompmgr or compton): Picom, but this was going on before I started using a compositor.
</pre>

**Comment by Airblader** [comment]
https://github.com/Airblader/i3#gaps:

> [...] inner gaps are those between two adjacent containers (or a container and an edge) [...]
> Note: Outer gaps are added to the inner gaps, i.e., the gaps between a screen edge and a container will be the sum of outer and inner gaps.

**Comment by Airblader** [comment]
If you want no gaps on the outside, set the outer gaps to the additive inverse of the inner gaps to make that sum come out to zero.
