### ISSUE TITLE
missing file 'configure.ac' or 'configure.in'

### ISSUE THREAD

**Issue by HugoGDRM** [Airblader/i3#381]
## I'm submitting a…

<pre>
[x] Bug
[ ] Feature Request
[ ] Documentation Request
[ ] Other (Please describe in detail)
</pre>

## Current Behavior

I'm currently trying to install i3 gaps on Ubuntu 20.04,
but i'm struggling on the compiling part
when running: `autoreconf --force --install`
we get this output : `autoreconf: 'configure.ac' or 'configure.in' is required`
I know that there is already an issue about this from 2016 but i don't understand it
Thanks for your help
## Environment

Output of `i3 --moreversion 2>&-`:
<pre>
i3 version: 
</pre>

<details><summary>Config file</summary><pre>
</pre>
</details>

<pre>
Logfile URL:
</pre>

<pre>
- Linux Distribution & Version:
- Are you using a compositor (e.g., xcompmgr or compton):
</pre>

**Comment by HugoGDRM** [comment]
I tried both branch 'gaps' and 'gaps-next' but there is still the same problem

**Comment by Airblader** [comment]
i3 does not use autotools anymore, it uses meson since 4.19, see release notes for details.
