### ISSUE TITLE
how to set the gap when window is maximized?

### ISSUE THREAD

**Issue by OriLiMu** [Airblader/i3#383]
## I'm submitting a…

<pre>
[ ] Bug
[ ] Feature Request
[ ] Documentation Request
[x] Other (Please describe in detail)
</pre>

I want the maxmized window leave a gap around(left right up down), dont occupied all the screen, I search for a while seems no related issue. how to make it thank you.

My try:
First I want to resize the window to what I want by remap the fullscreen shortcut, 
But I need to toggle not just max the window, so I need to get the status of the current window. which seems a little complicated. 

So is there a straight way to set the gaps in max mode? 

OS: manjaro 20
i3 version: 4.19

**Comment by Airblader** [comment]
i3 does not implement window maximization, only fullscreen, and for fullscreen gaps are not supported (and would imo violate the specification of what _NET_WM_FULLSCREEN is).

**Comment by Tonus1** [comment]
I think you might use some geometry on floating window as a workaround to achieve this goal.
