### ISSUE TITLE
debian bullseye failed building from source

### ISSUE THREAD

**Issue by liker169** [Airblader/i3#387]
When run 'meson ..' , I got two error messages:"Checking for function "mkdirp" : NO",and "Library iconv found: NO",and at the end build docs and build manpages both false;
when run 'ninja',I got five warning :/usr/bin/ld: warning: libxcb-util.so.0, needed by /usr/local/lib/libxcb-xrm.so, may conflict with libxcb-util.so.1
[92/103] Linking target i3-config-wizard
/usr/bin/ld: warning: libxcb-util.so.0, needed by /usr/local/lib/libxcb-xrm.so, may conflict with libxcb-util.so.1
[98/103] Linking target i3-input
/usr/bin/ld: warning: libxcb-util.so.0, needed by /usr/local/lib/libxcb-xrm.so, may conflict with libxcb-util.so.1
[102/103] Linking target i3
/usr/bin/ld: warning: libxcb-util.so.0, needed by /usr/local/lib/libxcb-xrm.so, may conflict with libxcb-util.so.1
[103/103] Linking target i3-nagbar
/usr/bin/ld: warning: libxcb-util.so.0, needed by /usr/local/lib/libxcb-xrm.so, may conflict with libxcb-util.so.1
I don't know how to fix thoes issu

**Comment by Airblader** [comment]
Please see https://github.com/Airblader/i3/wiki/Building-from-source#important-note
