### ISSUE TITLE
Windows not showing up when display is switched

### ISSUE THREAD

**Issue by elkoniu** [Airblader/i3#388]
## I'm submitting a…

<pre>
[x] Bug
[ ] Feature Request
[ ] Documentation Request
[ ] Other (Please describe in detail)
</pre>

## Current Behavior
I have a laptop connected to external display via HDMI. Laptop screen is on the left and external display
is on the right. Each display shows up different workspace. On the workspace presented on laptop (left
display) I have 3 floating windows. Now using arandr I am turning off laptop (left) display and leaving only
external (right) display running. After that all workspaces has been moved to the only display which is active - external one.
The problem is that windows which were floating disappeared. They are still there, I can see that workspace is not empty
but they are no longer visible on screen. It looks like they are still on old coordinates (left display coordinates) rather than
be on workspace related coordinates. To have them back I need to blindly focus on them and then
force them back to grid rather than floating windows. This way they shows up on the workspace.
When I move them back to be floating they behave normally again.

## Expected Behavior
After one of two video outputs is disabled all workspaces should move to remaining display.
All floating windows should move there to related workspace. (X, Y) position of floating window
should be based on workspace coordinates not the general screen coordinates.

## Environment

Output of `i3 --moreversion 2>&-`:
<pre>
Binary i3 version:  4.17.1 (2019-08-30) © 2009 Michael Stapelberg and contributors
Running i3 version: 4.17.1 (2019-08-30) (pid 2536)abort…)
Loaded i3 config: /home/ppolawsk/.config/i3/config (Last modified: czw, 25 lut 2021, 11:50:04, 8603 seconds ago)

The i3 binary you just called: /usr/bin/i3
The i3 binary you are running: i3
</pre>

<details><summary>Config file</summary><pre>
</pre>
</details>

<pre>
Logfile URL:
</pre>

<pre>
- Linux Distribution & Version: Fedora 31
- Are you using a compositor (e.g., xcompmgr or compton): yes
</pre>

**Comment by orestisfl** [comment]
Please update to latest i3 version, re-check if your issue persists and open a new issue in https://github.com/i3/i3/issues
