### ISSUE TITLE
ninja fails to build due to not being well integrated with package managers

### ISSUE THREAD

**Issue by cmpunches** [Airblader/i3#390]
## I'm submitting a…

<pre>
[x] Bug
[ ] Feature Request
[ ] Documentation Request
[ ] Other (Please describe in detail)
</pre>

## Current Behavior
`meson ../` seems to complete successfully but ninja fails due to a missing legacy perl dependency.

<pre>
[ bagira @ forge.silogroup.org ] << ~/development/external/i3-4.19.1/build >>

[- ninja
[1/96] Generating anyevent-i3 with a custom command
FAILED: AnyEvent-I3.stamp
sh -c 'cp -r /home/bagira/development/external/i3-4.19.1/AnyEvent-I3 . && cd AnyEvent-I3 && perl Makefile.PL && make && touch ../AnyEvent-I3.stamp'
Can't locate ExtUtils/MakeMaker.pm in @INC (you may need to install the ExtUtils::MakeMaker module) (@INC contains: /usr/local/lib64/perl5/5.30 /usr/local/share/perl5/5.30 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5) at Makefile.PL line 5.
BEGIN failed--compilation aborted at Makefile.PL line 5.
[2/96] Generating config.h with a custom command
ninja: build stopped: subcommand failed.
</pre>

## Expected Behavior
<pre>
make
sudo make install
</pre>

or

<pre>
cmake .
make
sudo make install
</pre>

*There should be no dependency on perl modules anywhere in a modern build process for C/C++ solutions.  This is a legacy regression, not just a bug to fix.

## Reproduction Instructions
verbatim instructions from the file `PACKAGE-MAINTAINER` on default installs of most linux distributions

## Environment
reproduced on v4.19.1 release source 

Output of `i3 --moreversion 2>&-`:
<pre>
N/A - doesn't compile due to this toolchain bug.
</pre>

<details><summary>Config file</summary>
<pre>
N/A - doesn't compile
</pre>
</details>

<pre>
provided above 
</pre>

<pre>
- Linux Distribution & Version:  Last attempted on Fedora
- Are you using a compositor (e.g., xcompmgr or compton):  Yes but this is not related.
</pre>

**Comment by Airblader** [comment]
i3-gaps uses the i3 build tooling, and I have absolutely no intention of deviating from that. 

Feel free to discuss on the i3 mailing list, but there was a reason to move away from Autotools, too. I'm closing this as non-specific to i3-gaps.

**Comment by cmpunches** [comment]
@Airblader ok, close it if you think that's appropriate, but be aware that this solution in the meantime simply does not compile with your build instructions.  Even if it's an upstream defect, it doesn't compile.  It seems like there will need to be interventions in the build process documentation, even if it's just mucking around with CPAN to make ninja do what cmake already did.

**Comment by cmpunches** [comment]
"instructions don't result in a successful compile" -> "closed ticket"

**Comment by Airblader** [comment]
No, I closed it because it isn't an issue specific to i3-gaps and thus at the very least should be addressed in upstream i3.

Your spamming of issues will now get you blocked, congratulations. It would be to your benefit to contribute issues by following the templates to begin with and reading responses rather than pushing some agenda.
