### ISSUE TITLE
please update instructions to result in a successful install

### ISSUE THREAD

**Issue by cmpunches** [Airblader/i3#391]
The documentation currently for building this, PACKAGE-MAINTAINER, does not result in a successful installation.

"instructions don't result in a successful compile" -> "closed ticket"

_Originally posted by @cmpunches in https://github.com/Airblader/i3/issues/390#issuecomment-792229342_

On some systems, a perl runtime requirement is needed or ninja will error out, but, after installing perl, ninja will build in the local directory but does not install.  The instructions do not reference installation of the compiled tree.

Can this please be updated to reflect a successful process?

**Comment by ghost** [comment]
After reading #389 #390 #391, it's my recommendation (and I'm sure I'm not alone after seeing this) that the i3-gaps project simply not be used until Airblader gets his act together.

Airblader was made aware of an issue that prevents this project from being used on most linux systems and lacks the bare minimum social skills required to solve even basic problems like this collaboratively:

He closed the first ticket with no explanation.

The follow up ticket which brought specific light to the upstream issue and how it broke the build process got a paragraph about how the toolchain change was upstream and he closed the ticket knowing that the issue creates a blocker to installation using the formal documentation that he supplies with his fork.

The last ticket was to address the -documentation- (yes, all 3 were different aspects of the same problem).  Instead, he closed it and threatened the user on the last ticket with a block and called it "spamming" to use the social feature of a ticket system to discuss an issue.

His behaviour here was rude, antisocial, and overtly hostile, and if he can't fix a documentation or build issue without aggressive behaviour like this unapologetically, then he simply shouldn't be contributing to open source projects.

We have enough toxic narcissists in the software industry; you are neither welcome nor competent.

**Comment by Airblader** [comment]
> He closed the first ticket with no explanation.

You opened that first ticket without a description.

---

I've now reported this to GitHub for abuse and spam and will cease to respond with any further interactions with you.
