### ISSUE TITLE
Copy-Paste - focus moved to irrelevant window

### ISSUE THREAD

**Issue by dammmn** [Airblader/i3#393]
## I'm submitting a bug report

<pre>
[x] Bug
[ ] Feature Request
[ ] Documentation Request
[ ] Other (Please describe in detail)
</pre>

## Current Behavior

xterm-1, xterm-2 and browser running at the same desktop. xterm-2 being a *scratchpad*. xterm-1 has some text which I want to copy over to *scratchpad*. Selecting the text from xterm-1 and then pasting it to xterm-2 brings focus on the browser window (usually). I have to manually click on the *scratchpad* window to get the focus.

## Expected Behavior

Focus should not be changed once paste operation is happening. 

## Reproduction Instructions

See __Current Behavior__ step.

## Environment

Output of `i3 --moreversion 2>&-`:
<pre>
i3 version: 
╰─>$ i3  --moreversion 
Binary i3 version:  4.19-25-g4e11a4ee © 2009 Michael Stapelberg and contributors
Running i3 version: 4.19-25-g4e11a4ee (pid 1021655)
Loaded i3 config: /home/dciprus/.config/i3/config (Last modified: Tue 23 Mar 2021 08:58:26 AM EDT, 3334 seconds ago)

The i3 binary you just called: /home/dciprus/Work/Tools/i3gaps/bin/i3
The i3 binary you are running: /home/dciprus/Work/Tools/i3gaps/bin/i3
</pre>

<details><summary>Config file</summary><pre>
https://pastebin.com/Phjb4dwD
</pre>
</details>

<pre>
Logfile URL:
</pre>

<pre>
- Linux Distribution & Version: **Description:    Ubuntu 20.04.2 LTS**
- Are you using a compositor (e.g., xcompmgr or compton): **picom**
</pre>

**Comment by Airblader** [comment]
Can you please describe in more detail how you're copy-pasting, i.e. using Ctrl+C/V or middle mouse button and the like? Can you reproduce this with other applications than xterm / that specific browser?

Also, did you unsuccessfully reproduce this in vanilla i3? I doubt that this is specific to i3-gaps.

**Comment by dammmn** [comment]
> Can you please describe in more detail how you're copy-pasting, i.e. using Ctrl+C/V or middle mouse button and the like? Can you reproduce this with other applications than xterm / that specific browser?
> 
> Also, did you unsuccessfully reproduce this in vanilla i3? I doubt that this is specific to i3-gaps.

Copy and paste is just selecting by mouse the text which I want to copy and then using shift-insert things get pasted. Also I use copyq as a clipboard manager. There was another one before copyq but I can't recall its name. One thing I know for sure is that this problem was there as well. 

As for the note about whether this is/is_not specific to i3-gaps - I do not believe that this is specific to i3-gaps either. Before going to mainstream i3 I would like to make sure that this statement is correct though. This problem has been reported on reddit 1-2 times already and there was no fix for it - at least I could not find successful resolution statement anywhere. 

Btw thank you for your work on this, it really is a nice piece of functionality which was brought to the linux world.

**Comment by Airblader** [comment]
> One thing I know for sure is that this problem was there as well.

Thanks, that's useful information. Can you maybe check if it happens without any clipboard managers as well?

> Before going to mainstream i3 I would like to make sure that this statement is correct though.

Sure, if you can verify first, all the better. Both @orestisfl and I are both here on i3-gaps and i3, though, so it would also be fine if we move it to upstream i3.

> This problem has been reported on reddit 1-2 times already

If you could add those links, if you still have them, that'd be great. :-)

**Comment by dammmn** [comment]
Tried copyq and clipit - with and without running those clipboard managers - same result as described in the reproduction scenario. 

Links from reddit - yeah, as soon as I find them I will add them here. Don't have them handy.

**Comment by Airblader** [comment]
Closing in favor of the upstream issue (thanks!)
