### ISSUE TITLE
Missing steps in building from source.

### ISSUE THREAD

**Issue by RennyDemmy** [Airblader/i3#395]
## I'm submitting a…

<pre>
[x] Bug
[ ] Feature Request
[ ] Documentation Request
[ ] Other (Please describe in detail)
</pre>

## Environment

Output of `i3 --moreversion 2>&-`:
<pre>
i3 version: 
</pre>

<details><summary>Config file</summary><pre>
</pre>
</details>

<pre>
Logfile URL:
</pre>

<pre>
- Linux Distribution & Version:
- Are you using a compositor (e.g., xcompmgr or compton):
</pre>

Dear Airblader, 

I followed your guide to install i3-gaps on Debian, only to fail. This person, however, made a more comprehensive guide. Is it okay to implement this guide?

Link: https://lottalinuxlinks.com/how-to-build-and-install-i3-gaps-on-debian/

Regards,

IntolerantRenny

**Comment by Airblader** [comment]
Which step exactly is missing? The only differences are the prefix, which the post explains they do differently and depends on preferences and distro anyway, and the install step, which I intentionally don't include. 
The instructions in the wiki are generic. I don't want overly specific instructions because people who don't know what they're doing shouldn't build from source in the first place, but rather ask their distributions to package i3-gaps. Unfortunately Debian is a very stubborn distribution.

@dsyates In your article you misspelled my username in the GitHub URL.

**Comment by Airblader** [comment]
Also if @dsyates sees this, here's the answer to one of their questions in the post: https://github.com/Airblader/i3/wiki/Frequently-Asked-Questions#why-doesnt-i3-gaps-change-the-name-of-the-binaries

**Comment by dsyates** [comment]
I will fix the mispelling

**Comment by dsyates** [comment]
misspelling*  ...dang it.

**Comment by IntolerantRenny** [comment]
> Which step exactly is missing? The only differences are the prefix, which the post explains they do differently and depends on preferences and distro anyway, and the install step, which I intentionally don't include. 
> The instructions in the wiki are generic. I don't want overly specific instructions because people who don't know what they're doing shouldn't build from source in the first place, but rather ask their distributions to package i3-gaps. Unfortunately Debian is a very stubborn distribution.
> 
> @dsyates In your article you misspelled my username in the GitHub URL. 

Oh, the prefix isn't needed afaik. It's just the "sudo ninja install" part was missing.

**Comment by Airblader** [comment]
That's intentional, because that's not building it anymore, that's installing it — something you shouldn't do unless you know how to do it anyway. Thanks for opening the issue, but I'd prefer to keep it this way as to not lead more users to install things randomly into their system. :-)

**Comment by RennyDemmy** [comment]
> Which step exactly is missing? The only differences are the prefix, which the post explains they do differently and depends on preferences and distro anyway, and the install step, which I intentionally don't include. 
> The instructions in the wiki are generic. I don't want overly specific instructions because people who don't know what they're doing shouldn't build from source in the first place, but rather ask their distributions to package i3-gaps. Unfortunately Debian is a very stubborn distribution.
> 
> @dsyates In your article you misspelled my username in the GitHub URL. 

What about "sudo ninja install"? I'm sure that should've been in the guide...

**Comment by Airblader** [comment]
^ See my comment above
