### ISSUE TITLE
International US keyboard stops working on specific workspaces

### ISSUE THREAD

**Issue by thevinter** [Airblader/i3#397]
## I'm submitting a…

<pre>
[x] Bug
[ ] Feature Request
[ ] Documentation Request
[ ] Other (Please describe in detail)
</pre>

## Current Behavior

Sometimes, on specific workspaces (mostly on the one i'm running telegram-desktop), the international keyboard stops behaving properly. All international keys (like ' and \`) stop working and act as dead keys. i.e. I press ` and nothing happens. To solve the problem I must manually change to another workspace and then back to the one I was on before.

## Expected Behavior

When pressing `e I should obtain the accented version of the letter "è" (should be the same with any other letter)

## Reproduction Instructions

It randomly happens after some time

## Environment

Output of `i3 --moreversion 2>&-`:
<pre>
i3 version 4.19.1 (2021-02-01) © 2009 Michael Stapelberg and contributors
</pre>

<details><summary>Config file</summary><pre> https://dpaste.com//6WMWAZMKX
</pre>
</details>

<pre>
Logfile URL:
</pre>

<pre>
- Linux Distribution & Version: Arch Linux 2021.05.01
--
- Are you using a compositor (e.g., xcompmgr or compton): No
</pre>

**Comment by Airblader** [comment]
Can you please reproduce this on vanilla i3 and then report it at i3/i3? There's nothing different in i3-gaps in terms of keyboard handling.
