### ISSUE TITLE
Smart hide mode for i3bar

### ISSUE THREAD

**Issue by henry-ta** [Airblader/i3#399]
## I'm submitting a…

<pre>
[ ] Bug
[x] Feature Request
[ ] Documentation Request
[ ] Other (Please describe in detail)
</pre>

## Current Behavior

<pre>
Currently, i3-gaps/i3 only has visible/hide/invisible mode for i3bar. 
</pre>
## Desired Behavior

<pre>
I am expecting a smart hide mode that hide i3 bar when there are active windows and show the bar when moving cursor to the bar area ( even some windows are active ) or when there's no windows left on the screen
</pre>
## Impact

<pre>
[ ] This feature requires new configuration and/or commands

This feature is a combination of all 3 modes from i3bar, so this won't requires new configuration but some tweaks to create a now mode
</pre>

 
## Environment

Output of `i3 --moreversion 2>&-`:
<pre>
i3 version: 
Binary i3 version:  4.19.1 (2021-02-01) © 2009 Michael Stapelberg and contributors
Running i3 version: 4.19.1 (2021-02-01) (pid 900)
</pre>

<pre>
- Linux Distribution & Version: Arch - Kernel(5.10.40-1-lts)
- Are you using a compositor (e.g., xcompmgr or compton): picom-ibhagwan-git
</pre>

**Comment by Airblader** [comment]
I apologize for the late response. I'm not looking to adding further features to i3-gaps at this point anymore. Thanks for understanding!
