### ISSUE TITLE
Docs: Add install instructions for Fedora Linux

### ISSUE THREAD

**Issue by justwheel** [Airblader/i3#400]
## I'm submitting a…

<pre>
[ ] Bug
[ ] Feature Request
[x] Documentation Request
[ ] Other (Please describe in detail)
</pre>

i3-gaps is available [in default repositories](https://src.fedoraproject.org/rpms/i3-gaps) for Fedora Linux. Install i3-gaps with the following command:

```sh
sudo dnf install i3-gaps
```

**Comment by Airblader** [comment]
Thanks for letting me know! I've added it to the wiki.
