### ISSUE TITLE
Putting computer to sleep => applets disappear from "notification area" 

### ISSUE THREAD

**Issue by liar666** [Airblader/i3#402]
## I'm submitting a…

<pre>
[X ] Bug
[ ] Feature Request
[ ] Documentation Request
[ ] Other (Please describe in detail)
</pre>

## Current Behavior

I'm using i3gaps installed from PPA:
```
i3-gaps/focal,now 4.18.2-1~regolith2 amd64 [installed]
```

I'm using the exact same config file as I had for i3 (+ a few gaps configs) that was working perfectly.

In this config file, I start some applets during i3's startup with:
 ```
exec --no-startup-id /usr/bin/xfsettingsd   # mostly for dark themes to XFCE/Gnome apps
exec --no-startup-id /usr/bin/nm-applet
exec --no-startup-id /usr/bin/blueman-applet
exec --no-startup-id /usr/bin/pnmixer
exec --no-startup-id /usr/bin/xfce4-power-manager
```
I've also tested with an external script:
```
exec --no-startup-id $HOME/.config/i3/scripts/start_applets.sh
```
And with just executable name or with full pathes.

When I start i3gaps, the icons of the applets appear in the "notification area".

When I put my computer to sleep (by closing the lid), then open the computer and unlock the screen (XFCE locker), i3 & ws come back correctly but icons of applets have disappeared (whole "notification area" -or its content - in fact).

When I try to run blueman-applet again manually, it tells me that applet already is running. I have to kill it and start it again... Not very convenient to do for each 5 of my applets :{

## Expected Behavior

Whole "notification area"/tray icon should reappear when waking computer from sleep.

## Reproduction Instructions

See Section "current behaviour":
1. start i3gaps with a few applets (e.g. nm-applet / blueman-applet)
2. close lid / pm-suspend computer
3. open lid /wakeup computer
4. unlock computer
5. observe that "notification area" / tray is empty

## Environment

Output of `i3 --moreversion 2>&-`:
<pre> 
Binary i3 version:  4.18.2 (2020-07-26) © 2009 Michael Stapelberg and contributors
Running i3 version: 4.18.2 (2020-07-26) (pid 2797)abort…)
Loaded i3 config: /home/gmuller/.config/i3/config (Last modified: Thu Jul 22 11:10:47 2021, 9986 seconds ago)

The i3 binary you just called: /usr/bin/i3
The i3 binary you are running: i3
</pre>

<pre>
see most relevant parts above
</pre>

<pre>
Logfile URL:
</pre>

<pre>
- Linux Distribution & Version: "Linux Mint 20 Ulyana"
- Are you using a compositor (e.g., xcompmgr or compton): no
</pre>

**Comment by Airblader** [comment]
Can you provide your full configuration, please, as well as the output of `xrandr` both before and after this happens? Also this doesn't seem to be specific to i3-gaps so we might close it and re-open it over at i3/i3 (but let's see).

**Comment by liar666** [comment]
Sorry, I wanted to verify there's nothing too personal in it before posting.

- Here is the config file:
[config.txt](https://github.com/Airblader/i3/files/6863308/config.txt)
- Here is the `xrandr` before the suspend:
[xrandr.after.txt](https://github.com/Airblader/i3/files/6863343/xrandr.after.txt)
- Here is the `xrandr` after the suspend:
[xrandr.before.txt](https://github.com/Airblader/i3/files/6863344/xrandr.before.txt)

The same config (without gaps) worked perfectly with i3-wm, so at the beginning, I thought it was a problem in i3-gaps, as I thought that i3-wm (Mint pkg) and i3-gaps-wm (ppa pkg) would be at the same version level. But after verification, the i3-wm that was installed was: `i3-wm/focal,now 4.17.1-1 amd64`.

So you're right the bug might be in i3-wm "4.18.2" (vs.  it was working in 4.17.1-1). I'll try to see if I can manage to install i3-wm "4.18.2" to check that.

**Comment by Airblader** [comment]
Thanks you. Actually before anything else, please upgrade to the latest version (i3 or i3-gaps), being 4.19.2, and make sure it still happens there. There were a bunch of changes to i3bar and the tray since then. Thanks!

**Comment by liar666** [comment]
Hi again,

I've cloned the repo and followed the instructions to compile the code, but then I get:
```
Binary i3 version:  4.19.1-138-g01a45d28 © 2009 Michael Stapelberg and contributors
```

`4.19.1-138-g01a45d28` is not `4.19.2` that you say is the lastest version. Where do I make a mistake? How do I get the version `4.19.2`?

**Comment by liar666** [comment]
FYI, I've made more tests:

`echo mem > /sys/power/state` => goes to sleep and recovers without loosing the items in the notification area
`echo disk > /sys/power/state`=> lead to `no space left on device` on my computer, so should not be the problem
`xrandr --auto` => looses the items in the notification area.

So the problem seems to come from changing/refreshing the resolution of the screen.

**Comment by Airblader** [comment]
Your config says

```
    tray_output primary
    tray_output eDP-1
    tray_output DP-2
```

Can you compare that configuration against the output of `xrandr` afterwards? Make sure no monitor is shown as connected if you don't expect it to be on, look which one is the primary one etc.

4.19.1 is good enough.

**Comment by liar666** [comment]
I've just tested without any monitor attached BEFORE and AFTER putting the computer to sleep.
`xrandr` says the same thing both before and after the sleep:
`eDP-1 connected primary 1920x1080+0+0 (normal left inverted right x axis y axis) 309mm x 173mm`

I've also tested by putting `tray_output eDP-1` as first entry, and same problem occurs.

I'll test with `i3-gaps 4.19.1`

**Comment by liar666** [comment]
OK seems to work with `i3-gaps 4.19.1`.
Thanks a lot for your help and patience!!!
I'll try to see if I can motivate some PPA owner to distribute this version :)

**Comment by Airblader** [comment]
Great, thanks. I'll close this then.

**Comment by liar666** [comment]
I'm copy-pasting below the nice answer from Ken Gilmer, who manages the PPA recommended in the Install instructions, so that others can benefit from it too (I don't know why I didn't find it when searching the PPAs):

>   You can install i3-gaps 4.19.1 from this PPA: https://launchpad.net/~regolith-linux/+archive/ubuntu/release <https://launchpad.net/~regolith-linux/+archive/ubuntu/release>.  This is built from the following repo: https://github.com/regolith-linux/i3-gaps-wm <https://github.com/regolith-linux/i3-gaps-wm>.  The package you want to install for vanilla i3-gaps (not Regolith) is: i3-gaps
