### ISSUE TITLE
i3bar - Grouping and spacing statusline blocks

### ISSUE THREAD

**Issue by ChrisSwinchatt** [Airblader/i3#403]
## I'm submitting a…
<pre>
[ ] Bug
[x] Feature Request
[ ] Documentation Request
[ ] Other (Please describe in detail)
</pre>

## Desired Behavior

i3bar should be able to divide statusline blocks into (e.g.) 3 groups with spacing between so users can have X blocks appear on the left of the bar, Y in the centre, and any remaining on the right. 

## Impact

<pre>
[x] This feature requires new configuration and/or commands
</pre>

A new command-line option and/or config command to set the number of blocks to put in each group.

Note
 * I will implement the changes myself.
 * I'm also submitting the FR to upstream i3 and in the unlikely scenario that they agree, I would make a PR to the upstream.

**Comment by Airblader** [comment]
I'm not looking to making major changes to i3-gaps anymore as it really hurts the ability to track upstream changes, sorry. I don't think we'll add this upstream either, though.
