### ISSUE TITLE
i3-migrate-config-to-v4 overwrites half of your config if you add spaces around '+' on 1 line

### ISSUE THREAD

**Issue by Fogapod** [Airblader/i3#405]
## I'm submitting a…

<pre>
[x] Bug
[ ] Feature Request
[ ] Documentation Request
[ ] Other (Please describe in detail)
</pre>

## Current Behavior

I added spaces around `+` in my bind commands in config because i think it looks better, the next day i booted with unusable system without any shortcuts and with default bar.
After some debugging I found that i3-migrate-config-to-v4 is responsible. For some reason it decided to overwrite my config, not understanding 3/4 lines in the process and commenting them out.
After some poking at config i was able to find line that triggers this behaviour.

`bindsym $mod+j focus left`
Note that this isn't even 1st line with bind or with `+`, but adding space there causes problem.

I am posting output of `i3-migrate-config-to-v4 ~/.config/i3/config > config` before and after I add space there:
before: https://hastebin.com/xuguvoyowu.bash
after: https://hastebin.com/guvehelawo.shell

## Environment

Output of `i3 --moreversion 2>&-`:
<pre>
Binary i3 version:  4.19.1 (2021-02-01) © 2009 Michael Stapelberg and contributors
(Getting version from running i3, press ctrl-c to abort…)%
</pre>

<details><summary>Config file</summary><pre>
hastebin because otherwise config breaks github formatting for some reason: https://hastebin.com/merecinice.bash
</pre>
</details>

<pre>
- Linux Distribution & Version: Arch Linux
- Are you using a compositor (e.g., xcompmgr or compton): xcompmgr
</pre>

**Comment by Airblader** [comment]
You seem to have deleted the hint at the top of the file. Please add

````
# i3 config file (v4)
````

back so the config parser knows not to migrate your config.

Closing as invalid & because this isn't specific to i3-gaps.
