### ISSUE TITLE
Update wiki Installation page to point to maintained PPA 

### ISSUE THREAD

**Issue by kgilmer** [Airblader/i3#406]
## I'm submitting a…

<pre>
[ ] Bug
[ ] Feature Request
[x] Documentation Request
[ ] Other (Please describe in detail)
</pre>

## Current Behavior
Example PPA link points to PPA that is no longer maintained and contains an old version of i3

## Expected Behavior
Example PPA has a relatively recent version of i3-gaps.

## Reproduction Instructions
Click link on Ubuntu PPA and see the old i3-gaps version.

## Other

Diff with updates to actively maintained PPA for i3-gaps is provided.  Additional help test also added.  
[ubuntu-wiki-update.diff.zip](https://github.com/Airblader/i3/files/6947024/ubuntu-wiki-update.diff.zip)

```diff
diff --git a/Installation.md b/Installation.md
index eca6b22..c8afb62 100644
--- a/Installation.md
+++ b/Installation.md
@@ -12,7 +12,17 @@ For Manjaro there is also a dedicated i3 community spin which comes with a preco
 
 ## Ubuntu
 
-There are several [PPAs](https://launchpad.net/ubuntu/+ppas?name_filter=i3-gaps) available, for example [this one](https://launchpad.net/~kgilmer/+archive/ubuntu/speed-ricer).
+There are several [PPAs](https://launchpad.net/ubuntu/+ppas?name_filter=i3-gaps) available, for example [this one](https://launchpad.net/~regolith-linux/+archive/ubuntu/release).
+
+To install i3-gaps, first the PPA must be added to your apt configuration and then the package may be installed.  The package name may vary depending on the PPA, as some packages may continue to use the upstream project's name `i3` while others use `i3-gaps`.  Example using PPA linked above:
+
+```bash
+sudo add-apt-repository ppa:regolith-linux/release
+sudo apt update
+sudo apt install i3-gaps
+```
+
+You will likely need to reboot in order for the login manager to recognize the new desktop session profile.
 
 ## NixOS
 

```

**Comment by kgilmer** [comment]
NOTE: I am the one that produced the packages for both PPAs.  The sources are built from: https://github.com/regolith-linux/i3-gaps-wm

**Comment by Airblader** [comment]
Thanks for letting me know! I'll busy this weekend but I'll update this next week.

**Comment by Airblader** [comment]
And done, thanks! I did shorten it, however. i3-gaps is not the right place to teach users how their package manager works.

**Comment by kgilmer** [comment]
The point I wanted to get across with the extra text was that the package name may vary based on which PPA is used (since AFAIK there is no convention for naming of i3-gaps relative to i3).  Your reduction is fine and will work perfect for the users that opt for the default (specified) PPA. :+1:
