### ISSUE TITLE
[Suggested Features] New gap positions

### ISSUE THREAD

**Issue by liar666** [Airblader/i3#409]
## I'm submitting a…

<pre>
[ ] Bug
[X ] Feature Request
[ ] Documentation Request
[ ] Other (Please describe in detail)
</pre>

## Expected Behavior

Hi,

Would be great if one could place gaps at the two following places:
- Between the tabs in tabbed mode (see brown marks in picture below)
![i3_gap_tabs](https://user-images.githubusercontent.com/3216927/129196925-3a3cbc07-4514-4592-8ece-63dc1b2cc42e.png)

- Between the workspaces names in the top bar (might not be i3 related as it's in the bar?)
![i3gaps_wsnames](https://user-images.githubusercontent.com/3216927/129197100-0fa52b6c-f042-494b-9a54-2b5e9ec7af84.png)

For the latter point, the idea is that I often open *personal* stuff in WS increasing from 0 to xxx and *professional* stuff in WS decreasing from 10 to yyy (or the converse), thus I would be interested in a means to separate the non-continuous ones WS names (e.g. 3 and 8 in the 2nd picture, not each WS name...).

**Comment by Airblader** [comment]
Thanks for opening this issue. I'm not really looking to adding further non-i3 features to i3-gaps as I've entered mostly a maintenance mode for i3-gaps (much like i3 did), but even a couple years back I probably wouldn't have wanted to add this. :-) If you care about it I would recommend patching it locally. Thanks for understanding!
