### ISSUE TITLE
Add include directive to i3 configs

### ISSUE THREAD

**Issue by ddevault** [Airblader/i3#41]
This has been rejected upstream a few times.

**Comment by Airblader** [comment]
Please keep this polite. Michael is doing a great job at i3 and there's nothing stupid about keeping out certain complexity, it's merely a choice.

**Comment by Airblader** [comment]
And since we're on the topic of reasoning, why exactly would this be relevant? Seems like a lot of overhead (parsing for includes, putting them in there, parsing again…). What exactly do you want to be includable?

**Comment by ddevault** [comment]
The use-case is to have a single shared i3 config among all of your hosts, and then include local configurations for each host to customize them.

**Comment by ddevault** [comment]
Also, it was suggested that something like `include ~/.i3/conf.d/*` would be useful, and could enable things like installing i3 configuration extensions from packages.

**Comment by Airblader** [comment]
OK. I see the usecase. I'll keep this on here for now, but I'm not sure when I will work on it. I'd also only want to add this if its effect on maintainability is reasonable.

Do you happen to have the ticket(s) or email threads when this was discussed upstream?

**Comment by Joe-Dowd** [comment]
I have this set-up currently working.
I made a script in my "~/.i3/" folder which contains "cat ~/.i3/config1 ~/.i3/config2 > ~/.i3/config"

This script is executed by "~/.xinitrc" before "exec i3"
I also have a key binding in i3 which runs the script so that the reload and restart functions can still retain layout.

Obviously its not as pretty as an include function, but it works quite well as long as you don't mind the extra keystroke before restarting.

**Comment by ddevault** [comment]
https://github.com/i3/i3/issues/1197

https://faq.i3wm.org/question/2402/split-configuration/

https://faq.i3wm.org/question/1367/anyway-to-include-in-config-file/

**Comment by Airblader** [comment]
@Joe-Dowd If you change your restart binding to trigger the script and then restart i3, you can even get rid of that extra keystroke :)

@SirCmpwn The `cat` approach seems fairly easy and straight-forward to me. It certainly avoids adding complexity to the fork (besides, Michael didn't seem to have rejected the idea). Which sort of really makes me think whether I'd want to add this at all. I prefer being able to maintain the fork and have it stay up to date over a feature that can be solved with a three line shell script. Any arguments on why that's not an option?

**Comment by ddevault** [comment]
The only problem I have with the cat solution is that it feels awfully hacky, and loses the advantage of being able to install configuration with something akin to packages (i.e. conf.d).

**Comment by ddevault** [comment]
Although a sophisticated enough script would be able to address that conf.d issue.

**Comment by Airblader** [comment]
I understand that, but I'm just not sure the benefit of adding this to the fork outweighs the benefit of maintainability. Besides, i3 is, afterall, targeted at power users, so some scripting should definitely not run someone off :)

So I think I will actually close this issue (and hope you don't think I'm stupid :) ). My suggestion would be that you write that script and open a pull request to add it to the contrib folder of i3.

**Comment by adrianmay** [comment]
I also want this feature and the logic for not doing it baffles me. It shouldn't take more than about ten lines to implement and it's clearly a powerful solution for lots of unforeseen scenarios. The foreseen scenario, namely to have most config common to multiple machines but local tweaks for keyboard layouts, number of monitors etc, is not exactly unusual, and any other workaround for the lack of an include directive is clumsy. Please just do this simple thing.
