### ISSUE TITLE
Right click quickly followed by left click when custom pixel border

### ISSUE THREAD

**Issue by ghost** [Airblader/i3#411]
## I'm submitting a…
<pre>
[X] Bug
[ ] Feature Request
[ ] Documentation Request
[ ] Other (Please describe in detail)
</pre>

## Current Behavior
When right clicking on a window (especially noticeable in Firefox) i3 left clicks shortly thereafter, with no discernible reason why.

## Expected Behavior
When right clicking, i3 sends a right click to the window being clicked on.

## Reproduction Instructions
Add `for_window [class=.*] border pixel 0` to your config

## Environment

Output of `i3 --moreversion 2>&-`:
<pre>
Binary i3 version:  4.19.1 (2021-02-01) © 2009 Michael Stapelberg and contributors
(Getting version from running i3, press ctrl-c to abort…)
</pre>

<details>
<summary>Config file:</summary>
<a href="https://pastebin.com/gndT1gHf">https://pastebin.com/gndT1gHf</a>
</details>
<details>
<summary>Installed programs (output of <code>xbps-query -l | sed --regexp-extended --expression='s/ii ([^ ]*)([[:space:]]*.*)/\1/g' --expression='s/(.*)-[^-]*/\1/g' | sort -f</code>):</summary>
<pre>
acl
acpid
adwaita-icon-theme
alsa-lib
at-spi2-atk
at-spi2-core
atk
attr
avahi-libs
base-files
base-system
bash
btrfs-progs
bzip2
c-ares
ca-certificates
cairo
confuse
coreutils
cpio
curl
dash
dbus
dbus-glib
dbus-libs
dbus-x11
dejavu-fonts-ttf
desktop-file-utils
device-mapper
dhcpcd
diffutils
dmenu
dnssec-anchors
dosfstools
dracut
e2fsprogs
e2fsprogs-libs
efibootmgr
encodings
ethtool
eudev
eudev-libudev
exa
expat
f2fs-tools
file
findutils
firefox
fish-shell
font-adobe-100dpi
font-adobe-75dpi
font-adobe-utopia-100dpi
font-adobe-utopia-75dpi
font-adobe-utopia-type1
font-alias
font-bh-100dpi
font-bh-75dpi
font-bh-lucidatypewriter-100dpi
font-bh-lucidatypewriter-75dpi
font-bh-ttf
font-bh-type1
font-bitstream-100dpi
font-bitstream-75dpi
font-bitstream-type1
font-cursor-misc
font-daewoo-misc
font-dec-misc
font-hack-ttf
font-ibm-type1
font-isas-misc
font-jis-misc
font-misc-misc
font-mutt-misc
font-util
fontconfig
freetype
fribidi
fuse
gawk
gdbm
gdk-pixbuf
git
glib
glibc
glibc-locales
gmp
gnutls
graphite
grep
groff
grub
grub-x86_64-efi
gtk+3
gtk-update-icon-cache
gzip
hicolor-icon-theme
htop
hwids
i3-gaps
i3blocks
i3blocks-blocklets
i3lock
i3lockr
i3status
iana-etc
icu-libs
inih
iproute2
iptables
iputils
ipw2100-firmware
ipw2200-firmware
iw
jansson
jbigkit-libs
kbd
kitty
kitty-terminfo
kmod
kpartx
lcms2
lemonbar
less
libaio
libarchive
libasyncns
libblkid
libcap
libcap-ng
libcap-progs
libcolord
libcrypto1.1
libcups
libcurl
libdatrie
libdb
libdrm
libedit
libefivar
libelf
libelogind
libepoxy
libev
libevdev
libevent
libfdisk
libffi
libflac
libfontenc
libgbm
libgcc
libglapi
libglvnd
libgomp
libgudev
libgusb
libharfbuzz
libICE
libidn2
libinput
libjpeg-turbo
libkmod
libldap
libldns
libllvm12
libltdl
libluv
liblz4
liblzma
libmagic
libmm-glib
libmnl
libmount
libndp
libnetfilter_conntrack
libnfnetlink
libnftnl
libnl3
libnm
libogg
libpcap
libpciaccess
libpcre
libpcre2
libpng
libpsl
libpulseaudio
libreadline8
librsvg
libsasl
libsensors
libSM
libsmartcols
libsndfile
libsodium
libsoxr
libssh2
libssl1.1
libstdc++
libtasn1
libtdb
libtermkey
libthai
libtirpc
libunbound
libunistring
libusb
libuuid
libuv
libvorbis
libvpx6
libvterm
libwacom
libX11
libXau
libxbps
libxcb
libXcomposite
libXcursor
libXdamage
libXdmcp
libXext
libXfixes
libXfont2
libXfontcache
libXft
libXi
libXinerama
libxkbcommon
libxkbcommon-x11
libxkbfile
libxml2
libXmu
libXrandr
libXrender
libxshmfence
libXt
libXtst
libXxf86misc
libXxf86vm
libzstd
linux
linux-base
linux-firmware-amd
linux-firmware-broadcom
linux-firmware-intel
linux-firmware-network
linux-firmware-nvidia
linux5.13
lm_sensors
LuaJIT
lzo
man-pages
mdocml
mesa
mesa-dri
mit-krb5-libs
mkfontscale
mobile-broadband-provider-info
msgpack
mtdev
ncurses
ncurses-base
ncurses-libs
neovim
nerd-fonts
nerd-fonts-otf
nerd-fonts-ttf
nettle
NetworkManager
newt
nghttp2
nspr
nss
nvi
oniguruma
openresolv
openssh
openssl
opus
orc
os-prober
p11-kit
pam
pam-base
pam-libs
pango
pango-xft
pciutils
perl
perl-AnyEvent
perl-AnyEvent-I3
perl-Authen-SASL
perl-Canary-Stability
perl-common-sense
perl-Convert-BinHex
perl-Digest-HMAC
perl-IO-Socket-SSL
perl-IO-stringy
perl-JSON-XS
perl-MailTools
perl-MIME-tools
perl-Net-SMTP-SSL
perl-Net-SSLeay
perl-TimeDate
perl-Types-Serialiser
perl-URI
pixman
playerctl
popt
procps-ng
python3
removed-packages
run-parts
runit
runit-void
seatd
sed
setxkbmap
shadow
shared-mime-info
slang
speexdsp
sqlite
startup-notification
sudo
tar
tiff
traceroute
tree-sitter
tzdata
unibilium
usbutils
util-linux
util-linux-common
void-artwork
vulkan-loader
wayland
wget
which
wifi-firmware
wpa_supplicant
xauth
xbps
xbps-triggers
xcb-util
xcb-util-cursor
xcb-util-image
xcb-util-keysyms
xcb-util-renderutil
xcb-util-wm
xcb-util-xrm
xf86-input-libinput
xf86-video-nouveau
xfsprogs
xinit
xkbcomp
xkeyboard-config
xorg-fonts
xorg-minimal
xorg-server
xorg-server-common
xset
xss-lock
yajl
zd1211-firmware
zlib
</pre>
</details>

<pre>
Logfile URL: unable to obtain a logfile without great hassle. If absolutely necessary I will make it happen
</pre>

<pre>
- Linux Distribution & Version: Voidlinux minimal install, fully updated <br><b>Linux 5.13.15_1 #1 SMP Fri Sep 10 16:52:33 UTC 2021 x86_64 GNU/Linux</b><br>
- Are you using a compositor (e.g., xcompmgr or compton): No
</pre>

**Comment by Airblader** [comment]
Can you reproduce this in vanilla i3? Can you describe how you determine that a left click is sent? And just to make sure, you're saying this is happening with _all_ programs, not just Firefox?

**Comment by ghost** [comment]
> Can you reproduce this in vanilla i3?

I have not tried yet but will this afternoon.

> Can you describe how you determine that a left click is sent?

I noticed that it does not just happen when clicking hyperlinks, that is just where it is most noticeable. You have a very slight window between right and left click to move the mouse between two points. This doesn't necessarily mean it's a left click, I guess, but it does increase the likeliness.

> And just to make sure, you're saying this is happening with _all_ programs, not just Firefox?

Indeed, in Discord as well, I can use the aforementioned window of time to move the mouse and, for instance, mark a channel as "read". ~~The only two programs I have installed right now that have a right click menu are Discord and Firefox, but I can install Thunar or another GUI file manager to test that it is not just Electron apps or browsers.~~ Discord, Firefox, and Thunar are affected so I will assume that it is all applications.

**Comment by ghost** [comment]
Turns out this __is__ an upstream issue, so I will be promptly closing and moving this issue. Anything else I can do to debug before I make a new issue over there? I have managed to obtain logs, so I'm going to restart then dump them.

**Comment by Airblader** [comment]
The logs should be a good place to start. I'll close this one for now, please open it upstream. Thanks!

**Comment by ghost** [comment]
This is not an i3 issue at all, just coincidental timing as I changed my config. Going to try with Chromium and then reinstall if that still does not fix it.
