### ISSUE TITLE
Request for 4.19.2 release

### ISSUE THREAD

**Issue by gkotian** [Airblader/i3#413]
[I'm intentionally not using the regular issue creation template, as this is simply a request for a new release]

I see that upstream has a [`4.19.2` release](https://github.com/i3/i3/releases/tag/4.19.2) but i3-gaps doesn't. Since you normally make a release soon after upstream, I suppose this one somehow slipped through the cracks?

**Comment by Airblader** [comment]
The upstream release only fixed an issue with the tarball that never affected i3-gaps, so there is no reason for a 4.19.2 to be released. Am I missing something?

**Comment by gkotian** [comment]
I was actually looking for this commit https://github.com/i3/i3/commit/0ad926825394f17e556a65d8a6ca83afd0822ca1 and GitHub makes it look like it was part of `4.19.2`.
![github](https://user-images.githubusercontent.com/1580240/134524552-186095b8-d451-4d6a-8925-85495830e3ae.png)

But I'm an idiot and didn't click the three dots next to the release number, or notice that the commit was made more than 6 years ago :man_facepalming:
