### ISSUE TITLE
PPA package missing/not found

### ISSUE THREAD

**Issue by kesumin** [Airblader/i3#414]
## I'm submitting a…

<pre>
[x] Bug
[ ] Feature Request
[ ] Documentation Request
[ ] Other (Please describe in detail)
</pre>

## Current Behavior

After adding ppa to apt repository, update reads out as following:
`Ign:6 http://ppa.launchpad.net/regolith-linux/release/ubuntu impish InRelease`
`Err:8 http://ppa.launchpad.net/regolith-linux/release/ubuntu impish Release
  404  Not Found [IP: 91.189.95.85 80]`
`E: The repository 'http://ppa.launchpad.net/regolith-linux/release/ubuntu impish Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.`

## Expected Behavior

ppa package download without errors

## Reproduction Instructions

`sudo add-apt-repository ppa:regolith-linux/release

sudo apt update`

## Environment

Output of `i3 --moreversion 2>&-`:
<pre>
Binary i3 version:  4.19.1-non-git © 2009 Michael Stapelberg and contributors
</pre>

<details><summary>Config file</summary><pre>
</pre>
</details>

<pre>
Logfile URL:
</pre>

<pre>
- Linux Distribution & Version: Linux debian 5.10.0-8-amd64 #1 SMP Debian 5.10.46-4 (2021-08-03) x86_64 GNU/Linux
- Are you using a compositor (e.g., xcompmgr or compton): no
</pre>

**Comment by Airblader** [comment]
I do not maintain those packages. Please contact the owners of the package directly, which seems to be the Regolith project in this case.
