### ISSUE TITLE
Suggestion: i3/#3724 into "The state of i3-gaps" (possible future merge)

### ISSUE THREAD

**Issue by Jonta** [Airblader/i3#419]
https://github.com/i3/i3/issues/3724

https://github.com/Airblader/i3/issues/417

**Comment by Airblader** [comment]
I'm sorry, I don't follow. What is your suggestion?

**Comment by Jonta** [comment]
#417 talks about i3-gaps' future

A significant future plan: Merge i3-gaps with i3

Therefore: Seemed like it might be important enough to mention in #417. =)

**Comment by Airblader** [comment]
Thanks for the suggestion. In general I'd agree, but I consider i3/i3#3724 a dead effort until the day arrives where someone starts working on it. Until then I think it's not relevant enough to mention. I appreciate your suggestion, however, thanks for that!
