### ISSUE TITLE
i have trouble compiling it

### ISSUE THREAD

**Issue by Quoteme** [Airblader/i3#43]
when i try compiling with make && sudo make install, i get following output:

> fatal: Not a git repository (or any of the parent directories): .git
> fatal: Not a git repository (or any of the parent directories): .git
> fatal: Not a git repository (or any of the parent directories): .git
> fatal: Not a git repository (or any of the parent directories): .git
> [i3] CC src/ipc.c
> In file included from ../i3-gaps/src/ipc.c:13:0:
> ../i3-gaps/src/ipc.c: In function ‘handle_get_version’:
> include/yajl_utils.h:17:50: error: expected expression before ‘)’ token
>  #define y(x, ...) yajl_gen_##x(gen, ##**VA_ARGS**)
>                                                   ^
> ../i3-gaps/src/ipc.c:822:5: note: in expansion of macro ‘y’
>      y(integer, MAJOR_VERSION);
>      ^
> include/yajl_utils.h:17:50: error: expected expression before ‘)’ token
>  #define y(x, ...) yajl_gen_##x(gen, ##**VA_ARGS**)
>                                                   ^
> ../i3-gaps/src/ipc.c:825:5: note: in expansion of macro ‘y’
>      y(integer, MINOR_VERSION);
>      ^

why does this happen, or how could I fix it?

**Comment by Airblader** [comment]
What's up with all the "Not a git repository" errors on top? In order to compile it you _must_ have a git repository so that tags are available. See #26 .

**Comment by Quoteme** [comment]
Ok, thanks. This time i used "git clone" instead of downloading the zip directly and it compiled perfectly.

**Comment by Airblader** [comment]
Glad to hear it!
