### ISSUE TITLE
Ubuntu/PopOs 22.04 installation not working

### ISSUE THREAD

**Issue by jontok** [Airblader/i3#433]
## I'm submitting a…

<pre>
[ ] Bug
[x] Feature Request
[x] Documentation Request
[ ] Other (Please describe in detail)
</pre>

## Current Behavior

No Ubuntu PPA is working! i3-gaps cannot be installed on Ubuntu 22.04 (and all Ubuntu 22.04 based Distros)

## Desired Behavior

I would like to install i3-gaps on PopOS 22.04
Please update a PPA or share instructions for the installation.

## Impact

<pre>
[ ] This feature requires new configuration and/or commands
</pre>

## Environment

Output of `i3 --moreversion 2>&-`:
<pre>
Binary i3 version:  4.20.1 (2021-11-03) © 2009 Michael Stapelberg and contributors
Running i3 version: 4.20.1 (2021-11-03) (pid 5326)
</pre>

<pre>
- Linux Distribution & Version: PopOS 22.04
- Are you using a compositor (e.g., xcompmgr or compton): yes (compton)
</pre>

**Comment by Airblader** [comment]
I do not maintain any packages for i3-gaps, this is left to the respective communities. You will have to contact the PPA maintainers.

> or share instructions for the installation.

https://github.com/Airblader/i3/wiki/Building-from-source
