### ISSUE TITLE
Outdated Fedora 36 repo package 

### ISSUE THREAD

**Issue by kjkent** [Airblader/i3#436]
## I'm submitting a…

<pre>
[x] Bug
[ ] Feature Request
[ ] Documentation Request
[ ] Other (Please describe in detail)
</pre>

## Current Behavior
Installing i3-gaps via Fedora default repo/ `dnf install i3-gaps` installs version 4.19.1.-3.fc36.

## Expected Behavior
Installing via dnf and default Fedora repo installs latest/a recent version.

## Reproduction Instructions
`dnf install i3-gaps`

## Linux Distribution & Version:
Fedora Workstation 36

**Comment by Airblader** [comment]
Please report this to the package maintainer. I don't manage the distro packages.

**Comment by kjkent** [comment]
Sure thing, I will do! Apologies for the erroneous issue and thanks for the work you do on this project.
