### ISSUE TITLE
Graphical glitches with tabs

### ISSUE THREAD

**Issue by rainerborene** [Airblader/i3#44]
`i3-gaps` isn't supposed to work with stacked and tabbed mode, right? I'm saying that because using the following configuration and still gets some graphical glitches sometimes (seems random).

```
new_window pixel 3
new_float pixel 3
```

Let me ask you a dumb question why stacked and tabbed mode does not work well with gaps? We can't get rid of the title bars entirely?

**Comment by Airblader** [comment]
It works fine with stacked and tabbed mode, but you have to disable window titles. Tabbed and stacked containers will still have the container tabs, don't worry.

The reason window titles cause issues with gaps is in the way they are created in i3. If I have time I'll try to see if I can fix it but don't get your hopes up. It's really complex code and i3 just does it in an unusual way.

**Comment by Airblader** [comment]
Closing this since it isn't really an issue. If there are further questions, feel free to ask them anyway.
