### ISSUE TITLE
Child container loses gaps

### ISSUE THREAD

**Issue by uspasojevic96** [Airblader/i3#443]
## I'm submitting a…

<pre>
[x] Bug
[ ] Feature Request
[ ] Documentation Request
[ ] Other (Please describe in detail)
</pre>

## Current Behavior
When moving a window to vsplit child container of root container, the gaps get lost inside the child
![image](https://user-images.githubusercontent.com/3018800/180612400-2e5b5e2c-9c6d-49c1-8913-87a0e4b3f505.png)

## Expected Behavior
There should be gaps

## Reproduction Instructions
Shown in screenshot that is provided
## Environment
Output of `i3 --moreversion 2>&-`:
<pre>
Binary i3 version:  4.20.1 (2021-11-03) © 2009 Michael Stapelberg and contributors
Running i3 version: 4.20.1 (2021-11-03) (pid 3577)
Loaded i3 config:
  /home/uros/.config/i3/config (main) (last modified: Sat 23 Jul 2022 05:39:46 PM CEST, 584 seconds ago)

The i3 binary you just called: /usr/bin/i3
The i3 binary you are running: i3-with-/i3
</pre>

<details><summary>Config file</summary><pre>
https://gist.github.com/uspasojevic96/484b2192bb1071aea9887bc69106d73e
</pre>
</details>

<pre>
Logfile URL:
</pre>

<pre>
- Linux Distribution & Version: Linux blacktoo 5.15.52-gentoo-dist #1 SMP Sun Jul 3 05:21:48 -00 2022 x86_64 AMD Ryzen 9 5900X 12-Core Processor AuthenticAMD GNU/Linux
- Are you using a compositor (e.g., xcompmgr or compton): picom
</pre>

**Comment by jorge-barreto** [comment]
This seems similar to the question I asked below. I think it is currently not possible without patching the behavior in. 

https://github.com/Airblader/i3/discussions/442#discussioncomment-3183677

A workaround for your particular case is to un-nest the vsplit. At the base level, you can have an vsplit in an hsplit

**Comment by Airblader** [comment]
I'm closing this issue has i3-gaps is being migrated into i3. If this issue still applies, please reopen it in i3.
