### ISSUE TITLE
Feature Request: Extension to hide_edge_borders to hide gaps too

### ISSUE THREAD

**Issue by litoj** [Airblader/i3#444]
I would love to be able to use (a variation of) `smart` setting for the `hide_edge_borders` option which would make it so, that when there is just one window on a workspace, the borders as well as the gaps would disappear.
Considering these functions are both present separately, it should be hopefuly a simple change.

**Comment by Airblader** [comment]
Aren't you just looking for `smart_gaps on`?

**Comment by litoj** [comment]
Oh, yes, I was.
Must have overlooked it.
Thank you

**Comment by litoj** [comment]
But then there is misleading description for smart gaps - it should say at least two, right?

**Comment by Airblader** [comment]
Yeah, seems like the description is wrong, indeed.
