### ISSUE TITLE
i3-Gaps Static build.

### ISSUE THREAD

**Issue by HalanoSiblee** [Airblader/i3#447]
## I'm submitting a release request
Hello :
Sorry for disturb
May you build a **Static** amd64 binaries of i3-gaps and release it !
Because I'm not able to build it.

## My PC

- OS: Debian GNU/Linux 11 (bullseye) x86_64

- Kernel: 5.10.0-16-amd64 

Thanks.

**Comment by antenore** [comment]
You can use this: https://github.com/barnumbirr/i3-gaps-debian

The deb files are in the Github releases:

https://github.com/barnumbirr/i3-gaps-debian/releases

To be clear, these builds are not supported by Debian and/or Airblader, this is just a shortcut if you DON"T want to build i3 by yourself

I'm not part of the project, just a random follower

**Comment by HalanoSiblee** [comment]
@antenore
Straight to the point 🕷 Thanks for share links.
