### ISSUE TITLE
pure mouse resizing from the gaps (like when dragging from the window borders)

### ISSUE THREAD

**Issue by quantenzitrone** [Airblader/i3#448]
## I'm submitting a…
<pre>
[ ] Bug
[x] Feature Request
[ ] Documentation Request
[ ] Other (Please describe in detail)
</pre>

## Current Behavior
In i3 and i3-gaps, it is possible to resize windows by perfectly hitting the border of a window and then dragging.

When dragging from the gaps, nothing happens.

## Desired Behavior
I think it should also be possible to resize windows from the gaps.

## Impact
I don't think this is that important since probably not a lot of people are using the pure mouse resizing, since it can be made easier with alt+right-click. 

Tho, I still think not being able to resize from the gaps but from the window borders is an unintuitive and odd behavior.

<pre>
[ ] This feature requires new configuration and/or commands
</pre>

## Environment

Output of `i3 --moreversion 2>&-`:
<pre>
i3 version: 4.20.1
</pre>

<pre>
- Linux Distribution & Version: NixOS 22.11.20220810.3a11db5
- Are you using a compositor (e.g., xcompmgr or compton): no
</pre>

**Comment by Airblader** [comment]
I'm closing this issue has i3-gaps is being migrated into i3. If this issue still applies, please reopen it in i3.
