### ISSUE TITLE
fix tabbed view+shadows

### ISSUE THREAD

**Issue by catwizard69** [Airblader/i3#45]
i'm not sure if there's a work-around here, but how easy would it be to fix the issue with shadows and tabbed view? notice how the shadows are darker around the entire tabbed frame because it's considered four separate windows, so the shadows stack. also, shadows are drawn from the window title
![screenshot](https://cloud.githubusercontent.com/assets/11712851/6889469/534536fe-d65c-11e4-8c89-a2adc3246eca.png)

**Comment by Airblader** [comment]
I know what you mean, but unfortunately this will be a "won't fix". i3 has a window for each tab (which makes sense) and changing that is basically impossible. Sorry.

**Comment by Airblader** [comment]
@catwizard69 There is an issue against i3 right now. I am implementing this and if it gets merged, you can get compton to do shadows correctly. Stay tuned. I'll reopen this for now.

**Comment by Airblader** [comment]
https://github.com/i3/i3/pull/1664

**Comment by Airblader** [comment]
This has now been merged upstream.

**Comment by CestDiego** [comment]
So, how could one set the options in compton for this shadows not to show? :O

**Comment by Airblader** [comment]
See http://www.reddit.com/r/unixporn/comments/330zxl/webmi3_no_more_overlaying_shadows_and_windows_in/

**Comment by ghost** [comment]
Hi there catwizard69 would like to know if you are the one who posted feedback regarding cymbal app? If so, please find me on cymbal as "AKP"
