### ISSUE TITLE
Thicker border on top of alacritty

### ISSUE THREAD

**Issue by imleko42** [Airblader/i3#454]
## I'm submitting a…

<pre>
[x] Bug
[ ] Feature Request
[ ] Documentation Request
[ ] Other (Please describe in detail)
</pre>

## Current Behavior

Thicker border on top of alacritty. (in the image kitty is right, and alacritty left). Issue isnt present in version 4.20.1.
![2022-09-23_22-48](https://user-images.githubusercontent.com/62111380/192057674-b38c7cc8-04be-4a7a-a90b-b713c58fe62b.png)

## Expected Behavior

Same border around all windows.

## Environment

Output of `i3 --moreversion 2>&-`:
<pre>
i3 version: 4.21
</pre>

<pre>
- Linux Distribution & Version: Arch linux
- Are you using a compositor (e.g., xcompmgr or compton): picom, issue persists when disabled
</pre>

**Comment by Airblader** [comment]
Please always look at recently closed issues to see if the issue has already been reported.

https://github.com/i3/i3/issues/5149
