### ISSUE TITLE
[Feature request] Toggle split direction

### ISSUE THREAD

**Issue by rr-** [Airblader/i3#49]
There are `split horizontal` and `split vertical` that change the orientation of the current workspace. There seems to be missing `split toggle`, though. My use case is as follows:
1. The desktop is blank.
2. I open a new window, `1`, so it has one container.
3. I open another window, `2`. The container changes like this:
   
   ```
   ### ###
   #1# #2#
   ### ###
   ```
   
    ...and the focus is given to `2`.

Now I'd like to press a hotkey that figures the current orientation for `2`'s container, and changes it, so that when I open a new window, `3`,
1. I get this:
   
   ```
   ### #2#
   #1#
   ### #3#
   ```
   
   instead of this:
   
   ```
   ## ## ##
   #1 #2 #3
   ## ## ##
   ```
2. I don't have to figure which key to press now to change the current orientation (which would be required if I used `split h|v`).

I'm aware that there is `layout toggle split`, but it acts on already opened windows, rearraging the whole layout. What I want is to change the orientation property "behind the scenes", so that it will only become visible after I actually open a new window.

I apologize if this feature is already implemented; I searched the manual and experimented with config but I just couldn't figure out a way to do what I described.

**Comment by Airblader** [comment]
Mh, can you open this as a feature request against i3 instead of my fork first, please? I'm personally really not convinced this is that useful, though.

Either way – why not implement it as a script? You can query the current layout and then issue the according opposite.

**Comment by rr-** [comment]
> Either way – why not implement it as a script? You can query the current layout and then issue the according opposite.

I just learned about IPC and it sounds good, although I'll probably need to traverse tree. Thanks.

**Comment by Airblader** [comment]
Don't worry, traversing the tree is fairly common. ;)  if you have trouble writing it feel free to comment here again. It shouldn't be all too hard though. 

As a hint: there are implementations for Python, for example, if you don't like Pert too much.

**Comment by oberon-manjaro** [comment]
Just to be sure. Is **split toggle** now included in the **gaps-next** branch?

**Comment by Airblader** [comment]
Yes

**Comment by oberon-manjaro** [comment]
Awesome! It's working brilliantly :laughing: I LOVE it!
Thank you. Pushing the package to unstable now.
