### ISSUE TITLE
Implement IPC command that returns current mode

### ISSUE THREAD

**Issue by s-ol** [Airblader/i3#50]
This would allow to add a mode-indicator to 3rd-party bars (for example a powerline segment would just use `i3-py` and call to something like `get_mode`).

**Comment by Airblader** [comment]
Can you please report this against i3? I don't see why it shouldn't be added there. However, I think it makes more sense to implement and event rather than a command as with a command constant polling would be necessary.

**Comment by s-ol** [comment]
okay, moved to i3/i3#1707
