### ISSUE TITLE
smart_gaps just for specific workspaces?

### ISSUE THREAD

**Issue by CestDiego** [Airblader/i3#53]
Thank you for this repo, it's been great, one thing though, is it possible to assign `smart_gaps` _only_ for certain workspaces?

As in

```
smart_gaps off
workspace 1 smart_gaps on
```

**Comment by Airblader** [comment]
No, this isn't possible. I also don't think it's worth adding. However, you can easily write a script that listens to the correct events to implement a per workspace smart gaps.

**Comment by CestDiego** [comment]
I tried running `i3-message smart_gaps_on` when switching to a workspace 1, but didn't work, is there another way of sending info about smart_gaps?

**Comment by Airblader** [comment]
If anything, it'd be `smart_gaps on` (no underscore before `on`), but `smart_gaps` is a config directive, not a command. You cannot send it at runtime (or for specific workspaces). Also, it's `i3-msg`, not `i3-message`.

You would have to write a script that listens to the "workspace" / "window" events on the IPC, count the windows on the workspace (by issuing a `get_tree` command and parsing the output) and then sending a corresponding `gaps` command.

**Comment by CestDiego** [comment]
Ye, it was a typo. So it'll kinda be reimplement smart_gaps? in a script? I would do smart_gaps off, and then listen to all workspaces, and their windows, and put a conditional that if it's the only window and not workspace x. to set outer, and inner borders to zero or something?...

**Comment by Airblader** [comment]
Yes, exactly. I know that's not very satisfying, but I'd really like to not implement this. It doesn't really seem like a strong usecase to me either and I'd have duplicate maintenance effort for both a config directive and a command.

I already have this with the gaps itself and it's really not pretty.

**Comment by CestDiego** [comment]
Ok, another question though, so is it possible to have sticky windows?

**Comment by Airblader** [comment]
No, this is currently not possible (note that this is an i3 question, not an i3-gaps question). However, there are two accepted feature requests for this (they just haven't been implemented yet):
- https://github.com/i3/i3/issues/1455 for displaying a floating sticky window on the focused workspace even if that changes
- https://github.com/i3/i3/issues/11 for displaying a window on all active workspaces (including tiling)

I'll close this issue here now, but you can keep commenting if you have more questions.

**Comment by CestDiego** [comment]
Thank you for your time :) I'll look into the IPC
