### ISSUE TITLE
Installing i3-gaps on Ubuntu 15.04 ends up with broken installation

### ISSUE THREAD

**Issue by petterroea** [Airblader/i3#55]
What it says on the tin. Some commands(such as Alt+D) cause the error `status_command not found or is missing a library dependency`, and the configuration file does not write to ~/.i3 after you are asked to generate a config file.

How i installed:

```
git clone https://www.github.com/Airblader/i3 i3-gaps
cd i3-gaps
git checkout gaps && git pull
make 
make install
```

Dependencies installed:

```
libxcb1-dev libxcb-keysyms1-dev libpango1.0-dev libxcb-util0-dev libxcb-icccm4-dev libyajl-dev libstartup-notification0-dev libxcb-randr0-dev libev-dev libxcb-cursor-dev libxcb-xinerama0-dev libxcb-xkb-dev libxkbcommon-dev libxkbcommon-x11-dev
```

(all the dependencies from here [https://github.com/Airblader/i3/wiki/Compiling-&-Installing](https://github.com/Airblader/i3/wiki/Compiling-&-Installing) )

OS: Ubuntu 15.04

Installation log:

```
[libi3] CC libi3/get_process_filename.c
[libi3] CC libi3/safewrappers.c
[libi3] CC libi3/root_atom_contents.c
[libi3] CC libi3/is_debug_build.c
[libi3] CC libi3/get_mod_mask.c
[libi3] CC libi3/string.c
[libi3] CC libi3/ipc_connect.c
[libi3] CC libi3/get_config_path.c
[libi3] CC libi3/ucs2_conversion.c
[libi3] CC libi3/dpi.c
[libi3] CC libi3/font.c
[libi3] CC libi3/get_exe_path.c
[libi3] CC libi3/resolve_tilde.c
[libi3] CC libi3/get_colorpixel.c
[libi3] CC libi3/strndup.c
[libi3] CC libi3/fake_configure_notify.c
[libi3] CC libi3/ipc_send_message.c
[libi3] CC libi3/mkdirp.c
[libi3] CC libi3/get_visualtype.c
[libi3] CC libi3/ipc_recv_message.c
[libi3] AR libi3.a
[i3] CC src/resize.c
[i3] CC src/log.c
[i3] CC src/debug.c
[i3] Generating command parser
[i3] CC src/commands_parser.c
[i3] CC src/regex.c
[i3] CC src/config.c
[i3] CC src/restore_layout.c
[i3] CC src/fake_outputs.c
[i3] CC src/bindings.c
[i3] CC src/manage.c
[i3] CC src/con.c
[i3] CC src/xinerama.c
[i3] CC src/scratchpad.c
[i3] CC src/match.c
[i3] CC src/main.c
[i3] CC src/window.c
[i3] CC src/move.c
[i3] CC src/key_press.c
[i3] CC src/x.c
[i3] CC src/config_directives.c
[i3] CC src/load_layout.c
[i3] CC src/output.c
[i3] CC src/floating.c
[i3] CC src/xcb.c
[i3] CC src/ipc.c
[i3] CC src/sd-daemon.c
[i3] CC src/version.c
[i3] CC src/commands.c
[i3] CC src/randr.c
[i3] CC src/xcursor.c
[i3] CC src/util.c
[i3] CC src/workspace.c
[i3] CC src/click.c
[i3] Generating config parser
[i3] CC src/config_parser.c
[i3] CC src/sighandler.c
[i3] CC src/ewmh.c
[i3] CC src/assignments.c
[i3] CC src/handlers.c
[i3] CC src/display_version.c
[i3] CC src/render.c
[i3] CC src/startup.c
[i3] CC src/tree.c
[i3] Link i3
[i3] Link test.commands_parser
[i3] Link test.config_parser
[i3-config-wizard] CC i3-config-wizard/main.c
[i3-config-wizard] Link i3-config-wizard
[i3-msg] CC i3-msg/main.c
[i3-msg] Link i3-msg
[i3-input] CC i3-input/keysym2ucs.c
[i3-input] CC i3-input/main.c
[i3-input] Link i3-input
[i3-nagbar] CC i3-nagbar/main.c
[i3-nagbar] Link i3-nagbar
[i3bar] CC i3bar/src/outputs.c
[i3bar] CC i3bar/src/parse_json_header.c
[i3bar] CC i3bar/src/config.c
[i3bar] CC i3bar/src/workspaces.c
[i3bar] CC i3bar/src/mode.c
[i3bar] CC i3bar/src/ipc.c
[i3bar] CC i3bar/src/main.c
[i3bar] CC i3bar/src/xcb.c
[i3bar] CC i3bar/src/child.c
[i3bar] Link i3bar
[i3-dump-log] CC i3-dump-log/main.c
[i3-dump-log] Link i3-dump-log
```

```
[i3] Install
[i3-config-wizard] Install
[i3-msg] Install
[i3-input] Install
[i3-nagbar] Install
[i3bar] Install
[i3-dump-log] Install
```

Version:

```
Binary i3 version:  4.10.3-347-g586854b (2015-07-30, branch "gaps") © 2009-2014 Michael Stapelberg and contributors
Running i3 version: 4.10.3-347-g586854b (2015-07-30, branch "gaps") (pid 1774)

The i3 binary you just called: /usr/bin/i3
RUNNING BINARY DIFFERENT FROM BINARY ON DISK!
The i3 binary you are running: i3
```

Log:

[logs.i3wm.org/logs/5629652273987584.bz2](logs.i3wm.org/logs/5629652273987584.bz2)

**Comment by Airblader** [comment]
> Some commands(such as Alt+D) cause the error status_command not found or is missing a library dependency

Well, what is Alt+D bound to in your config? This hardly seems like an installation issue. The log file you provided claims that you have no keybinding involving the Alt key in your i3 config.

> and the configuration file does not write to ~/.i3 after you are asked to generate a config file.

I think the default path changed to `~/.config/i3/` recently. This is vanilla i3, though, and has nothing to do with i3-gaps in particular.

> The i3 binary you just called: /usr/bin/i3
> RUNNING BINARY DIFFERENT FROM BINARY ON DISK!
> The i3 binary you are running: i3

Did you notice this warning?

The actual compiling and installation process seems fine and none of these things are any different between i3 and i3-gaps.

**Comment by petterroea** [comment]
The bottom bar does not show it's normal status stuff either.

The log is from the first time i3 was ran, so it will start with no binding for Alt+D. The first-run wizard should of generated a config for it, and keying the combination causes the mentioned error. This is why i believe there is a software problem, and not a configuration/installation issue. 

When it comes to the warning, i trusted that the installer did it's job and trusted that it was supposed to be like that.

Also, note that this is installed on a completely fresh copy of ubuntu.

I'l install i3 again tomorrow and get check out the rest of your points, though.

**Comment by Airblader** [comment]
> The bottom bar does not show it's normal status stuff either.

Can you please be more precise? Also, i3status is a tool that you have to install separately as it is a separate tool. So without instlaling it, the statusbar will, of course, not work out of the box.

> The first-run wizard should of generated a config for it, and keying the combination causes the mentioned error.

So I assume that the binding you expect is for calling dmenu? dmenu is also a separate tool that you need to install. It won't work otherwise.

**Comment by petterroea** [comment]
Aight. I think i see the issue. Having lived off the ubuntu-repository that was supplied for i3, i am oblivious to the fact that i need to install dmenu and i3status seperately. I'l close the issue, and rather re-open if lacking additional tools is not the issue.
