### ISSUE TITLE
Enhancement: Merge title_format functionality from vanilla i3

### ISSUE THREAD

**Issue by setzer22** [Airblader/i3#57]
The title_format feature is already implemented in main i3, but it seems to be missing on i3-gaps (latest commit, I just pulled the repo). Seeing that @Airblader is both the maintainer of this fork and the developer who implemented the feature, is there any reason this can't get merged? Or is it just a matter of time?

Thank you!

**Comment by Airblader** [comment]
It is merged. You'll need gaps-next though which is the equivalent of i3's next branch. i3-gaps is completely up to date with vanilla i3.
