### ISSUE TITLE
Compton compositing software conflict.

### ISSUE THREAD

**Issue by thejimble** [Airblader/i3#58]
i3's handling of window closing (destroying and freeing the pixbuff) completely removes compton compositing software's "fade out" feature's method of action, which relies on the closing window's pixbuff to draw the fading effect. This occurs even in windows which are closed natively, and with bordered windows as well, as I had thought a previous i3 patch involving avoiding unnecessary pixbuffs on borderless windows was the culprit. I have not yet tested whether this is an issue with vanilla i3, though I would wager it is. I would consider this a minor issue, as I cannot find any forum posts or related material referencing it, even though it is reproducible. I first encountered this issue on Arch, using the i3-gaps-git package from the user repository (packaged Sept. 8th). Let me know your thoughts, or if there's any more information I can provide.

**Comment by Airblader** [comment]
If anything, it's vanilla i3. However, we don't support compositing, so unless you find a way to make this a problem not related to compositing, it will be closed there as well. Sorry.
