### ISSUE TITLE
Inner/outer window border with different width and color

### ISSUE THREAD

**Issue by okraits** [Airblader/i3#65]
Hi,

this is just an idea of mine because i like the looks of double window borders. Did you ever think about implementing a second window border which can be configured to have a different width and color?

I'm thinking about something like 2bwm has.

Greetings,

Oliver

**Comment by Airblader** [comment]
I'm going to leave this to 2bwm as a feature. :)

**Comment by okraits** [comment]
Ok, nevermind :)
