### ISSUE TITLE
No transparency with i3blocks bar

### ISSUE THREAD

**Issue by nscott32** [Airblader/i3#66]
Hello,

I am not sure it is the right place to ask, but how can I get i3blocks transparent ?
I switched to i3-gaps because transparency is implemented for i3bar but I'm not sure it worked with i3blocks.

I have tried to add -t in two ways `i3bar_command i3blocks -t` and `status_command i3blocks -t` but it fails loading the bar becaus of the `-t` option.

Thank you

**Comment by Airblader** [comment]
It's only available on the `gaps-next` branch at the moment.

**Comment by reikdas** [comment]
Is it possible to add transparency with i3blocks now? `status_command i3blocks -t` doesn't work.

**Comment by Airblader** [comment]
i3blocks has nothing to do with it. The flag goes to the bar command, not the status command. You can see an example in the README.
