### ISSUE TITLE
Question: How to set top padding for custom bar program?

### ISSUE THREAD

**Issue by justbuchanan** [Airblader/i3#67]
I'm trying to use a custom bar program instead of  i3bar, which I launch via the `i3bar_command` in the i3 config file.  The problem though is that i3 doesn't leave room for the bar at the top the same way it does with the default bar.  Any suggestions on how to make this work?  Thanks!

**Comment by Airblader** [comment]
That's nothing i3 has to do. The bar has to request space from the window manager. If you use lemon, I think the common workaround that people use is an invisible fake conky instance to reserve the space.

**Comment by justbuchanan** [comment]
Makes sense, thanks!

**Comment by dennisotugo** [comment]
Any idea for the settings for this invincible conky? 
This is mine, it does not work. I need a padding of 30px above windows. Any ways to achieve this?
`alignment top_right
background yes
minimum_size 1 30
maximum_width 1
border_width 0
own_window yes
own_window_type dock
own_window_class conky
own_window_argb_visual yes
own_window_transparent yes
own_window_hints below  
short_units yes
use_xft yes
xftfont Roboto Slab:size=9 
gap_x 1
gap_y 0
own_window_argb_value 0
own_window_colour 000000`
