### ISSUE TITLE
cannot set border in i3blocks.

### ISSUE THREAD

**Issue by HiCodin** [Airblader/i3#69]
Hi Airblader,

I am trying to set border for blocks in i3blocks but whenever I am trying to set border, I am having an error. The error is `Error: status_command process exited unexpectedly (exit 1)`. I am using your i3-gaps also.

**Comment by HiCodin** [comment]
ah nvm. i didn't know that I had to use your fork of i3blocks. now that i installed the fork, i can set the borders ! but i loses the color for all the blocklets except for the one which is defined in the script itself.

**Comment by Airblader** [comment]
Sorry, I have no idea what that last comment means. Can you please be specific with what your config looks like and a screenshot?

**Comment by HiCodin** [comment]
sorry, i should've been clearer. seems like the issue is from [i3blocks](https://github.com/vivien/i3blocks/issues/146) where `color` key has no effect. So, i guess this can be closed as the original issue has been solved.
