### ISSUE TITLE
Example of setting border width on individual blocks?

### ISSUE THREAD

**Issue by pr0letariat** [Airblader/i3#70]
I have seen the JSON that you need to pass to the i3 bar. Are there any real world example configurations you know of this? I don't understand how to do it. I tried putting the JSON in my `~/.i3/config` in the `bar` part but I got an error. Do you use the `full_text` name of the block in `i3blocks.conf`?

**Comment by Airblader** [comment]
The border attributes are part of the JSON stream for the statusline, not of the i3 / i3bar config. An example can be seen in my dotfiles. Since I use i3blocks but i3blocks does not support those attributes, you'd need to use my fork i3blocks-gaps.

https://github.com/Airblader/dotfiles-manjaro/blob/master/.i3blocks.conf

**Comment by pr0letariat** [comment]
Something like this? In my `i3blocks.conf`:

```
[example]
{ \
  "full_text": "example", \
  "color": "\#FFFFFF", \
  "background": "\#222222", \
  "border": "\#9FBC00", \
  "border_bottom": 0 \ 
}
```

Doesn't work. I am using your fork since I have other blocks that use the `border` attribute okay.

**Comment by Airblader** [comment]
You can't just put JSON in your i3blocks config. Please refer to my own i3blocks config I linked above. An example would look like this:

```
[example]
full_text=example
color=#FFFFFF
background=#222222
border=#9FBC00
border_bottom=0
```

**Comment by pr0letariat** [comment]
Thank you, that makes sense. I just had a quick play with it, I was using the `border=#FFFFFF` before, which creates an underlining effect which I really like.

Is it possible to extend the underlining effect past the block text? For example:

![selection_002](https://cloud.githubusercontent.com/assets/14975253/13392371/e9211804-ded1-11e5-8309-df5889c36e09.png)

**Comment by Airblader** [comment]
Yes, but it sort of depends. If you display a static text like `test`, you can do

```
full_text=test
min_width=__test__
```

If it's a dynamic information (temperature, time or whatever), you can either use `min_width=100` or you can just pad the output with spaces:

```
command=printf "  %.0f  " $(somecommand)
```
