### ISSUE TITLE
Enhancement: Add ability to override default outer gap behaviour

### ISSUE THREAD

**Issue by Marneus68** [Airblader/i3#71]
Hello, 

I was curious to know if a way to prevent to the addition of the outer gap value to the inner gap value was planner and/or easy to implement.
The idea would be to allow for containers to have gaps in between other containers but no gaps between them and the edge of the screen.

I'm not well versed into the i3 codebase but know my way around C and C++, if this sounds doable I could probably help implement it with a bit of guidance.

That's a feature I'd love to have and could definitely lend a hand to implement.

**Comment by Airblader** [comment]
I'm not really looking into making this possible, sorry. The gaps command is already more than complex and adding the inner gaps to the outer gaps was a specific decision I made back then.

Of course, I'll be happy to help you if you want to write a patch for yourself. For a start, try removing this line:

https://github.com/Airblader/i3/blob/gaps-next/src/con.c#L2051

This might already do everything you need.

**Comment by Airblader** [comment]
(Closing this issue since I won't put this into i3-gaps, but feel free to keep talking on here.)

**Comment by Marneus68** [comment]
Thanks for the quick answer and the little direction. I'll look into it asap. I'll keep you posted if I manage to do something presentable.

**Comment by Marneus68** [comment]
Hello @Airblader ,

Sorry to bother you but I've made some progress in implementing this feature. Removing the portion of code you pointed me to does the job, and I've now added an enum to drive it in the container structure. The whole container/workspace/window structure has been quite simple to grasp, at least in concept, but now I would like to implement a way to drive the gap behavior globally (or maybe per workspace) via the configuration file and I'm a bit more puzzled by the structure of the config parser and the way it operates.

I created a branch in my own fork over here https://github.com/Marneus68/i3/tree/feature-noncumulative-gaps in case you're interested in getting a better idea of where I'm at right now.

I'd appreciate any tip on how to proceed.

Best regards;

**Comment by Airblader** [comment]
@Marneus68 First of all you need to decide whether you want a config directive or a command (or both). Then you need to define what it should look like. Only then should you start implementing it. :)

As for "how to do it", the easiest course of action would probably be to use `git log` on the corresponding parser spec, find a commit which added a directive / command and then just take a look at that commit in its entirety to see what you need to do.

You could even specifically look at the diff between upstream `next` and my fork's `gaps-next`. While it contains a few other things, it's still (or rather, once again) a relatively small diff.
