### ISSUE TITLE
no transparency in i3bar

### ISSUE THREAD

**Issue by HiCodin** [Airblader/i3#72]
Hi Airblader,

I am using your gaps-next branch but I can't get transparency to work for my i3bar.
The transparency doesn't work even if i copy your i3bar settings or someone else's.

here is my i3config - http://pastebin.com/G9TyJqK

**Comment by Airblader** [comment]
> This page is no longer available. It has either expired, been removed by its creator, or removed by one of the Pastebin staff.

Also, did you make sure to read the README on the i3bar transparency?

**Comment by HiCodin** [comment]
is compton needed for transparency ? coz I got the transparency working after installing comption. :D

**Comment by Airblader** [comment]
Yes, of course. Without compositing there can't be transparency.
