### ISSUE TITLE
Focus border color not leaving the second screen

### ISSUE THREAD

**Issue by ghost** [Airblader/i3#74]
i3 version 4.12 (2016-03-06, branch "4.12")

opened a new terminal on my external screen , then i try to move the focus to my main screen.
but the highlighted terminal on the second screen didn't go away.

**Comment by Airblader** [comment]
Sorry, I should've been clearer: please report it against upstream i3 since it's not related to i3-gaps specific functionality.

When reporting it there, please also include the log file and your config.
