### ISSUE TITLE
Desktop drawing error on gaps

### ISSUE THREAD

**Issue by l4rzy** [Airblader/i3#76]
### info

Binary i3 version:  4.12-51-gf6b2f05
Running i3 version: 4.12-51-gf6b2f05
(with composite manager: compton)
### problem

It was ok to change terminal (urxvt) gaps size. But if new client open in that workspace, the top of desktop will have error, I don't know how to describe this, so take a look at my screenshot 
http://i.imgur.com/82YQLKH.jpg
I think the problem is lacking of updating the root window after opening new client on gaps workspace (correct me). Thanks!

**Comment by Airblader** [comment]
Quoting the very first sentence on gaps in the README:

> Note: Gaps will only work correctly if you disable window titlebars entirely. Unfortunately this is necessary due to the way i3 creates such bars on windows. You can disable them via for_window [class="^.*"] border pixel 0 in your config. You can also use any non-zero value as long as you only use pixel-style borders.

But please do read the entire README.

**Comment by l4rzy** [comment]
Sorry, I didn't read it carefully
