### ISSUE TITLE
no bug

### ISSUE THREAD

**Issue by carepack** [Airblader/i3#77]
sorry,

but I can't send you a direct message. How the hell you created this beatuful design? especially the top bar and the symbols? I wan it too. Sorry for using the bug reportet to contact.

thx

**Comment by Airblader** [comment]
No worries. I'll close it, but you can keep asking questions if you want!

All my dotfiles can be found here: https://github.com/Airblader/dotfiles-manjaro
I use i3blocks-gaps (a small fork of i3blocks), the transparency i3-gaps offers and a bunch of custom-written scripts.

My bar is by now entirely transparent, FYI.

**Comment by Airblader** [comment]
Also thank you! :)

**Comment by carepack** [comment]
what and how would you remommend to switch from my i3 installation to i3-gaps and i3blocks-gaps to achieve the same design like you? Aksing this only because of university stress I have not much time to figure things out. But I want the design :-). Fast! 

Any advice or recommendation would be appreciated. Thx once again!

**Comment by Airblader** [comment]
Well you need to install i3-gaps and i3blocks-gaps. Follow the instructions on i3bar transparency in the i3-gaps README, take my i3blocks config and either also take over the scripts from there or change it to your liking.

Unfortunately there's no oneliner I can give you and I refuse to compile a long step by step list. I understand that you have little time, so do I, but then take it one step at a time and learn along the way. :)

**Comment by carepack** [comment]
that's not a one liner was clear ;). I played a little bit. my icons are not clear as yours on the picture in the bar und not clickable. any idea? but anyway. a big design improvement  anyway!!!!

**Comment by carepack** [comment]
ok. I think two little things then I would be satisfied for the moment. 
1. Running apps should appear in the statusline? for exmple nm, dropbox etc.
2. Where got you all the litte icons for wlan etc. I miss them all.

Sorry for annoying you!

**Comment by Airblader** [comment]
> Running apps should appear in the statusline? for exmple nm, dropbox etc.

If you mean in the top right of my i3bar, those are tray icons. They need to be provided by the application. For example, for networkmanager, run `nm-applet`. If your i3 config has `tray_output primary` and you don't see the icons, just delete that line and restart i3.

> Where got you all the litte icons for wlan etc. I miss them all.

https://fortawesome.github.io/Font-Awesome/icons/

**Comment by carepack** [comment]
how to donate? perfect. My mistake with the tray ouptut! And with the symbols all fine now!
One last question:
http://imgur.com/VYgCgGY

was ist der rote schraubenschlüssel?

**Comment by Airblader** [comment]
> how to donate?

I'm not doing this for money. :)

> was ist der rote schraubenschlüssel?

It's the number of packages ready to update (if you're on an Arch system). The block only shows up when updates are available.

**Comment by carepack** [comment]
:-) beer or a coffee?

Really cool setup and nice looking! i3 gaps tries to stay close to i3wm / upstream?

**Comment by Airblader** [comment]
> :-) beer or a coffee?

If it made your day better, that's enough for me, but thank you. ;)

> i3 gaps tries to stay close to i3wm / upstream?

Yes, I'm actually an active collaborator for upstream as well and it's rarely more than a few hours after a new commit in upstream until I update i3-gaps. Keeping i3-gaps up to date with upstream is currently my main focus for i3-gaps.

**Comment by carepack** [comment]
yes it does :-) candy for my eyes! nice to hear thats your main focus!

thank you very much. Goin' to see you sometime in munich! :-)

**Comment by carepack** [comment]
once again :-)
whats your method to identify the active window? soewhere i red that that the colored borders of an active window showing is not possible atm.
Is there something else except changing my window organization?

**Comment by Airblader** [comment]
You can have borders, just not titlebars. So using a border like `pixel 3` is fine. If you use a compositor (which you absolutely should), even titlebars, by now, work "mostly". I'd still not suggest activating them, though, it's still glitchy.

However, I've also used i3-gaps for a long time without any border. I'm not a fish, so I don't constantly forget which window is focused… :) But anyway, jjust use pixel borders to differentiate with a color.

**Comment by carepack** [comment]
very cool. I like the mix of colors and the borderless, transparent style. i3 in beauty. In the status bar the the icons are now visible. I adopted youre bashrc and vimrc. No I have the icons problem again. He shows only weired quarters. Any additional font pack?

**Comment by Airblader** [comment]
I use the powerline-patched version of the Hack font.

**Comment by carepack** [comment]
perfect! Once again thank you very much! I love the mod!

**Comment by Airblader** [comment]
Thanks. :)
