### ISSUE TITLE
Uninstall capability in makefile

### ISSUE THREAD

**Issue by RoundDuckKira-deprecated** [Airblader/i3#78]
This needs to happen, if I want to remove i3-gaps before upgrading my Ubuntu, I should be able to delete i3-gaps without needing checkinstall, by using `sudo make uninstall`

**Comment by Airblader** [comment]
For starters, such a request belongs into upstream i3 as it's not related to gaps. However, this has been brought up before and denied. Properly installing and uninstalling software is the job of the package manager or at the very least the package maintainer. For example the man pages aren't even installed from the Makefile at all, so it couldn't uninstall them if it wanted to.

**Comment by Airblader** [comment]
See also https://faq.i3wm.org/question/5175/uninstall-from-sources/
