### ISSUE TITLE
Help Please! Can I move status bar in screen?

### ISSUE THREAD

**Issue by kuzuka** [Airblader/i3#84]
I want to "move" status bar away from screen borders, to give it 5 pixels gaps like a window. Can I realise it?

**Comment by Airblader** [comment]
No, that's not possible with i3bar. You'll need to switch to something like lemonbar for this.

**Comment by kuzuka** [comment]
Why you aren't going to add thus feature?

**Comment by Airblader** [comment]
Because my primary goal is to keep i3-gaps up to date with upstream and this is a rather large change of which no part will be accepted upstream. i3bar already frequently causes merge conflicts, so I want to avoid making things worse.
