### ISSUE TITLE
i3bar transparency interfears with disabling tray ouput

### ISSUE THREAD

**Issue by jakevossen5** [Airblader/i3#85]
Output of `i3 --moreversion 2>&- || i3 --version`:

Binary i3 version: 4.12 (2016-03-06, branch "4.12") © 2009 Michael Stapelberg and contributors (Getting version from running i3, press ctrl-c to abort…)
Running i3 version: 4.12 (2016-03-06, branch "4.12") (pid 1600) Loaded i3 config: /home/jakev/.config/i3/config (Last modified: Wed 18 May 2016 11:42:28 PM MDT, 338 seconds ago) The i3 binary you just called: /usr/bin/i3 The i3 binary you are running: i3

URL to a logfile as per http://i3wm.org/docs/debugging.html:

logs.i3wm.org/logs/5660765553950720.bz2

**What I did:**

Enabled Transparency for i3bar and disables application icons

**What I saw:**

Enabling transparency with `i3bar_command i3bar -t` and disabling tray output with `tray_output none` makes the bar as a whole dissapear 

**What I expected instead:**
The bar should have stayed, stayed transparent, but disabled tray_output

**Comment by Airblader** [comment]
Can you start i3bar with debug mode as described here[1](at the very end)? Does i3bar show up this way or also disappear? When it disappears, does it still take up its space? Also please post the log file from doing this (the i3 log file probably won't help here).

**Comment by jakevossen5** [comment]
I can run i3bar in debug mode, but it has no transparency, although tray icons are gone.

All I get in debug mode was this

```
[libi3] libi3/font.c Using Pango font System San Francisco Display, size 8
[libi3] libi3/font.c X11 root window dictates 96.252632 DP
```

Although, the link you gave was dead, so I used this one instead https://i3wm.org/docs/debugging.html for the instructions

It does not take up any space, and it seems not to work at all because `killall i3bar` returns `i3bar: no process found
`

It never appears on the screen.

**Comment by jakevossen5** [comment]
It appears that it was a user error on my part.

After restoring a backup and redoing the edit, it seemed to work, which means I probably entered something wrong into my config. I am sorry. 

Have a good day.
