### ISSUE TITLE
smart_transparency

### ISSUE THREAD

**Issue by DanielVoogsgerd** [Airblader/i3#86]
I like i3gaps for both the gaps and the statusbar transparency, but when using smart gaps I feel that the transparent statusbar is quite out of place. Is it possible to include some sort of smart_transparency option to ignore the alpha channels when there is just a single window on screen?

I can understand if this feature request might be usage specific or gnarly to implement.

**Comment by Airblader** [comment]
> I can understand if this feature request might be usage specific or gnarly to implement.

Which is exactly why I'll reject it, sorry. This involves changing the background color at runtime, which is new, as well as i3 communicating with i3bar about the number of windows, which violates i3bar's idea of only caring about workspaces, not individual windows. It seems way too specific to be worth all the effort going into this, in particular the effort to maintain it.

**Comment by DanielVoogsgerd** [comment]
No problem, thanks anyway.
