### ISSUE TITLE
Unable to build gaps-next on ubuntu

### ISSUE THREAD

**Issue by aarobc** [Airblader/i3#88]
On Ubuntu 16.04 LTS 64 bit.
**What I did:**

verify all the dependencies listed in required in the readme. 
ran `make`

**What I saw:**

```
../i3-gaps-next/src/config_parser.c:38:25: fatal error: xcb/xcb_xrm.h: No such file or directory
compilation terminated.
src/i3.mk:58: recipe for target 'src/config_parser.o' failed
make: *** [src/config_parser.o] Error 1
```

**Other things I tried** 
For the sake of having a consistent build environment, I set up a docker image with the listed required dependencies. I've uploaded it here: https://hub.docker.com/r/aarobc/build_i3_env.
I then placed this docker-compose.yml file in the parent directory of the code directory:

```
builder:
  image: aarobc/build_i3_env 
  volumes:
    - ./i3-gaps:/opt/code
```

then ran:
`docker-compose run --rm builder make` but got the same error. 

I've tried using different ubuntu base images but always would get this error. Any ideas?

**Comment by Airblader** [comment]
We recently started depending on a new library[1] which is probably not configured in your image and probably also not (yet?) available on Ubuntu. You'll need to compile it from source.

[1] https://github.com/Airblader/xcb-util-xrm

**Comment by Airblader** [comment]
> verify all the dependencies listed in required in the readme. 

I guess you mean the wiki. You're right that xcb-util-xrm is not listed there yet. I'll update the wiki.
