### ISSUE TITLE
ubuntu 16.04 problem using make

### ISSUE THREAD

**Issue by christiankaseburg** [Airblader/i3#89]
I installed all the dependenices and I am on ubuntu 16.04, but when I try to do the make command I get this error:
/usr/src/i3-gaps$ sudo make
[i3] CC src/config_parser.c
../i3-gaps/src/config_parser.c:38:25: fatal error: xcb/xcb_xrm.h: No such file or directory
compilation terminated.
src/i3.mk:58: recipe for target 'src/config_parser.o' failed
make: **\* [src/config_parser.o] Error 1

Can I get some help?

I got this far but when I update i3 with super+shift+r nothing changes.

Here is my make :
christian@uBunny:/usr/src/i3-gaps$ sudo make
[libi3] CC libi3/format_placeholders.c
[libi3] CC libi3/draw_util.c
[libi3] CC libi3/get_process_filename.c
[libi3] CC libi3/safewrappers.c
[libi3] CC libi3/root_atom_contents.c
[libi3] CC libi3/is_debug_build.c
[libi3] CC libi3/get_mod_mask.c
[libi3] CC libi3/string.c
[libi3] CC libi3/ipc_connect.c
[libi3] CC libi3/get_config_path.c
[libi3] CC libi3/ucs2_conversion.c
[libi3] CC libi3/dpi.c
[libi3] CC libi3/font.c
[libi3] CC libi3/get_exe_path.c
[libi3] CC libi3/resolve_tilde.c
[libi3] CC libi3/get_colorpixel.c
[libi3] CC libi3/strndup.c
[libi3] CC libi3/fake_configure_notify.c
[libi3] CC libi3/ipc_send_message.c
[libi3] CC libi3/mkdirp.c
[libi3] CC libi3/get_visualtype.c
[libi3] CC libi3/ipc_recv_message.c
[libi3] AR libi3.a
[i3] CC src/resize.c
[i3] CC src/move.c
[i3] CC src/randr.c
[i3] Generating command parser
[i3] CC src/commands_parser.c
[i3] CC src/regex.c
[i3] CC src/config.c
[i3] CC src/restore_layout.c
[i3] CC src/bindings.c
[i3] CC src/manage.c
[i3] CC src/log.c
[i3] CC src/xinerama.c
[i3] CC src/scratchpad.c
[i3] CC src/match.c
[i3] CC src/commands.c
[i3] CC src/ewmh.c
[i3] CC src/key_press.c
[i3] CC src/x.c
[i3] CC src/config_directives.c
[i3] CC src/load_layout.c
[i3] CC src/output.c
[i3] CC src/floating.c
[i3] CC src/ipc.c
[i3] CC src/sd-daemon.c
[i3] CC src/version.c
[i3] CC src/window.c
[i3] CC src/con.c
[i3] CC src/main.c
[i3] CC src/handlers.c
[i3] CC src/xcursor.c
[i3] CC src/util.c
[i3] CC src/workspace.c
[i3] CC src/xcb.c
[i3] CC src/click.c
[i3] Generating config parser
[i3] CC src/config_parser.c
[i3] CC src/sighandler.c
[i3] CC src/fake_outputs.c
[i3] CC src/debug.c
[i3] CC src/assignments.c
[i3] CC src/display_version.c
[i3] CC src/render.c
[i3] CC src/startup.c
[i3] CC src/tree.c
[i3] Link i3
[i3] Link test.commands_parser
[i3] Link test.config_parser
[i3-config-wizard] CC i3-config-wizard/main.c
[i3-config-wizard] Link i3-config-wizard
[i3-msg] CC i3-msg/main.c
[i3-msg] Link i3-msg
[i3-input] CC i3-input/keysym2ucs.c
[i3-input] CC i3-input/main.c
[i3-input] Link i3-input
[i3-nagbar] CC i3-nagbar/main.c
[i3-nagbar] Link i3-nagbar
[i3bar] CC i3bar/src/outputs.c
[i3bar] CC i3bar/src/parse_json_header.c
[i3bar] CC i3bar/src/config.c
[i3bar] CC i3bar/src/workspaces.c
[i3bar] CC i3bar/src/mode.c
[i3bar] CC i3bar/src/ipc.c
[i3bar] CC i3bar/src/main.c
[i3bar] CC i3bar/src/xcb.c
[i3bar] CC i3bar/src/child.c
[i3bar] Link i3bar
[i3-dump-log] CC i3-dump-log/main.c
[i3-dump-log] Link i3-dump-log
christian@uBunny:/usr/src/i3-gaps$ sudo make install
[i3] Install
[i3-config-wizard] Install
[i3-msg] Install
[i3-input] Install
[i3-nagbar] Install
[i3bar] Install
[i3-dump-log] Install

**Comment by Airblader** [comment]
#88
