### ISSUE TITLE
Add xcb-util-xrm to the wiki

### ISSUE THREAD

**Issue by gngeorgiev** [Airblader/i3#94]
I recently had to build i3gaps from source on both ubuntu and openSuse and had a bit of hard time finding the xcb-util-xrm library. Please consider adding it to the wiki. Also, some more info about how to build xcb-util-xrm will be helpful.

**Comment by Airblader** [comment]
> Please consider adding it to the wiki.

It already is. As a big fat warning:

> IMPORTANT NOTE: As of May 2016, i3 also relies on xcb-util-xrm which is not yet available in most distributions. Once it is available in your distribution, please add the package name to the list(s) below. In the meantime, you might have to compile it from source.

.

> Also, some more info about how to build xcb-util-xrm will be helpful.

I'd rather get distributions to offer a package. You shouldn't have to build from source. Either way, it's not the job of i3-gaps to describe how to build its dependencies.

**Comment by gngeorgiev** [comment]
Yeah, really did not see that sorry.

My suggestion was to add the instructions of building xcb to its readme

**Comment by Airblader** [comment]
In general I have no problem with that. But build instructions depend on the distribution which is why only experienced users should do it. And those probably know how to use a simple autoconf setup. 

But we can still add it to the wiki. Please open a ticket for that in the library's repository.
