### ISSUE TITLE
[i3-gaps-next] Keybinds with shift stop working after some time.

### ISSUE THREAD

**Issue by xMister32** [Airblader/i3#98]
Output of `i3 --moreversion 2>&- || i3 --version`:

i3 --moreversion 2>&- || i3 --version
Binary i3 version:  4.12-118-g155f034 (2016-08-03, branch "gaps-next") � 2009 Michael Stapelberg and contributors
Running i3 version: 4.12-118-g155f034 (2016-08-03, branch "gaps-next") (pid 31891)
Loaded i3 config: /home/mister/.config/i3/config (Last modified: Tue 23 Aug 2016 04:44:54 PM CEST, 141 seconds ago)
The i3 binary you just called: /usr/bin/i3
The i3 binary you are running: i3

URL to a logfile as per http://i3wm.org/docs/debugging.html:

http://logs.i3wm.org/logs/5648161435549696.bz2

My issue is that sometimes on my i3-gaps-next some keybinds just stop working out of the blue. From what I noticed, it only occurs to bindings involving Shift. I mean that I can use $mod+h to go to the terminal on the left, but when I try to move it with $mod+Shift+h it acts like I just wanted to write "H" in my terminal, as if the mod key wasn't pressed at the time. I have no idea what triggers it because it happens (for me randomly?) from time to time. Shift itself is working properly.
i3-msg reload or i3-msg restart are not helpful either. To fix it, I have to use i3-msg exit and then startx in the tty.
I found a similar thread form 11 months ago on reddit but it said that the issue has been fixed in a commit so it won't get me anywhere.

**Comment by Airblader** [comment]
Please report issues not related to i3-gaps specific features upstream. Anyway, I think your issue is likely already covered in https://github.com/i3/i3/issues/2418 or https://github.com/i3/i3/issues/2417
