### ISSUE TITLE
Preselect location of new window

### ISSUE THREAD

**Issue by arnm** [Airblader/i3#99]
The default behavior when opening a new window is that it will be placed to the right, if in vertical split mode, or to the bottom, if in horizontal split mode.

There are scenarios where I want to tell the window manager where to place the new window in relation to the currently focused window, ie, top, bottom, left or right.

Currently, I have to deal with the fact that it will either be placed at the right or bottom of the focused window and then move it manually afterwards.

**Comment by Airblader** [comment]
https://github.com/i3/i3/issues/1767
